### ISSUE TITLE
Creation of Authentication Data

### ISSUE THREAD

**Issue by eldering** [DOMjudge/domjudge#10]
If the CCS uses a login/password mechanism to enforce secure authentication, it must support account creation and password assignment according to the following algorithm:

 1. read teams.tsv defining team accounts to be created
 1. read accounts.tsv defining additional accounts to be created (that is, accounts in addition to teams)
 1. read passwords.txt a list of passwords to be assigned
 1. assign passwords to accounts, deterministically (that is, the same password mapping must be produced if the same data is input a second time)
 1. generate a file userdata.tsv containing user account information in the format described in userdata.tsv.

**Comment by meisterT** [comment]
Implemented in ef9e317e1c674b3c360915338a50dc7de1b9b1fc and 9ec3b57a475ce49bbb7ed668801beb199bca0c9b.
