### ISSUE TITLE
Improve rejudgings overview

### ISSUE THREAD

**Issue by meisterT** [DOMjudge/domjudge#1018]
- [x] Rejudgings are tied to a contest in the common case, but even after switching contest, they are displayed on the rejudging page. We should only display the rejudgings that belong to the currently selected contest or are not tied to a contest (e.g. after rejudging a problem which is part of two contests).
- [x] We should order active rejudgings to the top (i.e. the ones which are not applied/canceled yet) to make it easier to navigate long lists.
- [ ] In case of repeated rejudgings it makes sense to fold them into one row, otherwise it will look like this: 
![image](https://user-images.githubusercontent.com/418721/112745280-6a42b880-8fa7-11eb-9613-1bac35e515d5.png)

**Comment by mvr320** [comment]
@meisterT would you ever care for the unfolding of the repeated redjudgings (as you can reach them via the last one?)

**Comment by meisterT** [comment]
Unlikely that you need it from the overview.

**Comment by mvr320** [comment]
@meisterT Just to be sure, if I would upload a problem to contest C1 with jury solutions, I change something so do a rejudge (at this moment the judgings in judging table are connected to a contest) and would than add these problems to another contest I should still see these judgings although they are connected to another contest?

**Comment by meisterT** [comment]
I would not show them. These are for a different `contestproblem`.
