### ISSUE TITLE
Add support for dots in identifiers

### ISSUE THREAD

**Issue by nickygerritsen** [DOMjudge/domjudge#1030]
The CCS spec now allows a dot in an identifierL icpc/ccs-specs#20. We should also allow this.

**Comment by thijskh** [comment]
Are we talking about the externalId then, I think? I think we are more liberal than that and just allow any string.

**Comment by nickygerritsen** [comment]
It's currently used in some places, like the ID of an executable (they don't have external ID's), but there are more. Searching for `[a-zA-Z0-9_-]` in the code will show it.

Is your suggestion to allow anything? That means we also need to allow it for the `execid` column. And in theory `teamid` (but we don't do that now even) and import of problem ZIP filenames. And with how the checks are currently set up also the `shortname` of contests and `langid` of languages.

**Comment by nickygerritsen** [comment]
> I think we should stick to the CCS specification unless we have a good reason not to.

Note that we currently are a bit wider: we DO allow a - at the beginning.
But we can improve on that. I also think we should have less places where we define the regex so if others agree we should adhere to the spec I can cook something up

**Comment by thijskh** [comment]
> I think we should stick to the CCS specification unless we have a good reason not to.

You mean we should be stricter on which externalId's we accept?
