### ISSUE TITLE
Add support for multiple categories per team and per-category scoreboards

### ISSUE THREAD

**Issue by nickygerritsen** [DOMjudge/domjudge#1077]
An open PR (icpc/ccs-specs#32) to the [contest API spec](https://ccs-specs.icpc.io/contest_api) is to support the following:

* The [scoreboard](https://ccs-specs.icpc.io/contest_api#scoreboard) API gets support for a parameter `group_id=x`, which will return the scoreboard for a given group.
* Besides this, the API already allows for a team to be in more than one group. However, DOMjudge only supports one group.
* There will be a list of values that can be used for the `type` field of a group, like `site`.

Use cases for these are contests that have separate groups, that should / could be scored separately.
We already have this with our `sort order` field on a team category. However, our current API implementation simply returns the scoreboard for teams that are in a category with the lowest sort order.

We have several options here:
1. Do nothing. We are not up to the spec anymore when it gets updated.
2. Do magic in the scoreboard API controller that recalculates the rank for teams if you filter on a group. This still has the issue that currently we only expose the scoreboard for the lowest sort order. We have no way to get the scoreboard for all sortorders combined currently, so that should also be more magic.
3. Properly add support for multiple team categories.

I think option `1` should not be considered and option `2` feels hackish.

Personally, I would like to do option `3`. We ourself already ran into issues with the current setup at BAPC's and NWERC's, where we also want to run the resolver for company teams. A general idea on how we can do option `3`:

* We DO NOT drop sortorder from team categories (more on this below).
* We add a type field to team categories, which auto completes to the options predefined in the spec, but allows you to add other options.
* We add a field to team category that is something like 'use as scoreboard', which determines whether our UI shows this category as a scoreboard. If not, we will not show it, but it can still be retrieved from the API.
* We also add a field to team category that is something like 'show as scoreboard badge', that makes it show up as the current yellow badge on the scoreboard, replacing the current logic (which is 'show it when we have more than 1 category'). I am not sure yet how to handle this if a team appears on more than one scoreboard. Imagine a team belonging to the following groups: `Netherlands`, `Students` and `TU/e`, where the first two have the 'use as scoreboard' flag set and the latter has the 'show as scoreboard badge' flag set. Do we then show `TU/e` on both scoreboards as a yellow badge? If we don't want this we probably need some hierarchy in the groups, but I'm not sure if I am a fan of that.
* We make the relation between team and team category a many2many.
* We modify the scoreboard classes (the ones in the `App\Utils\Scoreboard` namespace) to not use sortorder anymore. Instead of that we loop over the groups that have 'use as scoreboard' set and calculate the scoreboard (i.e. ranks) per group. If you specify a specific group we only calculate the scoreboard for that group. We also add support for getting the global scoreboard (i.e. ignore group info).
* We modify the scoreboard twig templates to loop over the groups which have 'use as scoreboard' set and display a scoreboard for each. We do this ordered on the sort order. We might want to add a header between each scoreboard with the name of the group (if there is more than one). We might also add some logic that if the number of scoreboards is too big, we only render one and show a dropdown to choose the scoreboard you want, similar to what Kattis did at [NAQ 2020](https://naq20.kattis.com/standings).
* We probably need to think about what to display at the team and affiliation detail pages of the jury interface, since a team is in multiple scoreboards. Maybe display the first one (based on sort order) by default and show a dropdown to switch?
* A general question that remains is what happens if a team is in two groups, one of which is hidden and the other is not. If these two groups both have a scoreboard it makes sense to show the team only on one (for public users), but what about the global scoreboard? I see the API does not actually specify if we should omit teams from hidden groups in the scoreboard endpoint, so I will bring that up.

What are the opinions on this? I think it can be a useful feature and another step towards allowing one to run the resolver without a CDS in between. Although the issue seems big, I think it is not too hard and I am willing to try to implement it if we answer the few questions and thoughts above. It should also not really be a performance impact, unless you have a lot of groups of course.

**Comment by nickygerritsen** [comment]
I think we should not do this, unless there is animo for it. It is an optional feature of the spec that we don't have to do and it does require quite a bit of changes.

If no one disagrees with this, I will close this issue.

**Comment by meisterT** [comment]
FYI: https://www.domjudge.org/demoweb/public?countries%5B%5D=DNK&filter=filter works fine except that awards are wrong-ish
