### ISSUE TITLE
Add support for POSTing awards?

### ISSUE THREAD

**Issue by nickygerritsen** [DOMjudge/domjudge#1079]
A change (icpc/ccs-specs#34) to the [contest API spec](https://ccs-specs.icpc.io/contest_api) is to add support for `POST` and `DELETE` to the awards endpoint, allowing an external tool to determine which awards to hand out and to store that back in the CCS. This allows one to determine awards using any logic one wants and then store them, thus making it possible to use tools like the resolver directly with a CCS with custom awards.

Do we want to add support for this? If so, we probably need a table to store awards, instead of emitting them in the API directly. And then when finalizing we can generate our current set if there are none (yet) or add a separate button to generate the default set. We could even add a UI somewhere where you can manually create / edit / delete awards.

What are the thoughts on this? It should be pretty easy to implement but does require an extra table (and optional page).

**Comment by meisterT** [comment]
I am not a big fan. The CCS needs to calculate the awards (like first to solve) during the contest anyway and should not have to wait for an external entitiy to tell it. And then you would also need to spec out explicitly what awards exist.

We discussed a somewhat legitimate use case yesteryday where the jury wants to highlight additional teams or submissions, e.g. for most creative solutions.

One related thing that we likely want though is to add one more column to the team category where we allow to specify the award winner name for this group, e.g. "Dutch champions", but the group is called "Netherlands".

**Comment by nickygerritsen** [comment]
I agree with all this and I think we should close this issue.

However, according to the spec the way we currently already expose awards on the `awards` endpoint but not have it in the feed yet is 'illegal'. We can either ignore that illegality or only expose awards at the end. I'm fine with either,

**Comment by meisterT** [comment]
Let's ignore this until someone complains.
