### ISSUE TITLE
Drop scoreboard.tsv export

### ISSUE THREAD

**Issue by nickygerritsen** [DOMjudge/domjudge#1094]
When icpc/ccs-specs#38 is merged, we no longer need the `scoreboard.tsv` export. We can replace it with something that internally gets the scoreboard API endpoint and downloads it as JSON.

**Comment by meisterT** [comment]
better than an internal request is to refactor the code and perhaps move the main part to scoreboard service and then call the function

**Comment by nickygerritsen** [comment]
Agreed, way better.
