### ISSUE TITLE
Rejudge remaining broken

### ISSUE THREAD

**Issue by mvr320** [DOMjudge/domjudge#1096]
Currently when running a competition in master:

When doing a partial judging, when you press the judge remaining (so when there is already a non correct verdict) there is a database error.

**Comment by thijskh** [comment]
This seems to be fixed in main?

**Comment by nickygerritsen** [comment]
I believe you fixed this in 1f38d4beb465b754c2549a35d35ea7d68414dd05

**Comment by mvr320** [comment]
I agree, will see if I finish the tests for this.

**Comment by thijskh** [comment]
> I believe you fixed this in 1f38d4b

No, that is rejudging, this is about judging remaining runs of a submission if it has stopped judging after finding e.g. a wrong-answer. But in either case, it's fixed.
