### ISSUE TITLE
Team Member role cannot query scoreboard from api for private contest she has access to

### ISSUE THREAD

**Issue by chistopher** [DOMjudge/domjudge#1106]
A user with only the Team Member role has access to public contests and contests her team or team category has access to.
`/api/v4/contests/{cid}/scoreboard` should be able to query the scoreboard for a contest the user has access to even when the contest is not public.

In `webapp/src/Controller/API/ScoreboardController.php` access is checked as follows
```php
$inactiveAllowed = $this->isGranted('ROLE_API_READER');
$accessAllowed   = ($inactiveAllowed && $contest->getEnabled()) || (!$inactiveAllowed && $contest->isActive());
if (!$accessAllowed) {
    throw new AccessDeniedHttpException();
}
```
Meaning, when the user does not have the api reader role, the contest has to be active which requires the contest to be public.
```php
public function isActive(): bool
{
    return $this->getEnabled() &&
        $this->getPublic() &&
        ($this->deactivatetime == null || $this->deactivatetime > time());
}
```
I think in this context `isActive` should not require the contest to be public.

**Comment by meisterT** [comment]
Sounds reasonable. Do you want to send a PR to fix this?

**Comment by nickygerritsen** [comment]
Yeah I think we need to change it to check if the team is part of the contest, which means either public or the team is part of it. We can 'borrow' this logic from `AbstractRestController::getContestQueryBuilder`.

I see that that `getContestId` (which we call in the line above the part you copied) already checks if the team can access the contest (by calling this `getContestQueryBuilder` method), so I think we could just drop the whole check. But to be sure we should probably add some tests to verify this.

**Comment by chistopher** [comment]
Thanks for the fast reply. I send a PR.
