### ISSUE TITLE
`apt` repository (and others) offline.

### ISSUE THREAD

**Issue by Wicloz** [DOMjudge/domjudge#1126]
The `apt` repository hosted at https://domjudge.org/debian is no longer accessible.

In fact, most links including the repository key https://www.domjudge.org/repokey.asc the sources https://www.domjudge.org/sources/ and snapshots https://www.domjudge.org/snapshot/ seem to be replaced by a 404.

**Comment by nickygerritsen** [comment]
Thanks. We are aware and working on the solution.

**Comment by thijskh** [comment]
The things you mention should be back online now. Sorry for the inconvenience.

**Comment by Wicloz** [comment]
Thanks for the quick fix, our `apt` is happy again!
