### ISSUE TITLE
Display time on /jury/contests page

### ISSUE THREAD

**Issue by vmcj** [DOMjudge/domjudge#1134]
### Description of the problem
> When you create a contest in multiple timezones the times on the overview page becomes hard to understand.

### Your environment
> DOMjudge 8.0.0DEV

### Steps to reproduce
> Create a new contest with the following timings:
- Activate time | -01:00
- Start time | 2020-01-01 09:00:00 UTC
- Freeze time | empty
- End time | 2020-01-01 11:00:00 Europe/Amsterdam
- Unfreeze time | empty
- Deactivate time | +06:00

### Expected behaviour
- We could have a user preference, so translate the timings to the current user, this could even be the browser locale.
- Translate everything to the timezone of start time as that is the start timepoint for all relative timings.
- Add the full time in the alt text, to remove some of the confusion and fix the timezone there. and add more indication of the alt. Add a indicator that the timezone is different from the start time.

### Actual behaviour
> All datetimes are translated to just time (even if this would be over multiple days or multiple timezones)

### Any other information that you want to share?
> This is more of a discussion starter, I'm not sure if this is worth the time.

**Comment by nickygerritsen** [comment]
> ### Any other information that you want to share?
> > This is more of a discussion starter, I'm not sure if this is worth the time.

Nice pun.

the hover idea is easiest I guess? I’m not really sure what I like most

**Comment by mvr320** [comment]
> not



> 
> 
> > ### Any other information that you want to share?
> > > This is more of a discussion starter, I'm not sure if this is worth the time.
> 
> Nice pun.
> 
> the hover idea is easiest I guess? I’m not really sure what I like most

Well, the hover is already there, but only today I found out the feature is there but currently broken, in the config settings there is also a setting of how times can be printed but that seems to not work (yet), if that would work we could just update the docs with the warning that when you use multiple timezones, we advice the user to print times more verbose.

**Comment by thijskh** [comment]
A completely different approach: how about we forbid mixing timezones within one contest? It does not seem a valid use case to allow it, more likely a mistake and it will be endlessly confusing if you do?

**Comment by nickygerritsen** [comment]
I was also thinking about that. People might run into issues on DST day when using stuff like CEST but then don’t use that…

**Comment by mvr320** [comment]
> A completely different approach: how about we forbid mixing timezones within one contest? It does not seem a valid use case to allow it, more likely a mistake and it will be endlessly confusing if you do?

The usecase I can see is an online contest or course where you allow people to submit in a timeframe, so its convenient to select beginning of the day of the earliest and the endtime of the other timezone. Which can also be achieved with relative time.

This would still leave the issue of the display in the overview page, but thats more of a bug so can be fixed on itself. When I have time to fix this I'll implement Thijs his suggestion.
