### ISSUE TITLE
Export problemset.yaml

### ISSUE THREAD

**Issue by vmcj** [DOMjudge/domjudge#1147]
### Description of the problem
> When you run a contest which will be shadowed there is no way to export a problemset.yaml in the UI. It makes sense to have this to setup another system for shadowing. Another usecase is a contest with prelims so exporting can be done from the jury system and a simple script can import the problems at the other sites.

### Your environment
> DOMjudge main

**Comment by nickygerritsen** [comment]
@mvr320 as you found it this is part of the contest.yaml export.
We do have the issue where we export `label` (which we also support as import field) but the format spec says it should be `letter`. Should we modify the export to export both `label` and `letter` and then close this issue? Or am I missing something else?

**Comment by vmcj** [comment]
> @mvr320 as you found it this is part of the contest.yaml export. We do have the issue where we export `label` (which we also support as import field) but the format spec says it should be `letter`. Should we modify the export to export both `label` and `letter` and then close this issue? Or am I missing something else?

I think half of that is done, but my original goal was to get the correct files to setup shadowing, so the export should be acceptable for the shadowing import script, so I'll check if thats now indeed possible.
