### ISSUE TITLE
Giving back judgings is broken for submissions that are judged on mulitple machines

### ISSUE THREAD

**Issue by nickygerritsen** [DOMjudge/domjudge#1153]
Both `judging `and `judgetask` have a `judgehost` associated with them.
Now if a submission gets judged by 2 machines, this is stored in `judgetask` correctly (per run the correct judgehost), but not in `judging` (obviously, since we only have one field to set).
Imagine we have judgehost `A` and `B` who did a submission, where `A` had a crash or something but `B` is stored on `judging`. Now we never give back the judgetasks for `A`.

First of all I wonder why we have the `judgehost` stored on a `judging`. Looking in the code we have quite some queries for `j.judgehost` still left, so we can't easily drop it. We also use it when we need to disable a judgehost because it had a different compilation outcome than another judgehost on the same submission.

Should we somehow change all `j.judgehost` queries to join on judgetask and use that? And then drop `judgehost` on `judgimg`?
We probably should at least do this in `JudgehostController::createJudgehostAction` where we load the judgings to give back, right?

**Comment by nickygerritsen** [comment]
@meisterT could really use your input on this.

**Comment by nickygerritsen** [comment]
Related: if a judgehost crashes in this scenario after we already determined the final outcome for a submission (because earlier runs are done and have a WA for example), runs stay in limbo forever, since we never give them back (we only give back unfinished judgings)

**Comment by meisterT** [comment]
Before I dive into code, one question to your example: for simplicity let's assume the problem only has two cases, one each is distributed to judgehost `A` and `B`. The testcase of `B` is judged as `correct`, while judgehost `A` crashes. The expectation here is that when we restart judgehost `A` then we re-create or reset the judgetask belonging to `A` while the one of `B` is untouched. If we would restart judgehost `B` but not `A`, then nothing would happen, right?

**Comment by nickygerritsen** [comment]
Yep exactly what I expect (but doesn’t happen yet)
