### ISSUE TITLE
R Installation on DOMJudge Host?

### ISSUE THREAD

**Issue by melongist** [DOMjudge/domjudge#1183]
Dear all

How can I install R compiler for DOMjudge host, and use R in contest?

But, I can't hardly find about it.

I'm preparing a event contest for school teachers .... R is needed for math teacher... :)... I think....

Best Wishes
Hyun-seok

**Comment by mvr320** [comment]
Hi @melongist 

How are you running the judgedaemon? As I tested with the current docker image and when I enable: DOMJUDGE_CREATE_WRITABLE_TEMP_DIR=1

And install R via dj_run_chroot I can run R from a submission when the language is enabled in the domserver.

**Comment by melongist** [comment]
Finally I did it!! :)

Testing : AWS Ubuntu 20.04 LTS(t2.micro) + DOMjudge 7.3.3 stable

...

How to enable R!

In the process of installing judgehost

#1. r-base needed!
...
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E298A3A825C0D65DFD57CBB651716619E084DAB9
sudo add-apt-repository 'deb https://cloud.r-project.org/bin/linux/ubuntu focal-cran40/'
sudo apt -y install r-base
...


#2. dj_make_chroot for r-base
...
echo 'y' | sudo /opt/domjudge/judgehost/bin/dj_make_chroot -i r-base
...


#3. DOMJUDGE_CREATE_WRITABLE_TEMP_DIR=1 for R judgedaemons
...
sudo -u $USER DOMJUDGE_CREATE_WRITABLE_TEMP_DIR=1 setsid /opt/domjudge/judgehost/bin/judgedaemon &
...




It is good to refer to the full automatic installation script I made below. :)

https://github.com/melongist/CSL/tree/master/DOMjudge
