### ISSUE TITLE
Please help me clean expired submission

### ISSUE THREAD

**Issue by giampq** [DOMjudge/domjudge#1198]
Hi guys,

I am using domjudge with docker
Currently, my submissions are getting bigger and bigger, i want to delete old submissions from disk, to save storage space
I can't find the API to delete old submissions

Please help me with this problem, my hard drive is more than 90% used
Many thanks for your help

**Comment by eldering** [comment]
There is no API to delete submissions.
There is a script `misc/dj_judgehost_cleanup` that you can use for this, run with argument `help` for more details. I'm not sure this is available in the docker image though.

**Comment by giampq** [comment]
Hi @eldering, 
Thanks for support, I'll try it 
Hope it working
