### ISSUE TITLE
Custom build script for interactors

### ISSUE THREAD

**Issue by RagnarGrootKoerkamp** [DOMjudge/domjudge#1219]
When adding a custom `build` script to an interactor (output validator) for an interactive problem, judging breaks. This is because the default build script for interactive problems [creates a `run` wrapper script](https://github.com/DOMjudge/domjudge/blob/main/judge/judgedaemon.main.php#L352-L401), that now needs to be created manually.

This can be worked around either by appending that code manually to the build file, or just by creating that as a runfile directly.

It appears that the `DOMJUDGE` environment variable is not set when invoking these scripts, so currently it's a bit ugly to detect whether the code is running under DOMjudge (because for BAPCtools you'd need to just call the `exec ./runjury` directly, instead of via the wrapper script).

I think this may be fixed properly by always appending the code mentioned to the `build` file, even if it already exists.

**Comment by meisterT** [comment]
@RagnarGrootKoerkamp you're probably right. Feel free to send a PR 😉

**Comment by RagnarGrootKoerkamp** [comment]
Rebased and tested now :heavy_check_mark:
