### ISSUE TITLE
Contest problems edit UI not optimal

### ISSUE THREAD

**Issue by eldering** [DOMjudge/domjudge#1267]
Two issues I noticed while trying to edit contest problem colors, see https://github.com/DOMjudge/domjudge/issues/1264:

- I cannot enter a color by name: any word colors I type are replaced by `#ffffff` when the field gets deselected. It would be nice if HTML color names are recognized.
- When I was entering colors and then pressed <tab> a couple of times to try and navigate to the color field on the next line, the form was automatically submitted. That's annoying.

**Comment by meisterT** [comment]
let's swap out the color picker with https://github.com/mdbassit/Coloris
