### ISSUE TITLE
Speed up jury/submissions page

### ISSUE THREAD

**Issue by RagnarGrootKoerkamp** [DOMjudge/domjudge#1268]
For our BAPC set it takes around 5 seconds to load the submissions page (with >200 jury submissions and >5000 runs), and still 1.5s when setting it to `new` instead of `all`.

I noticed that it's making one DB query per submission: [html twig](https://github.com/DOMjudge/domjudge/blob/b5ddb969cd1995cc8c874ec98d932ea58c8174cc/webapp/templates/jury/partials/submission_list.html.twig#L238) calling [this function](https://github.com/DOMjudge/domjudge/blob/2da497180d6cf5b20c9bd8db3a78d4ae8b618d28/webapp/src/Twig/TwigExtension.php#L417).

It would probably be faster to fetch all runs directly when fetching the submissions to show.

For my local instance (with fewer problems), the `jury/partials/submission_list.html.twig` is taking half the time:

![image](https://user-images.githubusercontent.com/6233682/137487185-cb50bac8-495a-4485-9182-fb67a276316b.png)

Do you think it's worth trying to fix this? It could also be that it's twig itself that's slow at rendering all the runs maybe?

**Comment by nickygerritsen** [comment]
it was not that query, it was another one that is now fixed in d96627f863a3283df03f0c74a02d4eb0a0afe610
