### ISSUE TITLE
Allow more elaborate LDAP queries

### ISSUE THREAD

**Issue by elieux** [DOMjudge/domjudge#128]
Would it be possible/desired to allow more complex LDAP queries, possibly in form of a callback? University's tree is kinda complicated(*) and I need to parse the auth token into several pieces to get the correct query. I know I could define LDAP_DNQUERY as '&' and put the whole query into the auth token, but I want to make it easy for the contest admin.

A somewhat hacky solution is in elieux/domjudge@8e0ffbe66104c9b547e89eb342b6844e1254f338

*) It's also possible I missed something and the query can be done in a simpler way.

**Comment by eldering** [comment]
Closing as wontfix for the master codebase. As individual workaround one can always add this functionality.
