### ISSUE TITLE
Improve documentation for adding new language

### ISSUE THREAD

**Issue by vmcj** [DOMjudge/domjudge#1280]
Currently when an user adds R as language the temp directory has to be writable, as this is currently not the case there is probably a reason for that.

Why is that the case?
Can we have better documentation how someone can set such a language up?
- How to test it in the chroot

Information like this should probably be added to the wiki as more languages might have this issue whereas supporting these language in DOMjudge itself can be overkill (but would remove knowing this for users).

**Comment by eldering** [comment]
> Why is that the case?

This is based on the principle of least privilege. None of the common languages need it. Furthermore it opens a security hole where the submission may write data to temp and this way pass information from one testcase run to the next.

> Can we have better documentation how someone can set such a language up?

In this case the best starting point is understanding how the `chroot-start-stop` script is called and modify that. The specifics depend on each language individual requirements though.

**Comment by vmcj** [comment]
Added some info in: https://github.com/DOMjudge/domjudge/wiki/Adding-a-new-language
