### ISSUE TITLE
Add C++11 support

### ISSUE THREAD

**Issue by elieux** [DOMjudge/domjudge#129]
ICPC contests seem to be gradually moving towards C++11 and UVa OJ is also giving the option. Could DOMjudge have C++11 configured by default?

**Comment by nerdDan** [comment]
C++11 still not supported in 2016?

**Comment by corneym** [comment]
This is something we do by altering the compile script in the cpp and c executable by adding an extra option:

 

For C++ add:    -std=c++11

For C add:  -std=c11

**Comment by nerdDan** [comment]
Do you mean C++11 is supported by DOMJudge without configuration?

I submitted a C++11 source code but got a compilation error. I am sure C++11 is supported on the judge machine.

**Comment by corneym** [comment]
If you have a version of a C++ or C compiler on your judgehost you just have to alter the compilation string in the C++ and/or C executable script via configuring the Web interface.

 

home --> executables --> cpp or (c) --> edit --> edit file contents --> select run tab

 

Change:

g++ -x c++ -Wall -O2 -static -pipe -DONLINE_JUDGE -DDOMJUDGE -o "$DEST" "$@"

gcc -x c -Wall -O2 -static -pipe -DONLINE_JUDGE -DDOMJUDGE -o "$DEST" "$@" –lm

 

to:

 

g++ -x c++ -Wall -O2 -std=c++11 -static -pipe -DONLINE_JUDGE -DDOMJUDGE -o "$DEST" "$@"

gcc -x c -Wall -O2 -std=c11 -static -pipe -DONLINE_JUDGE -DDOMJUDGE -o "$DEST" "$@" –lm

 

and save

**Comment by nerdDan** [comment]
found it. thank you :)
