### ISSUE TITLE
Sample set zips use the .out extension instead of .ans

### ISSUE THREAD

**Issue by 0xJoey** [DOMjudge/domjudge#1302]
NOTE: If this is a _discussion starter_, you need any _installation help_ or have a _question_ on how to accomplish something,
rather post at [our discussion channel](https://www.domjudge.org/chat) or send an email to our
[DOMjudge-devel mailinglist](https://www.domjudge.org/mailman/listinfo/domjudge-devel)
instead of filing an issue here.

### Description of the problem
Sample set zipfile contains .out files instead of .ans for answers

### Your environment
-

### Steps to reproduce
Download the sample zip file

### Expected behaviour
Expected answers are in files with the .ans extension

### Actual behaviour
Expected answers are in files with the .out extension

### Any other information that you want to share?
-

**Comment by 0xJoey** [comment]
@RagnarGrootKoerkamp

**Comment by nickygerritsen** [comment]
FYI discussed during BAPC: the problem package spec uses ans so we might want to do that as well?

**Comment by nickygerritsen** [comment]
The spec I was referring to was: https://www.kattis.com/problem-package-format/spec/problem_package_format#test-data

**Comment by nickygerritsen** [comment]
Soooo, should we just rename it?

**Comment by shuibinlong** [comment]
> The spec I was referring to was: https://www.kattis.com/problem-package-format/spec/problem_package_format#test-data

I agree with this spec, but for compatibility maybe we can support `.out` format when uploading testing data?
