### ISSUE TITLE
make ctrl-enter work in popups

### ISSUE THREAD

**Issue by RagnarGrootKoerkamp** [DOMjudge/domjudge#1305]

**Comment by eldering** [comment]
Can you explain a bit more exactly what you'd like to see happen and where?

**Comment by eldering** [comment]
@RagnarGrootKoerkamp explained in person that he wants to be able to use ctrl+enter to submit the popup form, e.g. for a rejudging. I showed that simply enter actually works.
Can this be closed?

**Comment by RagnarGrootKoerkamp** [comment]
In particular this was for the 'create rejudging' (of a single submission) popup. Fixing it would be nice but since enter works it's fine anyway.
