### ISSUE TITLE
Clarifications (not replies) to a single team not visible

### ISSUE THREAD

**Issue by eldering** [DOMjudge/domjudge#1306]
If the jury sends a clarification to a single team, not as a response to a clarification request from the team, then that clarification will not show up on the jury clarifications page. This is because it doesn't fall in any of the groups of clarifications we display there.

This is a problem because now you can't check whether anything has been sent. And generally it's useful to be able to look this up again.

**Comment by thijskh** [comment]
Any ideas on a good solution? Add another category? Treat them as “general” clarifications?

**Comment by eldering** [comment]
> Any ideas on a good solution? Add another category? Treat them as “general” clarifications?

I think "General clarification" should be fine. It is still listed there what team the clarification was sent to. And I normally don't expect there to be many such clarifications. In this case at the BAPC a few were sent to notify teams about judgings stuck due to https://github.com/DOMjudge/domjudge/issues/1307
