### ISSUE TITLE
Do not set awards (4 gold/silver/bronze) by default

### ISSUE THREAD

**Issue by RagnarGrootKoerkamp** [DOMjudge/domjudge#1309]
It's only at ICPC and subregionals that this is consistently used. It should be a conscious decision to add awards, since this is shown in the resolver.

**Comment by nickygerritsen** [comment]
So you propose to disable the option by default? Or set it to 1?

**Comment by RagnarGrootKoerkamp** [comment]
Hmm goed question. Giving out top 3 prices is quite common so that may be
preferable, but either sounds good to me.

**Comment by eldering** [comment]
Another option would be to create new contests with `process_awards` default off. I think that any awards should be consciously configured.

**Comment by nickygerritsen** [comment]
That was the first part of my suggestion. I'm also fine with either, so maybe we should even do both? Set it of by default but if you enable it set the number to 1 instead of 4 by default?

**Comment by eldering** [comment]
I think that if it is off by default, then having any number of awards there is fine. 4 actually might be nice since it's the ICPC default and it shows that you can pick more than 1.

**Comment by eldering** [comment]
BTW, does `process_awards` only affect additional awards like gold/silver/bronze medals? That is, if off, will the resolver still show e.g. "contest winner"? Is that even part of the event feed?

**Comment by nickygerritsen** [comment]
> BTW, does `process_awards` only affect additional awards like gold/silver/bronze medals? That is, if off, will the resolver still show e.g. "contest winner"? Is that even part of the event feed?

See http://github.com/DOMjudge/domjudge/blob/9761013a754ed2503089089e29d435bb9a54aafc/webapp/src/Controller/API/AwardsController.php#L96-L96. So yes, you still get a winner. And it is part of the event feed, but we only add them when you finalize (all of the awards that is).
