### ISSUE TITLE
Support uploading team affiliations logo on the team affiliations page

### ISSUE THREAD

**Issue by shuibinlong** [DOMjudge/domjudge#1317]
If I want to add a logo to an affiliation on the current page `/jury/affiliations`, I need to manually upload the logo image file to the `domserver/webapp/public/images/affiliations` folder, which brings a burden to both management and operation and maintenance personnel.

Can we provide a quick upload interface (such as upload button in `/jury/affiliations/{id}/edit` page) on the web page? When the administrator chooses to upload the team affiliation logo, it can be automatically placed in the corresponding folder through this interface.

**Comment by nickygerritsen** [comment]
Would be cool. Same for team photos. If we then also add it to the API that would be even cooler
