### ISSUE TITLE
Demoweb broken submissions

### ISSUE THREAD

**Issue by mvr320** [DOMjudge/domjudge#1328]
Currently a couple of submissions seem to be broken:
https://www.domjudge.org/demoweb/jury/submissions/9673

A quick look around seems to show that everything from 3+ is broken at: https://www.domjudge.org/demoweb/jury/submissions

**Comment by meisterT** [comment]
Without checking the log it could be that the twig extension that I wrote recently broke this because we delete some data for demoweb

**Comment by thijskh** [comment]
This is the line that fails:
https://github.com/DOMjudge/domjudge/blob/4482fb0d6374cd1830c059efe6e770ae150d0466/webapp/src/Entity/Judging.php#L538

Might it be because we migrated the demoweb database from a pre-judgetask database?

Confirmed that this fixes it, but not sure if we'd want it:
```php
            if ($run->getJudgeTask() === null || $run->getJudgeTask()->getJudgehost() === null) {
```
