### ISSUE TITLE
Update Clarification API filtering for authorized roles

### ISSUE THREAD

**Issue by brettreyno** [DOMjudge/domjudge#1333]
The API documentation for the `/contests/{cid}/clarifications` endpoint states that "[...]we restrict the returned clarifications in the query builder." It appears as though the endpoint is configured to return only those clarifications which are visible to all teams. While this makes sense from a security standpoint (and I see is one of your requirements as documented here: https://github.com/DOMjudge/domjudge/issues/48), this severely limits the utility of this portion of the API for jury and administrative users.

Would it be possible to adjust this filtering to correspond to the user's roles and team affiliations? Specifically, users with the 'admin' and/or 'jury' roles should be able to view all clarifications; users with the 'team' role should be able to view public clarifications (as currently) and those specifically sent to their associated team.

**Comment by thijskh** [comment]
I think your idea of what it should do makes sense. The issue you dug up is a nice acheological find but back then the CCS standard did not refer to any API at all.

The documentation is indeed a bit vague (just mentioning the querybuilder) but if you look at the actual code you'll see that if you have the `api_reader` role there are already no restrictions; if you have the team role you already get those pertaining to you.
https://github.com/DOMjudge/domjudge/blob/24b65b98c12604bcae43f95404ce28a5a1a16e35/webapp/src/Controller/API/ClarificationController.php#L295-L307

I wonder why it does not do for you what you expect. In any case it would make sense to update the API docs to make explicit what it returns.

**Comment by brettreyno** [comment]
I'm on an older version (7.3.0), so that could be the issue... although it looks like that snippet still exists on the 7.3 branch, so I'm not sure what's going on.

The user I'm logged in as has these roles: admin, jury, team, api_reader, api_writer, api_source_reader. If I'm reading the code correctly, because I have the api_reader role, it shouldn't be applying any of those filters. I also tried to check what got returned for an account that only has the "team" role and got the same result, even though that team did have a private clarification.

**Comment by thijskh** [comment]
Well, it should be on 7.3.0 but not on older versions than 7.3.0. I've confirmed the behaviour on current main. I've also created some test cases so we will check whether it continues to behave correctly, and updated the api docs to be more explicit about what the API functionally does.

**Comment by brettreyno** [comment]
Thank you! I've done a bit more digging and been able to confirm that it is working as you describe on my end as well; for some reason I must have been doing the authentication incorrectly. Sorry for the confusion.
