### ISSUE TITLE
Add 'ignored' flag to Clarifications API responses

### ISSUE THREAD

**Issue by brettreyno** [DOMjudge/domjudge#1345]
When viewing a clarification, DOMJudge offers jury users the option to click a "Set Answered" button, which moves the clarification into the "answered" section of the main clarification window and decrements the number of "open" clarifications displayed in the navigation bar across the top of the screen. However, when querying the API for clarifications, there is no data to indicate that a clarification has been ignored in this manner. Would it be possible to add a boolean 'ignored' flag or similar to the API responses to allow detection of this scenario?

**Comment by thijskh** [comment]
We store this in a boolean field 'answered' with each clarification (so there's no special case for ignored ones, this is always set to true either by pressing the button you mention or by actually answering it). Would that work for you?

We can trivially add this boolean `answered` to the API output. Probably only for nonstrict mode since the spec does not define it (looking at the specs gurus here).

**Comment by brettreyno** [comment]
That's perfect, yes! I'm currently identifying "answered" clarifications by scanning through the whole list for one with a matching "reply_to_id," so that would significantly reduce my processing time.

**Comment by thijskh** [comment]
Question is whether it’s “bad” to expose this state to a team that sent it. I’m leaning to ‘no’.

**Comment by brettreyno** [comment]
The only thing they'd gain from having access to that field (that they wouldn't already have anyway) is an answer to the question "Are the judges actively ignoring me?" It's probably best not answering that, yes, but on the other hand, the answer starts to make itself obvious if they haven't gotten a reply within a reasonable amount of time. ;-)

Is it possible to simply leave the value null for non-jury/API-reader users?

**Comment by nickygerritsen** [comment]
We could also only expose it to admins or is that not ideal?

**Comment by thijskh** [comment]
This is possible I think(but less straightforward)
