### ISSUE TITLE
Better documentation on pinning judgedaemon to a core

### ISSUE THREAD

**Issue by eldering** [DOMjudge/domjudge#1346]
https://github.com/DOMjudge/domjudge/pull/906 changed the judgedaemon service file to pin to a single CPU core automatically, but the documentation is still inconsistent:

- Some parts still describe an unpinned judgedaemon without `-n X` option.
- The documentation about using multiple judgedaeamons on a single machine sometimes use `n=0` and sometimes `n=1`. We should stick to a single choice (probably `n=2`) and explain why we picked that as default, and how/why you mick want to choose something else.

**Comment by vmcj** [comment]
@eldering do you agree this can be closed?

**Comment by eldering** [comment]
Sure.
