### ISSUE TITLE
Cannot delete test cases with API

### ISSUE THREAD

**Issue by giampq** [DOMjudge/domjudge#1348]
Hi guys,

I am using domjudge with docker
I can't find the API to delete test cases

![image](https://user-images.githubusercontent.com/16837400/142737012-66a15109-76cb-41ee-99de-30d2adc617e1.png)

---------------
Currently, when I need to delete test cases
Must log in and access this URL: "https://{domain}/jury/problems/{test_case_id}/delete_testcase"

Please help me with this issue
Many thanks for your help

**Comment by eldering** [comment]
You can't simply delete test cases for good reasons, only mark them deleted, see https://github.com/DOMjudge/domjudge/issues/189
There is no API endpoint for this (yet), though.

**Comment by eldering** [comment]
Can you explain what your use case is and why you need an API endpoint? Since this "delete" action doesn't have a very simple semantics, I'd be inclined to not support it in the API.

**Comment by giampq** [comment]
Hi @eldering,

I'm building an online learning system,
In our system:
- User with teacher permission can create questions, add test cases
- Users with student rights can load their solution
---
I have a cronjob worker to convert question & test case structure from our format to Domjudge's format, and sync them to Domjudge
then, when a student with student privileges submits their solution, I use Domjudge to grade it

I need to allow the teacher to update the test cases of the question (simply add and delete, no need to update) 

---
The reason why I need to build an online learning support system
- We need to log in with Google account (to link with Google Classroom)
- Contests are not for all, only some classes are implemented it
- The questions are all subject to topics
- Add difficulty to the question to calculate the score
- Extra points for each test case
- My leaderboard scoring is featured
- Improved user-friendly interface (exclusively for Vietnamese)
- ...

I would be grateful if you would allow me to remove the test cases using the API
(one or more test cases at the same time)

Extremely grateful

---
Some pictures of our system
![image](https://user-images.githubusercontent.com/16837400/142772093-27603146-40b1-4fed-9285-5ad48d8260cc.png)
![image](https://user-images.githubusercontent.com/16837400/142772222-6804270f-e806-46ff-b383-22e5936371a1.png)
![image](https://user-images.githubusercontent.com/16837400/142772253-ebf8121b-a8a3-4031-9d97-0fd1e09fe7b9.png)
![image](https://user-images.githubusercontent.com/16837400/142772264-ac647293-b0ab-448e-9203-da1b293e03e8.png)
![image](https://user-images.githubusercontent.com/16837400/142772298-99666a4f-c0ba-4e7c-a704-e2a07e0088e0.png)
![image](https://user-images.githubusercontent.com/16837400/142772413-c0c077cd-94a2-4485-9bf1-8ca50fe3d2a6.png)

**Comment by eldering** [comment]
I now realize that you should just be able to use the jury/admin interface and make a GET request to `http://example.com/domjudge/jury/problems/<testcase_id>/delete_testcase`. You do need to be logged in as user with admin role.
@nickygerritsen @meisterT or @thijskh can you confirm that this is possible and how to do authentication?

I'm not too enthusiastic about adding this to the API. What do others think?

**Comment by nickygerritsen** [comment]
Authentication is a bit hard if you do not have IP or header auth enabled, since you need to submit the auth form with a CSRF token, but it can be done, see: https://github.com/DOMjudge/domjudge/blob/main/gitlab/integration.sh#L175-L178

And yes, afterwards you can indeed do the GET request.

**Comment by giampq** [comment]
Hi @eldering 
I have a limitation, requests from users will be done automatically, through our system's API
using the interface to login and delete test cases is not possible

and I see @nickygerritsen  solution seems to work fine in server environment, I'll try and get back to you as soon as possible

Thanks  for  support
Many thanks

**Comment by giampq** [comment]
I tried with a bash file, happy it works well, I will try to improve to delete multiple test cases at once
Thank @nickygerritsen  for suggesting the authentication method

![image](https://user-images.githubusercontent.com/16837400/143714330-41c1dbed-d681-4bce-80cf-2f43105020bd.png)

**Comment by giampq** [comment]
### Update
![image](https://user-images.githubusercontent.com/16837400/143719271-256a278d-a467-4137-8f42-7a4f3a12ddf0.png)

**Comment by giampq** [comment]
hi @thuvh 

Currently, I have no plans to make the source code public, because this is a product for a master's certificate
After completing the certificate, maybe I will plan to make the source code public

Best regards

**Comment by eldering** [comment]
> hi @thuvh
> 
> Currently, I have no plans to make the source code public, because this is a product for a master's certificate After completing the certificate, maybe I will plan to make the source code public
> 
> Best regards

Given that you wrote this with support here in an open-source project, it would be courteous to share this snippet of code.

Also the code is already visible in your screenshot, so anyone could just type it over, but would just have to put in some more effort. And in general, sharing code or other texts (like error messages) in screenshots is not the best way.

**Comment by giampq** [comment]
hi @thuvh 

Sorry for misunderstanding 
that code is runnable, but it doesn't make much sense, because we can't get the list of IDs of the test case in question (via Domjudge's API)

[bash-script.zip](https://github.com/DOMjudge/domjudge/files/7725814/bash-script.zip)


I ignored that case, and handled it in a different way
That code is only for usability testing, and it has no effect when applied in practice
because we lack quite a lot of APIs (ex: get test case IDs)

There aren't too many people having the same problem I'm having, I think this issue can be closed

Best regards
