### ISSUE TITLE
Repeated rejudgings don't always set endtime for all instances

### ISSUE THREAD

**Issue by meisterT** [DOMjudge/domjudge#1352]
If you repeat a rejudging say 10 times, all intermediate rejudgings should have an endtime set whenever this instance is done. Then it will also create the next repetition. Sometimes, one of the instances doesn't have an endtime set, but it's not reproducible.

Since we only show the latest instance of a repeated rejudging, this is not visible in the list of rejudgings, but it is shown in the menu bar as [1]

**Comment by nickygerritsen** [comment]
So it seems that for the one case we have left on the NWERC dump, the repeats was set to 10 but we have 11 rejudgings. The 10th one doesn't have an endtime.

I checked starttime for all 11 judgings and they have at least half a second between each, except the last two. There is only a 0.019 second diff between these two, which makes me think we somehow create two rejudgings somewhere approximately at the same time but then only set one to be the 'last one'. We create the new rejudging for a repeat here: https://github.com/DOMjudge/domjudge/blob/main/webapp/src/Controller/API/JudgehostController.php#L1162

I'm not sure what happens exactly though.
