### ISSUE TITLE
Send back to previous page instead of defined page on some forms

### ISSUE THREAD

**Issue by nickygerritsen** [DOMjudge/domjudge#1355]
For example when claiming or verifying a problem you get send back to the submission page. Better would be to send back to the referrer

**Comment by thijskh** [comment]
Better to ajaxify instead?

**Comment by nickygerritsen** [comment]
It *is* way harder to Ajaxify, but it might be the better thing yes. Redirecting to the referrer is easy, so let's do that for 8.x and then improve upon that later?

**Comment by thijskh** [comment]
How do you validate the referrer?

**Comment by nickygerritsen** [comment]
https://github.com/DOMjudge/domjudge/blob/main/webapp/src/Controller/BaseController.php#L84

We already have this logic
