### ISSUE TITLE
Create a view for queue tasks

### ISSUE THREAD

**Issue by vmcj** [DOMjudge/domjudge#1378]
As mentioned by @meisterT

**Comment by meisterT** [comment]
I don't think this is necessarily to be done before we can release 8.0

**Comment by meisterT** [comment]
But @tuupke started on it

**Comment by vmcj** [comment]
It was in the thread in Slack.

**Comment by tuupke** [comment]
I'll continue on this after fixing the last of my plumbing issues 🙃
