### ISSUE TITLE
Will not automatically jump to the homepage after logging in for the first time

### ISSUE THREAD

**Issue by Dup4** [DOMjudge/domjudge#1389]
NOTE: If this is a _discussion starter_, you need any _installation help_ or have a _question_ on how to accomplish something,
rather post at [our discussion channel](https://www.domjudge.org/chat) or send an email to our
[DOMjudge-devel mailinglist](https://www.domjudge.org/mailman/listinfo/domjudge-devel)
instead of filing an issue here.

### Description of the problem
> Replace this line with a short description.

https://user-images.githubusercontent.com/38343778/145698381-eae1036f-8baa-42db-aa50-69def89ab069.mp4

### Your environment
> Include details about your installation here.
> - DOMjudge version (e.g. 7.0.0 or a github commit hash)
> - Operating system / Linux distribution and version (e.g. Ubuntu 18.04)
> - Webserver (e.g. Apache or nginx)

- 8.0.0DEV
- Ubuntu 20.04
- Nginx

BTW, I use docker to run domserver

### Steps to reproduce
> Replace this with a description how we can reproduce your bug.
> - Step 1
> - Step 2
> - Step 3

### Expected behaviour
> Replace this line with what you would expect to happen.

After logging in, it should be automatically redirected to the homepage.

### Actual behaviour
> Replace this line with what happens instead.

Will not automatically jump to the homepage after logging in for the first time.

### Any other information that you want to share?
> Please include webserver, symfony and judgedaemon log snippets here as appropriate.
> Screenshots may help in case of UI bugs.

**Comment by thijskh** [comment]
I cannot reproduce this in a private window. Anything additional needed to trigger this? Does it happen for any account or maybe it depends on the configuration/roles of said account? Any special authentication settings you changed from the default?

**Comment by Dup4** [comment]
After your reminder, I checked my authentication settings, it looks like this:

![image](https://user-images.githubusercontent.com/38343778/145718098-f10c2951-a38b-45d3-b9aa-7f2e93da9fe9.png)

But when I turn off `ip autologin`, it will automatically redirect after entering the username and password

**Comment by vmcj** [comment]
Did you have an IP configured for your user?

**Comment by Dup4** [comment]
> Did you have an IP configured for your user?

For some users, some users do not.

**Comment by Dup4** [comment]
But sadly, I can't reproduce it either.

I don't know if it's because I re-pulled the code and built it before, so it can't be reproduced on the current version.

**Comment by vmcj** [comment]
> But sadly, I can't reproduce it either.
> 
> I don't know if it's because I re-pulled the code and built it before, so it can't be reproduced on the current version.

Let's re-open this when someone else also gets into this case.
