### ISSUE TITLE
The Servers in the API Doc of Swagger UI may be wrong

### ISSUE THREAD

**Issue by Dup4** [DOMjudge/domjudge#1395]
NOTE: If this is a _discussion starter_, you need any _installation help_ or have a _question_ on how to accomplish something,
rather post at [our discussion channel](https://www.domjudge.org/chat) or send an email to our
[DOMjudge-devel mailinglist](https://www.domjudge.org/mailman/listinfo/domjudge-devel)
instead of filing an issue here.

### Description of the problem
> Replace this line with a short description.

I tried to request the API in the API Doc, but it faield.

![image](https://user-images.githubusercontent.com/38343778/147023284-6bab29d3-5808-43e4-ad37-d93ab303eb90.png)

I found that the reason may be that the Server is incorrect.

![image](https://user-images.githubusercontent.com/38343778/147023373-c17ad555-610e-46d5-b2a4-704411bee6e2.png)

I access via `https`, but the server protocol in the API Doc is `http`, which may be the cause of the error.

But I found that it is normal in `demoweb`.

![image](https://user-images.githubusercontent.com/38343778/147023721-56eb4503-e762-4696-b2b2-846527913d05.png)

So it may be caused by my special deployment architecture.

![image](https://user-images.githubusercontent.com/38343778/147024188-3bfca9b9-8a71-463b-b0a6-22103b3689a5.png)

### Your environment
> Include details about your installation here.
> - DOMjudge version (e.g. 7.0.0 or a github commit hash)
> - Operating system / Linux distribution and version (e.g. Ubuntu 18.04)
> - Webserver (e.g. Apache or nginx)

- 8.0.0DEV
- Ubuntu20.04
- Nginx

BTW, I use docker to run DOMserver.

### Steps to reproduce
> Replace this with a description how we can reproduce your bug.
> - Step 1
> - Step 2
> - Step 3

### Expected behaviour
> Replace this line with what you would expect to happen.

### Actual behaviour
> Replace this line with what happens instead.

### Any other information that you want to share?
> Please include webserver, symfony and judgedaemon log snippets here as appropriate.
> Screenshots may help in case of UI bugs.

**Comment by nickygerritsen** [comment]
I'm thinking this is because we might not be passing `HTTPS on` correctly to the Docker container. I will investigate.

**Comment by nickygerritsen** [comment]
OK this was indeed true. How I fixed it:

Add this to `/etc/nginx/sites-enabled/default`:

```
map $http_x_forwarded_proto $fastcgi_param_https_variable {
    default $https;
    https 'on';
}
```

Add this to `/etc/nginx/snippets/domjudge-inner` below the existing `fastcgi_param` items:
```
        fastcgi_param HTTPS $http_x_forwarded_proto if_not_empty;
```

I wonder if it would hurt that we always do this? I don't think so but I'm not sure. If it doesn't hurt I can put it in our default snippets.

**Comment by Dup4** [comment]
Oops, Although it adds `https`, it has an extra port `80`.

![image](https://user-images.githubusercontent.com/38343778/147122307-939a6c72-5e9f-440b-bb62-f5ce31e1725a.png)


Below is my configuration:

`/etc/nginx/snippets/domjudge-inner`:

![image](https://user-images.githubusercontent.com/38343778/147121921-e4be5a98-cf9c-42e6-a340-b26152268271.png)

`/etc/nginx/sites-enabled/default.conf`:

![image](https://user-images.githubusercontent.com/38343778/147122085-a33f7a56-75cb-4b09-8d39-6d894a31203b.png)

`/etc/nginx/sites-enabled/default/domjudge.conf`:

![image](https://user-images.githubusercontent.com/38343778/147122145-1a96f497-00f9-4fe0-ac49-1324349bbb06.png)

**Comment by nickygerritsen** [comment]
Can you remove `:$server_port` from the `Host` `proxy_set_header`. I think it is because of that.

**Comment by Dup4** [comment]
Yes, you are right.

It works now.

![image](https://user-images.githubusercontent.com/38343778/147122922-ad2fa061-c9ad-4e58-bef8-0f8dbcfe9f13.png)

And I can make API requests normally:

![image](https://user-images.githubusercontent.com/38343778/147123010-cb525c2f-1e1a-4663-bbd4-027283d37cbb.png)

**Comment by Dup4** [comment]
```plain
        fastcgi_param HTTPS $http_x_forwarded_proto if_not_empty;
```

So it will be added to the default snippets?

**Comment by nickygerritsen** [comment]
That's my proposal. Do you think it will break anything? I don't think so since we still fall back to `$https` (which was the default before)

**Comment by Dup4** [comment]
Yes, I agree with you.

```plain
    fastcgi_param HTTPS $http_x_forwarded_proto if_not_empty;
```

It seems that if `$http_x_forwarded_proto` is not set, it will remain the same as before.
