### ISSUE TITLE
Whether there is a corresponding Grafana Dashboard Configuration?

### ISSUE THREAD

**Issue by Dup4** [DOMjudge/domjudge#1397]
I noticed that in `8.0.0DEV`, the `/api/v4/metrics/prometheus` has been added in https://github.com/DOMjudge/domjudge/pull/745.

This API interface can be used with **prometueus** to collect metrics data.

But I don't seem to find the corresponding **Grafana Dashboard Configuration**. 

BTW, **Grafana** can visualize the collected metrics data.

If there is no Grafana Dashboard Configuration, I may try to contribute one.

**Comment by nickygerritsen** [comment]
See here: https://github.com/DOMjudge/domjudge-scripts/tree/main/icpc-wf/ansible/files/grafana/dashboards
