### ISSUE TITLE
When a problem is set to not `allow judge` in a contest, then set to `allow judge`, then the submission during this period will not be judged later

### ISSUE THREAD

**Issue by Dup4** [DOMjudge/domjudge#1398]
NOTE: If this is a _discussion starter_, you need any _installation help_ or have a _question_ on how to accomplish something,
rather post at [our discussion channel](https://www.domjudge.org/chat) or send an email to our
[DOMjudge-devel mailinglist](https://www.domjudge.org/mailman/listinfo/domjudge-devel)
instead of filing an issue here.

### Description of the problem
> Replace this line with a short description.

In the process of testing https://github.com/DOMjudge/domjudge/issues/1396, I found another phenomenon, I don't know if it is a feature or a bug.

https://user-images.githubusercontent.com/38343778/147307620-7194fafa-cb58-4a27-9ae5-c94ffd099ef4.mp4

In the video we can observe that we set a certain problem not `allow judge`, then set to `allow judge`, the the submission during this period will not be judged later.

But subsequent submissions will be judged.

### Your environment
> Include details about your installation here.
> - DOMjudge version (e.g. 7.0.0 or a github commit hash)
> - Operating system / Linux distribution and version (e.g. Ubuntu 18.04)
> - Webserver (e.g. Apache or nginx)

- 8.0.0DEV
- Ubuntu20.04
- Nginx

BTW, I use docker to run DOMserver and judgehost.

### Steps to reproduce
> Replace this with a description how we can reproduce your bug.
> - Step 1
> - Step 2
> - Step 3

### Expected behaviour
> Replace this line with what you would expect to happen.

### Actual behaviour
> Replace this line with what happens instead.

### Any other information that you want to share?
> Please include webserver, symfony and judgedaemon log snippets here as appropriate.
> Screenshots may help in case of UI bugs.

**Comment by nickygerritsen** [comment]
@meisterT maybe because of queue tasks?
