### ISSUE TITLE
Detecting .R for R language does not work but lowercase works

### ISSUE THREAD

**Issue by melongist** [DOMjudge/domjudge#1408]
### Description of the problem

R extension file not linked to R language.

But, after adding r extension, R extension file linked to R language correctly.

### Your environment
- DOMjudge version : 7.3.4 stable
- Operating system : Ubuntu 20.04.3 LTS server
- Webserver : Apache

### Steps to reproduce

<img width="1440" alt="r1" src="https://user-images.githubusercontent.com/92401080/147875627-e14c708d-bbcc-47e5-af20-c8c7fda2094d.png">
<img width="1440" alt="r2" src="https://user-images.githubusercontent.com/92401080/147875632-a69cac5a-ae7b-49a7-adf7-0728d6a290be.png">
<img width="1440" alt="r3" src="https://user-images.githubusercontent.com/92401080/147875636-8e17af8f-74e1-4f4a-853a-18e29a51b9b6.png">
<img width="1440" alt="r4" src="https://user-images.githubusercontent.com/92401080/147875639-0b7788f2-7ed8-452c-8214-c78dc61e3931.png">

**Comment by vmcj** [comment]
> ### Description of the problem
> 
> R extension file not linked to R language.
> 
> But, after adding r extension, R extension file linked to R language correctly.
> ### Your environment
> 
>     * DOMjudge version : 7.3.4 stable
> 
>     * Operating system : Ubuntu 20.04.3 LTS server
> 
>     * Webserver : Apache
> 
> 
> ### Steps to reproduce
> 
> <img alt="r1" width="1440" src="https://user-images.githubusercontent.com/92401080/147875627-e14c708d-bbcc-47e5-af20-c8c7fda2094d.png">
> 
> <img alt="r2" width="1440" src="https://user-images.githubusercontent.com/92401080/147875632-a69cac5a-ae7b-49a7-adf7-0728d6a290be.png">
> 
> <img alt="r3" width="1440" src="https://user-images.githubusercontent.com/92401080/147875636-8e17af8f-74e1-4f4a-853a-18e29a51b9b6.png">
> 
> <img alt="r4" width="1440" src="https://user-images.githubusercontent.com/92401080/147875639-0b7788f2-7ed8-452c-8214-c78dc61e3931.png">

Did you check if you get the same problem for other languages? I can reproduce this for the main branch, so I'll look at a fix.

**Comment by melongist** [comment]
> Did you check if you get the same problem for other languages? I can reproduce this for the main branch, so I'll look at a fix.

I have used and tested the following programming languages, but it works fine except for the R programming language. :)

C, C++, Java, Javascript, Python3, swift

Thank you~ :)

**Comment by vmcj** [comment]
Could you check if it works for you to change:
https://github.com/DOMjudge/domjudge/blob/176994bceeb7f0b36bc034c043102c805f090515/webapp/templates/team/partials/submit_scripts.html.twig#L68

and remove the .toLowerCase there? This seems to fix the issue for me.

**Comment by eldering** [comment]
The problem is most likely that we assume that extension to language matching should be case-insensitive, but somewhere in code we don't handle the case (pun intended) correctly where the specified language extension is uppercase (like `R`).
