### ISSUE TITLE
Notification on new balloon

### ISSUE THREAD

**Issue by rbottema** [DOMjudge/domjudge#141]
When a new balloon needs to be delivered, the balloon status page should play a sound to trigger the runners.

**Comment by mvr320** [comment]
If I would try to implement something like this, would an accepted way be to:
Only send notifications when the page is open (https://developer.mozilla.org/en-US/docs/Web/API/Notifications_API/Using_the_Notifications_API) which stop working when the page is not open anymore (Under the assumption that when you open the balloon /jury/balloons page you're at a runner station)

Or the alternative:
check if the user has the role of balloon runner and if so send him/her these events which is I think more open to breaking as there is not the visual aspect of having the normal page open if/when the different type of notifications stops (I would try: (https://notifications.spec.whatwg.org/#service-worker-api) )

**Comment by nickygerritsen** [comment]
1️⃣

**Comment by thijskh** [comment]
Note we already have (1) in DOMjudge, so makes sense to extend to balloons

**Comment by mvr320** [comment]
I think https://github.com/DOMjudge/domjudge/pull/755 fixes this together with:
In firefox the sound seems to be not part of the notification this is known behaviour, for me on chromium the sound is there so if the sound should be there regardless the browser the <audio> should be added, but I'm against this as I think a browser is a personal choice.

**Comment by nickygerritsen** [comment]
Fixed by merging #755
