### ISSUE TITLE
Whether to consider adding `shellcheck` during Github Actions

### ISSUE THREAD

**Issue by Dup4** [DOMjudge/domjudge#1415]
I noticed that there are still quite a few `shell` scripts in the repo.

For example:

- https://github.com/DOMjudge/domjudge/blob/main/install-sh
- https://github.com/DOMjudge/domjudge/blob/main/judge/compile.sh

And I detected quite a few peoblems using `shellcheck-in-vscode`, such as the following figure:

![image](https://user-images.githubusercontent.com/38343778/148645090-914af960-3f40-4021-91ce-bfd82811d54b.png)

So consider adding `shellcheck` to Github Actions and try to fix these issues.

**Comment by vmcj** [comment]
We already have shellcheck in the Gitlab CI.

I prefer the tweaking we can do for the shellcheck via Gitlab, but if/when we move to more Github actions we can revisit this.

Would you accept this as answer for the issue or do you see more merit in doing this via GHA?

**Comment by Dup4** [comment]
It doesn't really matter if you use Github Actions or not.

It is important to use `shellcheck` to detect errors which in shell scripts and resolve them.

If you are more inclined to use **Gitlab CI**, then there is no problem.

But I don't seem to see the configuration of `shellcheck` in the [configuration file of Gitlab CI](https://github.com/DOMjudge/domjudge/blob/main/.gitlab-ci.yml).

And in the shell scripts in the repo, there are still some problems.

I tried to configure `shellcheck` in [my fork repo](https://github.com/Dup4/domjudge/runs/4748283761?check_suite_focus=true
), and it checked some errors.

**Comment by vmcj** [comment]
> But I don't seem to see the configuration of `shellcheck` in the [configuration file of Gitlab CI](https://github.com/DOMjudge/domjudge/blob/main/.gitlab-ci.yml).
You can find it here:
https://github.com/DOMjudge/domjudge/blob/main/tests/syntax

> I tried to configure `shellcheck` in [my fork repo](https://github.com/Dup4/domjudge/runs/4748283761?check_suite_focus=true), and it checked some errors.
Yes, yesterday I found the same issue and I was already in the process of addressing some of the issues.

**Comment by Dup4** [comment]
ok, I found it.

**Comment by eldering** [comment]
FYI: `install-sh` comes from the upstream `autoconf` project, it's out of scope for fixes.

**Comment by Dup4** [comment]
> FYI: `install-sh` comes from the upstream `autoconf` project, it's out of scope for fixes.

ok
