### ISSUE TITLE
If there is no active contest at this time, accessing the public page will return `500 Internal Server Error`

### ISSUE THREAD

**Issue by Dup4** [DOMjudge/domjudge#1417]
NOTE: If this is a _discussion starter_, you need any _installation help_ or have a _question_ on how to accomplish something,
rather post at [our discussion channel](https://www.domjudge.org/chat) or send an email to our
[DOMjudge-devel mailinglist](https://www.domjudge.org/mailman/listinfo/domjudge-devel)
instead of filing an issue here.

### Description of the problem

> Replace this line with a short description.

<img align="right" width="420px" src="https://user-images.githubusercontent.com/38343778/148668037-e115ce27-dc95-47e0-8c35-db621432c3c1.png">

When all contests are finished and all contests are inactive status, then go to the `public page(/domjudge/public)`, it will show `500 Internal Server Error`.

Shouldn't the expected result be that there are currently no active contests or something instead of showing `500 Internal Server Error`?

### Your environment

<img align="right" width="200px" src="https://user-images.githubusercontent.com/38343778/148667926-2cc15fb3-2e4d-453b-941b-e89e7f771349.png">

> Include details about your installation here.
> - DOMjudge version (e.g. 7.0.0 or a github commit hash)
> - Operating system / Linux distribution and version (e.g. Ubuntu 18.04)
> - Webserver (e.g. Apache or nginx)

- Ubuntu 20.04
- Nginx

### Steps to reproduce
> Replace this with a description how we can reproduce your bug.
> - Step 1
> - Step 2
> - Step 3

### Expected behaviour
> Replace this line with what you would expect to happen.

### Actual behaviour
> Replace this line with what happens instead.

### Any other information that you want to share?
> Please include webserver, symfony and judgedaemon log snippets here as appropriate.
> Screenshots may help in case of UI bugs.

**Comment by vmcj** [comment]
In short, we never expect a 500, so this is a bug.
