### ISSUE TITLE
Whether to consider adding Git Commit ID to System Informaion

### ISSUE THREAD

**Issue by Dup4** [DOMjudge/domjudge#1418]
<p align="center">

<img width="320px" src="https://user-images.githubusercontent.com/38343778/148670702-f93ed7b2-7ebc-4182-8497-f1d6985e1673.png">

</p>

Let's take a look at the current `System information`.

It contains a version of DOMjudge.

But does not contain the **Git Commit ID**.

This is actually not friendly to users who directly pull the code from Git and install it.

For example, we are using `8.0.0DEV`, but when reporting the problem, you cannot know exactly which commit we are based on.

May be some problems have been solved, but we have not re-pulled the code to update it.

**Comment by thijskh** [comment]
Good idea, make it so

**Comment by vmcj** [comment]
@Dup4 will you make a PR for this?

**Comment by Dup4** [comment]
> @Dup4 will you make a PR for this?

Okay, these days I'll finish my work first, then try it out.

**Comment by vmcj** [comment]
I'll close this issue as you added the feature in https://github.com/DOMjudge/domjudge/pull/1476.
