### ISSUE TITLE
Documentation: specify that installation is done from a release download, not git sources

### ISSUE THREAD

**Issue by muhmah-motahari** [DOMjudge/domjudge#1454]
in <a href="https://github.com/DOMjudge/domjudge/blob/main/doc/manual/install-domserver.rst">this document</a> that installation section is incorrect.
in the installation process, we can configure with the ```./configure``` command that where hasn't file with this name in the repository at all.

**Comment by nickygerritsen** [comment]
Note that if you want to run from the repository, you need to perform these steps: https://www.domjudge.org/docs/manual/8.0/develop.html#bootstrapping-from-git-repository-sources

But better if you are not planning to develop is to use a release build: https://www.domjudge.org/download
That does have the `configure` script.

**Comment by muhmah-motahari** [comment]
Thank you very much for your prompt replies
I'm also very happy that the issue I wrote about eventually improved your repository.
