### ISSUE TITLE
Scoreboard cache problems (4.0.3)

### ISSUE THREAD

**Issue by wmacevoy** [DOMjudge/domjudge#148]
The JSON document on upload does not match the traversal in the impexp_baylor.php script, and so fails to import teams.  The upload standings uses the rankcache_public table, so stale results are uploaded as final results.  The scoreboard_cache also seems to get out of date; when I first uploaded the results, I was presented stale results on the jury interface and uploaded those stale results to ICPC.

**Comment by eldering** [comment]
Without any more data (ideally tto reproduce it) this problem is not really fixable. Please reopen if any data is available.
