### ISSUE TITLE
Problem re-import does not overwrite/delete old testcases

### ISSUE THREAD

**Issue by edomora97** [DOMjudge/domjudge#1485]
### Description of the problem
When a problem is re-imported (either from the admin UI, or from the API) the old testcases which are not present in the new zip are not deleted. Also, if a testcase is updated the old version is not removed.

### Your environment
Latest main revision, started using `docker-compose up` from this repository.

### Steps to reproduce
Attached to this issue there is [tests.zip](https://github.com/DOMjudge/domjudge/files/8237658/tests.zip) which contains two versions of the same task:

- `first/test.zip` has 3 testcases: 1, 2, 3
- `second/test.zip` has 2 testcases: 1 (same as before), 2 (modified)

Import the first zip, and check that 3 testcases have been imported.

> `curl 'http://localhost:12345/api/v4/contests/2/problems' -H 'Authorization: Basic <redacted>' -H 'accept: application/json' -X POST -F zip=@tests/first/test.zip | jq`

Then, import the second task overwriting the first:

> `curl 'http://localhost:12345/api/v4/contests/2/problems' -H 'Authorization: Basic <redacted>' -H 'accept: application/json' -X POST -F zip=@tests/second/test.zip -F problem=4 | jq`

This is what it outputs to me:
```json
{
  "problem_id": "4",
  "messages": [
    "Added problem statement from: problem.pdf",
    "Skipped sample testcase 1: already exists",
    "Added 1 secret testcase(s): {2}.{in,ans}",
    "Added/updated 0 attachment(s).",
    "No jury solutions added: must associate team with your user first.",
    "Saved problem 4"
  ]
}
```

![image](https://user-images.githubusercontent.com/6685454/158019814-31a94b88-23bb-4d95-a344-2ef96c014c78.png)

### Expected behaviour
I expect that when a problem is reimported, the new version is exactly the version I've just uploaded. This is especially important when testing a task.

### Actual behaviour
A mix of old data and new data is present after the import, which doesn't make much sense from an API for importing a task.

### Any other information that you want to share?

Reported to me by @dario2994

**Comment by nickygerritsen** [comment]
Kinda related to #189.

I wonder if/how we should handle updating of testcases. An 'easy' way to do this is to first delete the problem of course.

I think currently it would also add attachments, never remove old ones. And it would resubmit jury submissions (which might not be bad).

**Comment by meisterT** [comment]
At least in the UI it is not completely obvious that deleting is the behavior you want. It's meant additive right now (which of course is up for debate).

I sometimes add additional test data in a zip. I wouldn't want it to be a destructive operation.


> This is especially important when testing a task.

For that I always delete the problem and start from scratch.

**Comment by meisterT** [comment]
For the API we could have an additional argument to indicate to delete old data first.

**Comment by dario2994** [comment]
> For the API we could have an additional argument to indicate to delete old data first.

This would be perfect. 
Keeping the same problem-id and not deleting submissions by contestants.
Please keep also the resubmission of jury-solutions (which is never going to be a problem).

**Comment by nickygerritsen** [comment]
> For the API we could have an additional argument to indicate to delete old data first.

We could also do this in the UI with a checkbox or dropdown (`Keep all existing testcases` vs `Remove testcases not present in ZIP`) or something. Same for attachments. Or one checkbox/dropdown for both together.

**Comment by dario2994** [comment]
> > For the API we could have an additional argument to indicate to delete old data first.
> 
> We could also do this in the UI with a checkbox or dropdown (`Keep all existing testcases` vs `Remove testcases not present in ZIP`) or something. Same for attachments. Or one checkbox/dropdown for both together.

I would suggest to have only one argument (and a checkbox) that tells whether the behavior is 'addition' (as it is now) or 'creation' (as required by this issue). It seems to me that it is not worth it to make it more fine-grained.

**Comment by nickygerritsen** [comment]
After thinking a bit I think I agree. I think it also makes it easier: if checked, first delete all testcases/attachments and then import. It will have new testcase ID's then but the advantage is that the order is what you expect without adding a lot of custom logic to find the correct spot and reorder testcases.

**Comment by nickygerritsen** [comment]
Added support for the boolean/checkbox in https://github.com/DOMjudge/domjudge/pull/1492
