### ISSUE TITLE
Make problem.externalid only unique within a contest

### ISSUE THREAD

**Issue by nickygerritsen** [DOMjudge/domjudge#1499]
Currently we require the externalid of a problem to be unique, since it can be added to multiple contests.
However @dario2994 suggested use cases where you have multiple problems with the same 'externalid' (i.e. ZIP filename for now until #1496 is implemented) but slightly different content, each in its own unique contest.

We could make problem.externalid non unique and then only check uniqueness when adding the problem to a contest.

Do we want this? Or do we think this will complicate things too much if we implement #1496?

**Comment by dario2994** [comment]
I think this is not necessary if #1496 is implemented.

**Comment by nickygerritsen** [comment]
I will leave the issue open for a bit if anyone else has other opinions. If not, I will close it.

**Comment by nickygerritsen** [comment]
Well, no one said anything for four weeks so I think it’s safe to close.
