### ISSUE TITLE
[Feature Request] Allow `DomJudge` To Report If Test Case Output Are Different Data Types

### ISSUE THREAD

**Issue by Rubix982** [DOMjudge/domjudge#1510]
### Description of the problem

If I create a problem, and then I add test cases, I may mistakenly (with human error) add test cases that have different output data types.

For example, if I create a test case `1`, with (`1.in`, `1.out`), and `2`, with (`2.in`, `2.out`), where `1.out` is,

```text
NO
```

And `2.out` is,

```text
2
```

The output of `1.out` is a `STRING` data type, and output of `2.out` is a `INTEGER`, then DomJudge should show a warning because of differing data types. 

### Your environment

Latest, but the feature request is independent.

### Steps to reproduce

Mentioned above.

### Expected behavior

DomJudge should give a warning.

### Actual behavior

No warning is currently generated.

### Any other information that you want to share?

Nope.

Anything else? Thank you for this awesome project!

**Comment by meisterT** [comment]
To be honest I don't think this should be a feature in DOMjudge.

We see problem validation beyond submitting and verifying jury solutions out of scope.

You may want to consider reporting this to https://github.com/Kattis/problemtools or https://github.com/RagnarGrootKoerkamp/BAPCtools instead.

**Comment by Rubix982** [comment]
Hmm, noted. That is another perspective I did not consider.

**Comment by eldering** [comment]
Also see https://www.domjudge.org/checktestdata which you can use to validate both test case input and output.
