### ISSUE TITLE
Possibility of removing/adding new file to executable

### ISSUE THREAD

**Issue by baziorek** [DOMjudge/domjudge#1526]
I'm using DOMjudge for academic teaching. I'm creating new executable for each problem, because I'm checking submissions with Unit Tests in C++.
Unfortunately it is really hard to make its many times, because:

1. sometimes I add file by accident - the only way to remove the file is to attach entire executable again, then correct language to use the new script
2. sometimes I forgot to add some file - the only way as above
3. sometimes in files are national characters e.g. "ąśćżźć" and the text file is detected as binary and I can't edit

Possibility of adding/removing file would solve all the problems above.

I'm using DOMjudge: 7.3.4

**Comment by baziorek** [comment]
Hi,
I see that it was done in commits:
1. https://github.com/DOMjudge/domjudge/pull/1539
2. https://github.com/DOMjudge/domjudge/pull/1535
3. https://github.com/DOMjudge/domjudge/pull/1536

Thanks really much for making easier to edit executables!

What should I do now - it looks that the issue is implemented, so should I close its?

**Comment by meisterT** [comment]
I'm not fully done yet improving and simplifying the interface

**Comment by meisterT** [comment]
Also what I just noticed when running another contest: we drop binary files (such as executables) when editing.

**Comment by eldering** [comment]
See also #1841

**Comment by meisterT** [comment]
This is how the executables overview looks like now:
![image](https://github.com/DOMjudge/domjudge/assets/418721/04694433-bde6-4825-a401-06dc3381b2e2)

Possible improvements:
- put the id in `code` tags
- separate out used from unused executables
- either use some fontawesome icon or similar to visually distinguish the executable type
- perhaps up for debate: for the currently selected contest, add problem badges where appropriate

**Comment by nickygerritsen** [comment]
I like all these. Maybe even a table per type?

**Comment by vmcj** [comment]
> I like all these. Maybe even a table per type?

If we do the table, would we still want the icon?
