### ISSUE TITLE
Submission for problem with 0 testcases never finishes

### ISSUE THREAD

**Issue by thijskh** [DOMjudge/domjudge#153]
When you submit a solution for a problem that has 0 testcases associated, the judgedaemon gives back no final result and the submission stays in 'judging' state indefinitely.

We could change the API not to output those submissions to judgedaemons, thereby making them implicitly allow-judge:0. This may not be that obvious.
An alternative is to let the judgedaemon give back an internal-error result when it finished judging without any testcase. This may be more explicit that something is wrong.

**Comment by eldering** [comment]
I prefer the first option (allow-judge=false). The other means that these submissions have to be rejudged after fixing the issue. Also "queued" or "judging" in the submission list doesn't make that much of a difference.

**Comment by eldering** [comment]
Conclusion from discussion: the long term implementation plan is to let judgedaemon give an internal-error response (not visible to teams) that will disable judging for relevant language, problem, etc. depending on what stage of judging failed.

**Comment by eldering** [comment]
Short-term solution: keep these submissions queued, i.e. don't expose them to judgedaemons.
Long-term solution: generate internal-error, then we still have to decide what happens next...
