### ISSUE TITLE
shadowing issues

### ISSUE THREAD

**Issue by vmcj** [DOMjudge/domjudge#1549]
During SWERC2021 we had the following issues during practice:
```
domjudge@s1:~$ /opt/domjudge/webapp/bin/console import:eventfeed 1

 
 [OK] Starting import. Press ^C to quit (might take a bit to be detected).
 

[------------------>---------] Read up to event 1150109:56:15 CRITICAL  [console] Error thrown while running command "import:eventfeed 1". Message: "No result was found for query although at least one row was expected." ["exception" => Doctrine\ORM\NoResultException^ { …},"command" => "import:eventfeed 1","message" => "No result was found for query although at least one row was expected."]

In SingleScalarHydrator.php line 28:
 
  No result was found for query although at least one row was expected.
 

import:eventfeed [-s|--from-start] [-k|--skip-event-id SKIP-EVENT-ID] [--] [<extsourceid>]
```

(Removed the already fixed issue)

**Comment by nickygerritsen** [comment]
The first thing is already fixed. It was a typo.

**Comment by nickygerritsen** [comment]
While implementing improvements to the event feed importer I couldn't reproduce the second thing. Maybe this strange problem ID mismatch had to do with it?

**Comment by vmcj** [comment]
> While implementing improvements to the event feed importer I couldn't reproduce the second thing. Maybe this strange problem ID mismatch had to do with it?

I think the server is still online but it makes sense that the problemID had something to do with it.

**Comment by vmcj** [comment]
I close this issue as we've shadowed NAC and didn't get this issue, it makes sense that due to problemid being different between primary and shadow with different imports we got these issues.
