### ISSUE TITLE
Add possibility of extending error view

### ISSUE THREAD

**Issue by baziorek** [DOMjudge/domjudge#1564]
I'm using DOMjudge for students' education as academic teacher.

When students are attaching submissions and there are compiler errors - it is really hard to find the error in the small window. Especially because patches are really long (here is not the worst example):    
![Screenshot 2022-05-02 at 06-55-57 Grzegorz Prowadzący - DOMjudge](https://user-images.githubusercontent.com/15332594/166186610-b78d9eec-d276-4002-af28-6d7faea614dd.png)

I suggest to add possibility of expand the "window" with compile log - it would make students' life with DOMjudge much easier. And also it would make teacher's life easier because teacher wouldn't have to tell students to copy to external text editor when they can't find the error.

Currently students are copying output to external text editor, but IMO it shouldn't be necessarily for that common problem.

On the opposite in JURY's view the output is to entire webpage so it is much easier to find error reason.

NOTE: I'm using C++, in the language compiler is adding multiple notes and pointing place of code to change, which is making lines even longer and errors harder to find.    
EDIT: Here is sample of longer patches (but is is still not worse case I ever seen):    
![obraz](https://user-images.githubusercontent.com/15332594/166187204-8e41adef-94ca-4cf2-8f37-4f96c5d89d4e.png)

EDIT2: I'm using DOMjudge: 7.3.4

**Comment by nickygerritsen** [comment]
I'm thinking maybe we should always make the popup wide when compilation output is shown?
