### ISSUE TITLE
Body data exceeded php.ini's 'post_max_size' directive (currently set to 8M) but files are really small (about 2kb)

### ISSUE THREAD

**Issue by baziorek** [DOMjudge/domjudge#1567]
NOTE: If this is a _discussion starter_, you need any _installation help_ or have a _question_ on how to accomplish something,
rather post at [our discussion channel](https://www.domjudge.org/chat) or send an email to our
[DOMjudge-devel mailinglist](https://www.domjudge.org/mailman/postorius/lists/domjudge-devel.domjudge.org/)
instead of filing an issue here.

### Description of the problem
I noticed that judgehost are dead after finding internal error:
```
[Apr 29 23:00:34.824] compile.sh[12150]: Compilation successful
[Apr 29 23:00:34.826] compile.sh[12150]: exiting, code = '0'
[Apr 29 23:00:34.828] judgedaemon[36]: API request PUT judgehosts/update-judging/judgedaemon-0-0/63826
[Apr 29 23:00:34.939] judgedaemon[36]: executing chroot script: 'chroot-startstop.sh start'
[Apr 29 23:00:34.988] judgedaemon[36]: Running testcase 1...
[Apr 29 23:00:34.998] testcase_run.sh[12254]: starting '/opt/domjudge/judgehost/lib/judge/testcase_run.sh', PID = 12254
[Apr 29 23:00:35.000] testcase_run.sh[12254]: arguments: '/opt/domjudge/judgehost/judgings/judgedaemon-0-0/endpoint-default/testcase/testcase.13.1.86b4410b7b71c9c6a461c3a2a3cf610c.in' '/opt/domjudge/judgehost/judgings/judgedaemon-0-0/endpoint-default/testcase/testcase.13.1.4e3483205056b79ea8bb246a828e367e.out' '10:11' '/opt/domjudge/judgehost/judgings/judgedaemon-0-0/endpoint-default/14/5634/63826/testcase001'
[Apr 29 23:00:35.001] testcase_run.sh[12254]: optionals: '/opt/domjudge/judgehost/judgings/judgedaemon-0-0/endpoint-default/executable/run/run' '/opt/domjudge/judgehost/judgings/judgedaemon-0-0/endpoint-default/executable/compare/run' ''
[Apr 29 23:00:35.006] testcase_run.sh[12254]: setting up testing (chroot) environment
[Apr 29 23:00:35.016] testcase_run.sh[12254]: creating /dev/null character-special device
[Apr 29 23:00:35.023] testcase_run.sh[12254]: running program
[Apr 29 23:00:35.025] testcase_run.sh[12254]: runcheck: /opt/domjudge/judgehost/judgings/judgedaemon-0-0/endpoint-default/executable/run/run testdata.in program.out sudo -n /opt/domjudge/judgehost/bin/runguard -V TMPDIR=/testcase001/write_tmp -P 0 -r /opt/domjudge/judgehost/judgings/judgedaemon-0-0/endpoint-default/14/5634/63826/testcase001/.. --nproc=64 --no-core --streamsize=8192 --user=domjudge-run-0 --group=domjudge-run --walltime=10:11 --cputime=10:11 --memsize=2097152 --filesize=8192 --stderr=program.err --outmeta=program.meta -- /testcase001/execdir/program
[Apr 29 23:00:46.265] testcase_run.sh[12254]: comparing output
[Apr 29 23:00:46.267] testcase_run.sh[12254]: starting compare script '/opt/domjudge/judgehost/judgings/judgedaemon-0-0/endpoint-default/executable/compare/run'
[Apr 29 23:00:46.270] testcase_run.sh[12254]: runcheck: sudo -n /opt/domjudge/judgehost/bin/runguard -P 0 -u domjudge-run-0 -g domjudge-run -m 2097152 -t 60 -c -f 2621440 -s 2621440 -M compare.meta -- /opt/domjudge/judgehost/judgings/judgedaemon-0-0/endpoint-default/executable/compare/run testdata.in testdata.out feedback/
[Apr 29 23:00:46.323] testcase_run.sh[12254]: checking compare script exit-status: 43
[Apr 29 23:00:46.325] testcase_run.sh[12254]: checking program run exit-status
[Apr 29 23:00:46.341] testcase_run.sh[12254]: exiting with status '102'
[Apr 29 23:00:46.398] judgedaemon[36]: API request POST judgehosts/add-judging-run/judgedaemon-0-0/63826
[Apr 29 23:00:46.510] judgedaemon[36]: warning: Error while executing curl POST to url https://domjudge.labagh.pl/api/v4/judgehosts/add-judging-run/judgedaemon-0-0/63826: http status code: 400, request size = 11186126, response: {"code":400,"message":"Body data exceeded php.ini's 'post_max_size' directive (currently set to 8M)"}
```
But I checked the submission - it is really small:
[s5634.zip](https://github.com/DOMjudge/domjudge/files/8610879/s5634.zip)

To investigate I'm also attaching problem:
[DoubleObject, StringObject.zip](https://github.com/DOMjudge/domjudge/files/8610902/DoubleObject.StringObject.zip)

and compile script (it is not clean version to be shown in public):
[cpp.zip](https://github.com/DOMjudge/domjudge/files/8610906/cpp.zip)

### Your environment
> Include details about your installation here.
> - DOMjudge version 7.3.4
> - Operating system / Linux distribution and version: Fedora
> - nginx for DomServer, Docker for Domjudge

### Steps to reproduce
Each time the student is attaching his solution (even after changes) there is the same problem. Rest of student are not killing judgehost.

### Expected behaviour
Submission is being compiled

### Actual behaviour
As described above

### Any other information that you want to share?
To keep judgehost alive I needed to ignore submissions:
![obraz](https://user-images.githubusercontent.com/15332594/166467402-e0fe3778-788e-4c6c-96e7-ef9c644c1434.png)

**Comment by baziorek** [comment]
> This step is uploading the testcase result output to DOMjudge. This can exceed 8M. There is a configuration setting to limit the testcase output (upload), which you could set to <8M to prevent this. But you could also increase the upload size if you want the full testcase result contents.

Thanks a lot! Yeah - there were infinite output:D. But what do You think about making the error message more verbose? In future I'll know, but maybe somebody else is using the tool for education and his students will send task with infinite output:).

**Comment by thijskh** [comment]
One challenge in making the message more explicit is that this message is generic for all our endpoints.

**Comment by baziorek** [comment]
> One challenge in making the message more explicit is that this message is generic for all our endpoints.

I see. For me it is just nice-to-have feature, because now I know what can be reason for the problem in that situations. But for new people it can be problem. So it there are no plans to make message more explicit I think that the issue can be closed.

**Comment by eldering** [comment]
Closing this, as the original problem was resolved and there's no immediate thing to improve here.
