### ISSUE TITLE
combined_scoreboard is broken

### ISSUE THREAD

**Issue by thijskh** [DOMjudge/domjudge#157]
DOMjudge 4.0 removed the XML plugin interface, on which `combined_scoreboard` completely depends. It needs to be converted to use the current API interface.

**Comment by nickygerritsen** [comment]
I could try to fix this :). How to handle the fact that multiple contests could be active? One option is to only show the first contest of every location?

**Comment by nickygerritsen** [comment]
Or we could also add contest-ID or -shortname to the array of scoreboard to fetch

**Comment by thijskh** [comment]
Indeed make it possible to specify it explicitly; otherwise it could maybe fall back to the 'default' (as presented by the API)?
