### ISSUE TITLE
Running configure script as root causes invalid user errors during make install-judgehost process

### ISSUE THREAD

**Issue by machitgarha** [DOMjudge/domjudge#1571]
### Description

When installing from a tarball (or perhaps git source), when building a judgehost environment, running `./configure` as root user causes `make install-judgehost` to fail with a bunch of `invalid user` errors (errors stripped):

```raw
# make install-judgehost
...
make[1]: Leaving directory '/root/domjudge-8.0.0/misc-tools'
make[1]: Entering directory '/root/domjudge-8.0.0'
make check-root
make[2]: Entering directory '/root/domjudge-8.0.0'
make[2]: Leaving directory '/root/domjudge-8.0.0'
/usr/bin/install -c -m 0644 -o  -m 0700 -d /home/domjudge/judgehost/log
/usr/bin/install: invalid user ‘-m’
make[1]: [Makefile:138: install-judgehost-l] Error 1 (ignored)
/usr/bin/install -c -m 0644 -o  -m 0700 -d /home/domjudge/judgehost/run
/usr/bin/install: invalid user ‘-m’
make[1]: [Makefile:139: install-judgehost-l] Error 1 (ignored)
/usr/bin/install -c -m 0644 -o  -m 0711 -d /home/domjudge/judgehost/judgings
/usr/bin/install: invalid user ‘-m’
make[1]: [Makefile:140: install-judgehost-l] Error 1 (ignored)
/usr/bin/install -c -m 0644 -o  -m 0700 -d /home/domjudge/judgehost/tmp
/usr/bin/install: invalid user ‘-m’
make[1]: [Makefile:141: install-judgehost-l] Error 1 (ignored)
/usr/bin/install -c -m 0644 -o  -m 0600 -t /home/domjudge/judgehost/etc \
	etc/restapi.secret
/usr/bin/install: invalid user ‘-m’
make[1]: [Makefile:142: install-judgehost-l] Error 1 (ignored)
make[1]: Leaving directory '/root/domjudge-8.0.0'
```

Running `./configure` as a non-root user fixes the problem.

I personally think the problem relates to the `$(DOMJUDGE_USER)` variable in Makefile, however, not knowing what actually causes the error to happen.

Note that, running `./configure` as root is useful in a Docker container, as root is the default user. 

### Your environment

- DOMjudge version: 8.0.0
- Fedora 35 on Docker (20.10.12)

### Steps to reproduce

1. Login as the user `root`.
2. Run `./configure --prefix=/somewhere`.
3. Run `make judgehost`.
4. Run `make install-judgehost`.

### Expected behaviour

Successful build.

### Actual behaviour

Bunch of `invalid user '-m'` errors.

**Comment by nickygerritsen** [comment]
`./configure --help` shows:
```
[...]
Fine tuning of file ownership:
  --with-domjudge-user=USER
                          User that owns password files (default: current
                          user).
[...]
```

But we might want to improve our configure script to not allow running as root *without* that flag.

**Comment by machitgarha** [comment]
Thanks for the help!

Isn't [this line](https://github.com/DOMjudge/domjudge/blob/main/configure.ac#L70) supposed to do that? If so, why it does not get triggered?

**Comment by nickygerritsen** [comment]
Hey you are right. @eldering you are our build system guy. Do you know why it wouldn't work?

**Comment by eldering** [comment]
I'll look into it. First need to reproduce this myself.

**Comment by eldering** [comment]
When I run this as root, I get
```
# ./configure --prefix=/tmp/domjudge-install
checking whether configure should try to set CFLAGS... yes
checking whether configure should try to set CXXFLAGS... yes
checking whether configure should try to set LDFLAGS... yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether C compiler accepts -Wall... yes
checking whether C compiler accepts -fstack-protector... yes
checking whether C compiler accepts -fPIE... yes
checking whether C compiler accepts -D_FORTIFY_SOURCE=2... yes
checking whether the linker accepts -fPIE... yes
checking whether the linker accepts -pie... yes
checking whether the linker accepts -Wl,-z,relro... yes
checking whether the linker accepts -Wl,-z,now... yes
checking domjudge-user... configure: error: installing/running as root is STRONGLY DISCOURAGED, use --with-domjudge-user=root to override.
```
as expected.

@machitgarha what is the output of `id`?

**Comment by machitgarha** [comment]
Oops, sorry for my really late answer (maybe accidentally ignored its notification).

The output is:

```
uid=0(root) gid=0(root) groups=0(root)
```

Not sure if it's already fixed in current master, so I should try once again.

**Comment by vmcj** [comment]
$USER is not always set correctly inside podman (and probably docker)
