### ISSUE TITLE
Submissions list and run response

### ISSUE THREAD

**Issue by anatoly-kryzhanovsky** [DOMjudge/domjudge#1573]
there are a several question about api:
- if i try to get submissions list via team user (role team member) with request `GET /api/v4/contests/{cid}/submissions` i receive submissions for all teams (there are submission for different `team_id`). i think that it is a security lack. 
- i cannot find way how to get judgement output - i.e if there is compilation error i would like to receive compiler output, but there is no method for that

**Comment by meisterT** [comment]
You should only see data as a team that you can also see on the scoreboard. I need to verify but I think this was the intention.

For the new API: what's your use case? Are you wrapping DOMjudge into another system?

**Comment by anatoly-kryzhanovsky** [comment]
1) o i see, but can i filter submission only for current team? may be additional request parameter?
2) yes - i want to create contest inside our company by custom rule - every day at specified time participant receive new task. so i need only judgement process (compile and run test) process, but score calculation and scoreboard i implemented by my self.

**Comment by meisterT** [comment]
We don't want to modify DOMjudge's code to allow this.

There are two options for you:
- Add the necessary data yourself by implementing a patch to your own DOMjudge installation (e.g. by extending https://github.com/DOMjudge/domjudge/blob/main/webapp/src/Controller/API/JudgementController.php).
- Implement the judgehost API in your wrapper. That's what I did ~10 years ago when I had a similar scenario where I only needed the backend / judging logic.
