### ISSUE TITLE
Results more configurable and more expressive in scoreboard

### ISSUE THREAD

**Issue by baziorek** [DOMjudge/domjudge#1578]
I have two suggestions, which IMO would be nice-to-have but it is still possible to use DOMjudge without them. Of course in real life often we don't know that it would be good to have something tells us about them:).
1. Add possibility to change colors of results.
2. Add possibility to add extra statuses in easier way.

Those two suggestions in short words it would be something like this (it is just draft, in real world it would look better):
![proposition](https://user-images.githubusercontent.com/15332594/168450603-965ee7ea-9cc6-4a56-abe4-f8bd585237b0.png)
instead of:
![obraz](https://user-images.githubusercontent.com/15332594/168450252-a4587366-e2f7-4e4f-b991-a86d1eb16e48.png)

1. I'm using DOMjudge for students' education as academic teacher. Sometimes students does not see different between compilation error and run error - this is red and this is red and of course "it is working in my computer". Even better students when they have run-error are trying to find compile-errors in warnings. Similar situation is when there is timeout, or crashes. It would be easier for them to see what is happening when there would be possibility to see different not successful reasons in different colors (currently there is only red or green). Also it would be easier for teacher to check submitted exercises when there would be different colors - currently in scoreboard I see red and I need to click always and check how many points should I give for a student. With colors when I see compiler error it won't be necessarily. I know that is is not much to click few few times, but there are about 200 students for single teacher, it would help much to have those colors:).
2. Few days ago I've [asked in domjudge's chat](https://domjudge-org.slack.com/archives/CHHURFUM7/p1647783137946299) how to add extra statuses. The answer was to modify `etc/judgehost-static.php.in`, `judge/compile.sh`, `judge/testcase_run.sh` + update executables. But I think it would be nice to have configurable options included in the tool (examples, where it would be usefull: https://github.com/DOMjudge/domjudge/issues/1487). IMO it would be usefull not only for academic use, but I remember some competitions where e.g. there was forbidden `new` usage - it is not compiler error, but the message should be explicit.

**What do You think about those ideas?**
_________
I'm using DOMjudge: 7.3.4

**Comment by vmcj** [comment]
> I have two suggestions, which IMO would be nice-to-have but it is still possible to use DOMjudge without them. Of course in real life often we don't know that it would be good to have something tells us about them:).
> 
>     1. Add possibility to change colors of results.
> 
>     2. Add possibility to add extra statuses in easier way.
> 
> 
> Those two suggestions in short words it would be something like this (it is just draft, in real world it would look better): ![proposition](https://user-images.githubusercontent.com/15332594/168450603-965ee7ea-9cc6-4a56-abe4-f8bd585237b0.png) instead of: ![obraz](https://user-images.githubusercontent.com/15332594/168450252-a4587366-e2f7-4e4f-b991-a86d1eb16e48.png)
> 
>     1. I'm using DOMjudge for students' education as academic teacher. Sometimes students does not see different between compilation error and run error - this is red and this is red and of course "it is working in my computer". Even better students when they have run-error are trying to find compile-errors in warnings. Similar situation is when there is timeout, or crashes. It would be easier for them to see what is happening when there would be possibility to see different not successful reasons in different colors (currently there is only red or green). Also it would be easier for teacher to check submitted exercises when there would be different colors - currently in scoreboard I see red and I need to click always and check how many points should I give for a student. With colors when I see compiler error it won't be necessarily. I know that is is not much to click few few times, but there are about 200 students for single teacher, it would help much to have those colors:).
Alternative would be to add an extra icon for this, because to me green means good, red means bad but what other colors should we pick which are easy to distinguish from each other and are also "always" interpreted as "wrong" results?
> 
>     2. Few days ago I've [asked in domjudge's chat](https://domjudge-org.slack.com/archives/CHHURFUM7/p1647783137946299) how to add extra statuses. The answer was to modify `etc/judgehost-static.php.in`, `judge/compile.sh`, `judge/testcase_run.sh` + update executables. But I think it would be nice to have configurable options included in the tool (examples, where it would be usefull: [Possibity of adding extra steps for sent submissions #1487](https://github.com/DOMjudge/domjudge/issues/1487)). IMO it would be usefull not only for academic use, but I remember some competitions where e.g. there was forbidden `new` usage - it is not compiler error, but the message should be explicit.
> 
I would think that is part of the run-error, but my advice is to split this up in another issue to make the discussion about this easier.
> 
> **What do You think about those ideas?**
> 
> I'm using DOMjudge: 7.3.4

I think both are interesting discussions, are you willing to split those in 2 separate issues? Even if we choose to not implement is it can be used as documentation why we don't implement this (yet).

**Comment by baziorek** [comment]
> I think both are interesting discussions, are you willing to split those in 2 separate issues? Even if we choose to not implement is it can be used as documentation why we don't implement this (yet).

Of course there can be two separate issues. I don't know how Your development process is working, so should I now create two issues here and close this one?

**Comment by eldering** [comment]
> > I think both are interesting discussions, are you willing to split those in 2 separate issues? Even if we choose to not implement is it can be used as documentation why we don't implement this (yet).

Just create two separate issues. You can refer to this issue in them, but then we'll close this one. This doesn't have much to do with development, but just so we don't mix discussions about separate topics in a single issue.

**Comment by baziorek** [comment]
> > > I think both are interesting discussions, are you willing to split those in 2 separate issues? Even if we choose to not implement is it can be used as documentation why we don't implement this (yet).
> 
> Just create two separate issues. You can refer to this issue in them, but then we'll close this one. This doesn't have much to do with development, but just so we don't mix discussions about separate topics in a single issue.

I've created two separate issues linked to this one:
1. https://github.com/DOMjudge/domjudge/issues/1579
2. https://github.com/DOMjudge/domjudge/issues/1580

**Comment by eldering** [comment]
Closing in favour the 2 separate issues.
