### ISSUE TITLE
Python 2 judging problem

### ISSUE THREAD

**Issue by littleali** [DOMjudge/domjudge#158]
I've deployed a domserver and a judgehost on my vps (ubuntu 12.04).
When I want to submit python codes I get this error : 
python: error while loading shared libraries: libm.so.6: failed to map segment from shared object: Cannot allocate memory
I've created chroot from manual and changed the judgehost-config.php file to use chroot.
What can I do for this ?
Codes in other languages works fine.

**Comment by meisterT** [comment]
Probably you have to increase the memory limit. Log in as admin user, go to configuration settings and increase the value there.

**Comment by littleali** [comment]
That was the problem!
Thanks
