### ISSUE TITLE
Add possibility to add extra statuses in easier way

### ISSUE THREAD

**Issue by baziorek** [DOMjudge/domjudge#1580]
I'm academic teacher, who is using DOMjudge 7.3.4. I've suggested two nice-to-have features of DOMjudge, which were published in issue: https://github.com/DOMjudge/domjudge/issues/1578. I was suggested to split those two ideas into two issues.
________________
Few days ago I've [asked in domjudge's chat](https://domjudge-org.slack.com/archives/CHHURFUM7/p1647783137946299) how to add extra statuses. The answer was to modify `etc/judgehost-static.php.in`, `judge/compile.sh`, `judge/testcase_run.sh` + update executables. But I think it would be nice to have configurable options included in the tool (examples, where it would be usefull: https://github.com/DOMjudge/domjudge/issues/1487). IMO it would be usefull not only for academic use, but I remember some competitions where e.g. there was forbidden new usage - it is not compiler error, but the message should be explicit.
________________
**What do You think about the idea?**

**Comment by eldering** [comment]
We've discussed this internally and since extra custom logic would be required for each such status, we don't think it's worth the complexity to add these. Of course you can add whichever custom statuses you want in your own installation.
