### ISSUE TITLE
Some `CSS` is not working properly

### ISSUE THREAD

**Issue by Dup4** [DOMjudge/domjudge#1582]
NOTE: If this is a _discussion starter_, you need any _installation help_ or have a _question_ on how to accomplish something,
rather post at [our discussion channel](https://www.domjudge.org/chat) or send an email to our
[DOMjudge-devel mailinglist](https://www.domjudge.org/mailman/postorius/lists/domjudge-devel.domjudge.org/)
instead of filing an issue here.

### Description of the problem
> Replace this line with a short description.

I pulled the latest code, built the image, run it, and found that the UI has changed. 

I suspect that some CSS is not loaded correctly.

<img width="1714" alt="image" src="https://user-images.githubusercontent.com/38343778/169187389-b896ef16-ad49-4417-b4cb-5d4772b14056.png">

* You can see from Chrome's developer interface that no resource fails to load.
* Every link in the admin interface is underlined.
* Dropdown box not working.

### Your environment
> Include details about your installation here.
> - DOMjudge version (e.g. 7.0.0 or a github commit hash)
> - Operating system / Linux distribution and version (e.g. Ubuntu 18.04)
> - Webserver (e.g. Apache or nginx)

* 8.1.0DEV/e1e2adc
* Ubuntu20.04
* Nginx

### Steps to reproduce
> Replace this with a description how we can reproduce your bug.
> - Step 1
> - Step 2
> - Step 3

### Expected behaviour
> Replace this line with what you would expect to happen.

### Actual behaviour
> Replace this line with what happens instead.

### Any other information that you want to share?
> Please include webserver, symfony and judgedaemon log snippets here as appropriate.
> Screenshots may help in case of UI bugs.

Maybe it's related to the dependency upgrade a few days ago.

![image](https://user-images.githubusercontent.com/38343778/169187691-ff76845c-fbae-4853-a7c0-30c0ea0bb346.png)

**Comment by vmcj** [comment]
Hi @Dup4, sorry for the late response.

I've reverted part of those commits and I think everything works again. I'll close this issue for now but feel free to reopen if I missed something.
