### ISSUE TITLE
Add way to download static scoreboard with all linked files

### ISSUE THREAD

**Issue by nickygerritsen** [DOMjudge/domjudge#1595]
Add an export to export the static scoreboard together with:
* All CSS
* All Javascript
* All images
* A way to view team pages, either creating separate pages or doing something smart with some JSON. The latter is probably cleaner

Requested by @verwoerd and I like the idea.

**Comment by thijskh** [comment]
Is this not just documenting the right wget/curl/... invocation that will do just this?

**Comment by nickygerritsen** [comment]
Not really. First of all you also need CSS/JS. This you *could* do with some wget flag but is that ideal?
Second: we use absolute URL's for these CSS/JS and images (i.e. starting with `/`), while you might want to put the code on a different page. We could *maybe* change that in the Twig templates but I'm not sure.
Second: you either need to remove all `<a href>` link to team detail pages or find a way to also get them. They are in a 'subdir' in DOMjudge. This is one of the reasons we use absolute URL's for JS/CSS/images, but if you want those pages, you need a way to fix this.

For SWERC I once did this by writing a script that downloads all pages and did some regex replaces on it. But this was very ad-hoc.
