### ISSUE TITLE
Partial scoring

### ISSUE THREAD

**Issue by karimjouini** [DOMjudge/domjudge#161]
Hello,

I started experimenting DOMJudge recently, great job !

I am wondering if there is a way to make it give partial scores (like IOI) ?

Thanks,
Karim

**Comment by thijskh** [comment]
Hi Karim,

This is not currently supported out of the box. Please see this thread on the domjudge-devel mailinglist for some more background on the issue: https://lists.a-eskwadraat.nl/pipermail/domjudge-devel/2014-August/001501.html You are very welcome to contribute to implementing something like that as described in that thread.

Note that the mailing list is the right place to discuss such things, so I'm closing the issue.

Cheers,
Thijs

**Comment by ironmaniiith** [comment]
Hi @thijskh 
Any update over this issue? Also I'm unable to open the link given above, so could you post the current link where this thing can be discussed?

Thanks

**Comment by thijskh** [comment]
I've updated the URL above.
