### ISSUE TITLE
Error creating user for new team: create-new-user set as username

### ISSUE THREAD

**Issue by GugolPlex** [DOMjudge/domjudge#1612]
### Description of the problem

When creating a new team and a new user for it ("Create new user" is set in the "Add user to this team" combobox) the new user gets "create-new-user" as username instead of the "username" value filled in the form.

### Your environment

- DOMjudge version: 8.1
- Operating system: Debian 11.3
- Webserver: nginx +  php-fpm

### Steps to reproduce

- Teams - Add new team
- Fill in the form, for example:
  - Team name: test
  - Display name: test
  - Category: System
  - Public description: [emtpy]
  - Affiliation: -- no affiliation --
  - Penalty time: 0
  - Location: [empty]
  - Internal comments: [empty]
  - Contests: [empty]
  - Enabled: yes
  - Add user to this team: Create new user
  - Username: test
  - Photo: empty

In the new team description, the associated user will be "create-new-user" instead of "test". The user details show that the name of the user is, correctly, "test", but the username is "create-new-user".

This means that team members must use "create-new-user" for login. As username must be unique, no other team+user can be created if the username is not changed. But the frontend does not allow to change the username of a created user, show dababase access is needed to solve this issue (```UPDATE user SET username=name WHERE username='create-new-user';```)

### Expected behaviour

The user created for the team has "test" as username, so teams members use "test" in the login page.

### Actual behaviour

The user created for the team has "create-new-user" as username instead.

**Comment by vmcj** [comment]
@GugolPlex can you verify that this was fixed in the last released version (8.1.1)?

I'll close this already but feel free to reopen if the issue still persists.
