### ISSUE TITLE
Judge all test files on request even if lazy eval is enabled

### ISSUE THREAD

**Issue by meisterT** [DOMjudge/domjudge#162]
With lazy evaluation, judging stops at the first error with highest priority.

Sometimes, it's useful to have the possibility to request the judgement for all test files for a single submission even if lazy evaluation is enabled for that problem.

**Comment by nickygerritsen** [comment]
We could use the same button from #540 (which is probably stored as a field in the `submission` table or something)

**Comment by meisterT** [comment]
I think this requires another field in judgetask entity to indicate that you want to continue the remainder of tasks even if a previous one (out of the outstanding, requested test cases) has failed.
