### ISSUE TITLE
Windows-zipped executables cannot be run by Judgehost

### ISSUE THREAD

**Issue by alfphaderp** [DOMjudge/domjudge#1628]
### Description of the problem
> Executables zipped on a Windows machine contain build and run scripts that cannot be run by Judgehost. This is because Windows does not have/preserve *nix permission bits when compressing (at least not using the right click > Compress to Zip File option).

### Your environment
> - DOMjudge version 7.3.3
> - Windows 11 to zip executable, Ubuntu 20.04 to run Judgehost
> - Apache

### Steps to reproduce
> - On the Windows machine, create a simple compare executable with an empty build script and run script that always exits with 43
> - Move both build and run scripts into a directory, right click, and compress to zip file
> - As admin, upload the zip file as a new executable using the web interface
> - As admin, create a new problem with the new executable as the compare script, add it to a new contest, and enable it for judging
> - As user, submit any program to the new problem.

### Expected behaviour
> The user account should receive a wrong answer verdict no matter what they submit.

### Actual behaviour
> An internal error occurs: `fetching executable failed for compare script 'wa_cmp': Invalid executable, file 'build' exists but is not executable.`

### Any other information that you want to share?
> I was able to circumvent this issue for now by running WSL and using its linux zip command instead. Doing that produced an executable with preserved permissions.

**Comment by nickygerritsen** [comment]
We should either:
* add documentation that build/run **needs** to be executable and that windows ZIP does not do this; or
* always automatiaclly add the executable bit to build/run

I don't know why we don't the the last option currently, but probably there is a good reason for it?

**Comment by thijskh** [comment]
No problem to set them to executable after unzipping.
