### ISSUE TITLE
Problem with reported submission times in private contests in version 4.1.0 DEV

### ISSUE THREAD

**Issue by corneym** [DOMjudge/domjudge#168]
The scoreboard times for problems submitted in a private contest are reported as very large numbers (e.g. 23939991) and not as the number of minutes since the start of the contest.  If the scoreboard caches are recalculated through Home, Administrator, Refresh scoreboard cache, the correct submission times are then reported on the scoreboard.

If you take the reported time, multiply by 60 and using ctime, the result is the correct time and date of the submission.

**Comment by meisterT** [comment]
Fixed with 9f088ce38f5ce9abc64617681f887508ebdf329a.
