### ISSUE TITLE
Updating a problem zip shows info alert with "Array Array Array"

### ISSUE THREAD

**Issue by mpsijm** [DOMjudge/domjudge#1708]
### Description of the problem
Updating a problem zip shows info alert with "Array Array Array".
![image](https://user-images.githubusercontent.com/9739541/195858264-278f0a18-5569-41bb-850c-277ea9154003.png)

### Your environment
- DOMjudge version: 8.2.0DEV/f78205c8c
- Operating system / Linux distribution and version: probably Linux (I don't manage the hardware)
- Webserver: N/A (I don't manage the hardware)

### Steps to reproduce
- Go to an existing problem
- Edit the problem
- Upload a new problem zip

### Expected behaviour
- This info alert used to show things like "# test data uploaded, # submissions uploaded"

### Actual behaviour
- The info alert is shown as in the screenshot above.

**Comment by meisterT** [comment]
I don't have time to dig into this now, but I can imagine this is coming from https://github.com/DOMjudge/domjudge/commit/56c4ecb4468376afc819799a8ff06ad698f91426

Is is possible that you updated the server code recently but didn't delete the twig cache?

**Comment by nickygerritsen** [comment]
> I don't have time to dig into this now, but I can imagine this is coming from [56c4ecb](https://github.com/DOMjudge/domjudge/commit/56c4ecb4468376afc819799a8ff06ad698f91426)
> 
> Is is possible that you updated the server code recently but didn't delete the twig cache?

It's my server but yes that could be.

**Comment by nickygerritsen** [comment]
> > I don't have time to dig into this now, but I can imagine this is coming from [56c4ecb](https://github.com/DOMjudge/domjudge/commit/56c4ecb4468376afc819799a8ff06ad698f91426)
> > Is is possible that you updated the server code recently but didn't delete the twig cache?
> 
> It's my server but yes that could be.

I just cleared the twig cache but that didn't seem to have helped

**Comment by nickygerritsen** [comment]
Found the issue and fixed it. Will redeploy your server now.

**Comment by mpsijm** [comment]
Confirmed that it's fixed now, thanks for the quick response @meisterT and @nickygerritsen! :smile: :rocket:

**Comment by tossy310** [comment]
Hi, I've encountered very similar issue, and I found that even after the fix, sometimes the message says `Warning: Array to string conversion` on the HEAD of main:

![image](https://github.com/DOMjudge/domjudge/assets/19281814/281a3bc2-4f0a-4a4d-897a-24633f18a4af)

I've uploaded my quick proposal as #2354. Thank you!
