### ISSUE TITLE
Allow setting contest activate time via import

### ISSUE THREAD

**Issue by mpsijm** [DOMjudge/domjudge#1719]
When importing a contest (I'm using `bt export` from BAPCtools), the activate time of the contest is set to "-24:00" (1 day) by default. But, when I'm testing the uploading of a contest, it's typically the only contest in the system, so I would like it to be active immediately.

It would be nice if we can either:
- set the activation date/time, e.g., using an extra field in `contest.yaml`
- automatically mark the contest as "active" while uploading (could also be an API parameter, perhaps)

**Comment by meisterT** [comment]
I agree that this can be improved. Perhaps we should just set the activation time to the current time if a contest is created through the API?

**Comment by mpsijm** [comment]
That would also be fine :smile: I asked @nickygerritsen about it, and he said that there's not really a reason to set the activation time to -24:00, except that "multiple active contests at the same time is unhandy" :stuck_out_tongue: But for my use cases, it's always desirable to activate the contest immediately on import :slightly_smiling_face:
