### ISSUE TITLE
Role name (role.role column) may need to be made longer

### ISSUE THREAD

**Issue by pinkston3** [DOMjudge/domjudge#172]
I am going through the installation process on DOMjudge 5.0.0RC1, and I ran into an issue when running "dj-setup-database install".  I tracked it down to a schema issue:  the example data has a role name that is 17 characters long ("full_event_reader"), but the role.role column is only declared to be 15 characters.

When I changed role.role to be 25 characters long, the database setup worked fine.  I don't know if this is the correct length to choose, but it will allow me to proceed.

**Comment by eldering** [comment]
Thanks for reporting, fixed now.
