### ISSUE TITLE
Filter away the jury submissions in the balloon interface

### ISSUE THREAD

**Issue by vmcj** [DOMjudge/domjudge#1721]
We should (default) filter away the balloons for jury submissions (done for the verifier), I think we should keep the ones done by a jury member to test that balloons functionality does work.

**Comment by meisterT** [comment]
We do have a filter option on that page already:
![image](https://user-images.githubusercontent.com/418721/197345970-930359e8-b7de-420c-aaf9-e3661827245c.png)

So my proposal is to add a filter for team category and by default set it to all non-hidden categories. WDYT?

**Comment by vmcj** [comment]
> We do have a filter option on that page already: ![image](https://user-images.githubusercontent.com/418721/197345970-930359e8-b7de-420c-aaf9-e3661827245c.png)
> 
> So my proposal is to add a filter for team category and by default set it to all non-hidden categories. WDYT?

I think that is a good fix, sounds like good first time issue.

**Comment by nickygerritsen** [comment]
@brinky look at this beauty

**Comment by nickygerritsen** [comment]
Fixed in #2034.
