### ISSUE TITLE
Extend import contest with config options

### ISSUE THREAD

**Issue by vmcj** [DOMjudge/domjudge#1729]
### Description of the problem
Current import-contest does not set config options like datasource, lazy loading, removed intervals it would be nice if the first step for a contest is to optionally set these options

### Your environment
Main, nginx, deployed via ansible

### Steps to reproduce
Before importing we should set the datasource=1, I tend to forget this it would be good if this is forced.

### Expected behaviour
More config options are set after import-contest

### Actual behaviour
Config options are not set although they are connected to the way the contest works.

### Any other information that you want to share?
This might be a stretch on the concept of import-contest but given that this is optional I'm fine with this and it will make it easier to reproduce contests and when redeploying not forget to do manual tasks.

**Comment by meisterT** [comment]
I think the idea is interesting but would consider putting it into a separate script. `configure-domjudge` or similar.

**Comment by meisterT** [comment]
Started doing this here: https://github.com/DOMjudge/domjudge/pull/1731
