### ISSUE TITLE
Zip testcases documentation in 5.0

### ISSUE THREAD

**Issue by RagnarGrootKoerkamp** [DOMjudge/domjudge#176]
In release version 5.0, the admin manual says that the format should be according to the [kattis format](http://www.problemarchive.org/wiki/index.php/Problem_Format). Using the data/{sample,secret} directories and .in and .ans extensions does work.
The judge manual, however, states that a zip file containing just .in and .out files should add those to the current problem. I didn't get this to work. Trying .ans extensions instead of .out also didn't seem to help.

**Comment by corneym** [comment]
If the extra data is in the full directory structure it will add ok. Files must have .in and .and extensions.  Extra data successfully loads without a domjudge.ini file when using the zip upload method on the problem edit page.


Malcolm Corney

-------- Original message --------

**Comment by RagnarGrootKoerkamp** [comment]
Ah, thanks. For the plain testcases, I didn't use any directory structure inside the .zip, because this wasn't mentioned in the jury manual, but apparently I should have.

**Comment by eldering** [comment]
This is a documentation bug. Since version 5.0 we switched from our own format (as referenced in the judge manual) to the Kattis format. The reference in the judge manual is out of date.

**Comment by thijskh** [comment]
Some notes about the DOMjudge specific extensions have been added in 291bfd40e9285fcea9d422b56a0ffb03733d8881.
