### ISSUE TITLE
Source code view omitted white lines

### ISSUE THREAD

**Issue by robbertvs** [DOMjudge/domjudge#177]
In the source code view white lines at the start of the file are omitted. For this reason the line numbers in this view might differ from the line numbers in the original file.

In case the java compiler returns an error at a line number the jury might be looking at the wrong line to find the error.

**Comment by eldering** [comment]
Indeed, if the first line is completely empty (without whitespace also), then it doesn't show up in the source code display and edit. When downloading the source, the result is correct again, so this looks like it is a bug in ACE editor or tabber.js.
