### ISSUE TITLE
On a problem with zero testcases, submitting causes a 500 error

### ISSUE THREAD

**Issue by eldering** [DOMjudge/domjudge#1777]
This is because at that time it fails to create a judge task according to @meisterT .

**Comment by thijskh** [comment]
This is an improvement because earlier the judgedaemon would crash on such a problem.

**Comment by thijskh** [comment]
Solution is to just not show problems with <= 0 testcases in the team view?

**Comment by eldering** [comment]
> Solution is to just not show problems with <= 0 testcases in the team view?

Sounds ok, but we should then also clearly flag that problem as not used/submittable in the jury interface, so that there's no confusion about the state of that problem.

**Comment by thijskh** [comment]
Alternative is to just accept stuff, but assume it's (implied) on allow_judge = 0 until it has testcases

**Comment by meisterT** [comment]
Setting allow_judge=0 until it has test cases sounds reasonable to me
