### ISSUE TITLE
Make self-registration more prominent by adding a "Register" button

### ISSUE THREAD

**Issue by meisterT** [DOMjudge/domjudge#1780]
Currently, even when self-registration is enabled, we only display a login button here, not a "Register" button:
![image](https://user-images.githubusercontent.com/418721/200724501-74ddb808-96c1-4061-90b5-914b253810ad.png)

It is visible on the login page, so it should be easy to move to the main menu as well:
![image](https://user-images.githubusercontent.com/418721/200724701-49bcdb39-e934-47f8-b43b-45b556823cb3.png)

**Comment by eldering** [comment]
Implemented in 2a69e59dd309beaa5328a249d7f208236223dca9, but it could still do with a review and needs to be merged to `main`. @thijskh would you want to have a look at it?

**Comment by vmcj** [comment]
Alternative is to make it just [Register/Login] when self-registration is enabled for one of the categories instead of adding another button.

If we do this I would vote to remove the section ```Don't have an account?``` as this code is not often tested by us and there are not unit-tests added for it (yet).
