### ISSUE TITLE
Allow jury to see the problemset overview page before contest start

### ISSUE THREAD

**Issue by meisterT** [DOMjudge/domjudge#1781]
The jury should be able to see the problemset overview page that the teams will see even before contest start to see if all PDFs are there, colors are correct and attachments are available.

**Comment by thijskh** [comment]
Is the idea to make an exception for jury in the team or public interface? Currently we have exactly one exception in the team interface when you are jury, which is that you may submit something even if the contest is not yet started. The public interface is just the public interface and has no special behaviour for jury or admin.

We could to this but we would then make more exeptions/branches in the public and team interface code based on role. This is possible but on the other hand complicates this part of the interface and makes it less predictable/testable.

An alternative is to also make the problem overview page available in the jury interface.

**Comment by nickygerritsen** [comment]
I think the alternative is better indeed. Let's do that.
