### ISSUE TITLE
Inconsistency of clarification queue asssignment

### ISSUE THREAD

**Issue by eldering** [DOMjudge/domjudge#1785]
At the WF Dhaka dress rehearsal, this was reported by the judges:
![20221109_124110](https://user-images.githubusercontent.com/4692022/200758509-88da2a3f-0cfc-48d4-9393-6f84a3d74d20.jpg)
This showed as assigned to the jury queue on the clarifications overview page. After reassigning the original clarification request to the "Silly stuff" queue, it showed up there as (initially) expected.

We should probably only have a single queue for any clarification thread, or somehow make sure that the UX here is consistent.

**Comment by thijskh** [comment]
More or less a duplicate/specific case of https://github.com/DOMjudge/domjudge/issues/453#issuecomment-447668438

**Comment by nickygerritsen** [comment]
Proposal:
* Hide the edit button ever where except the top clarification
* Make that edit button edit all of them

**Comment by vmcj** [comment]
> Proposal:
> 
>     * Hide the edit button ever where except the top clarification
> 
Most of the time a non-issue, but I prefer that for a long thread you can re-assign based on the last message, so I would prefer to have the button on the first and the last (or even only the last as most of the time that will also be the first...) it will save scrolling.
>     * Make that edit button edit all of them

Yes,
