### ISSUE TITLE
Clarification reply quoted text wrapping is ugly

### ISSUE THREAD

**Issue by eldering** [DOMjudge/domjudge#1786]
When replying to a clarification request, the original text gets wrapped badly:

![20221109_125017](https://user-images.githubusercontent.com/4692022/200759378-47ce74b3-cb73-48d7-b0ae-5de40ffdd405.jpg)

**Comment by thijskh** [comment]
Probably there's an actual newline after `judging` in the original question?

**Comment by eldering** [comment]
> Probably there's an actual newline after `judging` in the original question?

Doesn't seem to be the case, I was able to reproduce this locally:
![image](https://user-images.githubusercontent.com/4692022/200797910-8a41aed8-26e9-47ca-9c92-149472aef124.png)

**Comment by eldering** [comment]
I had a look: wrapping is done inconsistently between jury and team code: the quote wrap length is not always the same and sometimes wrapping happens during rendering and sometimes when storing the clarification text.

@meisterT might look into better wrapping using markdown.
