### ISSUE TITLE
Handle multiple validators correctly

### ISSUE THREAD

**Issue by nickygerritsen** [DOMjudge/domjudge#1788]
The Problem Package Format allows [multiple validators](https://icpc.io/problem-package-format/spec/problem_package_format#output-validators), which we do not support. We should.

**Comment by eldering** [comment]
Maybe discuss if this can be removed from the problem package specification.

**Comment by vmcj** [comment]
@eldering I think we can close this as the spec has changed. Can you confirm as you know that part of the spec the best.

**Comment by vmcj** [comment]
The draft version of the spec does not allow this anymore. So I'll close this.

We should mention for any upcoming contests that we don't implement this feature.
