### ISSUE TITLE
Executables better error reporting

### ISSUE THREAD

**Issue by eldering** [DOMjudge/domjudge#179]
From experience of using a special compare script at UKIEPC, we should improve the error reporting of executables.

In this case, the 'run' script had u+x but not a+x and therefore starting it from runguard failed, but without a clear error. The actual error was in compare.tmp in the judging directory though.

We should try to send as much debug info to the admin/jury interface as possible when an executable fails.

**Comment by thijskh** [comment]
Why is that last sentence a question?

**Comment by eldering** [comment]
I guess I'm not 100% sure about it, but this seems rhetorical to you?

**Comment by thijskh** [comment]
Why should we not send as much debug info to the admin/jury interface as possible when an executable fails?

**Comment by eldering** [comment]
Removed question mark.
