### ISSUE TITLE
Scoreboard header/rows/footer misaligned

### ISSUE THREAD

**Issue by eldering** [DOMjudge/domjudge#1798]
On the WF Dhaka online judge the scoreboard was misaligned as shown below. Note that this was a private contest (where apparently the number solved and penalty time don't show) and affiliation logos were disabled.

![image](https://user-images.githubusercontent.com/4692022/201041903-b2f0beb7-6b44-4ec3-bda1-c8a52554dd95.png)

**Comment by nickygerritsen** [comment]
My guess: @meisterT removed the rank column but didn’t update the header and footer

**Comment by meisterT** [comment]
Exactly that was my comment earlier today. So, I agree.

**Comment by thijskh** [comment]
So not a bug then?

**Comment by meisterT** [comment]
It is a bug in the online judge version - if we ever run it again, we should do it properly.
