### ISSUE TITLE
Config check page is slow when 1+ contests have fully run

### ISSUE THREAD

**Issue by vmcj** [DOMjudge/domjudge#1820]
### Description of the problem
Visit https://domjudge.example.org/jury/config/check after the testsession has ran and it takes a long time to load the page

### Your environment
DOMjudge: | 8.1.3
Environment: | prod
Debug: | No
 
PHP: | 7.4.33
Symfony: | 5.4.9
Twig: | 3.4.1

### Steps to reproduce
> Load test contest
> Run the test contest with a real number of teams
> Load the second contest
> Visit the config checker

### Expected behaviour
> Page loads fast

### Actual behaviour
> Page takes longer than I would want

**Comment by meisterT** [comment]
Is this actually closed?

**Comment by nickygerritsen** [comment]
Would be nice if we have a dump where this happens. I loaded the Dhaka finals and the page loads in 2.5s, where 2s is finding the biggest testcase, which is just a heavy query.

**Comment by meisterT** [comment]
I am closing this for now. If it happens again, we can reopen it.
