### ISSUE TITLE
Confusing "Info: detected entry point:" message

### ISSUE THREAD

**Issue by meisterT** [DOMjudge/domjudge#1822]
### Steps to reproduce
- Configure python without requiring an entry point with the default compile script.
- Submit as a team
- Click on your submission in the submission list on the team page

### Actual behaviour
![image](https://user-images.githubusercontent.com/418721/204131629-ca326910-c6dd-4b29-b855-af9c9f37bfbd.png)

This is confusing because it is not actionable for teams. It is leaking that we need entry points for shadowing and should not be exposed at all to teams.

**Comment by nickygerritsen** [comment]
Note that on main we at least print the actually detected entry point

**Comment by meisterT** [comment]
I think this is helpful for us as we run the system but not helpful for the teams.

**Comment by nickygerritsen** [comment]
I fully agree. It’s never been useful and only confusing for teams
