### ISSUE TITLE
Upgrade in main broken due to executable hash changes

### ISSUE THREAD

**Issue by eldering** [DOMjudge/domjudge#1826]
The changed hashing of executables introduced in 496e5f1e82f47edc0036c78c4ddb25002396df59 and following commits breaks existing installations trying to upgrade, as the hashes are not recalculated and thus when trying to use any of the executables, the judgedaemon crashes due to a hash mismatch.

**Comment by eldering** [comment]
> We may have a similar problem. Updates were stuck and when that was resolved multiple updates happened at once.
> 
> Now the judgedaemon crashes with the following error message: `Argument 4 passed to fetch_executable() must be of the type string, null given, called in /usr/lib/domjudge/judgedaemon.main.php on line 1096`

Are you running the `main` branch? Note that upgrades there might sometimes be broken.

You should be able to fix this with a complete reinstall, but assuming you don't want to do that, you could re-upload or edit all the relevant executables that you use.

**Comment by spaanse** [comment]
I think we are running from the apt packages.
So this probably implies we do not run the main branch

**Comment by thijskh** [comment]
This is correct.

**Comment by nickygerritsen** [comment]
I wonder if/how we can easily solve the original issue. Hashes are only calculated when immutable executables are created (and the method is private), so we can't really update them. Should we create a migration that recreates all immutable executables? Sounds horrible as well.
