### ISSUE TITLE
Allow exactly one external contest source per contest

### ISSUE THREAD

**Issue by meisterT** [DOMjudge/domjudge#1842]
### Description of the problem

Currently, you can add multiple external contest sources per DOMjudge internal contest. This is not only conceptually not required but also leads to weird UI/UX issues:
![image](https://user-images.githubusercontent.com/418721/205737273-716e0697-337d-464a-bf23-4e180f0366b2.png)

Clicking on the warnings in the external contest sources menu currently brings you to the "external contest source" overview instead of the actual contest source that caused the warning.

**Comment by vmcj** [comment]
One reason why I would be in favor to keep the current behavior (but never used it yet) is to replay multiple prelims at the same time. So in case you have multiple Contest Archives and want to replay all at the same time to train the teams.

**Comment by meisterT** [comment]
Perhaps for that we could provide a simple python script that merges multiple contest archives?
