### ISSUE TITLE
"verified" badge on shadow page is confusing

### ISSUE THREAD

**Issue by meisterT** [DOMjudge/domjudge#1848]
### Description of the problem
For all submission lists, we display badges to show how many submissions we got, how many are queued, etc.

Now in shadow mode, when looking at differences, you see something like this:
![image](https://user-images.githubusercontent.com/418721/206863882-637b02cd-f3c5-4841-b5a9-89957fec986d.png)

Note that the differences are verified, but the submissions are not, making this confusing.

Ideas welcome how to make this less confusing.

**Comment by vmcj** [comment]
In shadow mode add these as extra badges?

Replacing the submission_verified with shadow_verified makes is more difficult to people who use the system as both and it is still possible to mark a submission as verified so in this case both badges do make sense.
