### ISSUE TITLE
Editing a problem archive with "delete old data" checked, removes the colour from its contest

### ISSUE THREAD

**Issue by mpsijm** [DOMjudge/domjudge#1858]
### Description of the problem
When editing a problem by uploading a problem archive, its associated colour in the contest is removed.

### Your environment

<details>
<summary>Snapshot 20221218, via Docker</summary>

`Dockerfile`:
```Dockerfile
FROM domjudge/domserver:latest
ADD https://www.domjudge.org/snapshot/domjudge-snapshot-20221228.tar.gz /opt/domjudge/domserver/
```

Build container:
```bash
docker build -t domjudge/domserver:20221228 .
```

`docker-compose.yml`: https://github.com/WISVCH/chipcie-startup-scripts/blob/main/domserver/docker-compose.yml, with this patch:
```diff
diff --git a/domserver/docker-compose.yml b/domserver/docker-compose.yml
index 90bff43..79e5c7f 100644
--- a/domserver/docker-compose.yml
+++ b/domserver/docker-compose.yml
@@ -2,31 +2,32 @@ version: "3"
 
 services:
   domserver:
-    image: ghcr.io/wisvch/domjudge-packaging/domserver:8.1.3
+    image: domjudge/domserver:20221228
     ports:
       - "8080:80"
     depends_on:
```

</details>

### Steps to reproduce
- Have a contest (I tested this with the default "demo" contest, with "boolfind", "fltcmp", and "hello").
- Import a problem zip to this contest.
- Edit the contest to give this new problem a colour.
- Either:
  - Edit the problem, scroll to the bottom, upload the same problem zip. Check "Delete old data" before importing.
  - Upload the problem via the [API `POST /api/v4/contests/{cid}/problems`](https://www.domjudge.org/demoweb/api/doc#operations-Problems-post_v4_app_api_problem_addproblem), with `delete_old_data` set to `true` (this flag was still there in 8.1.3, I don't see it in the documentation right now, though)

### Expected behaviour
The colour of the problem in the contest should not change.

### Actual behaviour
The colour of the problem in the contest is no longer set.

**Comment by nickygerritsen** [comment]
I believe this is fixed since d79f1830d63ef155236e46c8d47c3edefc08be54 and after talking to Maarten it seems he had some strange Docker image that was mostly based on 8.1.3, where this was indeed broken ("Delete old data" is also gone on main...). So closing it.
