### ISSUE TITLE
Detect and warn about low disk space on judgehosts?

### ISSUE THREAD

**Issue by eldering** [DOMjudge/domjudge#186]
We often run out of disk space on the judgehosts. Do we want to add a check and warning inside DOMjudge to notify about this? On the one hand this is probably a useful feature, on the other hand this would be something you'd setup monitoring software for.

**Comment by meisterT** [comment]
I suggest to rather improve documentation on what's useful to monitor (and maybe also by which tools) instead of doing our own checks.

**Comment by thijskh** [comment]
I agree that the monitoring of disk size is best left to dedicated software which can do this much better and exists already and that can warn before it's actually full.

However, when a judgehost actually runs out of disk space during a judging, we could perhaps do our best to detect this condition in the most graceful way possible and at least report back some kind of internal error. I guess that whenever 'we' write, this is already handled (is it?). Disk can of course most easily filled by the running contestant program. We could check that after judging completed we can still write one byte, if so, apparently the disk was not filled during judging.
