### ISSUE TITLE
Lazy evaluation: a mode that only stops evaluating when the "timelimit overshoot" is exceeded

### ISSUE THREAD

**Issue by mpsijm** [DOMjudge/domjudge#1860]
### Description of the enhancement request
DOMjudge currently has a "lazy evaluation" mode that is turned on or off (I will use "eager evaluation" for when "lazy" is off). I would like to request a setting that is between "eager" and "lazy": stop judging only when the run time of the submission exceeds the "timelimit overshoot".

### The goal you want to achieve
When importing a contest, I would like to see on the Analysis page that all submissions that are expected to be TLE, have been terminated at the "timelimit overshoot". Currently, some submissions will barely exceed the time limit on some earlier test case, while it can still hit the "timelimit overshoot" on a later test case. In order to verify this, I now need to click "judge remaining", but this will take a long while if the submission is actually expected to hit the "timelimit overshoot" for many of the remaining test cases.

### Expected behaviour
- In the config, at `/jury/config#config_lazy_eval_results`, I would like to see a third option between "lazy" and "eager" evaluation of results (I'm not sure what the name of this would be).
- If this setting is enabled: when running a submission, it will not terminate when getting a WA or TLE verdict, but it will terminate when its run time exceeds the "timelimit overshoot".

### Any other information that you want to share?
BAPCtools has this by default: when a submission is terminated after `floor(timelimit * 1.5)` seconds, the remaining test cases are skipped. Else, the submission is run on all test cases.

**Comment by vmcj** [comment]
@mpsijm why does using eager not fix your issue? We now have a lot of these small nuances on when to stop and the code becomes hard to verify if everything still works. So I'm not sure if this becomes an enhancement or will become the next major bug.

**Comment by mpsijm** [comment]
For submissions that _do_ consistently hit the "timelimit overshoot", it would be nice-to-have if they are killed, to save some time when importing an entire contest (which can take several hours already using lazy mode). But I understand if this enhancement would cause more trouble than necessary, apparently the related code is more complicated than I had hoped :slightly_smiling_face:

**Comment by eldering** [comment]
TBH, I don't think this is worth the extra complexity it would add in the code. The fact that the submission hits the overshoot/hard timelimit is not a stored as part of the judging data, so would involve extra work, and the code involving deciding whether to continue is already not completely trivial and it's the core of the system, so don't like adding things that can easily lead to bugs in the judging process.
