### ISSUE TITLE
Warn on single submission page if there is no judgehost which is not restricted

### ISSUE THREAD

**Issue by meisterT** [DOMjudge/domjudge#187]
If you use judgehosts restrictions, it may happen that a submission won't get (re-)judged, if every judgehost is restricted to (re)judge this particular submission. E.g.,, this may happen when using the not-self restriction and you already judged the submission on every judgehost and decide to rejudge it again.

**Comment by nickygerritsen** [comment]
This is fixed in aa29acd103f07a6855b6b95f718c466d8b063ee3
