### ISSUE TITLE
Allow deleting of testcase with associated judgings

### ISSUE THREAD

**Issue by eldering** [DOMjudge/domjudge#189]
Currently a testcase that has associated judging_run's cannot be deleted.
Proposal is to allow this, and make the judging_run.testcaseid a dangling reference. Then on the submission details page, we have to filter out links to any missing testcase in/output files.

**Comment by nickygerritsen** [comment]
I did a little digging and this is non-trivial: we use the testcase.probid to load the problem, but we should then use join's on judging and submission

**Comment by eldering** [comment]
Related issue on deleting problems: #243
After thinking more about it, I think that we should not support deleting testcases when these already have associated judging_runs. Besides being non-trivial to handle in the code (and thus bug-prone) by creating dangling references, it creates ambiguity about what it means for the correctness of the submission. If the deleted testcase was the only non-correct judging_run, does that turn the total judging result correct now??

**Comment by eldering** [comment]
Closing this because it technically tricky and also creates ambiguous situations when there are judgings, with some of the judging_runs associated to deleted test cases.

**Comment by eldering** [comment]
Reopening as this is an issue that we ourselves even ran into. We still have to decide how we can properly deal with the dangling references, or possibly delete all associated judgings in this case.

**Comment by meisterT** [comment]
If you want to delete a testcase, you want to rejudge the problem anyway. However, you probably also want to create a proper rejudging to have an overview what has changed. In this case we cannot delete associated judgings.

Another possibility is to mark the testcase as deleted by adding an attribute but not actually delete it. Then there's no dangling reference since the testcase still exist and we can handle it properly.

**Comment by bumfo** [comment]
Sorry for opening duplicated issues. I have searched that but didn't found this one.

An alternative way I think is to mark a test case as disabled, so it won't be run anymore. Should this be another issue called "Allow disabling problem test cases"?
