### ISSUE TITLE
Filter submissions by Affiliation

### ISSUE THREAD

**Issue by mzuenni** [DOMjudge/domjudge#1891]
Hello, in a decentralized contest, it would be nice to filter submissions by Affiliation (the feature is only available for balloons).

**Comment by vmcj** [comment]
> Hello, in a decentralized contest, it would be nice to filter submissions by Affiliation (the feature is only available for balloons).

Why would the jury not want to look at all solutions? If you filter you would get possible differences in judging between the sites.

**Comment by mzuenni** [comment]
For some beginner contests, we give hints, to do that we look at local submissions and try to see if there are common errors in the submissions.
Also, it is nice to see how the own teams are doing as contest site organizers.

**Comment by eldering** [comment]
I guess this makes sense in certain situations, and since we already have filters for plenty of things, I imagine this is not too hard to add. Although would be good to check if there are any weird corner cases that need considering!
Maybe you want to give it a shot to create a PR @mzuenni ?

**Comment by mzuenni** [comment]
I could try to adding a filter in `webapp/src/Form/Type/SubmissionsFilterType.php` but i am not sure if that is sufficient, and i am unable to get a testinstance running ^^'

**Comment by vmcj** [comment]
> I could try to adding a filter in `webapp/src/Form/Type/SubmissionsFilterType.php` but i am not sure if that is sufficient, and i am unable to get a testinstance running ^^'

You could also turn on debug mode on your running instance, or spin up a docker container (https://hub.docker.com/r/domjudge/domjudge-contributor) or follow the instructions here: https://www.domjudge.org/development and https://www.domjudge.org/docs/manual/8.0/develop.html#debugging-and-developing
