### ISSUE TITLE
Claiming a submission which is already claimed is unintuitive.

### ISSUE THREAD

**Issue by meisterT** [DOMjudge/domjudge#195]
Following situation:
- one jury member claims a submission
- another jury member views the submissions list, it is not refreshed yet, so he claims the same submission
- the first jury member is replaced

It would be more intuitive if the first jury member still claims the submission, but the second jury  member get's a "force claim" button instead.

**Comment by johnLate** [comment]
+1

**Comment by eldering** [comment]
I agree, but a "force claim" button is not necessary. Instead if we print a warning message that the submission wasn't claimed, then the second jury member can always click claim again on the submission page he landed on, and that will forcibly take the claim from the first jury member.

**Comment by TPolzer** [comment]
The idea behind the "force claim" button was that the second jury member probably does not want to look at the individual submission at all when a claim fails, so he should stay on the "submissions" page.

**Comment by eldering** [comment]
I see. However, I think that on the submissions page there is not as good a place to show a warning message that the submission was already claimed by another jury member and therefore not reclaimed by the current jury user, compared to on the submission detail page: the submissions page can be long and you might be scrolled down. Then, do we display the message at the top (meaning you have to scroll down again to where you were), or some popup message over the current position (more complicated code)?
Also, it is little work to press "back" once from the submission detail page.
