### ISSUE TITLE
Add documentation on cgroup v2 downgrading

### ISSUE THREAD

**Issue by Dup4** [DOMjudge/domjudge#1954]
In some newer Linux distributions (e.g. Ubuntu 22.04), cgroup v2 is turned on by default, but judgehost does not support cgroup v2 (#1072).

So do we need to add something to the documentation that tells users how to detect if cgroup v2 is on and how to turn it off?

We can check if we have cgroup v2 on by using this method: https://unix.stackexchange.com/a/668244/558695

```plain
systemd.unified_cgroup_hierarchy=0
```

By adding this parameter, we can turn on cgroup v1.

So, would it be appropriate to add the above to this page?

https://github.com/DOMjudge/domjudge/blob/main/doc/manual/install-judgehost.rst

**Comment by thijskh** [comment]
Documentation kind of exists, this is the output if you do not have v2 disabled:

```
Error: cgroup support missing memory features in running kernel. Unable to continue.

    To fix this, please make the following changes:
    1. In /etc/default/grub, add 'cgroup_enable=memory swapaccount=1' to GRUB_CMDLINE_LINUX_DEFAULT.
       On modern distros (e.g. Debian bullseye and Ubuntu Jammy Jellyfish) which have cgroup v2 enabled by default,
       you need to add 'systemd.unified_cgroup_hierarchy=0' as well.
    2. Run update-grub
    3. Reboot
```
