### ISSUE TITLE
Output of Python code altered when judging

### ISSUE THREAD

**Issue by machitgarha** [DOMjudge/domjudge#1961]
### Description of the problem

In one of the contests here, a submission of Python code resulted in wrong answer, which was wrong. The problem was, for one test case, the generated output of the code seemed to be altered. We tested the exact same code with the exact same test case input, both locally and even using the JudgeHost's PyPy3 executable (located in `/chroot/domjudge/usr/bin/pypy3`), the output was different. This means the PyPy executable isn't the problem, it might be the compare script, the runguard, etc.

### Your environment

- Version 8.1.2 (via Docker)
- Fedora Linux 36 (Server Edition)
- Apache

### Steps to reproduce

- Create a contest with one problem including a test case with the following input and output:

    Input:
    ```txt
    4
    abbaac
    ac
    bccddaaf
    zzzzzzzzzz
    ```

    Output (i.e. answer):
    ```txt
    abac
    ac
    bcdaf
    zzzzzz
    ```

- Login as a team of the contest, and submit the following Python code for the problem:

    ```python
    for i in range(int(input())):
        x = input()

        print(x[::2] + x[-1])
    ```

    It should give you a wrong answer.

- Now go to the submission in the admin panel, and view the diff output.

### Expected behaviour

Output of the code ran manually: 

```txt
abac
ac
bcdaf
zzzzzz
```

### Actual behaviour

Output of the code ran in DOMJudge:

```txt
aba

a

bcda

zzzzz

```

I have no idea why it converted the last character of every line into a new line character.

### Any other information that you want to share?

*No response*

**Comment by machitgarha** [comment]
@vmcj, upgraded Domserver and Judgehosts to 8.2.0, the problem is still present.

**Comment by nickygerritsen** [comment]
Could you provide us with a dump of your database by any chance? I think that would help in this case.

**Comment by machitgarha** [comment]
@nickygerritsen, I just created a fresh environment (i.e. new Docker containers) to reproduce the issue (and it's reproducable). And here is the `mysqldump` file: 

[mysqldump.txt](https://github.com/DOMjudge/domjudge/files/11072837/mysqldump.txt)

**Comment by eldering** [comment]
I would not want to do this automatically. You mean with a flag on importing via the CLI?
Another option would be to warn on import when the input contains `\r\n` (windows) or `\r` (mac) style newlines.

**Comment by nickygerritsen** [comment]
> I would not want to do this automatically. You mean with a flag on importing via the CLI? Another option would be to warn on import when the input contains `\r\n` (windows) or `\r` (mac) style newlines.

Yeah some flag that we can pass to the API/CLI, or a checkbox in the UI "Replace non linux newlines".

A warning is also fine.

Note that macOS has been using `\n` since macOS 10.0 which is 22 years old, I don't think only `\r` will happen very often.

**Comment by machitgarha** [comment]
@nickygerritsen, special thanks for your time and effort! Your great support and quick responses would cause DOMJudge to spread even more, and I hope so.

**Comment by eldering** [comment]
We'll add a warning if there are Windows (or macOS (classic)) newlines in the imported testdata.
