### ISSUE TITLE
Consider adding an option to choose whether or not to display the results of TOO-LATE submissions on the Team page

### ISSUE THREAD

**Issue by Dup4** [DOMjudge/domjudge#1967]
### Description of the enhancement request
> Replace this line with a short description.

DOMjudge is mainly used as a competition system.

However, we often use DOMjudge for training contest, and then after the training contest, the team members who take part in the training contest have the need to solve problems after the contest.

It would be useful to add an option to the configuration page to enable the display of TOO-LATE submissions on the team page.

**Comment by eldering** [comment]
I don't understand your description of the setting for which this configuration option would be useful. The "players" are contestants/teams in the training contest? What does "making up questions" mean here?

**Comment by Dup4** [comment]
> I don't understand your description of the setting for which this configuration option would be useful. The "players" are contestants/teams in the training contest? What does "making up questions" mean here?

Sorry, I've re-edited it.

The "players" means that team members who take part in the training contest.

They may still have a need to continue working on the problems after the contest is over.

So, it would be very helpful if the TOO-LATE submission also showed the results after the end of the contest.

<img width="857" alt="image" src="https://user-images.githubusercontent.com/38343778/226172230-a2b868b1-c7c5-4da4-b599-514d6a1d8da9.png">

<img width="714" alt="image" src="https://user-images.githubusercontent.com/38343778/226172276-ed93048b-62ee-4beb-b18e-5b97d8528efa.png">

Just like this.

**Comment by nickygerritsen** [comment]
We should add a global configuration option that enables this. @Dup4 would you be willing to implement this?
