### ISSUE TITLE
After edit and resubmit as a jury member, the new submission should be claimed.

### ISSUE THREAD

**Issue by meisterT** [DOMjudge/domjudge#197]
Currently, it redirects to the new submission, but it is not claimed.

**Comment by eldering** [comment]
This is not easy to do: we do not actually claim/verify submissions, but judgings. At the time of (re)submission of edited code, there is no associated judging yet to be claimed.

**Comment by eldering** [comment]
Maybe not too hard after all: when a judging is created, we can check if it is associated to resubmit, and if so directly set the owning `judging.jury_member` to the the jury user who made the resubmit.
