### ISSUE TITLE
Default value of domjudge-user in configure script is no longer current user

### ISSUE THREAD

**Issue by cubercsl** [DOMjudge/domjudge#1980]
In the configure scripts distributed, the default value for user is no longer the currently executing user, but instead defaults to "domjudge" (which may not exist on some people's systems). Running configure without `--with-domjudge-user` will cause some error since 8.2.0 (If user "domjudge" does not exist)

This may have been introduced in https://github.com/DOMjudge/domjudge/commit/e85980a8e601fc6dd08aa557fe3c9b6052b72b38. 

The default value for user now appears to be the user executing `autoconf` (but `autoconf`/ `m4` was already executed before the distribution of the source code)

[Slack Message](https://domjudge-org.slack.com/archives/CHHURFUM7/p1680968067657129?thread_ts=1680968067.657129&cid=CHHURFUM7)

**Comment by eldering** [comment]
Indeed, that `m4_esyscmd` shouldn't have been used as this default user should be taken when running `configure`, not when generating it. I'll look into the correct way to fix this (in portable shell code).
