### ISSUE TITLE
Add search for audit log

### ISSUE THREAD

**Issue by eldering** [DOMjudge/domjudge#201]
The auditlog has paging per 1000 entries, but a contest can typically accumulate many more, meaning that if you're searching for something specific, you need to press next/previous page many times.

It would be nice to have some improved interface that makes paging/searching a bit easier. I'm not sure we need a full blown solution, unless there is some handy JS code available to plug in.

**Comment by DrDub** [comment]
Would make the size (1000) configurable from the interface be enough?

**Comment by eldering** [comment]
I think it would help, but not be a real solution: from ICPC world finals we have about 50,000 entries. To page through these comfortably would require a page size of around 10,000. I tested this and it takes a few seconds to load, so not quite optimal.
Also, a recent case where I was searching for by who/when a config change was made, made me realise that having some form of searching or filtering is really what's needed. Ideally, we'd integrate some Javascript code that does this transparently, like https://github.com/koalyptus/TableFilter or https://github.com/javve/list.js
