### ISSUE TITLE
RUN-ERROR on java

### ISSUE THREAD

**Issue by nerdDan** [DOMjudge/domjudge#203]
`javac` works properly since a syntax error was precisely detected and described on DOMJudge web interface.

`java` failed with

```
/testcase001/execdir/program: 9: exec: java: not found
```

the environment is

* Arch Linux
* Open JDK 7

**Comment by meisterT** [comment]
You probably did not create the chroot: https://www.domjudge.org/docs/admin-manual-8.html#problems:chroot
