### ISSUE TITLE
Change contest time storage

### ISSUE THREAD

**Issue by ubergeek42** [DOMjudge/domjudge#206]
Contest time should be stored as absolute for the start time, and all other times will be stored relative. If someone needs to set an "absolute" end time or something we can do it in the UI. Basically it should work similar to how a typical calendar application works for appointments/meeting schedules.

**Comment by meisterT** [comment]
We actually have the option to enter relative times for everything but the start time and moving the start time works as you describe. We keep all absolute times as well, e.g. to save us from recalculating the end of the contest over and over. Are you saying we should remove that?
