### ISSUE TITLE
Allow hiding teams that never logged in from the scoreboard

### ISSUE THREAD

**Issue by ubergeek42** [DOMjudge/domjudge#2061]
We precreated a bunch of coach accounts for the icpc challenge, but they make the scoreboard giant list of teams that aren't active/won't submit. If we could hide teams until they log in (or submit?) that'd be kinda neat.

**Comment by vmcj** [comment]
> We precreated a bunch of coach accounts for the icpc challenge, but they make the scoreboard giant list of teams that aren't active/won't submit. If we could hide teams until they log in (or submit?) that'd be kinda neat.

I would than also like that we only inject these into the eventfeed when we start showing them. As otherwise they do show up in the resolver (which is ugly for every contest that I use the resolver for)

**Comment by eldering** [comment]
> > We precreated a bunch of coach accounts for the icpc challenge, but they make the scoreboard giant list of teams that aren't active/won't submit. If we could hide teams until they log in (or submit?) that'd be kinda neat.
> 
> I would than also like that we only inject these into the eventfeed when we start showing them. As otherwise they do show up in the resolver (which is ugly for every contest that I use the resolver for)

I don't think we should do this: it would make it a lot harder to have consistency of data in the event feed. Instead, I think that if you don't want to show such teams while resolving, this should be handled as an option by the resolver itself.

**Comment by vmcj** [comment]
Which option do we want? Login or on first submit? I prefer the login as I have smaller contests where a team not submitting anything is important information.

**Comment by vmcj** [comment]
Fixed with #2134
