### ISSUE TITLE
Make contest banner a max height

### ISSUE THREAD

**Issue by nickygerritsen** [DOMjudge/domjudge#2062]
This image is taking up way too much space, we should probably limit the width or height:
![image](https://github.com/DOMjudge/domjudge/assets/550145/d1d07e43-ec39-4412-8532-fc589acf8665)

**Comment by eldering** [comment]
Width is not really the problem, right, since there's nothing or either left/right side of it. So I'd say height should then be restricted (and of course width scaled accordingly).
