### ISSUE TITLE
Also show time elapsed on static scoreboard

### ISSUE THREAD

**Issue by nickygerritsen** [DOMjudge/domjudge#2064]
@clevengr suggested that besides time remaining we should also show (or with an option) the elapsed time of the contest. His argument is that all numbers in the scoreboard boxes are times since contest start and it makes sense to relate that to what the current contest time is.

**Comment by vmcj** [comment]
So do the inverse of what we do for the `static`? Display how many minutes have already elapsed?

**Comment by clevengr** [comment]
I don't know what "the inverse of what we do for the `static` " actually means in terms of DOMjudge code, but yes -- the idea is that it would be useful to (also) have the "number of elapsed minutes" shown on the scoreboard, since that's the time value shown in submission boxes.

**Comment by meisterT** [comment]
I assume this feature request was for the static scoreboard?

We display something like `63 minutes to go` there at the moment, example:
![image](https://github.com/DOMjudge/domjudge/assets/418721/fa992715-1e4c-4af0-94c3-d66822fbfdcc)

We added this to address the feature request in https://github.com/DOMjudge/domjudge/issues/1794 - where John already requested to add at least one of "elapsed time" or "remaining time" :-)

I am wondering whether we should change the time remaining to elapsed. Contestants (and jury) have the ticking clock in the upper right corner which is counting down:
![image](https://github.com/DOMjudge/domjudge/assets/418721/def2612b-d372-49fa-a124-200e6a3dcac5)

Now we could decide to unify things and to always display elapsed time (in minutes) in the gray bar regardless of whether we are in static mode or not.

cc @eldering and @thijskh who commented on the original issue

**Comment by eldering** [comment]
I'd indeed vote for only showing the time elapsed since contest start (and thus remove time remaining). That belongs more on an interactive display such as the CDS has, and definitely not on a static scoreboard.

**Comment by vmcj** [comment]
Implemented with https://github.com/DOMjudge/domjudge/commit/14032410ad7b57b54601bbbddef30a6e7783af44.
