### ISSUE TITLE
Download Contest Statements 

### ISSUE THREAD

**Issue by lperovskaya** [DOMjudge/domjudge#2069]
### Provide contestants with a single PDF file with contest statements in addition to existing ability to download each problem statement separately
Every contestant has to open each of problem statement pages at the beginning of the contest, or, if they have a printer access, send multiple print tasks to get a printed version of problem statements. Would be nice to have a single place to download a single pdf file with all problems in them.

### Expected behaviour
As soon as the contest starts the top of the list of problems page should have a way ( a separate button?) to download a concatenated PDF file with all problem statements

**Comment by nickygerritsen** [comment]
I was thinking of having a contest.pdf you could upload on a contest, similar to the banner

**Comment by nickygerritsen** [comment]
So after discussing this we have some questions / thoughts we first need to decide on:

* How to call the table / entity? `ContestStatement`?
* Do we allow more than PDF just like problem texts?
* Where do we put download button(s) for it? On the jury contest page and the team/public problemset page? But then where/how?
* Do we put this PDF in any of the ZIPs? Do we need a new ZIP?

Before we implement this, I think we need to answer these.

**Comment by mpsijm** [comment]
Regarding the zip (the last question): BAPCtools allows exporting a `samples.zip` with the following structure, which we extract in the contestant PCs' home directories before the start of the contest:
```
- A
  - 1.in
  - 1.ans
  - ...
- B
  - ...
- ...
- contest.pdf
- contest-web.pdf
```
If you end up implementing a zip button that downloads all samples and the contest PDF, it would be nice if it would follow the same structure :slightly_smiling_face:

**Comment by nickygerritsen** [comment]
Thanks that makes sense
