### ISSUE TITLE
Public favorite feature does not always display rank

### ISSUE THREAD

**Issue by vmcj** [DOMjudge/domjudge#2074]
### Description of the problem
The feature is implemented by doing a copy of the rendered team row on the scoreboard. If that team is on the same rank as the team above, then the rank is not rendered. If you favorite this second team you would not see the rank in your "favorite" view.

![image](https://github.com/DOMjudge/domjudge/assets/14887731/de9aa135-93e2-4714-aafd-f1f8de1b74dd)

### Your environment
Main

### Steps to reproduce
Go to demoweb and favorite a team at the bottom. 

### Expected behaviour
We copy the row, check if the rank is empty and use the rank above which does have a rank (so could be multiple teams above) or we store the rank as hidden field and use that.

**Comment by eldering** [comment]
Adding a hidden rank attribute seems like the better solution to me.
