### ISSUE TITLE
How to enable the printer to print balloon information and notify balloon runners when AC is available

### ISSUE THREAD

**Issue by yoyo30618** [DOMjudge/domjudge#2082]
I am using the docker version of domjudge
The version information is as follows
System information
DOMjudge: 8.1.3
Environment:prod
Debug: No
PHP: 7.4.30
Symfony: 5.4.9
Twig: 3.4.1

How can I set up to print out the balloon information sheet when there is a balloon notification

**Comment by eldering** [comment]
Did you check https://www.domjudge.org/docs/manual/8.2/config-advanced.html#printing ?

Note that you will need to have a printer configured that you can print to. Normally you'd set this up by running a CUPS server on the DOMjudge server, but this is outside of the scope of DOMjudge bugs/issues. You might try and ask on our slack channel, maybe people with experience with docker and CUPS can help there.

**Comment by yoyo30618** [comment]
Thanks a lot
