### ISSUE TITLE
default `configure` does not install service files for judgedaemon, docs do mention those.

### ISSUE THREAD

**Issue by vmcj** [DOMjudge/domjudge#2086]
### Description of the problem
When you follow the manual we mention the service files so you can start a judgehost with a service. The problem is that we don't advice the `fhs` flag which does set this.

We can fix this in multiple ways:
- Make the FHS default
- Don't respect the prefix and just install those service files
- Mention this explicit in the docs
- Mention this in the steps after the `make install-judgehost` that someone should do this (and template the files in the `make judgehost` step)

In my opinion we should go for either option {3,4} or discuss {1}.

@eldering what are your thoughts?

**Comment by eldering** [comment]
I think we can also (try to) install the service files when not in FHS mode, although that might fail if the user runs `make judgehost-install` without root.
I don't understand though why `systemd_unitdir` isn't set at https://github.com/DOMjudge/domjudge/blob/main/judge/Makefile#L36 from https://github.com/DOMjudge/domjudge/blob/main/configure.ac when FHS is not enabled.

**Comment by vmcj** [comment]
> I think we can also (try to) install the service files when not in FHS mode, although that might fail if the user runs `make judgehost-install` without root. I don't understand though why `systemd_unitdir` isn't set at https://github.com/DOMjudge/domjudge/blob/main/judge/Makefile#L36 from https://github.com/DOMjudge/domjudge/blob/main/configure.ac when FHS is not enabled.

@eldering I think we discussed and agreed that if you **don't** do FHS mode we (should and ) will **not** install service files anymore.

So that requires a change in de documentation.

**Comment by eldering** [comment]
Indeed, I'd propose to *never* install systemd unit files, in the same way that we don't install the apache or nginx config in `/etc/`, but just document how you can symlink/copy them. That will remove a good bit of complexity from our configure/makefile setup.
