### ISSUE TITLE
Add popup notification for clarification messages

### ISSUE THREAD

**Issue by 2018hahazhufeng** [DOMjudge/domjudge#2088]
### Description of the enhancement request
Currently when participant recieves a message from jury, it'll only appear quietly. But a browzer popup notification is neccesary, especially during contest participant doesn't notice the domjudge page frequently.

**Comment by eldering** [comment]
Note that we already have browser notifications for the jury, although they were broken recently, see #481.

So it probably should not be too difficult to also implement this on the team side. Would you want to consider creating a pull request?

**Comment by 2018hahazhufeng** [comment]
I‘d like to make PRs but I have no relevant develop experience. Anyway I'll make a try

**Comment by vmcj** [comment]
Alternative is to add the number of messages to the menu? We already do this for Balloons (when balloonrunner) and errors (when admin).
