### ISSUE TITLE
Contest Problems

### ISSUE THREAD

**Issue by eldering** [DOMjudge/domjudge#21]
Problems (including judge data, validators, execution time limit, etc) are configured using the ICPC problem format. The CCS must have full support for this standard but may assume that problem.tex exists (containing a problem statement in English) . All problems that are added or changed must be verified as defined in the problem standard.

**Comment by meisterT** [comment]
DOMjudge now supports the (essential parts of the) problem format as described here:
http://www.problemarchive.org/wiki/index.php/Problem_Format

Verification can be done externally with using the problemtools package:
https://github.com/Kattis/problemtools
