### ISSUE TITLE
First to solve rejudging

### ISSUE THREAD

**Issue by mzuenni** [DOMjudge/domjudge#2105]
### Description of the problem
There can be multiple persons with "first to solve" on the scoreboard due to rejudgings

### Your environment
DOMjudge 8.3.0DEV/5d0968d34

### Steps to reproduce
- have two submissions by two users (first gets WA later gets AC)
- (change a testcase for example because it was invalid)
- rejudge both submissions (now both AC)

### Expected behaviour
Only the first person gets the "first to solve" on the scoreboard after the rejudging

### Actual behaviour
Both get the "first to solve" on the scoreboard after the rejudging

**Comment by mzuenni** [comment]
that is the bug. The later team should no longer have it... but the scoreboard still shows it for some reason

**Comment by nickygerritsen** [comment]
I think we don’t update the score cache of untouched teams. We might want to but it will slow down the applying

**Comment by nickygerritsen** [comment]
We recently changed the logic in the code to only update the scoreboard cache at the end of applying a rejudging (#2099). Should we maybe, instead of that, do a full scorecache update for all teams in the contest for any 'touched' problem? That would solve this.

**Comment by meisterT** [comment]
cc @thijskh who might understand the first to solve code (and implicit contract) the best

**Comment by nickygerritsen** [comment]
I gave this a try in #2127. I first added a test (which of course failed), implemented the change and saw the test turn green. Isn't it magic?
