### ISSUE TITLE
Automatically update contest start time on change.

### ISSUE THREAD

**Issue by meisterT** [DOMjudge/domjudge#212]
While importing from Kattis, we should change contest start time, if Kattis does so.

**Comment by eldering** [comment]
See also #214. Note that this should be easier with the new JSON API and rest feed.

**Comment by meisterT** [comment]
Probably will be fixed with #495.

**Comment by meisterT** [comment]
@nickygerritsen will test this today.

**Comment by nickygerritsen** [comment]
This works 😄
