### ISSUE TITLE
Compact scoreboard option

### ISSUE THREAD

**Issue by iMylene** [DOMjudge/domjudge#2124]
### Description of the enhancement request
A compact scoreboard option, where the user can only see + for accepted problems, so without any time scores and tries. Ex. when a team solved problem A in one go and problem B in two tries, we would see:

|           | Score | A | B  | C |
|-----------|-------|---|----|---|
| test team | 2     | + | +1 | . |
|           |       |   |    |   |

By default, it should be turned off, but if a user turns compact mode on, it should stay on even during auto-refresh.

### The goal you want to achieve
The Pafos Programming Camp 2023 is currently running on Open Cup/Codeforces and I saw this feature which could be implemented in DOMjudge too. See pictures from their scoreboard in normal mode and in compact mode in the comments.

**Comment by iMylene** [comment]
![Screenshot 2023-08-20 at 13 33 17](https://github.com/DOMjudge/domjudge/assets/15448457/4cb88c1d-03b5-41d0-a9d9-dfc23889871a)
![Screenshot 2023-08-20 at 13 33 26](https://github.com/DOMjudge/domjudge/assets/15448457/b716bb0f-bd3b-4891-9bde-169aff9f17cd)

**Comment by nickygerritsen** [comment]
Instead of a +, why not hide the score and the word “tries”, leaving only the number of tries?
We also need to hide some info in the leftmost column that makes it two lines long

**Comment by iMylene** [comment]
Also a good idea. For the leftmost column, you could implement <team name> (<institution name>) to have it on one line

**Comment by iMylene** [comment]
Or leave it as an option for the tech team, to either show team name (for BAPC prelims for example), the institution name (BAPC) or the country

**Comment by nickygerritsen** [comment]
I would not add too many options. We could probably show the institution short name between () in compact mode

**Comment by vmcj** [comment]
What should happen to the banner in this view? Should Flags & Institution logo's be shown?

**Comment by iMylene** [comment]
Is it an option to let the user hide the banner? I would skip the flag/institution logo and replace it with the country code or institution's short name

**Comment by meisterT** [comment]
Would this be addressed by https://github.com/DOMjudge/domjudge/issues/2401?

**Comment by iMylene** [comment]
@meisterT Yes that would be solved indeed!
