### ISSUE TITLE
Last solved time in the scoreboard summary

### ISSUE THREAD

**Issue by iMylene** [DOMjudge/domjudge#2125]
### Description of the enhancement request
Show in the summary under the scoreboard the last solved time.

### The goal you want to achieve
Nice information for analytics

**Comment by vmcj** [comment]
I assume we only want this for non-team scoreboards?

And to be specific, you want last solved and not last attempted by a team?

If you can find a [icon](https://fontawesome.com/search?q=watch&o=r&m=free) which works better than this: 
![image](https://github.com/DOMjudge/domjudge/assets/14887731/c623ee0e-4231-4ded-ae26-3b63d819371e)
than we can create PR out of this.

**Comment by eldering** [comment]
I'm wondering if we should add this: is the extra information worth the extra clutter of icons in the bottom row? Also, this will easily cause confusion with the first to solve time.

**Comment by vmcj** [comment]
> I'm wondering if we should add this: is the extra information worth the extra clutter of icons in the bottom row? Also, this will easily cause confusion with the first to solve time.

I have the same thought, but as it was an easy branch to see if it can be done. If we can't find a better icon I think we shouldn't do this.

Alternative is to only add this as hint but I doubt people would find it in that way.

**Comment by iMylene** [comment]
@vmcj I think a [checkered flag](https://fontawesome.com/icons/flag-checkered?f=classic&s=solid) would be easier to recognize as a last correctly solved time stamp

**Comment by iMylene** [comment]
To be fair, the time stamps for first/last correctly solved would be easier to read (to at least get the hint) if the times at the bottom were in the format h:mm instead of only minutes. Is that maybe an idea? And if so, do I need to make a new issue?
