### ISSUE TITLE
Implement contest start time interface.

### ISSUE THREAD

**Issue by meisterT** [DOMjudge/domjudge#214]
API: https://clics.ecs.baylor.edu/index.php/Contest_Start_Interface

**Comment by eldering** [comment]
Note that the contest start interface is going to be merged into the general CCS API, see: https://clics.ecs.baylor.edu/index.php/Draft_CCS_REST_interface#PATCH_start_time

**Comment by eldering** [comment]
@meisterT Did you test this (at NWERC)? Is it working or is there still something to be done?

**Comment by meisterT** [comment]
This is fixed with the following commits:

- ad54d409be106d0495d993d1bab08fa3bd32bda1
- 93af033456a7668382d7c13c333ad0b6b57ff7d4
- f4fd34896c8bf986251a5e4dae867d2d0f11b58f
- 0702db8ddec64a92399ca962aaf64f69c14698eb
- 95428dc524ddd1910e3785a15d38085f83889a1b

**Comment by meisterT** [comment]
I've tested this with the CDS.
