### ISSUE TITLE
Implement a way to retrieve judging debug package?

### ISSUE THREAD

**Issue by meisterT** [DOMjudge/domjudge#215]
Either
- make it downloadable on the web interface, or
- provide a script to fetch it from the judgehost, or
- display "scp -r ..." command line in web interface to copy files.

**Comment by eldering** [comment]
"scp -r ..." assumes ssh access to the judgehosts; similarly, how would the script access a judgehost?

To make a complete package available in the web interface requires pulling it via the API and judgedaemon, which is ugly IMHO.

**Comment by meisterT** [comment]
Hmmm.

Maybe it's enough to display help to display the full path to the judging directory somewhere.

**Comment by meisterT** [comment]
tgre

**Comment by meisterT** [comment]
Maybe it's enough to display the full path to the judging directory?

**Comment by eldering** [comment]
Even displaying the full judging path is non-trivial: on the domserver we don't know what JUDGEDIR and endpoint ID are on the judgehost. We could print a generic path that would be a good guess in 99% of the cases.

**Comment by ubergeek42** [comment]
I'd like to see the judgehost extended to check for things that aren't judgings. So we could for example on the domserver tell the judgehost to do something when it checks in. One of these things could be "upload a debug package for c1/s1/j1". It may be enough that it be something as simple as, "judgehost, run this script" and the script can handle the rest of the logic(be that uploading a debug package or otherwise).

I'm sure there are other use cases for running scripts on the judgehosts(maintenance/cleanup/information/setup) so this may be worth doing for other reasons. Not sure if that's the best way to solve this, but I think I like the flexibility it would add. Thoughts?

**Comment by meisterT** [comment]
So parallel judging complicates things a bit since there's more than one judgehost involved. But the new API makes this possible.

To store the data, we likely need a new table that stores zip files, and a good UI to retrieve them (e.g. on a submission download them individually or bundled). Note that this can get large so we also may want to be able store metadata (such as the path) for manual inspection.

**Comment by nickygerritsen** [comment]
> So parallel judging complicates things a bit since there's more than one judgehost involved. But the new API makes this possible.
> 
> To store the data, we likely need a new table that stores zip files, and a good UI to retrieve them (e.g. on a submission download them individually or bundled). Note that this can get large so we also may want to be able store metadata (such as the path) for manual inspection.

If the data gets so big, isn't it better to store it outside the database (the ZIP I mean), for example in DJ_TMPDIR or similar? And only store metadata in the DB?

**Comment by meisterT** [comment]
That's a good idea, but only partially solves the problem. The debug package may become too big to upload from the judgehost for post max size.

**Comment by nickygerritsen** [comment]
Ah yeah fair point. Then we need to chunk it or something, which becomes more complex.

**Comment by thijskh** [comment]
```
package.arj
package.a01
package.a02
```

**Comment by eldering** [comment]
> ```
> package.arj
> package.a01
> package.a02
> ```

And then we can copy them over sneakernet with 3.5" floppies to the server, or wherever we want to have them really!

BTW, if reliability turns out to be a bit low, I have a solution for that :-p

**Comment by meisterT** [comment]
I started implementing this and it looks like with tar compressed archive we would rarely run into issues. I tested with the largest problem output wise of NWERC 2019 and added some statically initialized arrays so that the compiled program is ~1.5GB. The resulting archive was less than 25MB.
