### ISSUE TITLE
${PWD} in docker-compose.yml doesn't work

### ISSUE THREAD

**Issue by RagnarGrootKoerkamp** [DOMjudge/domjudge#2153]
For both me and @mpsijm we get an error when running `docker-compose up` from the root directory in the `main` branch:
```
 error decoding 'volumes[1]': invalid spec: .::cached: empty section between colons
 ```
 and
 ```
DOMjudge sources not found. Did you add a volume with your DOMjudge checkout at /domjudge? 
```

It seems to be caused by https://github.com/DOMjudge/domjudge/commit/c465958639922a67b267e6d24e810fe344687aad. Replacing it with `/domjudge` makes it work again, but I'm not sure if there are other implications of changing the working directory.

**Comment by nickygerritsen** [comment]
It shouldn’t break anything but having the same folder inside and outside docker eases in development.
I assume you are both on Linux? We should investigate how this works there

**Comment by RagnarGrootKoerkamp** [comment]
yes; we're both on linux. Yeah I understand what you're trying to do. I have no idea about why this would/wouldn't work.

**Comment by nickygerritsen** [comment]
Will investigate after my holiday

**Comment by nickygerritsen** [comment]
Turns out this happens if you run `docker-compose up` with `sudo`. If you do this, you should use `sudo -E`, since otehrwise sudo drops environment variables.
