### ISSUE TITLE
Allow users to delete accounts

### ISSUE THREAD

**Issue by narayanx** [DOMjudge/domjudge#2155]
Currently it is not possible for DOMjudge users to delete their own accounts. It would be nice for them to be able to delete their accounts if they create multiple accounts and no longer want or need some of them. Or, if they want to completely get rid of their account.

**Comment by meisterT** [comment]
Is this just about users or would you want to delete also the team behind it?

**Comment by narayanx** [comment]
This is just about individual user accounts

**Comment by vmcj** [comment]
@narayanx, why is the alternative solution of asking an admin to delete your account not an option?

We have limited time to implement all requests and I think this would become featurecreep. So although I can see the usecase, I think the simpler solution (ask the admin to delete the account) is the desired solution (effort/codewise).

Deleting the account would be semi-hard to do in a clean way and would open up room for mistakes (as we would need to give the team endpoint a route where it can delete accounts and limit that it can only be your account).

So currently I think we would not implement this soon, and for such issues I prefer to be clear that it's not really on the roadmap (at least for me).

**Comment by eldering** [comment]
Also, giving users the option to delete their accounts opens admins up for certain forms of misuse where users may now try to hide their traces. I agree that I don't see strong arguments for this, weighing against feature creep.
