### ISSUE TITLE
Deleting a problem or contest doesn't cascade to judgetask

### ISSUE THREAD

**Issue by mpsijm** [DOMjudge/domjudge#2156]
### Description of the problem
This occurs when deleting a problem or contest that contains unjudged submissions. After doing so, when starting a judgehost, it tries to fetch no-long-existing submissions.

### Your environment
- DOMjudge version 8.2.1
- Ubuntu 22.04
- https://github.com/WISVCH/domjudge-packaging
- https://github.com/WISVCH/chipcie-startup-scripts

### Steps to reproduce
- Reset and start DOMjudge. By default, a demo contest is created.
- Delete the demo contest or one/some of its problems.
- Start a judgehost.

### Expected behaviour
The judgehost does not crash.

### Actual behaviour
The judgehost crashes with "submission not found".

### Any other information that you want to share?
- Related to #2023.
- Currently, when this happens, we either reset DOMjudge again and do not delete anything anymore, or jump into phpMyAdmin to execute `DELETE FROM judgetask` (possibly with `WHERE submitid <= ...` if we also imported a new contest already).

**Comment by eldering** [comment]
This was fixed in 181ae06a5625611274f7217be85cfd28d5f351b4, but that hasn't been backported to the 8.2 branch, and looking at the code I'd say it's too complex to be worth it.
