### ISSUE TITLE
check for duplicate problems?

### ISSUE THREAD

**Issue by meisterT** [DOMjudge/domjudge#216]
Add a check for problems with same test data, either display a warning on import or make it available as config check or both.

**Comment by meisterT** [comment]
You get an error like this now: `Duplicate entry '2-guess' for key 'shortname'`
We should make it nice, but apart from that it's fine.

**Comment by thijskh** [comment]
'shortname' is a property of a contestproblem. Where do you get this? If I add a new contestproblem with an existing shortname, I get a nice form validation error.

**Comment by meisterT** [comment]
I cannot repro this message any more.

However, I found another related issue. Using the API to post a problem like this:
`curl -X POST -n -N -F zip[]=@achievement.zip http://localhost/domjudge/api/contests/10/problems`
works fine. If you do it again, you get:
```
{
    "code": 400,
    "message": "[\"Error: problem.externalid: This value is already used.\"]"
}
```
This is also fine.

If I go to the web interface and try the same there, I get a red flash message (good) but it doesn't contain any error text.
If I go to the last 10 requests in the symfony toolbar, I see a 302 which has the failing validator with the same message as I got above while using curl.

**Comment by meisterT** [comment]
@thijskh re-reading your comment, I think you added a new problem while I tried to import one.

**Comment by thijskh** [comment]
I can reproduce the unfriendly error on import, indeed.

**Comment by meisterT** [comment]
The flash message does contain text now "Error: problem.externalid: This value is already used.".

@nickygerritsen is there an easy way to customize that message?

**Comment by nickygerritsen** [comment]
I think you can set `message=` on the @unique
