### ISSUE TITLE
Cannot get list of contests as a jury if there's no contest

### ISSUE THREAD

**Issue by Suckzoo** [DOMjudge/domjudge#2160]
### Description of the problem
When there is no contest at all, [this line](https://github.com/DOMjudge/domjudge/blob/8.2.1/webapp/src/Controller/Jury/ContestController.php#L382) of released code makes NPE.
As a result, a jury cannot enter contest page, and cannot make any contest.

### Your environment
- DOMjudge version 8.2.1 (latest stable)
- Operating system / Linux distribution and version Ubuntu 22.04
- Webserver Apache2

### Steps to reproduce
- Just bare-install and jump into contest page as an admin

### Expected behaviour
- The contests page should not return 500 response.

### Actual behaviour
- NPE occurs: calling isLocked on null.

### Any other information that you want to share?
- As of the main branch, the bug seems to be fixed.

**Comment by vmcj** [comment]
> NOTE: If this is a _discussion starter_, you need any _installation help_ or have a _question_ on how to accomplish something, rather post at [our discussion channel](https://www.domjudge.org/chat) or send an email to our [DOMjudge-devel mailinglist](https://www.domjudge.org/mailman/postorius/lists/domjudge-devel.domjudge.org/) instead of filing an issue here.
> ### Description of the problem
> 
> When there is no contest at all, [this line](https://github.com/DOMjudge/domjudge/blob/8.2.1/webapp/src/Controller/Jury/ContestController.php#L382) of released code makes NPE. As a result, a jury cannot enter contest page, and cannot make any contest.
> ### Your environment
> 
>     * DOMjudge version 8.2.1 (latest stable)
> 
>     * Operating system / Linux distribution and version Ubuntu 22.04
> 
>     * Webserver Apache2
> 
> 
> ### Steps to reproduce
> 
>     * Just bare-install and jump into contest page as an admin
> 
> 
> ### Expected behaviour
> 
>     * The contests page should not return 500 response.
> 
> 
> ### Actual behaviour
> 
>     * NPE occurs: calling isLocked on null.
> 
> 
> ### Any other information that you want to share?
> 
>     * As of the main branch, the bug seems to be fixed.

Hi @Suckzoo, thank you for your issue. A PR would be welcome as I think you've already found the fix for the 8.2 branch.

**Comment by Suckzoo** [comment]
It seems that the commit in the main branch (authored by @nickygerritsen) [1294b6e](https://github.com/DOMjudge/domjudge/blob/1294b6e/webapp/src/Controller/Jury/ContestController.php) solves the problem. What I'd like to point out is this commit has not been included in a stable release. I'm kindly asking you when the next stable release is, or if there's any plan for it in the near future.

Thanks!

**Comment by Suckzoo** [comment]
Oh sorry I misread your comment. Then should I make a cherry-pick PR into the 8.2 branch?

**Comment by vmcj** [comment]
We're currently discussing when to release (as it takes some time and we're all busy).
