### ISSUE TITLE
Renaming the default Self-Registered category breaks the system

### ISSUE THREAD

**Issue by dc74089** [DOMjudge/domjudge#2165]
### Description of the problem
> Renaming the default `Self-Registered` category causes the system to throw a `Integrity constraint violation: 1062` upon next boot

### Your environment
> DOMserver Docker container
> DOMjudge 8.2.1
> PHP 7.4.33
> Symfony 5.4.20
> Twig 3.5.0

### Steps to reproduce
> 1. Rename the `Self-Registered` team category through the web interface
> 2. Terminate the Docker container
> 3. Attempt to start the Docker container

### Expected behaviour
> The container boots

### Actual behaviour
> The container does not boot, and throws the error below

### Any other information that you want to share?
> See full logs below
<details>
<summary>Full Logs</summary>
21:25:32 CRITICAL  [console] Error thrown while running command "-v domjudge:load-default-data". Message: "An exception occurred while executing a query: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'self-registered' for key 'externalid'" ["exception" => Doctrine\DBAL\Exception\UniqueConstraintViolationException^ { …},"command" => "-v domjudge:load-default-data","message" => "An exception occurred while executing a query: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'self-registered' for key 'externalid'"]

In ExceptionConverter.php line 62:
                                                                                                                      
  [Doctrine\DBAL\Exception\UniqueConstraintViolationException (1062)]                                                 
  An exception occurred while executing a query: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate ent  
  ry 'self-registered' for key 'externalid'                                                                           
                                                                                                                      

Exception trace:
  at /opt/domjudge/domserver/lib/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php:62
 Doctrine\DBAL\Driver\API\MySQL\ExceptionConverter->convert() at /opt/domjudge/domserver/lib/vendor/doctrine/dbal/src/Connection.php:1907
 Doctrine\DBAL\Connection->handleDriverException() at /opt/domjudge/domserver/lib/vendor/doctrine/dbal/src/Connection.php:1850
 Doctrine\DBAL\Connection->convertExceptionDuringQuery() at /opt/domjudge/domserver/lib/vendor/doctrine/dbal/src/Statement.php:194
 Doctrine\DBAL\Statement->execute() at /opt/domjudge/domserver/lib/vendor/doctrine/dbal/src/Statement.php:249
 Doctrine\DBAL\Statement->executeStatement() at /opt/domjudge/domserver/lib/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php:278
 Doctrine\ORM\Persisters\Entity\BasicEntityPersister->executeInserts() at /opt/domjudge/domserver/lib/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php:1145
 Doctrine\ORM\UnitOfWork->executeInserts() at /opt/domjudge/domserver/lib/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php:431
 Doctrine\ORM\UnitOfWork->commit() at /opt/domjudge/domserver/lib/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php:403
 Doctrine\ORM\EntityManager->flush() at /opt/domjudge/domserver/webapp/src/DataFixtures/DefaultData/TeamCategoryFixture.php:37
 App\DataFixtures\DefaultData\TeamCategoryFixture->load() at /opt/domjudge/domserver/lib/vendor/doctrine/data-fixtures/lib/Doctrine/Common/DataFixtures/Executor/AbstractExecutor.php:123
 Doctrine\Common\DataFixtures\Executor\AbstractExecutor->load() at /opt/domjudge/domserver/lib/vendor/doctrine/data-fixtures/lib/Doctrine/Common/DataFixtures/Executor/ORMExecutor.php:26
 Doctrine\Common\DataFixtures\Executor\ORMExecutor::Doctrine\Common\DataFixtures\Executor\{closure}() at /opt/domjudge/domserver/lib/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php:272
 Doctrine\ORM\EntityManager->wrapInTransaction() at /opt/domjudge/domserver/lib/vendor/doctrine/data-fixtures/lib/Doctrine/Common/DataFixtures/Executor/ORMExecutor.php:28
 Doctrine\Common\DataFixtures\Executor\ORMExecutor->execute() at /opt/domjudge/domserver/lib/vendor/doctrine/doctrine-fixtures-bundle/Command/LoadDataFixturesDoctrineCommand.php:158
 Doctrine\Bundle\FixturesBundle\Command\LoadDataFixturesDoctrineCommand->execute() at /opt/domjudge/domserver/lib/vendor/symfony/console/Command/Command.php:298
 Symfony\Component\Console\Command\Command->run() at /opt/domjudge/domserver/webapp/src/Command/LoadDefaultDataCommand.php:32
 App\Command\LoadDefaultDataCommand->execute() at /opt/domjudge/domserver/lib/vendor/symfony/console/Command/Command.php:298
 Symfony\Component\Console\Command\Command->run() at /opt/domjudge/domserver/lib/vendor/symfony/console/Application.php:1058
 Symfony\Component\Console\Application->doRunCommand() at /opt/domjudge/domserver/lib/vendor/symfony/framework-bundle/Console/Application.php:96
 Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() at /opt/domjudge/domserver/lib/vendor/symfony/console/Application.php:301
 Symfony\Component\Console\Application->doRun() at /opt/domjudge/domserver/lib/vendor/symfony/framework-bundle/Console/Application.php:82
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /opt/domjudge/domserver/lib/vendor/symfony/console/Application.php:171
 Symfony\Component\Console\Application->run() at /opt/domjudge/domserver/webapp/bin/console:42

In Exception.php line 28:
                                                                                                                
  [Doctrine\DBAL\Driver\PDO\Exception (1062)]                                                                   
  SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'self-registered' for key 'externalid'  
                                                                                                                

Exception trace:
  at /opt/domjudge/domserver/lib/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:28
 Doctrine\DBAL\Driver\PDO\Exception::new() at /opt/domjudge/domserver/lib/vendor/doctrine/dbal/src/Driver/PDO/Statement.php:136
 Doctrine\DBAL\Driver\PDO\Statement->execute() at /opt/domjudge/domserver/lib/vendor/sentry/sentry-symfony/src/Tracing/Doctrine/DBAL/AbstractTracingStatement.php:77
 Sentry\SentryBundle\Tracing\Doctrine\DBAL\AbstractTracingStatement->traceFunction() at /opt/domjudge/domserver/lib/vendor/sentry/sentry-symfony/src/Tracing/Doctrine/DBAL/TracingStatementForV3.php:43
 Sentry\SentryBundle\Tracing\Doctrine\DBAL\TracingStatementForV3->execute() at /opt/domjudge/domserver/lib/vendor/doctrine/dbal/src/Statement.php:190
 Doctrine\DBAL\Statement->execute() at /opt/domjudge/domserver/lib/vendor/doctrine/dbal/src/Statement.php:249
 Doctrine\DBAL\Statement->executeStatement() at /opt/domjudge/domserver/lib/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php:278
 Doctrine\ORM\Persisters\Entity\BasicEntityPersister->executeInserts() at /opt/domjudge/domserver/lib/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php:1145
 Doctrine\ORM\UnitOfWork->executeInserts() at /opt/domjudge/domserver/lib/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php:431
 Doctrine\ORM\UnitOfWork->commit() at /opt/domjudge/domserver/lib/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php:403
 Doctrine\ORM\EntityManager->flush() at /opt/domjudge/domserver/webapp/src/DataFixtures/DefaultData/TeamCategoryFixture.php:37
 App\DataFixtures\DefaultData\TeamCategoryFixture->load() at /opt/domjudge/domserver/lib/vendor/doctrine/data-fixtures/lib/Doctrine/Common/DataFixtures/Executor/AbstractExecutor.php:123
 Doctrine\Common\DataFixtures\Executor\AbstractExecutor->load() at /opt/domjudge/domserver/lib/vendor/doctrine/data-fixtures/lib/Doctrine/Common/DataFixtures/Executor/ORMExecutor.php:26
 Doctrine\Common\DataFixtures\Executor\ORMExecutor::Doctrine\Common\DataFixtures\Executor\{closure}() at /opt/domjudge/domserver/lib/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php:272
 Doctrine\ORM\EntityManager->wrapInTransaction() at /opt/domjudge/domserver/lib/vendor/doctrine/data-fixtures/lib/Doctrine/Common/DataFixtures/Executor/ORMExecutor.php:28
 Doctrine\Common\DataFixtures\Executor\ORMExecutor->execute() at /opt/domjudge/domserver/lib/vendor/doctrine/doctrine-fixtures-bundle/Command/LoadDataFixturesDoctrineCommand.php:158
 Doctrine\Bundle\FixturesBundle\Command\LoadDataFixturesDoctrineCommand->execute() at /opt/domjudge/domserver/lib/vendor/symfony/console/Command/Command.php:298
 Symfony\Component\Console\Command\Command->run() at /opt/domjudge/domserver/webapp/src/Command/LoadDefaultDataCommand.php:32
 App\Command\LoadDefaultDataCommand->execute() at /opt/domjudge/domserver/lib/vendor/symfony/console/Command/Command.php:298
 Symfony\Component\Console\Command\Command->run() at /opt/domjudge/domserver/lib/vendor/symfony/console/Application.php:1058
 Symfony\Component\Console\Application->doRunCommand() at /opt/domjudge/domserver/lib/vendor/symfony/framework-bundle/Console/Application.php:96
 Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() at /opt/domjudge/domserver/lib/vendor/symfony/console/Application.php:301
 Symfony\Component\Console\Application->doRun() at /opt/domjudge/domserver/lib/vendor/symfony/framework-bundle/Console/Application.php:82
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /opt/domjudge/domserver/lib/vendor/symfony/console/Application.php:171
 Symfony\Component\Console\Application->run() at /opt/domjudge/domserver/webapp/bin/console:42

In Statement.php line 134:
                                                                                                                
  [PDOException (23000)]                                                                                        
  SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'self-registered' for key 'externalid'  
                                                                                                                

Exception trace:
  at /opt/domjudge/domserver/lib/vendor/doctrine/dbal/src/Driver/PDO/Statement.php:134
 PDOStatement->execute() at /opt/domjudge/domserver/lib/vendor/doctrine/dbal/src/Driver/PDO/Statement.php:134
 Doctrine\DBAL\Driver\PDO\Statement->execute() at /opt/domjudge/domserver/lib/vendor/sentry/sentry-symfony/src/Tracing/Doctrine/DBAL/AbstractTracingStatement.php:77
 Sentry\SentryBundle\Tracing\Doctrine\DBAL\AbstractTracingStatement->traceFunction() at /opt/domjudge/domserver/lib/vendor/sentry/sentry-symfony/src/Tracing/Doctrine/DBAL/TracingStatementForV3.php:43
 Sentry\SentryBundle\Tracing\Doctrine\DBAL\TracingStatementForV3->execute() at /opt/domjudge/domserver/lib/vendor/doctrine/dbal/src/Statement.php:190
 Doctrine\DBAL\Statement->execute() at /opt/domjudge/domserver/lib/vendor/doctrine/dbal/src/Statement.php:249
 Doctrine\DBAL\Statement->executeStatement() at /opt/domjudge/domserver/lib/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php:278
 Doctrine\ORM\Persisters\Entity\BasicEntityPersister->executeInserts() at /opt/domjudge/domserver/lib/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php:1145
 Doctrine\ORM\UnitOfWork->executeInserts() at /opt/domjudge/domserver/lib/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php:431
 Doctrine\ORM\UnitOfWork->commit() at /opt/domjudge/domserver/lib/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php:403
 Doctrine\ORM\EntityManager->flush() at /opt/domjudge/domserver/webapp/src/DataFixtures/DefaultData/TeamCategoryFixture.php:37
 App\DataFixtures\DefaultData\TeamCategoryFixture->load() at /opt/domjudge/domserver/lib/vendor/doctrine/data-fixtures/lib/Doctrine/Common/DataFixtures/Executor/AbstractExecutor.php:123
 Doctrine\Common\DataFixtures\Executor\AbstractExecutor->load() at /opt/domjudge/domserver/lib/vendor/doctrine/data-fixtures/lib/Doctrine/Common/DataFixtures/Executor/ORMExecutor.php:26
 Doctrine\Common\DataFixtures\Executor\ORMExecutor::Doctrine\Common\DataFixtures\Executor\{closure}() at /opt/domjudge/domserver/lib/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php:272
 Doctrine\ORM\EntityManager->wrapInTransaction() at /opt/domjudge/domserver/lib/vendor/doctrine/data-fixtures/lib/Doctrine/Common/DataFixtures/Executor/ORMExecutor.php:28
 Doctrine\Common\DataFixtures\Executor\ORMExecutor->execute() at /opt/domjudge/domserver/lib/vendor/doctrine/doctrine-fixtures-bundle/Command/LoadDataFixturesDoctrineCommand.php:158
 Doctrine\Bundle\FixturesBundle\Command\LoadDataFixturesDoctrineCommand->execute() at /opt/domjudge/domserver/lib/vendor/symfony/console/Command/Command.php:298
 Symfony\Component\Console\Command\Command->run() at /opt/domjudge/domserver/webapp/src/Command/LoadDefaultDataCommand.php:32
 App\Command\LoadDefaultDataCommand->execute() at /opt/domjudge/domserver/lib/vendor/symfony/console/Command/Command.php:298
 Symfony\Component\Console\Command\Command->run() at /opt/domjudge/domserver/lib/vendor/symfony/console/Application.php:1058
 Symfony\Component\Console\Application->doRunCommand() at /opt/domjudge/domserver/lib/vendor/symfony/framework-bundle/Console/Application.php:96
 Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() at /opt/domjudge/domserver/lib/vendor/symfony/console/Application.php:301
 Symfony\Component\Console\Application->doRun() at /opt/domjudge/domserver/lib/vendor/symfony/framework-bundle/Console/Application.php:82
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /opt/domjudge/domserver/lib/vendor/symfony/console/Application.php:171
 Symfony\Component\Console\Application->run() at /opt/domjudge/domserver/webapp/bin/console:42

domjudge:load-default-data
</details>

**Comment by nickygerritsen** [comment]
Our fixtures try to create the category again. We should add a check if the one with the external id we try to create already exists.
