### ISSUE TITLE
Allow jury users to upload to the API?

### ISSUE THREAD

**Issue by nickygerritsen** [DOMjudge/domjudge#2189]
Currently at least `api/v4/contests/xxx/problems/add-data` requires admin privileges. Normally jury should be allowed to upload problems, shouldn't they?

**Comment by nickygerritsen** [comment]
Turns out the jury also can't upload via the web interface...

**Comment by eldering** [comment]
I don't think the jury role should be allowed to make such changes. Jury is about monitoring the contest, not setting it up. So if you want jury members to be able to do that, then just give them the admin role.

The point of the jury/admin role separation was to keep the jury interface cleaner and fail-safe from making mistakes that could screw up the contest data.

**Comment by nickygerritsen** [comment]
I agree so closing it.
