### ISSUE TITLE
Starting minutes are missing a space

### ISSUE THREAD

**Issue by iMylene** [DOMjudge/domjudge#2190]
### Description of the problem
Time passed is stated as "started45 minutes", there should be a space between "started" and "45"

### Your environment
DOMjudge system used at BAPC 2023

### Steps to reproduce
Step 1 Turn on SmartTV
Step 2 Go to the internet, and to scoreboard.bapc.eu
Step 3 Look to 

### Expected behaviour
"started 45 minutes"

### Actual behaviour
"started45 minutes"

### Any other information that you want to share?
See screenshots in the comments

**Comment by iMylene** [comment]
![Uploading D582D3F6-46AB-4013-8325-DBABFA271B53.jpeg…]()

**Comment by iMylene** [comment]
![IMG_7336](https://github.com/DOMjudge/domjudge/assets/15448457/c70fee4c-ca08-446f-82f8-9f825a1083bb)

**Comment by nickygerritsen** [comment]
This is on the static scoreboard
