### ISSUE TITLE
Cannot view inactive judging on jury submission page

### ISSUE THREAD

**Issue by eldering** [DOMjudge/domjudge#2191]
### Description of the problem
When I browse to a submission on the jury interface that has multiple judgings, then I cannot view an inactive judging.

### Your environment
Current `main` branch, both at BAPC and my laptop.

### Actual behaviour
See below screenshot for URL http://localhost/domjudge/jury/submissions/106?jid=106, but it still shows the currently active judging 107.
![image](https://github.com/DOMjudge/domjudge/assets/4692022/0e03dca6-743a-4b6b-b4fb-2505b66fe172)

**Comment by meisterT** [comment]
I cannot reproduce this behavior, neither in Chrome nor firefox. Did you type in the URL or did you click on the respective row in the judgings table?

**Comment by meisterT** [comment]
While trying to provoke the issue, I found another one:
![image](https://github.com/DOMjudge/domjudge/assets/418721/64617e94-4abb-4742-bdf5-d77ada0ffcc5)

Note that the order in this table should be by judgingid, see https://github.com/DOMjudge/domjudge/blob/main/webapp/src/Controller/Jury/SubmissionController.php#L221

I don't see where we would reorder things though.

**Comment by meisterT** [comment]
I think this is fixed, feel free to re-open if you can still repro.
