### ISSUE TITLE
Team submissions in jury interface show warning on expected result

### ISSUE THREAD

**Issue by vmcj** [DOMjudge/domjudge#2194]
![image](https://github.com/DOMjudge/domjudge/assets/14887731/22b4e35a-88ce-45c2-9ebc-21f790f41b98)

In https://judge.bapc.eu/jury/submissions/1873#run-13 (bapc2023 dump) but this seems to be for any submission page from teams.

**Comment by eldering** [comment]
Already fixed today in d61beaed5a974e0205fbd1fecd6e4e325853ebed.
