### ISSUE TITLE
race condition in import.php.in and submit_solution()

### ISSUE THREAD

**Issue by ubergeek42** [DOMjudge/domjudge#220]
There is a race condition where a submission id can be assigned/created, a judgedaemon can begin judging it, but the submission files may not actually be present yet in the database leading to the judgedaemon crashing when it is unable to download any submission files. These things need to be packed into a transaction.

This code should also be refactored so that we do not have the same code in two places.

**Comment by eldering** [comment]
Where do we still have duplicate code?

**Comment by eldering** [comment]
Removed duplicate code in b5b4e5bda5c8c8346e12d0478066cff0875d4938
