### ISSUE TITLE
some submissions incorrectly give no-output

### ISSUE THREAD

**Issue by ubergeek42** [DOMjudge/domjudge#221]
We observed a couple submissions that sometimes execute and give no-output when they should otherwise be correct. It looks like a race condition in runguard but is not reproducible.

We've noticed this primarily with c++ submissions.

**Comment by ubergeek42** [comment]
6b37fd1c7b1624d7a2619b4fbed95a68f657373f Possibly resolves this(or alters the behavior). As it isn't reproducible it is very hard to tell.

**Comment by eldering** [comment]
Closing this issues as we have not seen it since, also not during WF 2017, running on identical hardware.
