### ISSUE TITLE
Failed running script: 'chroot-startstop.sh stop'

### ISSUE THREAD

**Issue by HeRaNO** [DOMjudge/domjudge#2214]
### Description of the problem

When a judging task is finished, script `chroot-startstop.sh stop` will be executed. But we found the script running failed sometimes. To detect the bug, we change the `dj-umount` function in [`chroot-startstop.sh`](https://github.com/DOMjudge/domjudge/blob/main/judge/chroot-startstop.sh.in) as below.

```sh
dj_umount() {
	set +e
	if ! sudo -n umount "$1" < /dev/null; then
		>&2 lsof +c 15 +D "$1"
		>&2 echo "here1"
		>&2 echo "umount '$1' didn't succeed, trying harder"
		if ! sudo -n umount -f -vvv "$1" < /dev/null; then
			>&2 echo "umount '$1' failed twice"
			>&2 lsof +c 15 +D "$1"
			>&2 echo "here"
			>&2
			exit 1
		fi
	fi
	set -e
}
```

And the log says

```plain
...
[Nov 12 11:41:48.120] judgedaemon[196]:   🔓 Executing chroot script: 'chroot-startstop.sh stop'
umount: /opt/domjudge/judgehost/judgings/judgedaemon-lsof-0-0/endpoint-default/853/862/usr: target is busy.
here1
umount '/opt/domjudge/judgehost/judgings/judgedaemon-lsof-0-0/endpoint-default/853/862/usr' didn't succeed, trying harder
umount: /opt/domjudge/judgehost/judgings/judgedaemon-lsof-0-0/endpoint-default/853/862/usr: target is busy.
umount '/opt/domjudge/judgehost/judgings/judgedaemon-lsof-0-0/endpoint-default/853/862/usr' failed twice
here
[Nov 12 11:41:48.488] judgedaemon[196]: chroot script exited with exitcode 1
[Nov 12 11:41:48.509] judgedaemon[196]: => internal error 25
[Nov 12 19:41:48.528] /opt/domjudge/judgehost/lib/judge/evict[148243]: warning: Unable to open file: /opt/domjudge/judgehost/judgings/judgedaemon-lsof-0-0/endpoint-default/853/862/lib/ssl/private: Permission denied
[Nov 12 19:41:48.566] /opt/domjudge/judgehost/lib/judge/evict[148243]: warning: Unable to open file: /opt/domjudge/judgehost/judgings/judgedaemon-lsof-0-0/endpoint-default/853/862/usr/lib/ssl/private: Permission denied
[Nov 12 19:41:48.610] /opt/domjudge/judgehost/lib/judge/evict[148243]: warning: Unable to open file: /opt/domjudge/judgehost/judgings/judgedaemon-lsof-0-0/endpoint-default/853/862/usr/share/locale/locale.alias: No such file or directory
[Nov 12 11:41:48.638] judgedaemon[196]: No submissions in queue (for endpoint default), waiting...
```

### Your environment

- Alibaba Cloud ECS, 4C8T(AMD EPYC 7T83 64-Core Processor) 16G
- Ubuntu 20.04.6 LTS (5.4.0-166-generic)
- DOMjudge 8.2.2
- Dockerized Judgehost

domserver and judgehost are deployed on the same ECS. 4 judgehost containers are used.

```plain
docker run -d -it --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro --name judgehost-lsof-0 --hostname judgedaemon-lsof-0 -e DAEMON_ID=0 -e CONTAINER_TIMEZONE=Asia/Shanghai -e JUDGEDAEMON_PASSWORD=<PASSWD> -e DOMSERVER_BASEURL=<BASE_URL> domjudge/judgehost:8.2.2
```

### Steps to reproduce

It's hard to find a method that can steadily reproduce this problem. But in a three-hour (18:00-21:00) contest held yesterday, it happened pretty often.

![internal error](https://github.com/DOMjudge/domjudge/assets/18643142/0559e846-6ca0-49bc-a991-25d14c1021b0)

### Expected behaviour

The running environment should be cleaned with no error.

### Actual behaviour

Reporting an internal error making the judgehost down. After restarting the judgehost, no task has been affected, and seems that there's no side effect.

### Database dump

[domjudge.sql](https://mypikpak.com/s/VNj2gcDMtfcDHjl1LhKIp6Pro1)

**Comment by vmcj** [comment]
@HeRaNO what machines/load where your running this on?
Baremetal/VM?
OS?
Model/CPU/Number of cores vs threads
Is it a shared host? HOw many judgehost containers per machine?
Can you share a database dump so we can reproduce the amount of load you had (amount of teams, number of submissions per hour, number of testcases per problem etc.)

**Comment by HeRaNO** [comment]
> @HeRaNO what machines/load where your running this on? Baremetal/VM? OS? Model/CPU/Number of cores vs threads Is it a shared host? HOw many judgehost containers per machine? Can you share a database dump so we can reproduce the amount of load you had (amount of teams, number of submissions per hour, number of testcases per problem etc.)

Description updated, hope to be helpful for you.

**Comment by HeRaNO** [comment]
We ran another contest a few days ago, and we used an Intel ECS instead of AMD (only the CPU changed, the number of cores, RAM, and OS remained as before). We didn't change the way that the judgehost deployed. Surprisingly the failing event only happened once during the contest. It's so weird that I can't believe the CPU made differences. Unfortunately, the database of the contest has lost (too soon to release the ECS), so we cannot give more information. We will keep investigating this issue.

**Comment by Dbinggo** [comment]
你好 我也发生了相同的问题 我是用的docker部署 如果你有空的话 我很乐意请你登陆我的admin账号来重现问题
<img width="1527" alt="image" src="https://github.com/user-attachments/assets/d7e3b27c-a835-409f-b10f-c8972c218a0b">

**Comment by HeRaNO** [comment]
> 你好 我也发生了相同的问题 我是用的docker部署 如果你有空的话 我很乐意请你登陆我的admin账号来重现问题

Hi, and we have not encountered this (quite weird) issue in recently contests. Unfortunately, now I have no bandwidth to deal with this issue. If you found a method that can reproduce it *steadily*, pls open another issue.
