### ISSUE TITLE
Fedora Documentation Updates

### ISSUE THREAD

**Issue by mkfuron** [DOMjudge/domjudge#2222]
### Fedora Documentation Updates

For the installation of DOMjudge 8.x on recent Fedora releases, I have needed to make the following changes:  
  `dnf` is now used, replacing `yum`  
  `chronyd` is now used, replacing `ntp`  (`chronyd` is probably installed by default)  
  `php-fpm` needs to be installed (along with `nginx` if desired--Southern California now uses nginx)  
  configure needs `libcgroup-devel`, even if one is not building a judgehost

**Comment by meisterT** [comment]
@mkfuron thanks for reporting! Do you want to send a PR to fix the issues?

**Comment by mkfuron** [comment]
> @mkfuron thanks for reporting! Do you want to send a PR to fix the issues?

I can work on that in a few days.  It is the Thanksgiving holiday in the USA and I will be busy with family starting tomorrow through the weekend.

**Comment by vmcj** [comment]
Probably you need those parts of the code:
https://github.com/DOMjudge/domjudge/blob/main/doc/manual/install-domserver.rst?plain=1#L45

https://github.com/DOMjudge/domjudge/blob/main/doc/manual/install-judgehost.rst?plain=1#L40-L47

And if I remember correctly you also have a different setup for this part? https://github.com/DOMjudge/domjudge/blob/main/doc/manual/install-judgehost.rst?plain=1#L123-L148

**Comment by mkfuron** [comment]
I installed a base Rocky Linux 9 VM today.  I found that libcgroup-devel is not available; cgroups V1 is deprecated and removed in this version.  Time to work on updating `runguard` to cgroups V2...

**Comment by vmcj** [comment]
> I installed a base Rocky Linux 9 VM today. I found that libcgroup-devel is not available; cgroups V1 is deprecated and removed in this version. Time to work on updating `runguard` to cgroups V2...

We have an issue for that, but it requires really a bit of work. So you could get installation working for Rocky v8?

**Comment by vmcj** [comment]
@mkfuron I'll close this issue as I think you provided updated docs.

The issue with CgroupsV2 will be handled in another issue.
