### ISSUE TITLE
Improve handling of `timelimit_overshoot` validation

### ISSUE THREAD

**Issue by meisterT** [DOMjudge/domjudge#2227]
Currently, when specifying an incorrect value for timelimit overshoot, e.g. `57|10%` (note the missing `s`) or `1.5s|10%` validation is not done server side, but on the judgedaemon where it shows up as an error like this:
```
[Nov 23 10:58:58.526] judgedaemon[32640]: error: invalid timelimit overshoot token '57'
```
and then aborts the judgedaemon.

In order of preference, we probably should do one of:
- Do validation when changing the value. This is non-trivial as it is currently a `string` in our generic configuration mechanism which doesn't have any methods to do validation.
- Do validation before handing out a judgetask - server-side.
- Keep doing validation client side, but do not crash the judgedaemon, but report back an internal error as we do for most other errors in the judgedaemon.

**Comment by nickygerritsen** [comment]
We could add (custom) validation rules to the DB config. It's a bit of work but I think it can be done and could help us with other things as well.
