### ISSUE TITLE
Create rejudgings in multi_rejudge script

### ISSUE THREAD

**Issue by meisterT** [DOMjudge/domjudge#223]
Rather create full blown rejudging in multi_rejudge script to see the diff matrix.

**Comment by eldering** [comment]
When we create a rejudging, we can also then cancel it when ready, so that the contest retains the original judgings.

**Comment by meisterT** [comment]
Still TODO: Cancel the created rejudgings from the script. Perhaps also
create a single view in the web interface over all created rejudgings.

Maybe also convert the DB calls to API calls.
