### ISSUE TITLE
Affiliation logos

### ISSUE THREAD

**Issue by eldering** [DOMjudge/domjudge#226]
For the ICPC world finals we need to support university logos again on the scoreboard (and disable country flags).

**Comment by eldering** [comment]
See commits 7e984bd8e3e98901d730a408702a2b3772f0211e and ecd19691f9d6900d51b260333cd33f1aa655d5d8 where we removed the affiliation icons.

**Comment by meisterT** [comment]
Fixed with commit 6c9d9a91cb1d6ff7edbc76d2fe5c8062d46951ba.

**Comment by asdcxsd** [comment]
I can't find  lib/www/scoreboard.php ??
