### ISSUE TITLE
Balloon handed out twice

### ISSUE THREAD

**Issue by nickygerritsen** [DOMjudge/domjudge#2262]
At NWERC we had the same balloon handed out twice (with 2 balloon ID's). See screenshot.
![WhatsApp Image 2023-11-26 at 11 58 41](https://github.com/DOMjudge/domjudge/assets/550145/201d1945-c66c-46fa-8b2d-5d59418e915e)

**Comment by meisterT** [comment]
I looked into this a bit. If you look at the balloon code in https://github.com/DOMjudge/domjudge/blob/main/webapp/src/Service/BalloonService.php#L55, you will find that we try to avoid duplicates there, but there is no synchronization mechanisms, and I am aware of at least two cases where duplicates balloons can happen:

- A team submits twice in short succession for the same problem, both submissions are correct and complete judging "at the same time", running this code simultaneously. Both check whether there is already a balloon, there is none and both add one.
- There is just one (correct) submission, which is distributed across multiple judgehosts. The final two test cases are being judged on different hosts, and come in "at the same time".

Both race conditions are rare, but not impossible.

For scoring functions, we do use a lock currently, but for the balloons we don't. While also adding a lock here might be a potential fix, it might not the most elegant one.

An alternative would be to add the contest, problem, team IDs to the balloon table directly (currently it is only indirect via the submission ID). We could then add a composite unique constraint on the new columns and gracefully handle the constraint violation in case it already exists.

A final alternative that I can think of would be to keep this code as is. Then in the `BalloonController` we could change the query to present the maximum `balloonid` per actual balloon (if there are even multiple). When marking a balloon as done, we can not only mark this one as done but clean up the duplicates with lower `balloonid` (if they exist).
