### ISSUE TITLE
Decouple the implied trust between domserver & judgehost on handed out tasks

### ISSUE THREAD

**Issue by vmcj** [DOMjudge/domjudge#2297]
### Description of the enhancement request
Currently we trust the judgehost to report back a result when we have given a task. In case the judgehost would die (either a spot instance, result of a tableflip etc.)

It would be nice if we can have a take back tasks button or if we can handout the same task again if we didn't get a verdict in a reasonable time. This would complicate a lot but would make the system more robust in case people have AWS spot instances etc. The implied trust between the domserver/judgehost should be at a minimum (don't trust that the data is in the right format or that you even get an answer etc.)

**Comment by meisterT** [comment]
We do have "restart judging" button - are there scenarios where you would want more than that?

**Comment by vmcj** [comment]
> We do have "restart judging" button - are there scenarios where you would want more than that?

In case of spot instances you would need to do that very often.

**Comment by meisterT** [comment]
Perhaps we should recommend to not use spot instances then?

**Comment by eldering** [comment]
> Perhaps we should recommend to not use spot instances then?

Either that, or make sure to send a `SIGHUP` to the judgedaemon so it finishes properly.
