### ISSUE TITLE
Judgehost docker container fails to start with latest docker versions.

### ISSUE THREAD

**Issue by spitzlei** [DOMjudge/domjudge#2309]
### Description of the problem
Since the update to docker 24.0.7 the judgehost container fails to start. No change in docker 25.0.0

```
judgehost-0-1  | [..] Setting up cgroups
judgehost-0-1  | mkdir: cannot create directory '/sys/fs/cgroup/cpuset/domjudge': Read-only file system
judgehost-0-1  | mkdir: cannot create directory '/sys/fs/cgroup/memory/domjudge': Read-only file system
judgehost-0-1  | chown: cannot access '/sys/fs/cgroup/*/domjudge': No such file or directory
judgehost-0-1  | bin/create_cgroups: 41: cannot create /sys/fs/cgroup/cpuset/domjudge/cpuset.cpus: Directory nonexistent
judgehost-0-1  | bin/create_cgroups: 42: cannot create /sys/fs/cgroup/cpuset/domjudge/cpuset.mems: Directory nonexistent
judgehost-0-1 exited with code 2
```

### Your environment
- Debian Bookworm Host, DOMjudge in docker
- DOMjudge version: domjudge/judgehost:latest

### Steps to reproduce
- Start domserver:latest (site is reachable)
- Start judgehost:latest, like written in hub.docker.com with privileged and `/sys/fs/cgroup:/sys/fs/cgroup:ro`

### Expected behaviour
Judgehosts should run.

### Actual behaviour
Container exits with message above.

**Comment by eldering** [comment]
Could you file this against https://github.com/DOMjudge/domjudge-packaging/issues which contains the docker packaging?

**Comment by spitzlei** [comment]
> Could you file this against https://github.com/DOMjudge/domjudge-packaging/issues which contains the docker packaging?

Just did: https://github.com/DOMjudge/domjudge-packaging/issues/170
