### ISSUE TITLE
dj_make_ubuntu_chroot

### ISSUE THREAD

**Issue by thuvh** [DOMjudge/domjudge#231]
I downloaded file domjudge-5.1.2.tar.gz and follow some instructions to install it on my virtualbox (ubuntu 14.04). While installing, I can not find script dj_make_ubuntu_chroot. Is it still available?

**Comment by thijskh** [comment]
It's now called `dj_make_chroot` instead. Can I ask which instructions you were following?

**Comment by thuvh** [comment]
I follow the document on the [website](https://www.domjudge.org/docs/admin-manual-8.html#problems:chroot). In addition, I found that the command dj_make_ubuntu_java_chroot also call dj_make_ubuntu_chroot

**Comment by thijskh** [comment]
Thanks, I'll make sure we update the documentation.
