### ISSUE TITLE
How to add a new tool on the tools page?

### ISSUE THREAD

**Issue by Dup4** [DOMjudge/domjudge#2310]
I would like to recommend a [tool][p2d] that converts packages exported from the [Codeforces Polygon Platform][polygon] into [DOMjudge(Kattis) Problem Packages][kattis]. 

In East Asia Continent, many ICPC Regional Contest problem setters use the [Codeforces Polygon Platform][polygon] to create problems, so this tool is widely used in ICPC Regional Contests in that region.

I hope to have this tool added to [the tools page of DOMjudge][dj-tools] to promote its usage and help more problem setters who use the [Codeforces Polygon Platform][polygon].

By the way, the author of this tool is @cubercsl.

[p2d]: https://github.com/cn-xcpc-tools/Polygon2DOMjudge
[polygon]: https://polygon.codeforces.com/
[kattis]: https://icpc.io/problem-package-format/
[dj-tools]: https://www.domjudge.org/tools

**Comment by vmcj** [comment]
The answer is here: https://github.com/DOMjudge/domjudge-scripts/blob/main/website/tools.shtml

Can you close this issue and let him/her create a PR against that repo? I think it's better if the original author promotes the tool.

**Comment by Dup4** [comment]
OK, Thank you

**Comment by Dup4** [comment]
OK, Thank you
