### ISSUE TITLE
How can I import a large number of teams with custom team IDs in versions 8.1.X and later?

### ISSUE THREAD

**Issue by as6325400** [DOMjudge/domjudge#2312]
I am an assistant for a course and would like to use this system to allow students in my class to submit assignments. I want to create accounts for the students using their student IDs. In versions prior to 8.0.X, this was possible, but in later versions, it seems that team IDs are forcibly assigned to smaller, unused numbers.

When using domjudge-contributor to run version 8.0.X, there is an issue with the PHP version being too high. Is there a way to contribute to version 8.0.X (which allows custom team IDs)?

I apologize for any inconvenience, but I have specific features I would like to add, so I need to use a contributor. However, there is the issue of team IDs in version 8.1.X, and the problem of not being able to use the contributor docker image in version 8.0.X. How can I resolve these issues?

**Comment by nickygerritsen** [comment]
There is a setting at the configuration page called 'data source' (see screenshot). Set it to 'configuration data external' and you should be able to supply your own ID's.
<img width="446" alt="image" src="https://github.com/DOMjudge/domjudge/assets/550145/c1cdd6c0-36e6-4e6b-badb-96689961c251">

**Comment by as6325400** [comment]
Thanks
