### ISSUE TITLE
dc_make_ubuntu_java_chroot calls unknown command

### ISSUE THREAD

**Issue by bertptrs** [DOMjudge/domjudge#233]
The script `dc_make_ubuntu_java_chroot` attempts to call `dj_make_ubuntu_chroot`, which does not exist in the current domjudge debian package.

I suspect this should be changed to `dj_make_chroot`, which is present.

**Comment by thijskh** [comment]
Thanks. This has already been fixed in master in 62115509746742e3e5af641ae69fae100f652fd0. Indeed your suspicion is the right solution.
