### ISSUE TITLE
import-contest should create an upload log

### ISSUE THREAD

**Issue by vmcj** [DOMjudge/domjudge#2342]
### Description of the enhancement request
When you upload more problems than fit in your terminal window it is hard to check if you got any danger/warning messages. I would like it if we log all choices made and the returned warnings/errors which were printed (or alternative just all interactions)

(I've updated the requirement)

**Comment by eldering** [comment]
You can always scroll back, right? Maybe just print a final summary line of the number of warnings/errors so you're aware?

**Comment by vmcj** [comment]
> You can always scroll back, right? 

Not everyone will do that, 
> Maybe just print a final summary line of the number of warnings/errors so you're aware?

That's also fine,
