### ISSUE TITLE
Real number timelimit

### ISSUE THREAD

**Issue by myungwoo** [DOMjudge/domjudge#235]
As I know, DOMJudge can't evaluate submission with real number timelimit such as 1.2, even if Java time factor 1.2 and problem's timelimit is 1 since 'maxruntime' is calculated by "ceiling(timefactor * timelimit)".

I wish real number timelimit. :)

**Comment by eldering** [comment]
I think it may be possible to change to floats nowadays, since we check the actual wall/cpu time afterwards. This means carefully checking how the timelimit is passed from DB -> API -> judgedeamon -> testcase_run -> runguard.
