### ISSUE TITLE
Though restapi.secret has been set, the docker container of judgehost can't be run correctly.

### ISSUE THREAD

**Issue by HuParry** [DOMjudge/domjudge#2352]
NOTE: If this is a _discussion starter_, you need any _installation help_ or have a _question_ on how to accomplish something,
rather post at [our discussion channel](https://www.domjudge.org/chat) or send an email to our
[DOMjudge-devel mailinglist](https://www.domjudge.org/mailman/postorius/lists/domjudge-devel.domjudge.org/)
instead of filing an issue here.

### Description of the problem
The dockercontainer of judgehost can't be run correctly. 

### Your environment
- DOMjudge version is 8.2.0.
- Redhat 8.5.0
- Ngnix

### Steps to reproduce
I use docker-compose way from the project [domjudge-compose](https://github.com/SirlyDreamer/domjudge-compose). Definitely I've succeeded in set up a domjudge in my previous server. So this way is a perfect way for me. But today I use another server to set up a domjudge. Both database and domserver are formal, but when run judgehost docker container there are any wrong message.

### Expected behaviour
It should be successful.

### Actual behaviour
Let's see what happened in judgehost container:
![image](https://github.com/DOMjudge/domjudge/assets/103566602/e2a50020-10c9-4f8f-b610-ee76d35e3bfd)
Error while executing curl POST to url http://domserver/api/v4/judgehosts: http status code: 404. I learned the same situation of others. They all said that `restapi.secret` don't be set correctly. But now I've set it as before.

### Any other information that you want to share?
I'm a Chienese student, and not good in English. If someone can help me, I will appreciate it.

**Comment by 87ouo** [comment]
As you can see this in your screenshot and description:  http://domserver/api/v4/judgehosts
It's not a valid API address, don't you think so?
You should set this API address correctly with what address your domserver actually at, like http://192.168.0.220/api/v4/judgehosts.
If your domserver is also a docker container, you should be careful with the port.

**Comment by HuParry** [comment]
Alright. Domserver was set up by docker, either. 

How can I change the address? I never modify it before.

**Comment by Dup4** [comment]
Perhaps you can set your domserver address by injecting the `DOMSERVER_BASEURL` environment

**Comment by HeRaNO** [comment]
Maybe you can check the guide at [domjudge/judgehost - Docker Image | Docker Hub](https://hub.docker.com/r/domjudge/domserver), and set the `Environment variables`. These variables should also be set using docker-compose (w/o `--link` options).

**Comment by HuParry** [comment]
I got it. Thank you very much.
