### ISSUE TITLE
Add tests for problemset pages

### ISSUE THREAD

**Issue by nickygerritsen** [DOMjudge/domjudge#2393]
We currently don't have any tests that tests whether the public/team doesn't have access to the problemset pages and linked files before contest start.

I think we should, since this can be a big security risk.

**Comment by as6325400** [comment]
The CI that checks the access permissions for each page is written where?

Is this for GitLab?

**Comment by vmcj** [comment]
> The CI that checks the access permissions for each page is written where?
> 
> Is this for GitLab?

This is in `webapp/tests`, the PHPUnit tests.

**Comment by as6325400** [comment]
ok Thanks
