### ISSUE TITLE
Judgedaemon should not crash when one of multiple endpoints unreachable

### ISSUE THREAD

**Issue by eldering** [DOMjudge/domjudge#240]
Currently, when a configured REST API endpoint cannot be reached the judgedaemon crashes with an error. This is reasonable if there is only one endpoint (the default), but when multiple endpoints are available, I think the unreachable endpoint should simply be ignored, so that the others are still processed. Maybe the unreachable endpoint should periodically (every wait loop, less frequently?) be checked for availability.

**Comment by thijskh** [comment]
And perhaps this should happen always, not dependent on the number of configured endpoints.

**Comment by meisterT** [comment]
I agree with Thijs. The judgedaemon should almost never abort.
