### ISSUE TITLE
Allow to Set Team Group on Contest

### ISSUE THREAD

**Issue by jGleitz** [DOMjudge/domjudge#241]
To manage multiple, parallel running contests, it would be really nice to be able to assign some sort of groups (e.g. Team Category) of users to a contest. Right now, each team allowed to see a non-public contest needs to be specified on its own, which is a tedious (and error prone) process.

**Comment by meisterT** [comment]
Good idea! A patch to implement this feature would be very welcome.

**Comment by jGleitz** [comment]
@meisterT I already had a look at the code and tried to figure out what needs to be done for this.

Do I see it correctly that there are no data classes in DOMJudge but every code accesses the database directly? If yes, could you give a estimation which parts would be affected by this change?

**Comment by ubergeek42** [comment]
There's no ORM so to speak, but there are some helper functions that try to centralize some bits. But for the most part things get touched all over the place.

You'd probably want to start somewhere around here, as this determines what contest a team has access to: https://github.com/DOMjudge/domjudge/blob/master/lib/lib.misc.php#L35

Right now access is done by the contestteam table which is a mapping of contestid to teamid. Searching the codebase for references to that table will show the places you'd need to modify.

I'm not sure what the right way to implement it would be, maybe a contestcategoryteam table or something like that.

**Comment by eldering** [comment]
That is right, we do not (yet) an ORM. There are long-term plans to migrate to Symfony and Doctrine for this, see #198. All database access is done through the home-grown `lib/lib.database.php` library with the `$DB->q()` function.
As ubergeek42 said, I think a good option would be to copy the `contestteam` table and its use into a new `contestteamcategory` table.

**Comment by jGleitz** [comment]
@ubergeek42, @eldering Thanks for the guidance! I will look into this during the next days.
