### ISSUE TITLE
Allow Passing CLI Arguments

### ISSUE THREAD

**Issue by jGleitz** [DOMjudge/domjudge#242]
The concept of custom run scripts seems powerful and predestined to realise passing parameters to submissions. However, I did not find a straightforward way to do this.

Currently, I use this code in my run script to pass arguments to the tested software:

```bash
PROGSCRIPT=execdir/program # Script runing the tested software
printf %s "$(cat "$PROGSCRIPT")" > "$PROGSCRIPT" # remove last \n
echo ' "$@"' >> execdir/program # append $@ to call
```

This feels just like a very dirty hack. However, it allows to simply append parameters for the program to the `program` parameter passed to the run script.

I propose to add `$@` to the `program` script created for submissions. This would allow an easy, non-hacky way to pass parameters to submissions.

**Comment by eldering** [comment]
If I understand you correctly, you mean adding this to `program` scripts that are generated for interpreted languages, including e.g. Java?
This sounds reasonable to me. The default `run` script already passes arguments through to `program` and if that is a compiled C/C++ source then it already receives any extra arguments. Thus it seems reasonable that the same is true for other languages.

**Comment by jGleitz** [comment]
> If I understand you correctly, you mean adding this to program scripts that are generated for interpreted languages, including e.g. Java?

Exactly. Sorry for not being precise enough.
