### ISSUE TITLE
Self-registering allows weak password

### ISSUE THREAD

**Issue by eldering** [DOMjudge/domjudge#2458]
### Description of the problem

When I self-register, I can use a password that consists of only 8 lowercase characters, while if I change/set a password from the jury interface (for the very same user I just created) it tells me that the password requires at least 10 characters.

### Your environment

DOMjudge `wfluxor-online` branch.

### Expected behaviour

I'd expect the same password policy to be applied.

**Comment by vmcj** [comment]
Closing as the message for https://github.com/nickygerritsen/domjudge/commit/0f88011e804fe39a381236abd6ca23902ddbd2a2 uses the keyword for it.
