### ISSUE TITLE
Default script file size limit is too low

### ISSUE THREAD

**Issue by meisterT** [DOMjudge/domjudge#247]
Use c++11 and compile something like:
int array[$large_num] = {-1};

This will create a large binary outside of DOMjudge and crash with an unintuitive gcc internal error in the sandbox.

a) report back, when the program is exactly on file size limit to give a better error message?
b) increase defaults
c) add config check

**Comment by eldering** [comment]
I already committed https://github.com/DOMjudge/domjudge/commit/223e31f43885a8ca5c14d7b5ab0d43b99fd532c1
Do you think that addresses the issue correctly? Feel free to make changes.

**Comment by meisterT** [comment]
I must have missed that, closing.
