### ISSUE TITLE
Disable clarifications in teams interface

### ISSUE THREAD

**Issue by vmcj** [DOMjudge/domjudge#2474]
When you deploy a mirror contest you might not want to allocate human judges to answering on the mirror. To make this explicit it would be good if teams can't submit those clarifications at all (the alternative would be to just send a global clarification about this).

**Comment by eldering** [comment]
Not sure this is worth adding another configuration item. As mentioned, you can either send a general clarifation about this, or mention this outside of DOMjudge.
