### ISSUE TITLE
Make it possible to diff with non-consecutive submissions

### ISSUE THREAD

**Issue by meisterT** [DOMjudge/domjudge#248]
Sometimes it's useful to diff this submission not to the most recent previous submission but the first submission of that team.
Maybe display a list of submissions by that team on the source code or diff page (or both)?

**Comment by eldering** [comment]
I would suggest to put this on the source code page; the submission page is already cluttered enough as it is. What about tracing a list of "ancestry" of this submission: another submission is a parent if it is either:
- a submission linked by `origsubmitid`
- a previous submission with the same team,language,problem
Then we allow a diff with all ancestors via a dropdown selection box, and we choose a sensible default to display initially.
Only problem I see, is that if you resubmit as jury, you might get offered diffs to other (re)submissions that are completely unrelated. I'm not sure there is a perfect way of filtering these out while keeping all possible relevant submissions. An alternative is to allow giving an explicit submission ID to diff against.
