### ISSUE TITLE
Handle invalid RGB value in problemset

### ISSUE THREAD

**Issue by meisterT** [DOMjudge/domjudge#2482]
When importing a problemset with invalid RGB values (such as `#tobiii`), it crashes the import, and provokes an internal server error that can only be fixed by manual database changes.

**Comment by nickygerritsen** [comment]
What do we want here? I expected the code to NOT save the contest problem. Clearly it IS doing that, but is that the fix, not creating the contest problem and still throwing the error? Or should we fall back to some color?

**Comment by nickygerritsen** [comment]
Ah I now know what's wrong: when adding all problems initially it already breaks but we don't check. I will add validation there.
