### ISSUE TITLE
Reconsider problemset names

### ISSUE THREAD

**Issue by meisterT** [DOMjudge/domjudge#2483]
The currently supported list of names doesn't include `problemset.pdf`: https://github.com/DOMjudge/domjudge/blob/main/misc-tools%2Fimport-contest.in#L120

This bit us at the finals where we then had to upload things manually and uploaded the dress for one of the contests first...

**Comment by thijskh** [comment]
Should the list of allowed names not follow from one of the specs?

**Comment by meisterT** [comment]
Good point, @eldering is this specified somewhere?

**Comment by nickygerritsen** [comment]
The spec says that you should specify the filename in the JSON/YAML: https://ccs-specs.icpc.io/draft/contest_package#file-references

**Comment by meisterT** [comment]
That sounds like a very complex mechanism for something where we could just agree on a standard name.

**Comment by nickygerritsen** [comment]
I agree. I believe there is an undocumented agreement that the filename matching the property is the way to go, so that would be `problemset`.
