### ISSUE TITLE
Improve urgent/warning status in menu

### ISSUE THREAD

**Issue by meisterT** [DOMjudge/domjudge#2486]
We probably could reduce clutter by only adding menu items if they're relevant to the user currently. 

Rejudgings only need attention if there's actually one going on. 

Judgehosts only need attention if there's an internal error. 

And there may be other warnings that we should show, e.g. when a language or problem is disabled....

**Comment by eldering** [comment]
I think at some point in the past we had menu items only show up when they were "relevant" something like you describe. I recall that that was confusing.

Highlighting menu items in need of attention seems fine to me, but I think we already do so.
