### ISSUE TITLE
Status of jury/unfrozen scoreboard.zip

### ISSUE THREAD

**Issue by meisterT** [DOMjudge/domjudge#2487]
If you download a jury/unfrozen scoreboard zip from the jury/contest page, it says "contest over, waiting for results" which is technically correct since the contest is still frozen, but this should be final standings.

**Comment by tuupke** [comment]
Furthermore, the contest has to be at least active. (did not test with different states yet) When the contest has not yet started downloading the unfrozen scoreboard throws a 500, downloading the public scoreboard zip does work.
