### ISSUE TITLE
Security flaw in runguard: process group not set

### ISSUE THREAD

**Issue by trampgeek** [DOMjudge/domjudge#250]
When `testcase_run.sh` calls `runguard`, it gives it a `--user` parameter but not a `--group` parameter. So the process still runs with its initial group, which is root (because it's run with `sudo`)! Furthermore, setting the `--group` parameter doesn't solve the problem either, because even after the `setuid()` and `setgid()` calls, the process retains all its initial auxiliary groups, which still includes group 0 (root).

As a simple demonstration, submit the following Python3 job:

    with open('/etc/sudoers') as fin:
        print(fin.read())

You'll see that instead of getting a Permissions error (which is what you expect, as the file is owned by root, has root as its group, and has a mode of 640) you get the full file contents.

The fix I've implemented in my own use of runguard (the Jobe server) is to include the `--group` parameter in the call and add the following two lines after the `setgid()` call:

    gid_t aux_groups[] = {rungid};
    if (setgroups(1, aux_groups)) error(errno, "cannot clear auxiliary groups");

However, I think it would be safer if you didn't even need to use the separate `--group` parameter at all.

**Comment by thijskh** [comment]
Thanks for the report! We'll see to addressing this shortly.

**Comment by eldering** [comment]
The fix is fairly large (introducing a configure option for a RUNGROUP and use this), this combined with the fact that in the default chroot environment there is no file group-owned by root, we're not sure yet whether and how to backport this to other branches.
