### ISSUE TITLE
Live Iso images do not get mounted

### ISSUE THREAD

**Issue by leder11011** [DOMjudge/domjudge#253]
Hello,

the live iso images:
2016-05-02  8.4 (Jessie)    5.1.1
2017-02-12  8.7 (Jessie)    5.1.3

are reported as corrupt by windows and do not let themselves be mounted.

Is this a known issue?

Thanks!

BR
Gerrit

**Comment by eldering** [comment]
Hi Gerrit,

Be aware that these are **not** iso images, just raw disk images with a partition table on them and partitions in (Linux) ExtFS 3/4 format. You can for example use https://www.virtualbox.org/ to run the image as a virtual machine.

**Comment by leder11011** [comment]
Hi Eldering,

thanks for the info! 

BTW This describes howto get VDI file from RAW:
https://blog.sleeplessbeastie.eu/2012/04/29/virtualbox-convert-raw-image-to-vdi-and-otherwise/

BR
Gerrit

**Comment by eldering** [comment]
Indeed, see also our documentation at https://github.com/DOMjudge/domjudge-packaging/tree/master/live-image
