### ISSUE TITLE
Adding account to team without user fails with ds=1

### ISSUE THREAD

**Issue by vmcj** [DOMjudge/domjudge#2535]
### Description of the problem
Given datasource=1 & a team without an account. It is not possible to use the `Add user to this team > Create new user`
I suspect because we don't have a field for external ids and don't autocreate one.

**Comment by nickygerritsen** [comment]
We should probably set the external ID to the username here.

**Comment by meisterT** [comment]
One more reason to clean up the data source mess

**Comment by nickygerritsen** [comment]
It seems the whole 'add user to team' for existing teams doesn't work. Looking at the code this form shouldn't be rendered for existing teams so I am going to find out why it does and drop it.
