### ISSUE TITLE
Jury interface not showing teams

### ISSUE THREAD

**Issue by krivosbellus** [DOMjudge/domjudge#254]
Jury interface (5.3.1) is not showing teams (aka "No teams defined") in case when there is no public contest (only private ones). 
Adding team in  jury interface adds team to database but not showing team in `www/jury/teams.php` - it allows also multiple teams with the same teamname ... even when `-no contest` is selected in jury interface.

You have to add team, add it in the contest and only then it shows in teams interface.

**Comment by eldering** [comment]
The commit referencing this should also apply to version 5.1.3 (5.3.1 was a typo I assume).
