### ISSUE TITLE
Default to C11/C++11 for gcc/g++

### ISSUE THREAD

**Issue by SolalPirelli** [DOMjudge/domjudge#257]
The first version of gcc to fully support C++11 was [4.8.1](https://gcc.gnu.org/projects/cxx-status.html#cxx11), which was released [in May 2013](https://gcc.gnu.org/gcc-4.8/). Even Ubuntu 14.04 LTS [includes it](http://packages.ubuntu.com/fr/trusty/gcc-4.8).

As for C11, [the features not in GCC 4.8](https://gcc.gnu.org/wiki/C11Status) seem extremely unlikely to be used in programming competitions.

I suggest changing the default C compile script to include `-std=c11` and C++ to include `-std=c++11`.

**Comment by eldering** [comment]
My personal preference would be to keep the standard unspecified in the default compile script. This way the compiler will always pick a standard that is well supported, and the script is future proof.

**Comment by SolalPirelli** [comment]
Looking at the GCC doc archives, it seems there was a sudden jump recently from having C++98 (well-supported for quite a while, but old) as the default to C++14 (pretty new), which may indicate that in the future the default version will move quicker.

I'll close this, since it seems to be a problem that will fix itself fairly soon.
