### ISSUE TITLE
Test database upgrades

### ISSUE THREAD

**Issue by vmcj** [DOMjudge/domjudge#2577]
Currently the database upgrade is not tested:

- Install an older (un)supported release via the documentation
- Do some minimal actions:
  - Create a team
  - Create a clarification
  - Answer it
  - Upload a problem
  - Submit a problem
  - Create some extra entities and delete those for example:
    - Create a contest,
    - With a team submit
    - Delete the contest again 

Keep the dump small, upgrade tests can be fast as we don't need a lot of problems/submissions but rather more (rarely used) functions/features tested.

When we have this dump we can make an CI job to test the upgrade with `./bin/dj_setup_database upgrade`.

**Comment by as6325400** [comment]
So should I run some operations locally, export the database, and then run dj_setup_database upgrade in CI to check for errors? Where should I store the exported .sql file?

Or should everything be done in CI, including the old version of Domjudge?

**Comment by as6325400** [comment]
So, where should the old database file be placed?
