### ISSUE TITLE
Add a button to "heat up" all judgehosts with all problems

### ISSUE THREAD

**Issue by SolalPirelli** [DOMjudge/domjudge#258]
When first judging a problem, a judgehost has to retrieve related data: inputs, expected outputs, compare programs, etc.

Even when problems are tested beforehand, if there are many judgehosts, it is almost certain that contestants who first submit solutions for a problem will experience slow judging because their problem will be judged by a host who has not judged that problem before. For problems with large input/output or many testcases, it can take quite a while.

I imagine that one solution to this would be to create, for all problems, a fake submission with a program that does nothing, and send it to all judgehosts for judging, to ensure they all have local versions of everything needed for judgement.

**Comment by eldering** [comment]
I'm not a big fan of submitting fake submissions: it requires a default team to be present and creates "ghost" submissions. Instead, I would prefer a special command that suggests judgehosts to pre-cache this data. However, that requires a redesign of how judgehosts connect, because currently they only poll for submissions, and there is no easy way to submit commands; this also affects #215.

**Comment by thijskh** [comment]
Could it not instead be a configuration option of judgehosts, e.g. 'judgehosts_prefetch`? That instead of only polling for something to judge, they also periodically see if there are new problems visible to them and if so, immediately download all stuff related to those problems?

**Comment by meisterT** [comment]
By adding a new judgetasktype (e.g. prefetch) this would be simple to implement client side. Don't do the judging, but just the fetching.

**Comment by meisterT** [comment]
This can now be triggered on a contest and then on the client side fetches new scripts and data:
![image](https://user-images.githubusercontent.com/418721/113482000-e6a03480-949c-11eb-8838-dfdd42657a3c.png)
