### ISSUE TITLE
Our HTML5 websubmit does not support ordering multiple files

### ISSUE THREAD

**Issue by eldering** [DOMjudge/domjudge#261]
The HTML5 standard says nothing about the ordering of multiple files in a file picker dialog. This means that it is up to the browser in what order to send the files, so we can't use the ordering information to infer what is the main source file.
(For the command line submit client this works fine, since we control the order of files.)

**Comment by thijskh** [comment]
This has been "fixed" with the `entry_point` field?

**Comment by eldering** [comment]
Correct-ish, I think.
If an `entry_point` is provided, then that eliminates the need for an ordering of the files. However, if `entry_point` is not required and not provided, then we still need to determine the main file.
Maybe we should just declare that that choice is not well determined, and you have to specify the `entry_point` to make sure that a particular file/class is used.

**Comment by meisterT** [comment]
It might make sense to reduce the number of available code paths and always require an entry point.

**Comment by eldering** [comment]
I really prefer not to bother teams with this extra question if we don't have to. That is, if they submit a single file e.g. in Python, or a multifile Java submission with a uniquely defined class with the right `main` method, then the `entry_point` should not be asked for.

I'm gravitating towards some settings/scripts per language:
- a setting: does this language use an `entry_point` without explicitly specifying what it means, or maybe as string that can be used in frontend to describe the meaning of it.
- a script that runs server-side at submit time to determine the `entry_point`. Since it runs on the domserver, it should be plain POSIX shell and not have any dependencies besides the standard UNIX stuff. This script may not always return an `entry_point`.
- the compile script should be able to handle an empty/no `entry_point` passed to it; either by auto-detecting it or failing with a compiler-error.
- if the global setting `require_entry_point` is set, then we show teams this field in the submission form. If they don't enter anything and the submit-time script fails to detect the `entry_point`, then the submission fails.

**Comment by meisterT** [comment]
Executing (even simple shell scripts) on submitted code on the server is probably not the best idea considering security implications. It also adds one more level of complexity - we then would have entry point guessing in the web interface (in JS) (or the submit client in C), server side in the script (in Shell), in the compile script on the judgehost (called from shell, can be anything). It becomes non-trivial to add a new language.

Another idea would be: when the entry_point is required (both globally and for the selected language), it has always to be specified. When the entry_point is not required, we don't do auto-detection but follow some convention, e.g. main source file for problem A has to be called A.py and main class for A has to be called A and so on. This is at least transparent and rather light weight.

I guess we should spend some time to discuss our options in real life when we meet.

**Comment by meisterT** [comment]
One more question to think about until we discuss in person: for what language do we actually want to look into the file contents (in the server side script)? All other information (file names, problem name, language) are available before hitting the submit button.

**Comment by eldering** [comment]
Related issue: #319

**Comment by eldering** [comment]
I think this can be closed indeed. I still think that in some corner cases we may not have a perfect solution, e.g. submitting a multi-file python solution without require_endpoint set, but that's too much an edge case to deal with.
