### ISSUE TITLE
The line break in the tooltips of public statistics does not show correctly

### ISSUE THREAD

**Issue by cubercsl** [DOMjudge/domjudge#2613]
### Description of the problem
The line break in the tooltips of public statistics does not show correct and inconsistent behavior in `/jury`, `/team`, and `/public`

![image](https://github.com/DOMjudge/domjudge/assets/22931465/3d8e4d56-a540-479f-a3fe-038a0ebadf07)

### Your environment

- DOMjudge 8.4.0 DEV
- Debian 12
- Nginx

### Any other information that you want to share?
Before fix in #2603, `<br/>` shows in `/public` and `/team`, because
bootstrap5 uses `data-bs-*` instead of `data-*`, so `data-html` should be replaced by `data-bs-html`. After that, `<br/>` can be shown as a line break correctly.

https://github.com/DOMjudge/domjudge/blob/b62fe65651c5b7a418b0d568979ee0a7f1732fda/webapp/templates/partials/problem_list.html.twig#L92-L98

Also, all the tooltips should be initialized by js. If we use jQuery, it should be

```js
$('[data-bs-toggle="tooltip"]').tooltip();
```

while this already included in `/jury`, but not in `/public` and `/team`.

To fix this issue (and/or other potential problems), we should:
- Change bootstrap related data attributes from `data-*` to `data-bs-*`;
- Enable all tooltips in a suitable template.

**Comment by vmcj** [comment]
@cubercsl do you want to create a PR for this?
