### ISSUE TITLE
./configure searches in the wrong location for jsoncpp headers

### ISSUE THREAD

**Issue by Earnestly** [DOMjudge/domjudge#262]
* jsoncpp 1.8.0

When attempting to build domjudge 5.1.3 and running `./configure` I encounter the following error:

```
...
checking jsoncpp/json/json.h usability... no
checking jsoncpp/json/json.h presence... no
checking for jsoncpp/json/json.h... no
configure: error: JSONcpp headers not found (required for submit client)
```

Inside `config.log` I find it fails here:

```
configure:6447: checking jsoncpp/json/json.h usability
configure:6447: g++ -c -g -O2 -Wall -fstack-protector -fPIE -D_FORTIFY_SOURCE=2  conftest.cpp >&5
conftest.cpp:54:31: fatal error: jsoncpp/json/json.h: No such file or directory
 #include <jsoncpp/json/json.h>
                               ^
```

Now I have installed `jsoncpp` with its fairly standard locations and its upstream defaults (`/usr` prefix) to `/usr/include/json/json.h`.

jsoncpp.pc also comes with a `jsoncpp.pc` file which you could use in the form of `pkg-config --cflags jsoncpp` if you wish to alter the default location from standard.

**Comment by Earnestly** [comment]
Nevermind, I was still using `5.1.2` where this was still broken and find that `5.1.3` searches correctly for the standard location as well.

I will suggest using `pkg-config` regardless.

**Comment by eldering** [comment]
Indeed, see also https://www.domjudge.org/pipermail/domjudge-devel/2016-July/002065.html

We might have a look into `pkg-config`
