### ISSUE TITLE
Retrieve Test Cases using API

### ISSUE THREAD

**Issue by muhammad-tayyab** [DOMjudge/domjudge#2623]
I am developing a plugin that interacts with DOMJudge using its API. I can access other information such as available contests, problems with their pdfs etc. however, I don't know how to get/ download sample test cases as a team member using this API.

Additionally, I was not able to find information on retrieving a login token, instead of providing username, password with every request.

**Comment by vmcj** [comment]
> I am developing a plugin that interacts with DOMJudge using its API. I can access other information such as available contests, problems with their pdfs etc. however, I don't know how to get/ download sample test cases as a team member using this API.
> 
You can find this on the API doc: https://www.domjudge.org/demoweb/api/doc, search for `samples.zip`.

> Additionally, I was not able to find information on retrieving a login token, instead of providing username, password with every request.

We don't support having a login token, you can set IP authentication or can use `REMOTE_USER` for more advanced usecases (see the manual for that).

I'll close this now, if you have more questions its better to ask those in chat (https://www.domjudge.org/chat).
