### ISSUE TITLE
Hide problem texts from public (in the scoreboard)

### ISSUE THREAD

**Issue by machitgarha** [DOMjudge/domjudge#2634]
### Description of the enhancement request

In some situations, it's useful to have a public scoreboard, but deny the access to contest problems. Even further, I think it should be opt-in rather than opt-out: It shouldn't be visible to everyone out of the contest teams. Having a contest-specific option for this is a good idea.

P.S.: Currently, the way to do it is to edit the `PublicController` class, and redirect the endpoints elsewhere (e.g. back to the scoreboard).

### The goal you want to achieve

The primary goal for this is to provide contest security.

### Expected behaviour

When you click on the problems in the header of the scoreboard, you shouldn't see the problem text, or at least there should be a way to disable it.

**Comment by meisterT** [comment]
Out of curiosity: under what circumstances is it not ok to share problem texts but their difficulty with the general public?

**Comment by machitgarha** [comment]
I talked to our team, and this feature seems to have little to no impact for our situation.

We wanted to prevent cheats during the contest. Participants were connected to a local area network, and at the same time, people out of the contest could be connected to the same network at the same time. Configuring the firewall didn't work, so we wanted to reduce what unprivileged people can do and see, and this was one of them. We wanted to prevent them sending the solutions, but for it they need to open up a local connection in the first place, and we didn't pay attention that if this happens, the participants could send the password over the connection, and denying the access to problems helps nothing. :)

So I'm going to close this. Thanks for the quick reply.
