### ISSUE TITLE
Improve problem import

### ISSUE THREAD

**Issue by meisterT** [DOMjudge/domjudge#265]
- Read timelimit from .timelimit file if exists (and is not overwritten in domjudge-problem.ini)
- If problem title is not in domjudge-problem.ini,
  * parse problem_statement.tex?
  * set it to some default but do not fail import

**Comment by eldering** [comment]
See also #269

**Comment by eldering** [comment]
All done now. Problem name is already read from the `problem.yaml` file as specified in http://www.problemarchive.org/wiki/index.php/Problem_Format#Problem_Metadata
