### ISSUE TITLE
Import of accounts.tsv: create teams for non-team accounts

### ISSUE THREAD

**Issue by meisterT** [DOMjudge/domjudge#266]
While importing data from accounts.tsv we should create teams for jury users automatically so they can edit and resubmit.

**Comment by meisterT** [comment]
This was already done by 7a7e5fc27381383da43d9004f6fee572c1c6a083.

However, it now complains with
`eventlog: API ID not specified or inferred from data`
probably because teams in the jury category are not visible.

@eldering, can you please have a look?
￼

**Comment by eldering** [comment]
Closing this as it has been unreproducible and we've made many changes to the API code in the mean time.
