### ISSUE TITLE
Improve REST import

### ISSUE THREAD

**Issue by meisterT** [DOMjudge/domjudge#267]
* on differences, ask interactively if the internal data should be overwritten with the imported data
* also check timelimits
* automatically detect mappings, ideally, the import configuration only consists of credentials and contest id

**Comment by eldering** [comment]
Time limits are now read from `domjudge-problem.ini` or `.timelimit`, see 7dd8b92cc0ca832180d56b4d36c2d3eb6e7a9f63.
The final point on detecting mappings is not clear to me. Also we still do not have a specification of a single source of data.

**Comment by meisterT** [comment]
This issue was about the rest import and can be closed. I'll still comment on the items because we probably want the same properties when we implement the import from the new feed.

With differences I was for example referring to updates of the start time. With the new feed there should be proper events for things like these and we should probably just do the change. Previously, we either didn't recognize a change, ignored it even if we did recognize it or bailed out.

With time limit checking I was not referring to import (which is still great that you've implemented that) but comparison of the configured time limits with the primary system.

The mapping between internal and external IDs was a mess to configure and I think with the new system that you introduced for the event feed it could be much less or even zero configuration.
