### ISSUE TITLE
 judgehost docker launch Error

### ISSUE THREAD

**Issue by Thaumaturge2020** [DOMjudge/domjudge#2678]
NOTE: If this is a _discussion starter_, you need any _installation help_ or have a _question_ on how to accomplish something,
rather post at [our discussion channel](https://www.domjudge.org/chat) or send an email to our
[DOMjudge-devel mailinglist](https://www.domjudge.org/mailman/postorius/lists/domjudge-devel.domjudge.org/)
instead of filing an issue here.

### Description of the problem
> Replace this line with a short description

judgehost launch Error

### Your environment
> Include details about your installation here.
> - DOMjudge version (e.g. 7.0.0 or a github commit hash)
> - Operating system / Linux distribution and version (e.g. Ubuntu 18.04)
> - Webserver (e.g. Apache or nginx)

### Steps to reproduce
> Replace this with a description how we can reproduce your bug.
> - Step 1

cat the secret : 
cat restapi.secret
```# Randomly generated on host d0f3dc389f81, Wed Sep 11 01:34:30 CST 2024
# Format: '<ID> <API url> <user> <password>'
default	http://localhost//api	judgehost	a3Ouk6R07WwrHxMv/8X+UwOnYoLWSPfz
# NOTE(password-mismatch):
# The database was not automatically updated to use this judgehost password.
```

> - Step 2

use the secret a3Ouk6R07WwrHxMv/8X+UwOnYoLWSPfz with a hostname like judgehost-0 or judgehost to launch the judgehost machine

### Expected behaviour
> Replace this line with what you would expect to happen.

the docker machine launch normally

### Actual behaviour
> Replace this line with what happens instead.

the docker machine quit immediately after I start it and I got the error log in the follow:

I launch the judgehost machine but the judgehost quit immediately,and I got this error log:
```
[..] Setting timezone

Current default time zone: 'Asia/Shanghai'
Local time is now:      Wed Sep 11 11:19:39 CST 2024.
Universal Time is now:  Wed Sep 11 03:19:39 UTC 2024.

[ok] Container timezone set to: Asia/Shanghai

[..] Setting up restapi file
[ok] Restapi file set up

[..] Setting up cgroups
[ok] cgroups set up

[..] Copying resolv.conf to chroot
[ok] resolv.conf copied

useradd warning: domjudge-run-1's uid 62860 outside of the UID_MIN 1000 and UID_MAX 60000 range.
[Sep 11 03:19:40.077] judgedaemon[196]: Judge started on judgehost-1 [DOMjudge/8.2.3]
[Sep 11 03:19:40.077] judgedaemon[196]: 🔏 Executing chroot script: 'chroot-startstop.sh check'
[Sep 11 03:19:40.083] judgedaemon[196]: Registering judgehost on endpoint default: http://domserver/api/v4
[Sep 11 03:19:40.097] judgedaemon[196]: warning: Authentication failed (error 401) while contacting http://domserver/api/v4/judgehosts. Check credentials in restapi.secret.
[Sep 11 03:19:40.097] judgedaemon[196]: Registering judgehost on endpoint default failed.
[Sep 11 03:19:40.105] judgedaemon[196]: error: Authentication failed (error 401) while contacting http://domserver/api/v4/config?. Check credentials in restapi.secret.
```

### Any other information that you want to share?
> Please include webserver, symfony and judgedaemon log snippets here as appropriate.
> Screenshots may help in case of UI bugs.

**Comment by vmcj** [comment]
Can you run this and verify that this is the same as what you get for the judgehost container?
```
docker exec -it domserver cat /opt/domjudge/domserver/etc/restapi.secret
```

How did you start the 2 containers? Via a docker-compose file? Or did you start them after each other?

**Comment by vmcj** [comment]
I'll close this for now, when @Thaumaturge2020 responds we can check if there is indeed a bug or if the documentation needs to be updated.
