### ISSUE TITLE
Fix handling of runguard crash

### ISSUE THREAD

**Issue by meisterT** [DOMjudge/domjudge#268]
At least during compilation, the current behavior is broken since it returns a compile error (with unhelpful output).

**Comment by eldering** [comment]
Runguard will write its error message into the meta file with tag `internal-error`. We have to decide how to deal with it and where/how to show. The current problem is that the judgedaemon only uploads the compile output when the compilation finished (either correctly or failed).

**Comment by eldering** [comment]
We should check for this `internal-error` tag in the metadata file and trigger an internal error in the web interface.
