### ISSUE TITLE
Unable to run judgedeamon as a service, documentation seems to be incorrect

### ISSUE THREAD

**Issue by niconaus** [DOMjudge/domjudge#2681]
### Description of the problem
When trying to run the judgehost deamon as a service, I get an error.

### Your environment
- DOMjudge version  8.3.0
- Operating system Ubuntu 24.04.1 LTS
- Apache

### Steps to reproduce
[The manual states the following](https://www.domjudge.org/docs/manual/8.3/install-judgehost.html#starting-the-judgedaemon):

> The judgedaemon can also be run as a service by running:
> 
> `sudo systemctl enable --now domjudge-judgehost`

This gives me:

`Failed to enable unit: Unit file domjudge-judgehost.service does not exist.`

Looking at the domjudge source files, it seems that the way to launch the judgedeamon as a service has changed to the following:

`sudo systemctl enable --now domjudge-judgehost.target`

This does launch, and the deamon becomes active after this. For me, the judgehost still does not show up in the domjudge web interface, but I'm assuming that's a separate issue.

**Comment by Kevinjil** [comment]
Short on time to investigate, but possibly related to #2086

**Comment by vmcj** [comment]
> Short on time to investigate, but possibly related to #2086

Yes, that one was fixed in `main` with more documentation during the installation (See: ec7ca6c710d45b4bfa21e06be02d35d69a599998).

I think the problem here is that we need to update the documentation for `8.2` & `8.3` as in certain cases autocomplete does not pick this up.
