### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by AbdullahHashmi663** [DOMjudge/domjudge#2694]
NOTE: If this is a _discussion starter_, you need any _installation help_ or have a _question_ on how to accomplish something,
rather post at [our discussion channel](https://www.domjudge.org/chat) or send an email to our
[DOMjudge-devel mailinglist](https://www.domjudge.org/mailman/postorius/lists/domjudge-devel.domjudge.org/)
instead of filing an issue here.

### Description of the problem
>The server returned a "500 internal Server Error".

### Your environment
> Include details about your installation here.
> - DOMjudge version (e.g. 7.0.0 or a github commit hash)
> - Operating system / Linux distribution and version (e.g. Ubuntu 18.04)
> - Webserver (e.g. Apache or nginx)

### Steps to reproduce
> Replace this with a description how we can reproduce your bug.
I have followed every step as showed in documentation to install it at least three time but still I am facing the same error.

### Expected behaviour
> It should be installed easily.

### Actual behaviour
> Facing same 500 internal server error again and again.

### Any other information that you want to share?
> Please include webserver, symfony and judgedaemon log snippets here as appropriate.
> Screenshots may help in case of UI bugs.
![image](https://github.com/user-attachments/assets/fb41d797-2fb8-4307-ac23-0e895932023a)

**Comment by melongist** [comment]
Give it a try. The automated installation script I created for DOMjudge 8.3.1

https://github.com/melongist/CSL/tree/main/DOMjudge

**Comment by vmcj** [comment]
Hi, @AbdullahHashmi663 in the first section of the template we suggest that you ask this question in Slack instead of filing an issue. Can you ask your question in Slack and answer the other questions from the issue template.

I'll close this issue for now, if there is indeed an issue with the whole installation setup we'll re-open this issue.
