### ISSUE TITLE
Spurious keys visible for keyboard shortcuts

### ISSUE THREAD

**Issue by meisterT** [DOMjudge/domjudge#2701]
We should ignore more key combinations, e.g. when pressing `Ctrl+P` to print or `Ctrl+C` to copy something we currently detect this as `p` (or `c` respectively).

**Comment by mpsijm** [comment]
I also noticed this. Why not ignore all shortcuts if `e.ctrlKey` at https://github.com/domjudge/domjudge/blob/main/webapp/public/js/domjudge.js#L833?

**Comment by meisterT** [comment]
Yes, and probably also other keys

**Comment by mpsijm** [comment]
Oh, I had assumed that the "Fix #..." in the commit message would've auto-closed this, woops :joy:

**Comment by vmcj** [comment]
> Oh, I had assumed that the "Fix #..." in the commit message would've auto-closed this, woops 😂

I think it should (https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests) but I suspect github is of the opinion that you should be able to close issues you did not create yourself (unless you are part of the DOMjudge team).
