### ISSUE TITLE
Change submissions over time to bar plot

### ISSUE THREAD

**Issue by eldering** [DOMjudge/domjudge#2703]
On the `/jury/analysis` page it would be nice to replace the current submissions over time plot (see below) by a bar plot with submissions in given time interval buckets, so it's easier to see how many submissions arrived at each point/interval of time. Currently that's difficult to read off from the slope of the plot.

![image](https://github.com/user-attachments/assets/315097db-c125-4d16-9006-f79b5f0bcdea)

**Comment by as6325400** [comment]
Could you provide me with a dataset of submissions evenly distributed throughout a contest that I can import?

I think I can try modifying it, but I don't have the data. Thanks!

**Comment by eldering** [comment]
> Could you provide me with a dataset of submissions evenly distributed throughout a contest that I can import?
> 
> I think I can try modifying it, but I don't have the data. Thanks!

I can share the demoweb SQL dump with you. Can you ping me privately in slack?

**Comment by as6325400** [comment]
> > Could you provide me with a dataset of submissions evenly distributed throughout a contest that I can import?
> > I think I can try modifying it, but I don't have the data. Thanks!
> 
> I can share the demoweb SQL dump with you. Can you ping me privately in slack?

OK

**Comment by as6325400** [comment]
this issue can be close?
