### ISSUE TITLE
Add ability to favorite / heart teams in the mobile view

### ISSUE THREAD

**Issue by JustSamuel** [DOMjudge/domjudge#2762]
### Description of the enhancement request
Currently the mobile view does not support the ability to favorite teams.

### The goal you want to achieve
Align mobile view with desktop view.

### Expected behaviour
1. Go to the scoreboard with mobile view
2. see the heart symbol
3. have it work
4. ???
5. profit

### Any other information that you want to share?
Desktop:
![image](https://github.com/user-attachments/assets/f03fa5c0-1d19-491e-ac02-5979fa11b90f)

Mobile:
![image](https://github.com/user-attachments/assets/4106b376-b373-4ab0-8335-9939f9220899)

**Comment by nickygerritsen** [comment]
The mobile view is still a WIP but we know people want hearts 😁

**Comment by JustSamuel** [comment]
> The mobile view is still a WIP but we know people want hearts 😁

I was trying to make the PR myself, but I believe that opening an issue first is always good practice.

**Comment by nickygerritsen** [comment]
Feel free to do it. There is a mobile scoreboard branch you can use or the bapc2024 branch. We can cherry-pick it
