### ISSUE TITLE
Memory usage does not get reported 

### ISSUE THREAD

**Issue by eldering** [DOMjudge/domjudge#2763]
### Description of the problem
It was reported by @RagnarGrootKoerkamp that "a [submission](https://judge.bapc.eu/jury/submissions/1079) goes out of memory, yet shows 0B memory usage. Memory here should only grow in factors of 2, so it shouldn't go from 0 to a failing too large allocation, so somehow the memory measurement is underreporting."

![image](https://github.com/user-attachments/assets/7f521143-26ef-40ab-bf6f-6feea526114c)

All submissions at BAPC report 0 bytes memory usage.

### Your environment
At BAPC 2024 running current `main` branch including group v2.

**Comment by Kevinjil** [comment]
As noted in the Slack channel, this is reported in the compilation metadata:
```
internal-warning: Kernel too old and does not support memory.peak
```

**Comment by eldering** [comment]
> As noted in the Slack channel, this is reported in the compilation metadata:
> 
> ```
> internal-warning: Kernel too old and does not support memory.peak
> ```

Note that BPAC runs on Ubuntu 22.04, kernel 5.15.0.

**Comment by Kevinjil** [comment]
The `memory.peak` was introduced here:
https://lore.kernel.org/all/20220507050916.GA13577@us192.sjc.aristanetworks.com/T/#u

It is introduced in [v5.19](https://github.com/torvalds/linux/commit/8e20d4b332660a32e842e20c34cfc3b3456bc6dc) and [v6.5](https://github.com/torvalds/linux/commit/e0e0b4126c1f1effd480777507a61bd09360dc8f)

**Comment by nickygerritsen** [comment]
PC^2 does not report peak usage on these older kernels for this reason

**Comment by meisterT** [comment]
I have an older kernel, but it is recorded for me... weird.

```
$ cat /proc/version
Linux version 6.1.0-26-amd64 (debian-kernel@lists.debian.org) (gcc-12 (Debian 12.2.0-14) 12.2.0, GNU ld (GNU Binutils for Debian) 2.40) #1 SMP PREEMPT_DYNAMIC Debian 6.1.112-1 (2024-09-30)
```

**Comment by meisterT** [comment]
Ah, it's already in 6.0: 
![image](https://github.com/user-attachments/assets/e4280c7a-b31a-4e9c-a255-35cbb721d2a9)

**Comment by Kevinjil** [comment]
> Ah, it's already in 6.0:

Hmm good catch. The search function was just utterly borked :|
