### ISSUE TITLE
Indicate newly added testcases in judgings

### ISSUE THREAD

**Issue by Kevinjil** [DOMjudge/domjudge#2765]
### Description of the enhancement request
We should indicate the status of new testcases in existing judgings.

### The goal you want to achieve
Make it clear how a verdict was made, even though some test-cases are pending. At first glance, the screenshot below looks like a bug, but the test cases were modified (added later).

### Any other information that you want to share?
![image](https://github.com/user-attachments/assets/364291bf-3492-4e8d-a101-365891b96723)

**Comment by meisterT** [comment]
Similar to the other issue: was there no warning message on top?

**Comment by Kevinjil** [comment]
> Similar to the other issue: was there no warning message on top?

Nope
