### ISSUE TITLE
Shadowing import crashes when a team is found with an unknown category or affiliation

### ISSUE THREAD

**Issue by nickygerritsen** [DOMjudge/domjudge#2776]
When we find a team in the event feed that has a category or affiliation not yet present in DOMjudge, we try to create it [here](https://github.com/DOMjudge/domjudge/blob/0aa38dfb86e527c9563976246ad7cca2ae6774d8/webapp/src/Service/ExternalContestSourceService.php#L1100-L1100). However, we do not set any name and this gives an SQL error.

We can do two things:
* Do not import the team at this point and put it as pending, wait for the group / category to show up.
* Come up with a name (based in the external ID)

This happened because I could not import JSON files for the PC^2 GNY2024 shadow (since they are wrong) and they never gave us the group event. It should never happen in practice, but clearly it did.

My vote would be option 2, to make the event feed reader a bit more robust.

**Comment by vmcj** [comment]
> When we find a team in the event feed that has a category or affiliation not yet present in DOMjudge, we try to create it [here](https://github.com/DOMjudge/domjudge/blob/0aa38dfb86e527c9563976246ad7cca2ae6774d8/webapp/src/Service/ExternalContestSourceService.php#L1100-L1100). However, we do not set any name and this gives an SQL error.
> 
> We can do two things:
> 
> * Do not import the team at this point and put it as pending, wait for the group / category to show up.
> * Come up with a name (based in the external ID)
> 
> This happened because I could not import JSON files for the PC^2 GNY2024 shadow (since they are wrong) and they never gave us the group event. It should never happen in practice, but clearly it did.
> 
> My vote would be option 2, to make the event feed reader a bit more robust.

I assume we still update it when the correct event comes in?

**Comment by nickygerritsen** [comment]
If the whole a script wouldn't crash then yes we would

**Comment by nickygerritsen** [comment]
Already fixed in #2789.
