### ISSUE TITLE
Kotlin warning libjansi.so.lck

### ISSUE THREAD

**Issue by nella17** [DOMjudge/domjudge#2797]
### Description of the problem
Because in chroot judgement environment, `/tmp` not exists and not writable.  
In `kt` executable, it overwrites tmpdir to `/` (`-Djava.io.tmpdir=/`), it will result in permission denied.

### Your environment
- DOMjudge version 8.3.1
  - by [docker.io/domjudge/domserver:8.3.1](https://hub.docker.com/r/domjudge/domserver)
- Judgehost 
  - by [docker.io/nella17/judgehost:8.3.1](https://hub.docker.com/r/nella17/judgehost)
  - build via [Dockerfile](https://github.com/NYCU-PCCA/Winter-Camp-Contest-2023/blob/main/services/judgehost/Dockerfile) with build arg `DOM_VERSION=8.3.1` `KOTLIN_VERSION=2.0.21`

### Steps to reproduce
1. Install kotlin on judgehost
2. Submit Kotlin code.

### Expected behaviour

No warning in version check and compilation output.

### Actual behaviour

Kotlin complain the warning `/tmp/jansi-2.4.0-5f40a068bfd66cdb-libjansi.so.lck (No such file or directory)` in compiler version check.
<img width="713" alt="Screenshot 2024-11-14 at 22 32 38" src="https://github.com/user-attachments/assets/57bff5dd-d75a-4f4e-bf6c-4c9fe9ded54e">
It will show `/jansi-2.4.0-21816e7142183b0f-libjansi.so.lck (Permission denied)` when compile the Kotlin program.
<img width="746" alt="Screenshot 2024-11-14 at 22 35 05" src="https://github.com/user-attachments/assets/ac717db7-d173-4f82-a293-9ad920cfb668">

**Comment by vmcj** [comment]
Hi @nella17, can you explain why you think this is a problem with DOMjudge and not with how the kotlin release you use has been build? If this is a question for help it's better to ask it within the community (https://www.domjudge.org/chat).

Assuming you use debian/ubuntu in your chroot you can use the package from the repository which does work (but is a bit outdated).

**Comment by nella17** [comment]
Hi @vmcj, I followed the instructions in wiki [Installing Kotlin by editing judgehost install scripts](https://github.com/DOMjudge/domjudge/wiki/Adding-a-new-language#installing-kotlin-by-editing-judgehost-install-scripts) to build judgehost image using JetBrains/kotlin's release build [v2.0.21](https://github.com/JetBrains/kotlin/releases/tag/v2.0.21). 
I used the same Dockerfile with arguments `DOM_VERSION=8.1.3` `KOTLIN_VERSION=1.8.0` last year (2023 Feb); at that time, it didn't show this warning.

Besides, when I execute `kotlinc -version` using `/opt/domjudge/judgehost/bin/dj_run_chroot` script, it will work correctly without `No such file or directory` warning.
<img width="773" alt="Screenshot 2024-11-16 at 13 55 55" src="https://github.com/user-attachments/assets/154b3b41-fd9a-4b3d-a5b0-ae2e40ffe1be">

**Comment by vmcj** [comment]
> Hi @vmcj, I followed the instructions in wiki [Installing Kotlin by editing judgehost install scripts](https://github.com/DOMjudge/domjudge/wiki/Adding-a-new-language#installing-kotlin-by-editing-judgehost-install-scripts) to build judgehost image using JetBrains/kotlin's release build [v2.0.21](https://github.com/JetBrains/kotlin/releases/tag/v2.0.21). I used the same Dockerfile with arguments `DOM_VERSION=8.1.3` `KOTLIN_VERSION=1.8.0` last year (2023 Feb); at that time, it didn't show this warning.
> 
> Besides, when I execute `kotlinc -version` using `/opt/domjudge/judgehost/bin/dj_run_chroot` script, it will work correctly without `No such file or directory` warning. <img alt="Screenshot 2024-11-16 at 13 55 55" width="773" src="https://private-user-images.githubusercontent.com/14134195/386823254-154b3b41-fd9a-4b3d-a5b0-ae2e40ffe1be.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE3NDcyMzQsIm5iZiI6MTczMTc0NjkzNCwicGF0aCI6Ii8xNDEzNDE5NS8zODY4MjMyNTQtMTU0YjNiNDEtZmQ5YS00YjNkLWE1YjAtYWUyZTQwZmZlMWJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE2VDA4NDg1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE1MzExZmU4ODFiMWU5ZGI4OWQ2ZmZmNWZiZDkyYmE2MGUwYzc1MDBiYzU1MzlhOWU1NDAzMDc1YjU5NjM4NGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Uru58Fmitf3F2qDZVJpUjSMadoLjHdn3doNTHW5gnac">
> 
> I think this problem is related to the chroot script making `/tmp` unwritable.

So this is a question for help, can you ask it via the channel I mentioned?

The wiki part you link to was provided by someone in the community and not by us. 

And you are right this will be because of `/tmp` not being available (but that's by design) and you would need to find out why `libjansi` doesn't respect the `tmpdir` which is something kotlin specific (so content). If you accept the security risk you could use this: https://github.com/DOMjudge/domjudge/blob/ec356dd0e6273feed1499f4d67c6e16bd5779bfd/etc/judgehost-config.php#L12

**Comment by vmcj** [comment]
Closing as this is not a bug within domjudge but a problem with the specific way how the language is build in the chroot.

If you need more help you can ask it in chat so the rest of the community can also share their insights if they encountered that issue.
