### ISSUE TITLE
FHS Directory Tree Broken

### ISSUE THREAD

**Issue by EaTzUrFaCe** [DOMjudge/domjudge#280]
When using the latest (6.0.0-DEV) version of DOMjudge from source, running the configure script with the flag '--enable-fhs', the path for the webapp on the domserver is left empty. This causes an error when attempting to build and install the domserver role on a machine.

Reproduce by running `./configure --enable-fhs --disable-submitclient --sysconfdir=/etc --localstatedir=/var`

and then

`make domserver && sudo make install-domserver`

and see the target 'install-domserver' fail because of missing arguments on an install command:

`make[1]: Entering directory '/home/FIRSTBYTES/administrator/domjudge/webapp'`
`/usr/bin/install -c -d ;`
`/usr/bin/install: missing file operand`
`Try '/usr/bin/install --help' for more information.`
`Makefile:23: recipe for target 'install-domserver' failed`
`make[1]: *** [install-domserver] Error 1`
`make[1]: Leaving directory '/home/FIRSTBYTES/administrator/domjudge/webapp'`
`/home/FIRSTBYTES/administrator/domjudge/Makefile.global:63: recipe for target 'install-domserver' failed`
`make: *** [install-domserver] Error 1`

**Comment by eldering** [comment]
Indeed, this is due to a regression, see: https://github.com/DOMjudge/domjudge/commit/760b450b5fa4b33aea44e0db76263d6d46f29460#commitcomment-24037887
The current workaround is to run 'make composer-dependencies' after running 'make dist' when you clone a fresh repository copy.
