### ISSUE TITLE
Limit the document size for printing

### ISSUE THREAD

**Issue by vmcj** [DOMjudge/domjudge#2806]
### Description of the enhancement request
Currently we allow sourcecode to be printed to be the same size as the uploadsize. This would make it easy for teams to slow down the printer a lot even for mistakes (instead of doing this with malicious intent).

### The goal you want to achieve
Limit either the number of pages which get printed or have a custom size for how large a document can be.

### Any other information that you want to share?
I'm not 100% sure what is the best method here, an alternative is to extend the docs and extend the example there with filtering on only the first 3 pages for example.

**Comment by nickygerritsen** [comment]
We could just use the sourcesize limit setting? That is the biggest amount you can upload in DJ as a submission anyway.

**Comment by eldering** [comment]
I'm not sure we should necessarily use the source size limit. What if people want to use this to print other things than just their submission code? I think that's a fair expectation, especially if no other means of printing is available.

**Comment by nickygerritsen** [comment]
So we close the issue?

**Comment by eldering** [comment]
Unless someone has other arguments. Also, I don't really see the vulnerability. Sure you can accidentally send big documents. But in that vein we should also rate-limit printing requests. I don't think we want to go there.

**Comment by vmcj** [comment]
So we could handle this in a soft way by extending the docs a bit and close it afterwards.

**Comment by vmcj** [comment]
Apparantly we already limit the number of pages in the docs: https://github.com/DOMjudge/domjudge/blob/cb99f6ca11d56012fb182bedb58a8f5aad234950/doc/manual/config-advanced.rst#L318 so I think thats enough of a suggestion to fix it with the printing backend.
