### ISSUE TITLE
[Feature request] Add an option to switch to an inline diff editor.

### ISSUE THREAD

**Issue by cubercsl** [DOMjudge/domjudge#2863]
### Description of the enhancement request

Now that the editor has been changed to monaco, then we can add an option to swich to inline diff editor in submission page: `jury/submissions/<sid>/source`

### The goal you want to achieve

Add a toggle button and/or a global preference (like editor theme) to switch between side by side and inline diff editor.

### Any other information that you want to share?

The inline diff editor can be created by option `renderSideBySide: false`

![image](https://github.com/user-attachments/assets/b719ab03-eef2-40e0-8ee2-c40b3221aaf0)

**Comment by pandadtdyy** [comment]
Should this setting be a system setting or a user preference? Maybe I will implement it in the regional competition with @cubercsl on Saturday first and then come to pr.

**Comment by Kevinjil** [comment]
I would suggest adding a toggle to the UI, and dynamically updating the diff editor using [updateOptions](https://microsoft.github.io/monaco-editor/typedoc/interfaces/editor.IStandaloneDiffEditor.html#updateOptions).

**Comment by nickygerritsen** [comment]
We already do something similar for switching themes, so you can use that as inspiration.
