### ISSUE TITLE
[Documentation] Broken Links on Problem format specification Page

### ISSUE THREAD

**Issue by qwedc001** [DOMjudge/domjudge#2869]
related: #2652 #2653 
I found more.

https://www.domjudge.org/docs/manual/8.3/problem-format.html
https://www.domjudge.org/docs/manual/8.2/index.html

The above link wrote: The base of the format is the [ICPC problem package specification](https://icpc.io/problem-package-format/spec/problem_package_format). with a broken link which is fixed on main document.

Seems that a patch needs to be applied to older documents.

**Comment by qwedc001** [comment]
Also out of curiosity,is the newer version of `2023-07-draft` format stable now?Or we're still going to wait for it?

**Comment by vmcj** [comment]
> Also out of curiosity,is the newer version of `2023-07-draft` format stable now?Or we're still going to wait for it?

When we release we'll consider changing it in the released tarball. But when there is still `-draft` in the version I would assume CLICS hasn't finalized the version yet.
