### ISSUE TITLE
Update import-{REST,XML}feed scripts to new Contest API specification

### ISSUE THREAD

**Issue by eldering** [DOMjudge/domjudge#289]
We should port the `import-{REST,XML}feed` scripts from the `ICPC-live` branch into `master` and update them, and eventually merge into a single script that uses the new (still draft) Contest API specification: https://clics.ecs.baylor.edu/index.php/Draft_CCS_REST_interface

**Comment by meisterT** [comment]
I've a hacky script lying around on my laptop which I've used for the PacNW. I'll clean this up soonish.

**Comment by meisterT** [comment]
See #495

**Comment by nickygerritsen** [comment]
Since #495 is merged and seems to work this can be closed.
