### ISSUE TITLE
Add external_id to team_affiliation

### ISSUE THREAD

**Issue by meisterT** [DOMjudge/domjudge#296]
We currently don't store the external_id/icpc_id in the team_affiliation table while importing the teams2.tsv file.
We also currently create teams based on shortname which is not guaranteed to be unique and also sometimes empty.

**Comment by nickygerritsen** [comment]
External ID will now be stored in team_affiliations. The API also exposes it and the Doctrine entity has a property for it.
I even fixed errors with calling `eventlog` with an `$action` of `"create/update"` by checking if `REPLACE INTO` returns 2 (`delete` + `insert` = `update`) or 1 (`insert`) rows.
See d99acfd...f491564.

I am not sure what to do with the team shortname thing. My example file had all unique team names. Furthermore, it has no other fields that hold a longer team name? We could always keep track of used team names in `tsv_teams_prepare` and if we find a double one append something to it (like the team ID?). Same for empty team names.

**Comment by nickygerritsen** [comment]
I think this can be closed now? Or do we need to do something for the shortnames still?
