### ISSUE TITLE
Quick Installation Failed

### ISSUE THREAD

**Issue by iriszero** [DOMjudge/domjudge#301]
Ubuntu 16. 04
Domjudge 5.3.0

Quick installation failed.

```
$ ./configure
checking whether configure should try to set CFLAGS... yes
checking whether configure should try to set CXXFLAGS... yes
checking whether configure should try to set LDFLAGS... yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether C compiler accepts -Wall... yes
checking whether C compiler accepts -fstack-protector... yes
checking whether C compiler accepts -fPIE... yes
checking whether C compiler accepts -D_FORTIFY_SOURCE=2... yes
checking whether the linker accepts -fPIE... yes
checking whether the linker accepts -pie... yes
checking whether the linker accepts -Wl,-z,relro... yes
checking whether the linker accepts -Wl,-z,now... yes
checking domjudge-user... ubuntu (default: current user)
checking webserver-group... www-data (detected)
checking runuser... domjudge-run (default)
checking rungroup... domjudge-run (default)
checking for cgroup_init in -lcgroup... no
configure: error: Linux cgroup library not found.
```

I think we should do "Set up cgroup support: enable kernel parameters in /etc/default/grub and reboot, then use misc/create_cgroups to create cgroups for DOMjudge." prior to the "./configure"

**Comment by nickygerritsen** [comment]
You need the `libcgroup-dev` package. Easiest is to look at https://www.domjudge.org/docs/admin-manual.html#toc3.2 and peform both `apt-get install`s. But yes, you also need to change grub (but this can happen after install).

**Comment by matt-hermes** [comment]
The issue here is that libcgroup-dev is not included in the list for the
apt install.

On Oct 25, 2017 7:24 AM, "Nicky Gerritsen" <notifications@github.com> wrote:

You need the libcgroup-dev package. Easiest is to look at
https://www.domjudge.org/docs/admin-manual.html#toc3.2 and peform both apt-get
installs. But yes, you also need to change grub (but this can happen after
install).

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/DOMjudge/domjudge/issues/301#issuecomment-339312352>,
or mute the thread

**Comment by nickygerritsen** [comment]
It is for the judgehost but as it is needed for configure we should maybe note that somewhere.

**Comment by eldering** [comment]
I agree with @nickygerritsen and think that the documentation as is, is ok. The link in the quick installation refers to the whole section of prerequisite software, which indeed includes the `apt-get installl` command for judgehosts.

Also note that the beginning there is the explicit remark:

> Note: this is not a replacement for the thorough installation instructions below, but more a cheat-sheet for those who've already installed DOMjudge before and need a few hints. When in doubt, always consult the full installation instruction.

**Comment by matt-hermes** [comment]
Yes, but that comment is easily interpreted as "Section 3.1 is not a
replacement for the thorough installation instructions below (3.2+)"

**Comment by eldering** [comment]
Well, that comment should indeed precisely be interpreted as "Section 3.1 is not a replacement for the thorough installation instructions below, that is sections 3.2 and further". So section 3.2 is part of the full instructions. And if you carefully follow the quick installation guide, then you'll first install the required software including `libcgroup-dev`, then run `./configure` and then configure cgroups and reboot, and finally start a judgedaemon. I think this should all work as advertised.
Now this may be very terse, but I think it is correct (and in the right order). And again, for those who are not comfortable with those terse instructions there is the full installation in the remainder of the chapter. So I think that the current request is either based on miscommunication on what is the issue, or a misunderstanding of the instructions. But feel free to create a pull request with a proposal for how to change the documentation.

**Comment by iriszero** [comment]
The documentation is correct, "as is". Section 3.1 gives convenience to the revisitors but, for beginners, it makes a little bit confused. As @matt-hermes pinpointed, there is no guideline or flowchart visualizing the whole procedure. I'd like to suggest to wrap the important note by box or change its font-size or color so that it would stick out, or replace 'Quick Installation' to "Full Installation" as long as it cannot fully cover by itself. I think it is a fairly good trade-off against beginner's convenience.
Indeed, I couldn't see the notation to follow the full instruction which is in the first line of Section 3.1

**Comment by matt-hermes** [comment]
Even then, in the list of prerequisites, it lists libcgroup-dev as a
requirement for judgehosts, not as a general dependency, even though the
configure script requires it. I will make a change and propose it as a
change request later to see about clarifying that.

**Comment by iriszero** [comment]
@matt-hermes Exactly. That's the problem I faced.

**Comment by matt-hermes** [comment]
I made the proposed change, and it is awaiting review.

https://github.com/DOMjudge/domjudge/pull/304
