### ISSUE TITLE
Fatal error maybe related to PHP7 

### ISSUE THREAD

**Issue by easior** [DOMjudge/domjudge#302]
Domjudge is great. I downloaded domjudge-5.3.0 and built it on Fedora box. However, it can't work. Apache complains that
`[php7:error] [pid 752] [client 127.0.0.1:35876] PHP Fatal error:  Cannot read database credentials file /etc/domjudge/dbpasswords.secret in /var/lib/domjudge/use_db.php on line 11`
What's wrong with it?

**Comment by matt-hermes** [comment]
Your dbpasswords.secret file probably isn't readable by the web server
user/group

**Comment by easior** [comment]
Thanks a lot. I figure it out.
