### ISSUE TITLE
API access control per role

### ISSUE THREAD

**Issue by eldering** [DOMjudge/domjudge#306]
The Contest API requires [access control per role](https://clics.ecs.baylor.edu/index.php/Contest_API#Roles) where certain roles may have no or only time-embargoed access to certain endpoints or attributes. We still need to implement this.

This implies in particular that we have to create events for affected elements at different points in time depending on role.

Related issue: #282

**Comment by meisterT** [comment]
What still needs to be done here specifically?

**Comment by nickygerritsen** [comment]
I think we hand out all events, which means only api readers may read them. For example a real role or public role can not access the feed now
