### ISSUE TITLE
API: implement contest state endpoint

### ISSUE THREAD

**Issue by eldering** [DOMjudge/domjudge#314]
We have to implement https://clics.ecs.baylor.edu/index.php/Contest_API#Contest_state

**Comment by nickygerritsen** [comment]
I have pushed a first version. It still needs a check on the `public` role to not send finalized until the scoreboard is unfrozen. Also finalized might mean something else than I think.

**Comment by matt-hermes** [comment]
Just my two cents: I believe 'finalized' is meant to be after an
administrator has metaphorically signed off on the results.

--Matt H.

**Comment by eldering** [comment]
@matt-hermes is correct: finalizing a contest is described in https://clics.ecs.baylor.edu/index.php/Contest_Control_System_Requirements#Finalizing_the_Contest
It's a procedure that we don't really have in DOMjudge, but exists in the ICPC-live branch specifically for the world finals. In the master branch, where we don't have it, we can simply never send this event.

**Comment by eldering** [comment]
Done.
