### ISSUE TITLE
Add team's penalty time to API

### ISSUE THREAD

**Issue by myungwoo** [DOMjudge/domjudge#317]
Since there is a few custom scoreboard like [Spotboard](https://github.com/spotboard/spotboard), team's penalty time must show on API (e.g. /api/teams).

I'd like to add this feature to the v5.3 lineup. 😄

**Comment by meisterT** [comment]
Perhaps I do understand wrong what you actually want to request, but the total time of a team (which includes penalty time) is given in the scoreboard endpoint of the API: https://github.com/DOMjudge/domjudge/blob/5.3/www/api/index.php#L1266

**Comment by myungwoo** [comment]
Since, [Spotboard](/spotboard/spotboard) only accepts data with two files, [contest.json](/myungwoo/spotboard/tree/046b5856ebb894a65452b5908e545580d30ddd9d/webapp/src/sample/contest.json), and [runs.json](/myungwoo/spotboard/tree/046b5856ebb894a65452b5908e545580d30ddd9d/webapp/src/sample/runs.json) to show below information either.
![image](https://user-images.githubusercontent.com/9026019/33050466-6c124fa4-cea8-11e7-9182-ad3e12351e50.png)
[Spotboard demo link](https://spotboard.github.io/)
So it needs team's default penalty instead of total penalty. Thank you,

**Comment by eldering** [comment]
It there a particular reason you're using the `contest` and `runs` API endpoints and not the `scoreboard`?

I think that one would be better because then you're leaving the scoring calculation to the contest control system, which should be the correct, authoritative source of truth. Also, the team penalty time would automatically be included.

**Comment by meisterT** [comment]
You may want to integrate your scoreboard with https://clics.ecs.baylor.edu/index.php/Contest_API which PC^2, Kattis and DOMjudge implement.

**Comment by eldering** [comment]
Closing for now as the reason to add it is unclear and alternatives exist. Feel free to reopen.
