### ISSUE TITLE
Debian installation command is missing curl, jsoncpp

### ISSUE THREAD

**Issue by TPolzer** [DOMjudge/domjudge#323]
libcurl4-nss-dev libjsoncpp-dev

**Comment by eldering** [comment]
Note that these are specified on a separate line a little below the `apt install` command in
https://www.domjudge.org/docs/admin-manual-3.html#ss3.2. Are you referring to this or a different location?

**Comment by TPolzer** [comment]
Oh, you're right I didn't see those. Might be more obvious if you split Debian/RedHat (because I stopped reading at yum). Feel free to close.

**Comment by eldering** [comment]
Fixed in bc28ccb681739ab0be440f935a4e782feb2bac00, which mistakenly referenced #324.
