### ISSUE TITLE
make install-{domserver,judgehost} fails ootb

### ISSUE THREAD

**Issue by TPolzer** [DOMjudge/domjudge#324]
```
cp -R           -t /opt/domjudge/domserver/lib/vendor vendor/*
cp: cannot stat 'vendor/*': No such file or directory
```

**Comment by eldering** [comment]
Oops, referenced the wrong issue.

**Comment by eldering** [comment]
Which version of DOMjudge are you using? If running from git checkout, did you run the `make dist` as specified in https://www.domjudge.org/docs/admin-manual-10.html#ss10.1 ?

**Comment by TPolzer** [comment]
I'm running from git checkout, yes. I didn't even notice that section of the manual exists I have to admit.
