### ISSUE TITLE
Support generating `results.html` file.

### ISSUE THREAD

**Issue by eldering** [DOMjudge/domjudge#325]
At the World Finals we need to be able to generate a file `results.html` containing the final ranking, including first to solve and regional winner awards.
The exact specifications of this file are not documented, but see https://clics.ecs.baylor.edu/index.php/Contest_Control_System_Requirements#Data_Export and files from previous years.

**Comment by nickygerritsen** [comment]
See c84c98b1a2fc5fd0ff6c26dd66975b902e886e3a for the first attempt at this.

**Comment by thijskh** [comment]
This can now be closed I think? Should open more specific issues if anything is missing.
