### ISSUE TITLE
broken SQL query in www/jury/statistics.php

### ISSUE THREAD

**Issue by bredereck** [DOMjudge/domjudge#326]
A "COUNT" seems to be missing in line 41

The following patch seems to fix it.
[statisticsfix.patch.txt](https://github.com/DOMjudge/domjudge/files/1668002/statisticsfix.patch.txt)

PS: We are using DOMjudge/5.3.2.

**Comment by thijskh** [comment]
I don't think it's missing, that select field is supposed to be a boolean value. Do you get any specific error or see a problem that this change solves?
