### ISSUE TITLE
I keep getting Compiler Error

### ISSUE THREAD

**Issue by mkutays** [DOMjudge/domjudge#329]
I was trying to setup a domjudge on Digital Ocean Ubuntu Machine. I followed the guide till end. System is running smoothly except that when I try to submit an answer I keep getting this error. 
Would you please help, I can't fix it for 2 days.
Compiling failed with exitcode 255, compiler output:
/home/magnus/domjudge/judgehost/bin/runguard: creating cgroup: Failed to remove a non-empty group(50029)
Try `/home/magnus/domjudge/judgehost/bin/runguard --help' for more information.
Error: failed to set /sys/fs/cgroup/memory/domjudge/dj_cgroup_3376_1517615852/memory.memsw.limit_in_bytes: Cgroup, requested group parameter does not exist

**Comment by meisterT** [comment]
I guess you followed the steps here: 
https://www.domjudge.org/docs/admin-manual-3.html#ss3.7
to change the kernel command line. Can you please verify that it is changed by executing
cat /proc/cmdline
?

Make sure that the output contains swapaccount=1 cgroup_enable=memory.

If it's missing, check if /etc/default/grub.d/ contains a file that overwrites the configuration that you've added to /etc/default/grub.

**Comment by mkutays** [comment]
Here is my cmdline. 
root=UUID=a9b6d43b-dd20-4077-a5c4-d462d8d0d073 ro console=tty1 console=ttyS0 cra                                                                                                                                                             shkernel=384M-2G:128M,2G-:256M

I tried to change it but something keep overwriting it different.
this how I change the grub line.
GRUB_CMDLINE_LINUX_DEFAULT="quiet cgroup_enable=memory swapaccount=1"

**Comment by meisterT** [comment]
Did you check if you've a file in /etc/default/grub.d/ that overwrites the GRUB_CMDLINE_LINUX_DEFAULT value?

**Comment by mkutays** [comment]
I changed the files that in the grub.d but cat /proc/cmdline output is still the same. I made update-grub. Should I reboot the server ?

**Comment by meisterT** [comment]
Yes, change file, update-grub and reboot server to see any effect.

**Comment by mkutays** [comment]
That work thank you so much. You are a life saver.

**Comment by meisterT** [comment]
You're welcome. I've tried to improve documentation a little bit in 03fb2f9.
