### ISSUE TITLE
Rejudging Run Selection

### ISSUE THREAD

**Issue by eldering** [DOMjudge/domjudge#33]
The CCS must provide the ability to specify a filter defining the set of runs to be rejudged. The CCS must support any combination of filters of the following types: 
- [x] A specific (single) run.
- [x] All runs which have been submitted for a specific problem.
- [x] All runs which have been submitted using a specific language.- 
- [x] All runs which have been submitted by a specific team or set of teams. 
- [ ] All runs which were submitted between some contest time T0 and some subsequent contest time T1. 
- [x] All runs which have been assigned any specific one of the allowable run judgments as defined in Judge Responses,
- [x] or all runs that received any judgment other than "Accepted" (that is, all rejected runs).
- [x] All runs which have been judged on a specific computer (identified in some reasonable way, e.g., IP address or hostname). This requirement is only applicable if the CCS uses multiple machines to judge runs.

**Comment by thijskh** [comment]
One way to approach this is to make a "create rejudging" page that allows to specify for each of these dimensions what you want (e.g. multi select list of langs, judgehosts, teams), a judging type, specifiy time interval. Relatively simple feature I say.
