### ISSUE TITLE
Internal server error on bin/judgedeamon

### ISSUE THREAD

**Issue by GuillaumeMilan** [DOMjudge/domjudge#341]
I just installed the github `mater` version of domjudge but I got the following after lauching the `bin/judgedeamon`:

```
[Feb 27 14:36:00.079] judgedaemon[25270]: Judge started on guillaume-MacPro [DOMjudge/6.0.0DEV]
[Feb 27 14:36:00.083] judgedaemon[25270]: Registering judgehost on endpoint http://localhost/domjudge/api/v4
[Feb 27 14:36:00.332] judgedaemon[25270]: error: Error while executing curl POST to url http://localhost/domjudge/api/v4/judgehosts: http status code: 500, response: {"error":{"code":500,"message":"Internal Server Error"}}
```

I don't know if there is a link but when i tried to set up the `apache2` server, i had the following error:

```
 ➜  domjudge git:(master) a2enconf domjudge
ERROR: Conf domjudge does not exist!
```
But when I restarted the apache2 server it had taken in count the conf file. (I saw that when I dis activated the rewrite mod)

**Comment by thijskh** [comment]
I recommend you look into the error logs of the apache webserver, where it likely has logged why it returned a 500 internal server error.

**Comment by GuillaumeMilan** [comment]
In fact. I don't know how nginx server had replaced my apache server ...
Thanks and sorry
