### ISSUE TITLE
Register a user without admin credential

### ISSUE THREAD

**Issue by GuillaumeMilan** [DOMjudge/domjudge#343]
Is it possible to create an user account without login as admin to the domjudge server? 

I got a way to verify the identity of my user and i wan't to create a domjudge account with the information i received. Is there a way to do this?

Thanks

**Comment by meisterT** [comment]
See https://github.com/DOMjudge/domjudge/commit/09de1642dd6b20159e192af13d926802b8a75438 for the (removed) implementation of self registering teams.

@ubergeek42 why did you remove this? Is this or will this be replaced by new symfony code?

**Comment by ubergeek42** [comment]
@meisterT it looks like I added it back in the symfony style of things here: https://github.com/DOMjudge/domjudge/commit/3f6965b2241951de8b57f8a672eb865e3ee7dc53
