### ISSUE TITLE
DOMjudge make install domserver not create sym link 

### ISSUE THREAD

**Issue by GuillaumeMilan** [DOMjudge/domjudge#344]
I just reinstalled my domjudge server and previously I could works on php files in the directory `webapp/web` but now a new directory appeared `domserver` in which all files are copied on make command. And they are not simlink. 
Do you know why? Can I reset my DOMjudge server as a developpement one. 

Thanks

PS: On my side `ln -s etc/apache.conf /etc/apache2/conf-available/domjudge.conf` need to be transformed to `cp etc/apache.conf /etc/apache2/conf-available/domjudge.conf`.

**Comment by GuillaumeMilan** [comment]
I don't know if there is any link but now when I login to the admin jury then `/domjudge/jury` throw an internal error 500.

**Comment by meisterT** [comment]
It seems that you switched from maintainer-conf and install to normal installation?

Are you using domjudge master branch? Look in webapp/var/logs/ for a log file that explains the 500.

**Comment by GuillaumeMilan** [comment]
Hello sorry for the late reply I was unable to code this weekend.
Indeed the install switched form maintainer-conf to normal install. But that doesn't annoy me if was in testing phase. 
But the log says that the database is not correctly initialized: 

`line: 8, Error#1146: Table 'domjudge.rejudging' doesn't exist, query: 'SELECT rejudgingid           FROM rejudging          WHERE endtime IS NULL'"`

Do you know how i can reset the mysql database from scratch to reinstall it correctly?

**Comment by eldering** [comment]
First, when you have questions or problems with setting up DOMjudge, please use the emaillist domjudge-devel for that, or IRC. Issues are reserved for actual bugs or feature requests.

To completely reset the database, you can run:
```
dj_setup_database uninstall
dj_setup_database install
```

**Comment by GuillaumeMilan** [comment]
Indeed I think I ran the configure script after making the `make maintainer-conf  && make maintainer-install`
