### ISSUE TITLE
Teams don't have a logout button

### ISSUE THREAD

**Issue by meisterT** [DOMjudge/domjudge#349]
### Your environment
The new web UI.

### Steps to reproduce
Login as a team :-)

### Expected behaviour
Logout button somewhere in the top menu bar.

### Actual behaviour
No way to log out as a team unless you know the magic URL.

**Comment by thijskh** [comment]
Suggestions welcome on a good place to put a logout link/button!

**Comment by eldering** [comment]
I'd say top-right is conventional, so in between the submit button and the clock, thus moving the submit button to the left.

**Comment by GuillaumeMilan** [comment]
public member that only have access to the public domain (only the score board), do not have logout button too. 
I don't know if this kind of user are used in real contest. But for development purpose it is great to have one. 
Personally i added the following code to the `www/public/menu.php`
```
<?php
logged_in();
if ( !logged_in() ): ?>
      <div id="loginbut"><a class="nav-link justify-content-center" href="login.php"><button type="button" class="btn btn-info btn-sm"><span class="octicon octicon-sign-in"></span> Login</button></a></div>
      <div id="loginbut"><a class="nav-link justify-content-center" href="../sap-login.php"><button type="button" class="btn btn-info btn-sm"><span class="octicon octicon-sign-in"></span> SAP Login</button></a></div>
<?php else :?>
      <div id="logoutbut"><a class="nav-link justify-content-center" href="../logout"><button type="button" class="btn btn-info btn-sm"><span class="octicon octicon-sign-in"></span>Logout</button></a></div>
<?php endif; ?>
```
