### ISSUE TITLE
Multiple problems with the same shortname in different contests breaks queries

### ISSUE THREAD

**Issue by nickygerritsen** [DOMjudge/domjudge#356]
We query the `problem` table for the `shortname` and expect one result, while the `shortname` field is not unique, which breaks code.

We should either fix the queries by joining on `contestproblem` and filtering on `cid` or not allow duplicate `shortname`s

**Comment by thijskh** [comment]
First solution is the right one.

**Comment by thijskh** [comment]
Searched for it but cannot find an occurrence, do you know where this happens?

**Comment by nickygerritsen** [comment]
I have no clue anymore of course :(. I tried looking for it as well but can't find it.
Of course this issue was created during WF so I have probably created in a hurry because it appeared somewhere...

Might be that it only happened somewhere in the icpc-live branch.

**Comment by nickygerritsen** [comment]
I re-checked the code again and I can't find it. I'm going to close this issue, as it doesn't seem to happen anymore. `shortname` is not even in the `problem` table...
