### ISSUE TITLE
Config check doesn't work with judgehost restrictions

### ISSUE THREAD

**Issue by nickygerritsen** [DOMjudge/domjudge#357]
If you have judgehost restrictions, the config webpage reports errors it shouldn't.

**Comment by thijskh** [comment]
What kind or errors/how to reproduce this?

**Comment by thijskh** [comment]
@nickygerritsen

**Comment by nickygerritsen** [comment]
I tried reproducing this a few weeks ago and couldn’t. So I have no clue and will close this for now
