### ISSUE TITLE
Submit client should set team login activity

### ISSUE THREAD

**Issue by eldering** [DOMjudge/domjudge#359]
When using the command line submit client, the team `teampage_first_visited` field in the database is not updated. We should probably generalize that name and make the submit client also update it.

**Comment by thijskh** [comment]
You cannot know the result from your submission, so a team that does not have a value for teampage_first_visited would need to be flagged regardless. What would changing this for the submit client solve?

**Comment by nickygerritsen** [comment]
During the WF we had a graph showing how many teams used DOMjudge. It never reached 100% because some of them always used the submit client.

**Comment by thijskh** [comment]
And how did they know their results?

**Comment by nickygerritsen** [comment]
By going to the public scoreboard I guess. Or by receiving a balloon if reltime < 4h.

**Comment by meisterT** [comment]
Do you want to do that for every API call or only for submissions?
Perhaps it would make more sense to move the field to the user table instead?

**Comment by nickygerritsen** [comment]
We now do this using an event. `teampage_first_visited` is now a totally wrong name, so that should be fixed later. But at least we have this working now for the world finals 😄
