### ISSUE TITLE
Disable refresh when you start entering in a form.

### ISSUE THREAD

**Issue by meisterT** [DOMjudge/domjudge#361]
This is not yet implemented on all pages, e.g. on a problem page when you are about to start a rejudging.

**Comment by nickygerritsen** [comment]
We were discussing using AJAX to only the part(s) of the page that actually need updating. It might be the case that when we do this, we do not have to disable refresh anymore when entering data into a form, because the form is outside of the parts that need updating.

**Comment by nickygerritsen** [comment]
Is this still relevant? I think most pages now refresh using AJAX.
