### ISSUE TITLE
Importing a problem complains that contest is not active but it is.

### ISSUE THREAD

**Issue by meisterT** [DOMjudge/domjudge#365]
Set up multiple contests and load a problem. During import it complains that the contest is not active but is still doing everything correctly.

**Comment by eldering** [comment]
I cannot reproduce this. I have two contests, both are active and I've tried loading a problem into either contest, which works fine.

**Comment by meisterT** [comment]
Since I never saw this again, I'll close the issue. Probably I was misremembering..
