### ISSUE TITLE
Pin scoreboard header and footer

### ISSUE THREAD

**Issue by eldering** [DOMjudge/domjudge#366]
In various cases you might want to view the header and/or footer of the scoreboard while scrolling through a long scoreboard, as suggested by the ICPC WF 2018 jury. We could look into (optionally) pinning the header and/or footer of the scoreboard table, allowing to scroll through the main rows.

**Comment by mvr320** [comment]
I'm currently trying to get a fix for this, atleast half of the problem is fixable

**Comment by thijskh** [comment]
Should somehow take sortorders into account...

**Comment by nickygerritsen** [comment]
The header is fixed in #782 (pun intended). We discussed that pinning the footer is less useful so will close this issue for now. If anyone has a real use case for pinning the footer please let us know.
