### ISSUE TITLE
Add more data to judgehosts page

### ISSUE THREAD

**Issue by eldering** [DOMjudge/domjudge#368]
We should add more data to the judgehosts overview page:
- which judging is currently judged by each judgehost
- summary line with load averages

**Comment by thijskh** [comment]
Summary line: should only average over _active_ judgehosts I think. Or even: only on active+green?

Which judging: this could be defined as judging where judgehost = hostname and endtime is null and valid = 1; maybe take most recent one when multiple? What is the usecase for having this in the overview?

**Comment by thijskh** [comment]
Just active, don't have to be green

**Comment by eldering** [comment]
> Summary line: should only average over _active_ judgehosts I think. Or even: only on active+green?

Probably over active+green. The point is to see the pressure on judgehosts and whether e.g. more are needed.

> Which judging: this could be defined as judging where judgehost = hostname and endtime is null and valid = 1; maybe take most recent one when multiple? Alternative: display the submission instead. What is the usecase for having this in the overview?

The use-case is: a judgehost is taking a long time and might already show orange. Then it would be nice to quickly see what it is (supposed to be) working on, without having to ssh into it.

**Comment by meisterT** [comment]
The first half is done, the second half is #1164
