### ISSUE TITLE
Port entry_point handling to master

### ISSUE THREAD

**Issue by meisterT** [DOMjudge/domjudge#373]
To get 6.0 out of the door, we should first port the current entry point handling from ICPC live to master (which was tested at NWERC and the finals).
See
https://github.com/DOMjudge/domjudge/commit/f73b05e8592220e2327ca669cf380a4e5db837ab and https://github.com/DOMjudge/domjudge/commit/1241f8ac1e50006a09c54e2a312aa49c06733616 for example.

**Comment by thijskh** [comment]
This should be rather complete now. Requires another round of integral testing to verify we now have all the ingredients in place.

**Comment by thijskh** [comment]
Should be done now.
