### ISSUE TITLE
Decide how to proceed with current special casing in ICPC-live

### ISSUE THREAD

**Issue by meisterT** [DOMjudge/domjudge#379]
Examples for special cases: https://github.com/DOMjudge/domjudge/commit/d9a5d909d421ec6850bda411b1ed75ec207f1f13 and https://github.com/DOMjudge/domjudge/commit/fcf4df06261da5092895b5a94efdc75a20f3366e and https://github.com/DOMjudge/domjudge/commit/7358f7e48253620751ccba0ca4a39f241d42ac7a

Can we solve this with the mapping in lib/lib.misc.php?

**Comment by thijskh** [comment]
I've decided to merge all three:

1. Is not harmful to merge, can improve on it later if we have a better solution.
1. Just merged (adjusted to master codebase).
1. Merged using definedness of `ICAT_URL` as feature toggle.

You say "examples", is there more to this issue?

**Comment by meisterT** [comment]
I just wasn't sure if my list is complete.

**Comment by thijskh** [comment]
Closing then since it now lacks concrete actions to take.
