### ISSUE TITLE
Process more than one event at a time

### ISSUE THREAD

**Issue by meisterT** [DOMjudge/domjudge#382]
This was necessary to apply a rejudge for a problem with many submissions, see https://github.com/DOMjudge/domjudge/commit/4caded8ec9917d51dcee354d6230c8714cb77354

**Comment by nickygerritsen** [comment]
We should think about how to do this in a nice way perhaps. This solution was quite hacky IMHO

**Comment by meisterT** [comment]
I know, that's why I didn't just cherry-pick it but assigned it to you :-P
