### ISSUE TITLE
Port flags/country handling to master

### ISSUE THREAD

**Issue by meisterT** [DOMjudge/domjudge#384]
We revived the functionality to display flags in https://github.com/DOMjudge/domjudge/commit/47cc318705ba6b50fb048219c45e023513c98059 and others.

**Comment by thijskh** [comment]
Master supports flags, not sure what this is about?

**Comment by nickygerritsen** [comment]
I think this is about the option to *disable* flags, as this was required during this WF

**Comment by eldering** [comment]
Agreed that this is already in master. This was added in both by @thijskh in cf67d394350d5e7dad6ec63877d10805a71bf621 and 2ea000cd3bc223e2e47a594640bc329948a47b0b, and 07e0adfa139ce9f0cf3955013425baff3404c973 cherry-picked from ICPC-live to fix the API.
We might still want to cherry-pick 36710c2f45f79d62321667627afdd6de4467c4ac and 53663fe4328fe6accaf0244c73df537619b7a654 from ICPC-live, but I'm not sure.

**Comment by thijskh** [comment]
Makes sense to me so :cherries::pick:'d those.
