### ISSUE TITLE
Network Access inside Chroot environment

### ISSUE THREAD

**Issue by sarthakgarg27** [DOMjudge/domjudge#388]
NOTE: If this is a _discussion starter_ or you need any _installation help_,
rather send an email to our 
[DOMjudge-devel mailinglist](https://www.domjudge.org/mailman/listinfo/domjudge-devel)
instead of filing an issue here.

### Description of the problem / feature request
> We want to provide Network access inside the chroot environment.

### Your environment
> Include details about your installation here. 
> - DOMjudge version - 5.2.1
> - Operating system -centos 6.5
> - Webserver - Apache

### Steps to reproduce
> Replace this with a description how we can reproduce your bug.
> - Step 1 Run the following code 
 import java.net.*;
import java.io.*;

public class Solution {
   public static void main(String[] args) throws Exception {

       URL str = new URL("http://www.google.com/");
       BufferedReader in = new BufferedReader(
       new InputStreamReader(str.openStream()));

       String inputLine;
       while ((inputLine = in.readLine()) != null)
           System.out.println(inputLine);
       in.close();
   }

> - Step 2 - Domjudge will throw an exception:java.net.UnknownHostException: www.google.com.

### Expected behaviour
>  I want the program to have network access inside chroot environment.

### Actual behaviour
> Domjudge throws an exception:java.net.UnknownHostException: www.google.com.

**Comment by thijskh** [comment]
Please read the first paragraph of your own report. This is not a support forum. Please use the mailing list for support questions.
