### ISSUE TITLE
Merge compile scripts into master

### ISSUE THREAD

**Issue by meisterT** [DOMjudge/domjudge#395]
We have several changes in ICPC-live, some of which we want to port and others we probably don't (or create a separate script).

- Filtering out submissions with incorrect filenames
- Entry point handling
- UTF8 handling

**Comment by eldering** [comment]
I'm happy merge UTF8 handling to master. I'm not sure about entry point handling, or at least we should still offer the old, fully auto-detected method. Filtering filenames I'd prefer not to merge too.
Anyways, there's also the defining of ONLINE_JUDGE and DOMJUDGE, so we have to keep separate versions of the compile scripts anyways.

**Comment by thijskh** [comment]
What is the idea behind those defines?

**Comment by eldering** [comment]
Allowing contestants to have debugging code run on their own machine, but not on DOMjudge. ONLINE_JUDGE is a very common define across online judges.

**Comment by meisterT** [comment]
To be honest, I would remove the defines. If you run domjudge in an online judge setting and want to have them, they're easy to add.

I always remove them when hosting a contest to ensure consistency with the provided shell aliases.

If a team wants to have a difference between local and remote compilation they can always use their own defines, e.g. LOCAL_EXEC.
