### ISSUE TITLE
Remove role restriction from event feed reading

### ISSUE THREAD

**Issue by meisterT** [DOMjudge/domjudge#405]
In theory, we should everyone allow to read the event feed. However, before we can allow that we have to solve two issues:

a) make sure that we don't leak information that's not available through other channels to the teams or the public (e.g. number of test cases per problem), and
b) make sure that we cannot be DOSed easily by opening a handful of event-feed connections (which do not have a timeout).

For now, I'll restrict it to the jury again.

**Comment by nickygerritsen** [comment]
In our current implementation of the new scoreboard we give out the event ID of the latest event, regardless of whether you have access to it. This should also be fixed.

**Comment by vmcj** [comment]
Should we actually do this, in which cases would this be useful as I think the code will be harder to maintain even besides the issues @meisterT mentioned IMO.

**Comment by meisterT** [comment]
We decided that if you actually want more people to read the event feed (with different permission/access levels), you should put a CDS in front of it, see https://tools.icpc.global/.
