### ISSUE TITLE
Show (max) runtime in submissions table

### ISSUE THREAD

**Issue by nickygerritsen** [DOMjudge/domjudge#408]
Ragnar from the BAPC jury requested that it would be nice if runtimes are shown in the submission overview page. He wants to use this to determine the max runtime per problem do determine time limits.

Showing it somewhere else (problem page?) is also possible of course.

**Comment by TimonKnigge** [comment]
Seconding this, when moving from your local machine to domjudge for final finetuning this would be really helpful.
