### ISSUE TITLE
Switching contest in the jury in Safari doesn't (always) work

### ISSUE THREAD

**Issue by nickygerritsen** [DOMjudge/domjudge#409]
If you have more than one contest, switching them in the jury interface using Safari does nothing (sometimes).

**Comment by thijskh** [comment]
Probably something about the form-auto-submit javascript?

**Comment by nickygerritsen** [comment]
Yeah not sure yet, but I am by now annoyed with it, so I'll look into it tomorrow :). This was basically a reminder for myself.
