### ISSUE TITLE
Do not hardcode sortorder 0 for scoreboard stats

### ISSUE THREAD

**Issue by nickygerritsen** [DOMjudge/domjudge#416]
Here:
https://github.com/DOMjudge/domjudge/blob/7231671bc92965a6ab1f3732cbe356bb1869fc22/lib/www/scoreboard.php#L613
we hardcode a `0`, which uses the `best_time_sort` of the team category with sortorder `0`, but that might not exist. We might want to think of a better way to calculate this, like taking the minimum of all categories or maybe taking the minimum of all non-hidden categories.

Thanks @verwoerd and @Erackron for finding this.

**Comment by thijskh** [comment]
Taking the minimum keeps the problem that the row at the very bottom does not summarize everything above it but only a specific part.

Would it not be better to make the summary per-sortorder? Afterall, why wouldn't you want a summary line e.g. of the fastest company teams?

Alternative: make the summary line be the summary of all non-hidden categories. So on the public/team scoreboard the bottom row shows the fastest solve time of everyone who is on that scoreboard.

**Comment by nickygerritsen** [comment]
I think a summary per sortorder makes sense

**Comment by eldering** [comment]
I agree. Basically, the sortorder is a simple way of splitting the scoreboard into multiple separate ones.

**Comment by nickygerritsen** [comment]
This is now fixed, although the scoreboard layout might need a tweak for this
