### ISSUE TITLE
Consider adding sortorder to contestproblem

### ISSUE THREAD

**Issue by nickygerritsen** [DOMjudge/domjudge#417]
Yesterday during the CLICS call we had a discussion about the `ordinal` field in the `problems` endpoint. See the [Contest API spec](https://clics.ecs.baylor.edu/index.php?title=Contest_API#Problems) for info on this field. It should contain information about the ordering of problems inside a contest.

Currently we calculate this field by sorting the contestproblems on shortname and then looking at the index. This has two disadvantages:
* There is no way to have a sorting that does not look at the shortnames
* When requesting only one problem in the API, we always need to load all problems to determine this index

Wouldn't it be better if we just add a `sortorder` field to the `contestproblem` table, which we then use to order the problems. This would solve both problems and I think implementing this shouldn't be too hard. We could do some fancy drag-and-drop on the contest-edit page (or just add "up" and "down" buttons after the problem rows) + change importing of problems to fill this field. It also doesn't add a lot of complication anywhere I think.

If we want to do this, I think now would be a good time, because I can then take this into account before rewriting the `problems` endpoint to the new API thingy.

Any thoughts?

**Comment by thijskh** [comment]
My thought is that this is corner case functionality.

Yes, a contest might have existed somewhere that had problems ordered A B C AA BB. But how common is this? I don’t think we need to conplicate things to support something that someone has at one time done once.

The ordering of problems on the scoreboard is just a cosmetic thing, not something that is relevant to scoring or outcomes.

So even if one system displays it as A B C AA BB and the other as A AA B BB C, there’s still no real problem as there will still be the same winners with the same scores.

Let’s just declare this as unsupported.

**Comment by nickygerritsen** [comment]
I am fine with either way. If others agree with Thijs, then I'll do some custom magic in the API to get the sortorder exposed :)

**Comment by eldering** [comment]
I don't have a strong opinion either way. Only, that if we implement it, I'd prefer to call it `rank` instead of `sortorder` like with the test cases.
