### ISSUE TITLE
Ballon process broken in newest version

### ISSUE THREAD

**Issue by baziorek** [DOMjudge/domjudge#418]
NOTE: If this is a _discussion starter_, you need any _installation help_ or have a _question_ on how to accomplish something,
rather send an email to our 
[DOMjudge-devel mailinglist](https://www.domjudge.org/mailman/listinfo/domjudge-devel)
instead of filing an issue here.

### Description of the problem / feature request
> Replace this line with a short description.
Ballon process is crashing because of changes in database: "shortname" oraz "id" is missing in array in version 6.0.1

### Your environment
> Include details about your installation here. 
> - DOMjudge version (e.g. 5.3.1 or a github commit hash)
> - Operating system / Linux distribution and version (e.g. Ubuntu 16.04)
> - Webserver (e.g. Apache)
Domjudge 6.0.1
Ubuntu 18.04
Apache

### Steps to reproduce
> Replace this with a description how we can reproduce your bug.
> - Step 1
> - Step 2
> - Step 3
just run ballon process

### Expected behaviour
> Replace this line with what you would expect to happen.

### Actual behaviour
> Replace this line with what happens instead.

### Any other information that you want to share?
> Please include webserver, symfony and judgedaemon log snippets here as appropriate.
> Screenshots may help in case of UI bugs.

**Comment by thijskh** [comment]
Fixed, thanks a lot for reporting! This is likely broken since 5.0.0.
