### ISSUE TITLE
Add functionality to edit testcase's description

### ISSUE THREAD

**Issue by baziorek** [DOMjudge/domjudge#419]
### Description of the problem / feature request
It is easy to make a mistake, so it should be possibility to correct the mistake without directly changing database.

### Your environment
6.0.1
Ubuntu 18.04
Apache

**Comment by meisterT** [comment]
We had the functionality back in time, that you could double click the description and then edit it. But that doesn't work anymore. I don't know if it was removed or just doesn't work anymore.
