### ISSUE TITLE
Runguard: improve or remove cpu index check

### ISSUE THREAD

**Issue by nickygerritsen** [DOMjudge/domjudge#420]
In https://github.com/DOMjudge/domjudge/blob/master/judge/runguard.c#L1063 we check if the passed cpuset argument is less than the number of CPU's, if we pass only one integer.

However in the case where a CPU has hyperthreading and we disable some of the cores to disable this HT, it might be the case that the CPU core ID's are not numbered from `0..n-1`, but contain 'gaps'.

We should either detect which CPU cores are active or just remove the whole check completely. Removing it doesn't really hurt IMHO, as actually setting the cpuset cgroup will error out if you use a core ID that doesn't exist (with a 'permission denied' error).

**Comment by eldering** [comment]
Agreed, I already ran into the same issue. I think we can safely remove the check.
