### ISSUE TITLE
DOMserver reads a gigabyte of data per minute

### ISSUE THREAD

**Issue by SolalPirelli** [DOMjudge/domjudge#421]
### Description of the problem / feature request

In a contest, my DOMserver is reading about a gigabyte of data per minute: https://ibb.co/go5Cm9

### Your environment

DOMjudge on Docker version 5.3.2, running on Azure

### Steps to reproduce

I'm not sure. There are a few problems whose archives weight hundreds of megabytes, and whose outputs are expected to be in the megabytes as well. Maybe that's an issue? There are about 60 active users.

### Expected behaviour

I shouldn't have to restart PHP very often because it gets stuck.

If my setup with very large problems is unusual, that's fine, but I didn't see warnings about it.

### Actual behaviour

I have to restart PHP all the time. :(

**Comment by SolalPirelli** [comment]
Looks like the judgehosts are fine indeed, nothing specific in logs. Server is also writing quite a bunch of data though: https://ibb.co/gqh39U

**Comment by eldering** [comment]
For debugging this issue it might be easier to join our IRC channel #domjudge on FreeNode.
Does the large amount of reads/writes still happen when you disable judging (under the problem toggle "allow judge")?

**Comment by SolalPirelli** [comment]
Writing down the summary of the IRC discussion here for posterity - it seems that having a 900MB problem with testcases that expect a few dozen 10MB outputs is not a great idea on an Azure B1ms.
