### ISSUE TITLE
Submissions are not judged in order after server crashes

### ISSUE THREAD

**Issue by SolalPirelli** [DOMjudge/domjudge#422]
### Description of the problem / feature request

I have to restart PHP on the server all the time because of the memory issue I just opened.
As a consequence, submissions are not judged in order; 20-minute-old submissions are still pending but recent ones get judged...

### Your environment

DOMjudge 5.3.2 on Docker on Azure

### Steps to reproduce

- Restart PHP while submissions are pending

### Expected behaviour

Old submissions should always be judged first

### Actual behaviour

New submissions are judged first

**Comment by eldering** [comment]
Closing this. Please reopen if you think the behaviour is actually wrong (given the expected prioritization we perform).

**Comment by SolalPirelli** [comment]
This seems wrong: https://ibb.co/cgNjip

**Comment by SolalPirelli** [comment]
There are indeed rejudgings, could this be the cause?

**Comment by eldering** [comment]
Yes, since for single rejudgings we have a separate policy to reset the "last judgement" time of a team, to make sure that that rejudging is done as quickly as possible. Does that explain it?
