### ISSUE TITLE
Come up with a way to put eventlog calls back inside SQL transactions

### ISSUE THREAD

**Issue by nickygerritsen** [DOMjudge/domjudge#424]
Because the `eventlog` function now uses API endpoints in Symfony, and thus Doctrine, and the callers of the `eventlog` function are outside of Symfony code, and thus do not use Doctrine, I had to move these calls outside of any SQL transactions that were active. This is not ideal and should be fixed.

Currently the `lib.database.php` file uses our own SQL wrappers, but we could rewrite it to use the connection of the Doctrine EntityManager. In that way, it should re-use the transactions. However, that would mean that CLI scripts (like the eventdaemon) can not use `lib.database.php` anymore (some these CLI scripts already can not use the transaction-stuff probably as they perform HTTP calls). We could do two things:

* Have the logic in `lib.database.php` only use Doctrine when available. This will make the code less nice I guess
* Rewrite CLI scripts to be Symfony Commands, so we have access to Doctrine anyway

Maybe there are other options. We should investigate.

**Comment by nickygerritsen** [comment]
The first one is fixed, as I moved the first API endpoint that used it to Symfony. After moving all of the API to Symfony we should be almost done, except for `rejudging_finish()`. However, that function only uses functions that the APII endpoints also use, so moving that method to Symfony should then be easy as well.

**Comment by nickygerritsen** [comment]
Most of them are done now, except for the one in `rejudging_finish`

**Comment by nickygerritsen** [comment]
The `rejudging_finish` one is now also done. The only places we still have them are in some CLI tools

**Comment by meisterT** [comment]
#425 tracks the remaining bits and pieces
