### ISSUE TITLE
Move misc-tools to use API or Symfony

### ISSUE THREAD

**Issue by thijskh** [DOMjudge/domjudge#425]
Several of the tools under `misc-tools/` set up a direct database connection to perform queries. It's probably better if these tools use the API instead. This avoids code duplication and breakage due to database changes.

Maybe it's not (yet) possible in every case to perform the desired actions via the API. Perhaps that should then be made possible.

Probably it's a good idea to have some kind of shared code that handles the API setup and calling?

- [x] `create_accounts.in`
- [x] `judging_statistics.in`
- [x] `save_sources2file.in`
- [x] `balloons.in`
- [x] `multi_rejudge.in`
- [x] `simulate_contest.in`
- [x] `eventdaemon.in`
- [x] `combined_scoreboard.in`
- [x] `restore_sources2db.in`

**Comment by nickygerritsen** [comment]
This would also help with #424

**Comment by thijskh** [comment]
Move to API or Symfony code, but in any case should no longer depend on legacy code base

**Comment by meisterT** [comment]
For things like `create_accounts` I propose to just add better documentation how to use the existing API endpoint (https://github.com/DOMjudge/domjudge/blob/master/webapp/src/Controller/API/UserController.php#L208).

WDYT?
