### ISSUE TITLE
Judgedaemon crash due to eventlog internal issue

### ISSUE THREAD

**Issue by ubergeek42** [DOMjudge/domjudge#427]
### Description of the problem / feature request
Judgedaemon unable to judge too late submission due to eventlog issue

### Your environment
DOMJudge master, but quite a few commits ago...not sure how far back. I built it on 2018-10-14 23:51  from master, so I guess somewhere around here c3688084d99a12fd1cf646c35005082d7b97f8ab is the last commit I have.

### Steps to reproduce
Submit a solution too-late, judgehost will crash, seemingly due to eventlog internal function on the webserver returning 404 not found for the contest judgements endpoint(I'm guessing because the contest is over)

### Expected behaviour
The judgedaemon to not crash

### Actual behaviour
```
[Oct 17 22:59:20.693] judgedaemon[2685]: No submissions in queue (for endpoint default), waiting...
[Oct 17 23:01:24.398] judgedaemon[2685]: error: Error decoding JSON data 'executing internal GET request to url http://localhost/api/contests/1/judgements: http status code: 404, response: HTTP/1.0 404 Not Found^M
Access-Control-Allow-Origin: *^M
Cache-Control:               no-cache, private^M
Content-Type:                application/json^M
Date:                        Wed, 17 Oct 2018 23:01:24 GMT^M
^M
{&quot;error&quot;:{&quot;code&quot;:404,&quot;message&quot;:&quot;Not Found&quot;}}

eventlog: got no JSON data from '/contests/1/judgements'
{"submitid":33,"cid":1,"teamid":2,"probid":1,"langid":"py3","rejudgingid":null,"entry_point":"panoptes.py","origsubmitid":null,"maxruntime":3.0,"memlimit":524288,"outputlimit":4096,"run":"run","compare":"compare","compare_args":null,"compile_script":"py3","compare_md5sum":"89097552fc8d1957549a10640ee63346","run_md5sum":"21e4361c2f8fff4fc4ead6cf4e5719a6","compile_script_md5sum":"66337880dc2cbd0eb306a7af45f28436","judgingid":34}
': Syntax error
[Oct 17 23:01:29.682] judgedaemon[18438]: Judge started on ip-172-31-6-88-0 [DOMjudge/6.1.0DEV]
```

**Comment by nickygerritsen** [comment]
I think I fixed this already, as I encountered the same issue. I did not expose too late submissions when requested with the ids[]= param.
That is fixed for sure and it seems this is the same case

**Comment by thijskh** [comment]
@ubergeek42 Can you confirm that this is indeed now fixed?

**Comment by ubergeek42** [comment]
Yes, sorry for the delay. I can confirm this is fixed.
