### ISSUE TITLE
500 error on submission page after removing problem from contest

### ISSUE THREAD

**Issue by eldering** [DOMjudge/domjudge#428]
### Your environment
Reproduced on DOMjudge 6.0DEV at UKIEPC.

### Steps to reproduce
1. Create a contest and a problem in it.
1. Submit to that problem.
1.  Remove the problem the contest.
1. Visit the submission page: it gives a 500 error:
![screen](https://user-images.githubusercontent.com/4692022/47253549-babba080-d454-11e8-81de-6ecfd6afa65e.jpg)

**Comment by meisterT** [comment]
What's the expected behavior in these cases?

Warn that the action will remove submissions (if they exist) and then do it?

**Comment by nickygerritsen** [comment]
We were talking about this, but the way you add/remove problems to/from a contest currently is with a multiselect. I don't know how easy it is to add a message there...?
