### ISSUE TITLE
Generate/change initial admin password

### ISSUE THREAD

**Issue by eldering** [DOMjudge/domjudge#430]
Currently a new install comes with credentials admin/admin. This is prone to lead to security issues when someone forgets to change it.
We should either generate a random password during installation or on first login force that the password is changed.

**Comment by meisterT** [comment]
This is mitigated by 
https://github.com/DOMjudge/domjudge/commit/5f18d2cf8275fe96f51655171317a8479313b4f4
and
https://github.com/DOMjudge/domjudge/commit/815c01967b0af0641c5d022507d485229c8dba8e

**Comment by thijskh** [comment]
815c019 is not a good permanent thing to have since it verifies all admin passwords (an expensive operation) on every index page view. So when fixed properly, this check should be removed.

**Comment by thijskh** [comment]
How about: a new user flag, bool password_must_change, when set, post login a user is prompted for mandatory password change before they can do anything. We obviously set this flag when creating the default admin user.

**Comment by thijskh** [comment]
How about: the install scripts generate a random password for the admin user and dump it somewhere on the filesystem

**Comment by meisterT** [comment]
Both options sound ok to me. The second is probably easier to implement.

**Comment by eldering** [comment]
I'd prefer the second, simpler solution.
