### ISSUE TITLE
Unfrozen scoreboard only shown after finalize

### ISSUE THREAD

**Issue by eldering** [DOMjudge/domjudge#433]
When you unfreeze a scoreboard without finalizing the contest, it still shows as frozen to teams and public. This should not be the case.
We might want to put a check in place that in ICPC WF setting we cannot unfreeze before finalizing, but that should not be compulsory in all contexts.

**Comment by thijskh** [comment]
This was broken by c0f583a791ddeed80861179c9cb96c3e4597a970. @meisterT any idea what the problem was?

**Comment by thijskh** [comment]
The check mentioned by Jaap is already in place. It's just the scoreboard logic that has been broken.

**Comment by nickygerritsen** [comment]
Note that the freezedata-logic is now also in the `FreezeData` class in Symfony.

**Comment by thijskh** [comment]
This is not a straightforward fix without reintroducing another problem. I'll review the code around this and come up with a (hopefully) complete fix while trying to avoid duplicated code.

**Comment by meisterT** [comment]
Sorry, I don't remember the problem from back then. @thijskh is this something that needs fixing before NWERC?

**Comment by thijskh** [comment]
The easy workaround is just to finalize the contest when the contest is done.
