### ISSUE TITLE
Judgehost crashing when missing testcase's output (bug)

### ISSUE THREAD

**Issue by baziorek** [DOMjudge/domjudge#436]
### Description of the problem / feature request
I've not added output file to testcase -it was just warning, but judgehost is crashing, so I suggest to replace it with error or to handle that situations in judgehosts.
What is more in list of testcases not-existing file has it's own hash -so it is hard to find (if somebody forgot)

### Your environment
> Include details about your installation here. 
> - DOMjudge version (e.g. 5.3.1 or a github commit hash)
> - Operating system / Linux distribution and version (e.g. Ubuntu 16.04)
> - Webserver (e.g. Apache)
6.0.1
Linux (Ubuntu 18.04)
Apache

**Comment by meisterT** [comment]
How did you add the problem? Per zip upload or through the web interface? Or directly in the DB?

**Comment by meisterT** [comment]
Also which DOMjudge version do you use?

**Comment by meisterT** [comment]
I've just commited a1e0ea7543ca3bd33d8fbfa4101e7c9ee4c5c619 for the master branch.

**Comment by baziorek** [comment]
@meisterT 
I'm using 6.0.1 version.
I was adding this normally through web administrator's interface:
1. I've added problem problem normally
2. I entered testcased of the problem -> Edit
3. I've just choose single file (Input testdata: ) but I didn't choose (Output testdata:),  then I've pressed "submit all changes"
4. I noticed just warning, but it was succesfully added

**Comment by meisterT** [comment]
Ok, this should now be fixed both in master and 6.0 branch. Thanks for reporting!
I've also added a check in the judgedaemon to create an internal error.

**Comment by baziorek** [comment]
Thanks for fast fix:).
