### ISSUE TITLE
submissions api endpoint times out on larger contests

### ISSUE THREAD

**Issue by ubergeek42** [DOMjudge/domjudge#439]
Accessing `api/contests/<cid>/submissions` may time out on large contests. maybe the php time limit should be increased so this endpoint is usable?(large is ~750 submissions). I think the default timelimit is 30 seconds.

**Comment by nickygerritsen** [comment]
I am wondering whether this was before as well... probably this is because we need to loop over everything.
The CCS API is not really built for pagination, which you start to notice for submissions, judgings and runs

**Comment by nickygerritsen** [comment]
@ubergeek42 I committed a potential fix. Could you verify if it is fast(er) again?

**Comment by nickygerritsen** [comment]
@ubergeek42 reported this has been fixed
