### ISSUE TITLE
Export/Import a problem does not preserve problem text pdf

### ISSUE THREAD

**Issue by ubergeek42** [DOMjudge/domjudge#440]
### Description of the problem / feature request
export import problem is broken

### Steps to reproduce
export a problem that has problemtext, then import it again

### Expected behaviour
the problem text to be imported

### Actual behaviour
No problem text is imported. it is in the exported zip though.

**Comment by nickygerritsen** [comment]
I think we import the pdf from a different location compared to where we export...

**Comment by eldering** [comment]
Indeed, this was already reported by someone else. I don't remember anymore who.

**Comment by meisterT** [comment]
I would argue that we should change the export not the import of the problem. Isn't problem.pdf in the main dir of the problem the more natural location?

**Comment by eldering** [comment]
I'm following https://clics.ecs.baylor.edu/index.php?title=Problem_format#Problem_Statements

**Comment by meisterT** [comment]
IMHO, this is not talking about the final statement but the elements to produce it.

For example this is suggesting that this is incomplete:
> The problem statements must only contain the actual problem statement, no sample data.


Also, if you run problem2pdf on a problem, it'll produce a pdf in the problem main dir not in a subdir.
