### ISSUE TITLE
Removing problems from a contest doesn't emit a `delete` event

### ISSUE THREAD

**Issue by nickygerritsen** [DOMjudge/domjudge#441]
When we remove problems from a contest, we do not call `eventlog` for deletion of that problem.
This means that the CDS will think a lot of problems exist in the contest which actually do not.

**Comment by eldering** [comment]
We still need to look into how we can generate these delete events, because we also (first) have to generate delete events for all cascading deletes.

**Comment by nickygerritsen** [comment]
Perhaps we can do this more easily when stuff is moved to Symfony? I can imagine we can hook on some event to do some magic

**Comment by meisterT** [comment]
Did you remove the problem during the contest? If not, then I usually delete all events and restart the event daemon.
