### ISSUE TITLE
Allow downloading zip with all sample in/output

### ISSUE THREAD

**Issue by nickygerritsen** [DOMjudge/domjudge#442]
One of the judges during BAPC told me it would be nice if we'd offer a way to download all sample in/output files as a ZIP, where each in/output is called `N.zip` with N the rank.

We could put this on the problems page under the individual testcase data for example.

**Comment by DerBaer0** [comment]
This would be nice (either automatically generate a zip file with all samples or offer an option to upload a zip file to the contest with samples (that might also include additional files required) ).

Moreover, downloading the entire problemset in a single pdf is helpful if you want to e.g. print everything.

**Comment by nickygerritsen** [comment]
I added an option to download a ZIP with sample cases. For the other requests I think it is best to create new issues if wanted.
