### ISSUE TITLE
Login page return HTTP ERROR 500

### ISSUE THREAD

**Issue by hungthuanmk** [DOMjudge/domjudge#446]
### Description of the problem / feature request
Public page can show normally, but login page can not and it returns HTTP ERROR 500

### My environment
> - DOMjudge version 6.0.2
> - Operating system : Ubuntu 18.04 LTS
> - Webserver: Apache2

![image](https://user-images.githubusercontent.com/12544161/47954261-c6fa3e80-dfba-11e8-84ef-5bba40288ade.png)
![image](https://user-images.githubusercontent.com/12544161/47954264-cf527980-dfba-11e8-8cee-619990e1ece4.png)

**Comment by nickygerritsen** [comment]
Could you check both the Apache error log as well as `webapp/var/log/prod.log` and see what kind of error it gives?

**Comment by nickygerritsen** [comment]
I think the cache for the production environment is not correctly cleared or your parameters are not correct.

Could you:
* Check `webapp/app/config/parameters.yml` to see if your DB credentials are in there. If not, you probably missed a `make` step from the manual
* Otherwise, run `bin/console cache:clear --env=prod` in the `webapp` directory

**Comment by hungthuanmk** [comment]
I found that i wrote` make install domserver` instead of `make install-domserver`, everything seem works well now, but the logo can not appear
![image](https://user-images.githubusercontent.com/12544161/47954843-dfba2280-dfc1-11e8-97be-bbbed216a172.png)

**Comment by nickygerritsen** [comment]
I think you need ‘make docs’ for the logo or install-docs

**Comment by hungthuanmk** [comment]
Omg, why the error keep come to me T_T
When i assign the user to some teams, it makes error 500 when that user try logging in
![image](https://user-images.githubusercontent.com/12544161/47955488-70e1c700-dfcb-11e8-9d3d-78606423e4fa.png)

**Comment by nickygerritsen** [comment]
Could you again check prod.log? Probably you also need to assign the “team” role to the user

**Comment by hungthuanmk** [comment]
It seems there is NO new logs and i also set role "team member" to the user
![image](https://user-images.githubusercontent.com/12544161/47955526-20b73480-dfcc-11e8-9141-e1d077f8e93d.png)

**Comment by nickygerritsen** [comment]
Can you then check the Apache error log?

**Comment by hungthuanmk** [comment]
This is new error.log from Apache2
`[Sun Nov 04 01:02:35.860502 2018] [core:error] [pid 27782] [client 192.168.1.100:50573] AH00037: Symbolic link not allowed or link target not accessible: /home/hungthuanmk/domjudge/domserver/webapp/web/images/DOMjudgelogo.png, referer: http://hcmiuiot.zapto.org/domjudge/login
[Sun Nov 04 01:02:40.455248 2018] [php7:error] [pid 27787] [client 192.168.1.100:50576] PHP Fatal error:  require(): Failed opening required '/home/hungthuanmk/domjudge/domserver/webapp/var/cache/prod/doctrine/orm/Proxies/__CG__DOMJudgeBundleEntityTeam.php' (include_path='/home/hungthuanmk/domjudge/domserver/lib/vendor/phpseclib/phpseclib/phpseclib:.:/usr/share/php') in /home/hungthuanmk/domjudge/domserver/lib/vendor/doctrine/common/lib/Doctrine/Common/Proxy/AbstractProxyFactory.php on line 209, referer: http://hcmiuiot.zapto.org/domjudge/login
[Sun Nov 04 01:02:45.791092 2018] [php7:error] [pid 28023] [client 192.168.1.100:50588] PHP Fatal error:  require(): Failed opening required '/home/hungthuanmk/domjudge/domserver/webapp/var/cache/prod/doctrine/orm/Proxies/__CG__DOMJudgeBundleEntityTeam.php' (include_path='/home/hungthuanmk/domjudge/domserver/lib/vendor/phpseclib/phpseclib/phpseclib:.:/usr/share/php') in /home/hungthuanmk/domjudge/domserver/lib/vendor/doctrine/common/lib/Doctrine/Common/Proxy/AbstractProxyFactory.php on line 209, referer: http://hcmiuiot.zapto.org/domjudge/login`

**Comment by nickygerritsen** [comment]
Can you run the `bin/console cache:clear —env=prod` command again? I think that will create the missing file :)

**Comment by hungthuanmk** [comment]
Awesome. thanks for your support <3

**Comment by Anirudhaagrawal** [comment]
<img width="1440" alt="Screenshot 2020-07-07 at 10 58 38 PM" src="https://user-images.githubusercontent.com/44918113/86819590-81521b00-c0a5-11ea-8033-a8efc280eef2.png">

**Comment by Anirudhaagrawal** [comment]
any ideas why i am getting this error?

**Comment by thijskh** [comment]
A random github issue is not a support forum. Please continue this conversation on Slack
