### ISSUE TITLE
Addon feature to display efficiency of teams in solving problems

### ISSUE THREAD

**Issue by GaurangTandon** [DOMjudge/domjudge#448]
### Feature request

Show two more columns - on the scoreboard page - with number of attempts and attempts per problem for each team. I implemented this client side with simple JavaScript:

![image](https://user-images.githubusercontent.com/6308683/48008662-1ae26000-e140-11e8-8bf7-67f2ce57e319.png)

I was wondering if there's any interest in the developers in having in this feature available as an add-on/by default. I for one find this feature very useful, to quickly find the most efficient teams. 

If you point me to the necessary files on the repo, I'll also happily make a PR for this :)

**Comment by eldering** [comment]
Similar-ish data is already available on the jury analysis page. See https://github.com/DOMjudge/domjudge/blob/master/webapp/src/DOMJudgeBundle/Controller/Jury/AnalysisController.php and https://github.com/DOMjudge/domjudge/blob/master/webapp/src/DOMJudgeBundle/Resources/views/jury/analysis/team.html.twig for the implementation details.
I'm not sure how much interest there is, but if addition should likely only add a column (or maybe two), so I'd say a good PR is welcome.

**Comment by meisterT** [comment]
closing in favor of #429
