### ISSUE TITLE
Add a way to filter clarification queues in clarification overview

### ISSUE THREAD

**Issue by meisterT** [DOMjudge/domjudge#449]
Currently we mention the queue in the table of clarifications, but we don't have a way to show only a subset of clarification queues. With the new table format we also lost the ability to sort by queue.

Also to avoid cluttering probably it would be the best to list each queue separately (if they exist) and on top the unsorted issues.

**Comment by nickygerritsen** [comment]
We can easily reintroduce sorting of course if desired. A basic filter at the top like we have at submissions is also easily done.

If we list each queue individually don’t we possibly have quite a few tables?

**Comment by eldering** [comment]
I also think that sorting and filtering in a single table is better than introducing multiple tables.

**Comment by nickygerritsen** [comment]
I added datatables filtering / sorting for now, so we have something :)
We should do some proper filtering like on the submissions page later.

**Comment by thijskh** [comment]
You can now (since 8374c3fa67b37e63e12b508eb45d29e206d20295) actually use the datatables filtering to display only the clarifications related to a specific queue. A small improvement while we await a more thorough redesign of the clarification concept.

**Comment by meisterT** [comment]
We are all satisfied with the current state.
