### ISSUE TITLE
Missing entry point for jury resubmit leads to http error 500

### ISSUE THREAD

**Issue by meisterT** [DOMjudge/domjudge#450]
### Description of the problem / feature request
Missing entry point for jury resubmit leads to http error 500

### Your environment
DOMjudge nwerc2018 branch

### Steps to reproduce
- add a language with a required entry point
- submit in that language
- as jury, edit and resubmit the source without specifying an entry point

### Expected behaviour
The code is submitted, using the same auto detection as for jury problem zip import.
Alternatively reject the submission and request entry point. But then we should really make sure not to loose the source code edits.

### Actual behaviour
The missing entry point causes an HTTP error 500.

**Comment by nickygerritsen** [comment]
I am wondering what it did before. Anyway we should figure out what the 500 is
