### ISSUE TITLE
Import from baylor website is broken

### ISSUE THREAD

**Issue by meisterT** [DOMjudge/domjudge#451]
### Description of the problem / feature request
In the admin import section we allow import of teams and uploading of standings from/to baylor.

### Your environment
Probably any DOMjudge version is affected.

### Steps to reproduce
- create a web service token in the export section on the baylor website
- go to import page in DOMjudge admin interface
- insert your contest id and web service token and try to import

### Expected behaviour
DOMjudge will download team data from baylor and create teams in DOMjudge if necessary.

### Actual behaviour
We don't get team data back.

### Any other information that you want to share?
We probably have to update the URLs to match the ones in https://icpc.baylor.edu/cm5-contest-rest/rest/contest/export/CLICS/CONTEST
Perhaps other things like client_id.

**Comment by meisterT** [comment]
Documentation is of course in https://icpc.baylor.edu/community/cmsinterface and not the URL in the initial comment.

**Comment by meisterT** [comment]
I tried fixing this, but sadly get a permission error back:
{"location":"SERVER","date":"2018-11-09 20:05:50.720","statusCode":403,"severity":"ERROR","summary":"ACCESS DENIED","detail":"You don't have the permissions"}

(both on the command line as well as in the code)

**Comment by meisterT** [comment]
Ignore this, the contest ID is Northwestern-Europe not NWERC, so I'm getting data back.

**Comment by thijskh** [comment]
This is very messy and also contains a lot of custom auth handling/curling. Likely best to reimplement from scratch against current API.

**Comment by nickygerritsen** [comment]
And probably use guzzle as http client if we move it to Symfony, as that should be installed already anyway

**Comment by thijskh** [comment]
Strictly speaking this issue is closed: the teams import works (in 7.3.2). Upload standing doesn't but is not implemented at all. This is hard for me to test also. I propose to close the issue as I see not much value in using this as a tracking item.
