### ISSUE TITLE
Contest activate button present when contest already started

### ISSUE THREAD

**Issue by eldering** [DOMjudge/domjudge#452]
See https://www.domjudge.org/demoweb/jury/contests/
The contest is already finished, but the activate contest button is still present.

**Comment by nickygerritsen** [comment]
I noticed this as well. It seemed to already be there before I moved this logic to Symfony, so I copied it.... It should probably be easy to fix.

**Comment by meisterT** [comment]
Yeah, I was about to file the same bug. It's even worse: the button works and sets activate time past starttime.

**Comment by nickygerritsen** [comment]
This is probably partly related to that you can press the button if you have the page open from 'before'. I think we should use [this logic](https://github.com/DOMjudge/domjudge/blob/master/webapp/src/DOMJudgeBundle/Entity/Contest.php#L1236) also when submitting the form. And `$showButton` should be false for activate when the contest has been activated.
