### ISSUE TITLE
Externalid is null for teams from admin interface

### ISSUE THREAD

**Issue by akmohtashami** [DOMjudge/domjudge#454]
### Description of the problem / feature request
When creating a new team from admin interface, the team externalid must be automatically set. Otherwise results.html (and basically anything that relies on externalid) will be broken

### Your environment
Domjudge 6.0.2

### Steps to reproduce
A result of this issue can be seen in this way:
1- Create two teams from admin interface
2- Try generating result.html from import/export section

### Expected behaviour
Name of both teams shown on the output

### Actual behaviour
Name of one of the teams shown twice.

**Comment by nickygerritsen** [comment]
The whole external ID thing is kinda new in 6.0 and indeed doesn’t work correctly when using the UI to add stuff.
Currently on master we added support for showing external ID’s in the overviews and after the programming contest season we will drastically improve the usage of this, such that you can set these ID’s in the UI as well.

What are you using results.html for? I think currently this is pretty much linked to the formats used during the ICPC world finals

**Comment by akmohtashami** [comment]
I wanted to use the "First to solve" part of it. I could not find any easier way to produce a decent list like this one.

Do you recommend using the master for holding a contest?

Also one more question: I understand DOMjudge is in a transition state. However, are there any documentation which explains which parts/features are fully functional?

**Comment by nickygerritsen** [comment]
I would not recommend master currently no.
We have a regional contest next week during which we will test it.

6.0 is rather stable, but stuff like first to solve is indeed not easily exported. This is a feature added for/during the world finals which could still be polished.
Note that the scoreboard does show first to solve with a darker green color. Also the balloon interface shows some stuff about first to solve.

Documentation is lacking behind for 6.0 and onward currently.

**Comment by nickygerritsen** [comment]
I have now made it so that results.html works without external ID's as well so I have closed this issue. Thanks for reporting!
