### ISSUE TITLE
Scoreboard summary column shown out of place

### ISSUE THREAD

**Issue by akmohtashami** [DOMjudge/domjudge#455]
### Description of the problem / feature request
Currently, it seems the colspan for summary column is statically set. This does not work since DOMJudge allows showing/not showing country flags and affiliation logos. Setting a configuration where both of these are hidden / displayed, this row will not be shown correctly.

### Your environment
Domjudge 6.0.2

### Steps to reproduce
1- Disable showing affiliation logos AND country logos from configuration
2- load scoreboard and check summary row

### Expected behaviour
Correctly aligned row

### Actual behaviour
Incorrectly aligned row :-)

**Comment by nickygerritsen** [comment]
This has been fixed on master this week actually :). We might consider backporting this to 6.0

**Comment by thijskh** [comment]
Will be fixed in 6.0.3.
