### ISSUE TITLE
Only php-based authentication is working

### ISSUE THREAD

**Issue by akmohtashami** [DOMjudge/domjudge#456]
### Description of the problem / feature request
I was not able to get IP based authentication working. Changing AUTH_METHOD does not seem to have any effects. It seems master branch has changed the way authentication works (uses symphony), but meanwhile 6.0.2 is lacking ip-based authentication (At least I was not able to enable it, nor was I able to find the code which performs any checks against AUTH_METHOD).

### Your environment
Domjudge 6.0.2

**Comment by nickygerritsen** [comment]
This one is yet again fixed on master. Backporting to 6.0 is way less trivial though

**Comment by thijskh** [comment]
It was dropped in 6.0 and a completely new system added in 6.1. If you require IP based authentication, your option for now is to use the master branch or 6.1 as soon as it's released.

I've updated the documentation on 6.0 to reflect this, sorry for the confusion.
