### ISSUE TITLE
Creating duplicate user gives 500 error

### ISSUE THREAD

**Issue by eldering** [DOMjudge/domjudge#460]
### Description of the problem / feature request
In the admin interface trying to create a user that already exists, results in a 500 server error when trying to save. It should give a more helpful message.

### Your environment
DOMjudge `nwerc2018` branch at NWERC.

**Comment by thijskh** [comment]
Did what I described in the third paragraph.
I don't think we need to keep this issue open for the last paragraph, since we're on that path anyway.
