### ISSUE TITLE
Interactive problems checkers are not very robust

### ISSUE THREAD

**Issue by meisterT** [DOMjudge/domjudge#465]
### Description of the problem / feature request
Support interactive problems properly, preferably by supporting the problemtools format, see https://github.com/Kattis/problemtools/tree/develop/examples/guess for an example similar to our own boolfind. 

Currently it's easy to block a judgedaemon or produce "incorrect" verdicts because of how we separate running from validation.
We should consider adding a proper wrapper to both runner / validator scripts during problem import to make setting up these problems as easy as possible.

### Steps to reproduce
Example of a incorrect/malicious submission:
```
int main() {
	while (true) {
		cout << "READ 0" << endl;
	}
	return 0;
}
```

### Expected behaviour
Wrong answer.

### Actual behaviour
Judgedaemon is hanging.

### Any other information that you want to share?
There are other problematic submissions as well, I'll add examples in a later post when I got them.

**Comment by eldering** [comment]
I think I never committed that image, but just sent it to domjudge-devel. See attached.

**Comment by meisterT** [comment]
Thanks for the image, that looks roughly like what I had in mind.
Since adding an image doesn't fix the bug, I'll reopen it ;-)

**Comment by meisterT** [comment]
I investigated a bit more.

In the runpipe we wait until both children have exited (note that not the team submission is one of them but runguard). After that we would close the pipes / file descriptors. But the children didn't exit so far.

In runghard, we killed the team submission which is in zombie state because we didn't wait for it yet. We do hang on a blocking read, so we don't reach the waitpid which would allow us to terminate ourselves.

My current (not well thought out) guess is that we should merge runpipe into runguard.

**Comment by meisterT** [comment]
I investigated a bit more.

In the runpipe we wait until both children have exited (note that not the team submission is one of them but runguard). After that we would close the pipes / file descriptors. But the children didn't exit so far.

In runghard, we killed the team submission which is in zombie state because we didn't wait for it yet. We do hang on a blocking read, so we don't reach the waitpid which would allow us to terminate ourselves.

My current (not well thought out) guess is that we should merge runpipe into runguard.

**Comment by meisterT** [comment]
@eldering what is this code supposed to do?https://github.com/DOMjudge/domjudge/blob/master/judge/runpipe.c#L252-L253
I don't get why we do a blocking wait right after the non-blocking wait, but perhaps I'm missing something.

Anyway, Jaap mentioned in IRC that merging runpipe into runguard is a lot of change which we probably don't want if we can avoid it.
So I toss another idea around:
- add option `--notifyontle <pid>` to runguard
- special case runpipe to make it aware which command is which and add own pid to runguard's arguments
- send SIGUSR1 from runguard to runpipe when we run into SIGALRM
- do the "right thing" in runpipe on SIGUSR1 receival, i.e. probably close all fds, so that the normal flow in runguard that keeps reading from the pipes can finish

@eldering, since you are clearly the best person to fix this, I'll assign the bug to you :-)

**Comment by meisterT** [comment]
Update: this is now mostly solved and interactive problems work in the problemtools format. There is still room for improvement, but I don't know if any functional changes that are still to do.

**Comment by thijskh** [comment]
So then the issue can be closed?

**Comment by meisterT** [comment]
I'll do some more testing (probably to evening) and close it afterwards.

**Comment by meisterT** [comment]
I've done more testing and integrated the problemtools example in our travis test. I also sent https://github.com/Kattis/problemtools/pull/112
