### ISSUE TITLE
dotnet core 2.2 hangs using runguard

### ISSUE THREAD

**Issue by pa-ng** [DOMjudge/domjudge#476]
### Description of the problem / feature request
runguard hangs waiting on completion of compile.sh script using dotnet core 2.2.

### Your environment
- DOMjudge 5.3.3 docker image
- Debian 9 
- Nginx 

### Steps to reproduce
- Step 1 :  install dotnet core 2.2 on judgehost
- Step 2 : disable chroot and modify domjudge-run-1 to have home and shell
- Step 3 : login as domjudge-run-1 to initialize dotnet core: execute "dotnet new console" and "dotnet run"
- Step 4 : create new executable in domjudge for dotnet and language C#, or VB.Net
- Step 5 : submit demo problem hello world using dotnet lang
- Step 6 : problem fails with runguard for time-limit error

### Expected behaviour
expected pass/fail result for Hellow World problem.

### Actual behaviour
fails with time-limit error

### Any other information that you want to share?
output of running runguard. runs successfully without runguard.

sudo -n /opt/domjudge/judgehost/bin/runguard -v -u domjudge-run-1 -g domjudge-run -m 2097152 -t 60 -c -f 540672 -s 540672 -M /opt/domjudge/judgehost/judgings/judgedaemon-1-1/endpoint-default/c2-s7-j77/compile.meta -- /opt/domjudge/judgehost/judgings/judgedaemon-1-1/endpoint-default/executable/dotnetcore/run program 524288 prob1.txt
/opt/domjudge/judgehost/bin/runguard: verbose: cpuset undefined
/opt/domjudge/judgehost/bin/runguard: verbose: setting hard wall-time limit to 30.000 seconds
/opt/domjudge/judgehost/bin/runguard: verbose: setting filesize limit to 553648128 bytes
/opt/domjudge/judgehost/bin/runguard: verbose: disabling core dumps
/opt/domjudge/judgehost/bin/runguard: verbose: using group ID `1001'
/opt/domjudge/judgehost/bin/runguard: verbose: using user ID `1001' for command
The template "Console Application" was created successfully.

Processing post-creation actions...
Running 'dotnet restore' on prj/prj.vbproj...
  Restoring packages for /opt/domjudge/judgehost/judgings/judgedaemon-1-1/endpoint-default/c2-s7-j77/prj/prj.vbproj...
  Generating MSBuild file /opt/domjudge/judgehost/judgings/judgedaemon-1-1/endpoint-default/c2-s7-j77/prj/obj/prj.vbproj.nuget.g.props.
  Generating MSBuild file /opt/domjudge/judgehost/judgings/judgedaemon-1-1/endpoint-default/c2-s7-j77/prj/obj/prj.vbproj.nuget.g.targets.
  Restore completed in 221.09 ms for /opt/domjudge/judgehost/judgings/judgedaemon-1-1/endpoint-default/c2-s7-j77/prj/prj.vbproj.
/opt/domjudge/judgehost/bin/runguard: warning: timelimit exceeded (hard wall time): aborting command
/opt/domjudge/judgehost/bin/runguard: verbose: sending SIGTERM
/opt/domjudge/judgehost/bin/runguard: verbose: sending SIGKILL

**Comment by meisterT** [comment]
Is there a reason why you disable the chroot? I would rather move into a direction where we don't support disabling this anymore and would like to learn under which circumstances it's currently required.

**Comment by pa-ng** [comment]
I disabled chroot to simplify the issue. Get the root cause worked out before introducing other variables.  After some debugging, I found out the issue dotnet core leaves the compiler process hanging around after creating a new app.  As runguard waits for all child processes to complete, dotnet core won't work with domjudge.

**Comment by meisterT** [comment]
I guess this would be fixed by adding a `dotnet build-server shutdown` at the end of your compile script. Can you please give it a try?
