### ISSUE TITLE
If no freeze time is set, API reports a huge scoreboard_freeze_duration

### ISSUE THREAD

**Issue by hex539** [DOMjudge/domjudge#477]
### Description of the problem / feature request

In the //contests/<cid> endpoint, give "00:00:00" for the freeze duration instead of some nonsense number in the case that the contest doesn't have a freeze.

It could be fixed by checking "!empty()" before calculating freeze duration [here in Entity/Contest.php](https://github.com/DOMjudge/domjudge/blob/2dc45f9ecb8368e0b284716afcb103d3e36a2cbd/webapp/src/DOMJudgeBundle/Entity/Contest.php#L1108), like how it already does in a few other places in this file): 

### Your environment
DOMjudge  6.0.2DEV (https://domjudge.bath.ac.uk/)
PHP 7.0.30-0+deb9u1.

### Steps to reproduce
- Create a contest with a Start time and an End time.
- Leave "Scoreboard freeze time" empty.
- Verify that the scoreboard is not frozen.

So far, so good

- Check the CLICS API endpoint at //api/contests/<cid>. Specifically look at scoreboard_freeze_duration

### Expected behaviour
Ideally "scoreboard_freeze_duration" wouldn't even show up if the scoreboard doesn't ever freeze, but it looks like the API spec requires that this is either always given as something non-null, or never given. The next-best behaviour would be to return "00:00:00" for this.

### Actual behaviour
The scoreboard freeze is given as number of minutes between the end time and the UNIX epoch because it subtracts "freeze time" from "end time" without checking if either is null.

For example:

{
"id": "6",
"name": "Bath 2018 December Contest 2",
"formal_name": "Bath 2018 December Contest 2",
"start_time": "2018-12-19T20:00:00.000+00:00",
"duration": "328:00:00.000",
"scoreboard_freeze_duration": "429564:00:00.000",
"penalty_time": 20,
"external_id": null,
"shortname": "bath18dec2",
"end_time": "2019-01-02T12:00:00.000+00:00"
}

This confuses scoreboard clients which go into resolve mode after the end of the contest.

**Comment by hex539** [comment]
I don't think making "required" in the api apply separately to each contest would fix the bug. I can still set up a contest with a freeze time and decide to remove it later -- in which case what should DOMjudge say the freeze duration is? It can't be null or empty if it said "00:30:00.000" earlier.

Ideally `scoreboard_freeze_duration` should be nullable, but for the current spec the best bet seems to be to return "00:00:00" if there is no freeze.

**Comment by thijskh** [comment]
Why can't we change the spec to make freeze_duration nullable? That seems like an appropriate way to express "this server implements the freeze concept, but in this specific contest there's no freeze configured".

**Comment by eldering** [comment]
I agree with Thijs, and in my email to the email list where we discuss the specification, I already proposed that: http://hera.ecs.csus.edu/pipermail/cliccs/2018-December/003667.html

**Comment by eldering** [comment]
After some discussion the Contest API specification was updated to support null, so I'll implement the pull request that way.
