### ISSUE TITLE
Browser notifications are broken

### ISSUE THREAD

**Issue by thijskh** [DOMjudge/domjudge#481]
Since the introduction of the new layout, browser desktop notifications are broken. The switch is still there but the JS simply does not implement it.

**Comment by meisterT** [comment]
What do we want to use notifications for?

**Comment by thijskh** [comment]
It would send a notification when a new clarification arrives or when a judgehost goes down.

**Comment by thijskh** [comment]
There has also been a request for notification on new balloon: #141

**Comment by eldering** [comment]
I would add team notification when receiving any new clarification, also general ones.

**Comment by thijskh** [comment]
I have restored the desktop notification functionality as it was.

The other ideas are good ideas but maybe better as a feature request/PR. They're not trivally addable because e.g. the public/teams interface now does not have any ajaxy stuff at all. Maybe better when everything is moved to the same interface.
