### ISSUE TITLE
Error while uploading several problem zip files at once

### ISSUE THREAD

**Issue by DerBaer0** [DOMjudge/domjudge#491]
### Description of the problem
Uploading multiple zip files with problems at once results in internal error 500 and not all problems are linked to the contest.

### Steps to reproduce
> Go to problems
> Select at least 2 problem archives
> Select a contest to link the problems to
> Upload

### Actual behaviour
An internal error appears with the following message:
> 
>A new entity was found through the relationship 'DOMJudgeBundle\Entity\ContestProblem#contest' that was not configured to cascade persist operations for entity: DOMJudgeBundle\Entity\Contest@0000000013adca430000000034a77b12. To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist this association in the mapping for example @ManyToOne(..,cascade={"persist"}). If you cannot find out which entity causes the problem implement 'DOMJudgeBundle\Entity\Contest#__toString()' to get a clue.

It seems that all problems are uploaded successfully, except that some are not linked to the contest.

**Comment by nickygerritsen** [comment]
There is a potential fix in 64d043c14d341e9d581e268f5bbdf455aa7cdebd. @DerBaer0 could you test this?
