### ISSUE TITLE
Executables with invalid characters can be uploaded

### ISSUE THREAD

**Issue by DerBaer0** [DOMjudge/domjudge#492]
#### Steps:
1. Upload a problem with a custom output validator
2. Go to Executables -> _your Executable_ -> Edit
3. Click 'Save' (no changes needed)

#### Error-Message:
_Only alphanumeric values are allowed_
So, I can successfully upload executables that violate rules, but I cannot edit them later.

#### System:
DOMjudge with latest Commit: 545b10a3f231c42104098e5a6d93d5e1988cb96c

#### Guess:
Just a guess, but currently no time to verify this:
The executableID contains an underscore (because '_cmp' was appended) and this is not allowed for the ID.

**Comment by thijskh** [comment]
I of course fixed your problem (the `_` should be allowed) but indeed te zip file upload did not put the same restrictions as the rest of DOMjudge. Fixed that now.
