### ISSUE TITLE
Balloon filter is reset on refresh

### ISSUE THREAD

**Issue by DerBaer0** [DOMjudge/domjudge#496]
### Description of the problem / feature request
> Filtering in Balloonoverview is resetted on reload / mark as done

### Your environment
> DOMjudge on commit cc458fe102d848274840d66263fc174cea1fac95

### Steps to reproduce
> Open balloons view and apply a filter
> wait for the reload or mark a balloon as delivered

### Actual behaviour
> The filtering is empty again

### Additional notes
The way this filter works is not consistent with the other filters (e.g. submissions can be filtered by language or problem with multiple selections possible). Maybe it would be an option to add a similiar mechanic here.
And for multi-site contests, a filter by affiliation would be nice (but this can be solved using different rooms for the teams)

**Comment by thijskh** [comment]
What would you want to filter the list by?

**Comment by DerBaer0** [comment]
Filter by affiliation would be great for us / GCPC.

**Comment by meisterT** [comment]
Pagination would probably solve this.

**Comment by thijskh** [comment]
Fixed in #607
