### ISSUE TITLE
Fix judgedaemon needing both internal and external contest ID properly

### ISSUE THREAD

**Issue by nickygerritsen** [DOMjudge/domjudge#501]
While setting up and testing for the system test, I noticed the following problem:

* `JudgehostController::getNextJudgingAction` returned the external ID of the contest (if configured to use it) as `cid`
* The judgedaemon uses this value for the following:
  1. Getting submission source code using `api/contests/<cid>/submissions/<sid>/source-code` where `<cid>` should indeed be an external ID and `<sid>` is the internal submission ID
  2. Creating a directory `c<cid>-s<sid>-j<jid>` to store judging data in.
  3. *If* an internal error occurs that the judgedaemon decides is contest related, disable the contest using `api/judgehosts/internal-error` passing the `<cid>`. This API action accepts internal ID's, so it expects the internal contest ID

So point i. and iii. expect *different* ID's in the case external ID's are enabled.

Currently on the WF branch I have fixed it by passing both ID's to the judgedaemon (see 96afb4ced905c3a13ebaa52bfe23eb253c9d065e and 6f5dea0cd3e0fd733b1e9197b18bac4d5024d0f6), but I'm not sure if this is the way we want it to work.  That's also why I haven't cherrypicked it into master yet.
I think we have three options:

1. Let `internal-error` accept an external ID for contest. (besides `cid` or instead of `cid`? how to call it?
2. Let `api/contests/<cid>/submissions/<sid>/source-code` use an internal contest ID. But then it is not really rest-API compatible, as all other things under `api/contests` use external ID's
3. Pass both ID's like we do now

Personally I'd say let's use option 1.
Internal-error supports other arguments (language, judgehost and problem) but `cid` is treated there differently anyway, as we use that as a base filter.

Any opinions?

I think we should fix this properly before releasing 6.1

**Comment by thijskh** [comment]
:one:

**Comment by eldering** [comment]
I think option 2 is a no-go. Also shouldn't `sid` be the external submission ID in case we're shadowing?
Secondly, for things like creating directories we should use internal IDs, so we need to pass the internal `cid` to the judgedaemon (too).
I'm on the fence about what to use for the `internal-error` API endpoint: it's part of the API, so for consistency I would say the external ID, but then again, it's a private extension and not really bound to a particular contest, so internal ID is not too weird.

**Comment by nickygerritsen** [comment]
Why should `sid` be the external ID? If we do that we need to pass two, if you also want to use internal ID's for directories... And why do you want to use internal ID's for directories?

I'm not saying you are wrong, I'm just wondering what is the best approach. It feels so ugly to pass two ID's for the same thing...

**Comment by eldering** [comment]
> OK you are right I think. Currently `<sid>` in that call is _always_ the internal ID, but that does sound ugly, although it is consistent with `internal-error`, since both are private extensions....

Huh?? But the source code is available via a Contest API specification, right? So we shouldn't be using a private extension to fetch that.

**Comment by nickygerritsen** [comment]
> Huh?? But the source code is available via a Contest API specification, right? So we shouldn't be using a private extension to fetch that.

Yes but under another endpoint. Our endpoint stores it base64-encoded while the public one is a ZIP.

Yes we should use the public one, but I think not for 6.1 maybe?

**Comment by eldering** [comment]
Ok, fair enough. But then we should also track that issue, either here or in a new issue.

**Comment by nickygerritsen** [comment]
#504 has been created

**Comment by nickygerritsen** [comment]
So we need to fix this before doing the next release. #504 has differing opinions, so we should decide to do something. On master this is currently broken if `data_source` is `1` or `2` (on `wf2019` we have the 'ugly' fix of passing both ID's).

**Comment by eldering** [comment]
We'll use external ID all the way and the judgedaemon will store judging directories as `.../$ext_cid/$sid/$jid/`.
