### ISSUE TITLE
"Contest over" when contest is not active yet

### ISSUE THREAD

**Issue by meisterT** [DOMjudge/domjudge#502]
### Description of the problem / feature request
Confusingly, we display "contest over" when the selected contest has not yet been activated.
 
### Your environment
wf2019 branch

### Steps to reproduce
Import a contest with contest.yaml that is more than 1 hour in the future, it gets selected automatically and we display "contest over" in the top right menu.

### Expected behaviour
Either not select contest, make it active or tell the user to activate it.

### Any other information that you want to share?
Didn't we have an "activate now" button in the past? I can't find it anymore.

**Comment by nickygerritsen** [comment]
Activate now is there normally if and only if there is currently no active contest but there is one upcoming

**Comment by meisterT** [comment]
Why is this? We do support multiple contests in general.

**Comment by nickygerritsen** [comment]
I think because the UI gets cluttered otherwise but I have no problem if we change it

**Comment by meisterT** [comment]
To be precise: I mean to add such a button on the page of a specific contest not the overview page.

**Comment by nickygerritsen** [comment]
Ahhhh ok that makes sense. We do not have that button yet there but it's easy to add

**Comment by eldering** [comment]
I don't understand exactly what the issue is. Are you talking about what's displayed in the top right corner or buttons on the contest(s) page?

**Comment by meisterT** [comment]
the top right corner
