### ISSUE TITLE
internal error improvements

### ISSUE THREAD

**Issue by meisterT** [DOMjudge/domjudge#503]
### Description of the problem / feature request
There are some flaws with internal error.

### Your environment
Current master.

### Steps to reproduce
Upload broken validator, start judging.
After the internal error is posted, delete the problem.

### Expected behaviour
Only exactly one internal error is posted; and that one is deleted with the problem.

### Actual behaviour
Concurrent judgings may post the same internal error. We may want to deduplicate this and only update the log.
Also the deletion of the problem should cascade to internal errors.

**Comment by nickygerritsen** [comment]
> Concurrent judgings may post the same internal error. We may want to deduplicate this and only update the log.

We should probably put it in a transaction to fix this.

> Also the deletion of the problem should cascade to internal errors.

Our current DB setup for this (a serialized field) doesn't easily support that.

**Comment by meisterT** [comment]
A transaction wouldn't help. Judging A posts the error while judging B just started. B then also fails, but the transaction of A is done for seconds/minutes/...

**Comment by nickygerritsen** [comment]
Hmm but in the API we do a check if an error already exists, see https://github.com/DOMjudge/domjudge/blob/master/webapp/src/DOMJudgeBundle/Controller/API/JudgehostController.php#L896
