### ISSUE TITLE
Use submission/<id>/files API in judgedaemon

### ISSUE THREAD

**Issue by nickygerritsen** [DOMjudge/domjudge#504]
Currently we use a private extension to the CLICCS API to get submission source code, but there is a official one available under `submission/<id>/files`. We should use it.

It does mean we need to unzip stuff, but that shouldn't be too hard.

**Comment by meisterT** [comment]
We should check that the extra zip doesn't harm performance too much. The server should use gzip anyway, right?

**Comment by nickygerritsen** [comment]
Good point as it might, although the zips aren’t too big

**Comment by thijskh** [comment]
Why does it need to be a zip? Just adds complexity and risk over the base64 encoding that we currently use. Not sure what the gain is of using zip.

At least the provided zip files could use 0 compression?

**Comment by nickygerritsen** [comment]
If we want to use the official cliccs endpoint we have to use zip, as it is stated in the spec.
The idea was that we don’t want to have two api calls that do something very similar: give you submission source code

**Comment by thijskh** [comment]
So I'm questioning why the CLICCS api made this to be a zip instead of something much more simple.

**Comment by nickygerritsen** [comment]
@eldering is our CLICCS guy. He will hopefully know

**Comment by eldering** [comment]
> So I'm questioning why the CLICCS api made this to be a zip instead of something much more simple.

What do you have in mind that would be more simple?
I don't remember all reasons we discussed, but a couple of points:

- We want to support multiple files and make it easy/efficient fetch all in one go.
- These multiple files may live inside a nontrivial directory tree; that's automatically encoded in a zip file.
- Given that we bundle them, zip is a very-well supported format across all platforms.

**Comment by meisterT** [comment]
The current `source-code` endpoint also fulfills the same criteria.

The zip file might be simpler for humans to handle but for machines I don't see any difference.

**Comment by eldering** [comment]
I agree that the `source-code` endpoint satisfies all our needs. However, it's duplicate with the `files` endpoint that's already in the Contest API. So I'd say we should move to that even if the only benefit is to get rid of a duplicate non-standardized endpoint.

**Comment by thijskh** [comment]
Just seems to me that the current implementation is a lot simpler. With zips you need to add all kinds of safeguards to prevent path traversals, strange filenames, etc. I would say that it is a disadvantage, rather than an advantage, to allow directory trees inside a submission? How do you upload those submissions, do teams need to create a zipfile first?

I'm all for following the spec but don't see why the spec needs to add an extra wrapper around the things we already have. As said we can have all the mentioned properties without adding the complexities of the rather extensive zip format.

**Comment by nickygerritsen** [comment]
After some discussion we decided to keep the base64 endpoint for the above reasons. If ever CLICS changes to base64 we can use it.
