### ISSUE TITLE
Submission times for multi-day contests

### ISSUE THREAD

**Issue by eilx2** [DOMjudge/domjudge#506]
It would be nice to introduce full time stamps for submissions, instead of only showing the hour and minutes. This is especially important for multi-day contests where you want to track people's submissions.

**Comment by eldering** [comment]
Are you looking for the configuration setting `time_format`?

**Comment by eilx2** [comment]
Yes, I actually have already changed my local version of the `putSubmissions` in `common.php` with the following line:
`echo "<td><a$link>" . printtime($row['submittime'], '%T %F', $row['cid']) . "</a></td>";`

It's good enough, though if you try sorting by time it does it wrong by taking into account only the minutes and hours. Also this format is a bit redundant for 5 hour contests, so maybe one could add a check to see if the contest takes part in the span between 2 different dates?

**Comment by eldering** [comment]
Please check the configuration setting `time_format` (from the admin web interface) and explain why you can't use that.

**Comment by eilx2** [comment]
Oh, sorry. I didn't know that this setting existed because I only ever looked at contest settings. 

Still, probably it would be better to make the time format contest specific in my opinion. Thanks for your help!
