### ISSUE TITLE
Error loading webapp resources.

### ISSUE THREAD

**Issue by ashihCT** [DOMjudge/domjudge#511]
I was having similar issues to Issue #446, and managed to get to the Login screen.
I am still having issues with the image not loading even after I run the following command:
`bin/console cache:clear —env=prod`

I got output:
` // Clearing the cache for the dev environment with debug true                                                          
                                                                                                                        
 [OK] Cache for the "dev" environment (debug=true) was successfully cleared.   `

I did a hard refresh on my browser and still the same error being thrown.

` Symbolic link not allowed or link target not accessible: /home/ubuntu/domjudge/domserver/webapp/web/images/DOMjudgelogo.png, referer: http://IPAddress/domjudge/login`

### Your environment
> Include details about your installation here. 
> - DOMjudge 6.0.3
> - AWS AMI- Ubuntu 18.04
> - Apache2

**Comment by nickygerritsen** [comment]
I think you are missing an extra `-` before `-env`. It should be two.

Also the error you pasted seems like you need to allow the `doc` directory to be accessible by Apache, which is outside of `webapp`.

**Comment by ashihCT** [comment]
Ahh ok, I re-ran the it with `--env`. 
How do I give apache access to the `doc` directory?

**Comment by nickygerritsen** [comment]
My Apache config skills are rusty, but I think the `FollowSymLinks` option should work (see e.g. https://stackoverflow.com/questions/5570085/accessing-files-outside-the-document-root-with-apache )

**Comment by ashihCT** [comment]
I tried adding 

`<Directory />
        Options FollowSymLinks
        AllowOverride None
  </Directory>`

to `000-default.conf` in `/etc/apache2/sites-enabled`. No luck

**Comment by nickygerritsen** [comment]
Maybe someone else with more Apache skills can help? I’m not entirely sure why it isn’t working

**Comment by ashihCT** [comment]
Sure, I appreciate the quick response.

**Comment by thijskh** [comment]
What does the symlink point to and does it indeed exist?

**Comment by thijskh** [comment]
Is it only the logo that does not work; i.e. css/js etc work fine?

**Comment by ashihCT** [comment]
> Is it only the logo that does not work; i.e. css/js etc work fine?

The CSS does not work. 
<img width="1274" alt="screen shot 2019-02-28 at 9 18 51 am" src="https://user-images.githubusercontent.com/42871040/53572742-f587c080-3b39-11e9-914e-4832afbea30b.png">

**Comment by ashihCT** [comment]
@thijskh In case you are curious, it seems to only happen in the admin pages.

**Comment by nickygerritsen** [comment]
@ashihCT this is how our jury interface is supposed to look like 🙈 .
In the next version this will be updated to a Bootstrap layout just like the team and public interfaces.

So indeed it seems only the logo is missing...
Can you check where the symlink points to? The one in `webapp/web/images/
DOMjudgelogo.png`. Does the target exist?

**Comment by ashihCT** [comment]
@nickygerritsen Are you sure that's the case? The demo version on at `https://www.domjudge.org/demoweb/jury` looks different.

<img width="1088" alt="screen shot 2019-03-01 at 10 22 56 am" src="https://user-images.githubusercontent.com/42871040/53647764-3bad5480-3c0c-11e9-88a7-2dc63ed532ec.png">

**Comment by nickygerritsen** [comment]
> @nickygerritsen Are you sure that's the case? The demo version at `https://www.domjudge.org/demoweb/jury` looks different.

The demo is running the `master` branch :)

**Comment by ashihCT** [comment]
@nickygerritsen Ahh! That cleared up the confusion. I followed the link `webapp/web/images/ DOMjudgelogo.png` and it was indeed broken. Recreated the symlink to the doc's `/domjudge/doc/logos/DOMjudgelogo.png` and it's working! Thanks for circling back on this!
