### ISSUE TITLE
Running compile.sh caused a runguard error/crash: 'runguard crash'

### ISSUE THREAD

**Issue by ashihCT** [DOMjudge/domjudge#512]
NOTE: If this is a _discussion starter_, you need any _installation help_ or have a _question_ on how to accomplish something,
rather send an email to our 
[DOMjudge-devel mailinglist](https://www.domjudge.org/mailman/listinfo/domjudge-devel)
instead of filing an issue here.

### Description of the problem / feature request
I am trying testing out my DOMJudge using the Hello World test with the following code:
`test-hello.java` in the `tests` folder

I copied pasted the code into: `helloworld.java` and submitted it using a member in a team via the web interface.
```
/*
 * This should give CORRECT on the default problem 'hello'.
 *
 * @EXPECTED_RESULTS@: CORRECT
 */

import java.io.*;

class Main {
    public static void main(String[] args) throws Exception {
		System.out.print("Hello world!\n");
    }
}
```

I am getting the following error return under Internal Error and the Judge Host goes down.

```
[Feb 28 17:50:30.425] judgedaemon[2121]: API request POST judgehosts
[Feb 28 17:50:30.539] judgedaemon[2121]: Found unfinished judging j6 in my name; given back
[Feb 28 17:50:30.539] judgedaemon[2121]: API request GET config
[Feb 28 17:50:30.632] judgedaemon[2121]: API request POST judgings
[Feb 28 17:50:30.739] judgedaemon[2121]: Judging submission s2 (endpoint default) (t3/p1/java), id j7...
[Feb 28 17:50:30.739] judgedaemon[2121]: API request GET config
[Feb 28 17:50:30.832] judgedaemon[2121]: API request GET config
[Feb 28 17:50:30.924] judgedaemon[2121]: API request GET config
[Feb 28 17:50:31.016] judgedaemon[2121]: API request GET config
[Feb 28 17:50:31.107] judgedaemon[2121]: API request GET config
[Feb 28 17:50:31.199] judgedaemon[2121]: Working directory: /opt/domjudge/judgehost/judgings/ip-172-31-95-162/endpoint-default/c2-s2-j7
[Feb 28 17:50:31.202] judgedaemon[2121]: API request GET submission_files
[Feb 28 17:50:31.299] compile.sh[2133]: starting '/opt/domjudge/judgehost/lib/judge/compile.sh', PID = 2133
[Feb 28 17:50:31.301] compile.sh[2133]: arguments: '/opt/domjudge/judgehost/judgings/ip-172-31-95-162/endpoint-default/executable/java_javac_detect/run' '/opt/domjudge/judgehost/judgings/ip-172-31-95-162/endpoint-default/c2-s2-j7'
[Feb 28 17:50:31.302] compile.sh[2133]: source file(s): helloworld.java
[Feb 28 17:50:31.306] compile.sh[2133]: starting compile
[Feb 28 17:50:31.322] compile.sh[2133]: checking compilation exit-status
[Feb 28 17:50:31.326] compile.sh[2133]: exiting, code = '101'
[Feb 28 17:50:31.330] judgedaemon[2121]: Running compile.sh caused a runguard error/crash: 'runguard crash'

--------------------------------------------------------------------------------

Compiling failed with exitcode 255, compiler output:
/opt/domjudge/judgehost/bin/runguard: invalid groupname or ID specified: `domjudge-run'
Try `/opt/domjudge/judgehost/bin/runguard --help' for more information.

--------------------------------------------------------------------------------

Since the file 'compile.meta' is empty, above error is most likely caused by a crash in runguard.`
```

Not sure what's going on here.

### Your environment
> Include details about your installation here. 
> - DOMjudge 6.0.4
> - AWS / Ubuntu 18.04)
> - Apache 2

**Comment by nickygerritsen** [comment]
It seems you are missing the `domjudge-run` user. See this chapter for how to add it: https://www.domjudge.org/docs/admin-manual-3.html#ss3.7

**Comment by ashihCT** [comment]
I executed `sudo useradd -d /nonexistent -g nogroup -s /bin/false domjudge-run` when setting it up. I tried adding it again, but it says `useradd: user 'domjudge-run' already exists`

**Comment by nickygerritsen** [comment]
I think it also needs a group `domjudge-run` which should be the main group for the `domjudge-run` user. Debian/Ubuntu does this by default I think but maybe AWS made some changes.

**Comment by ashihCT** [comment]
You are a boss, @nickygerritsen! 
You are right AWS Ubuntu didn't assign `domjudge-run` to the `domjudge-run` group. Created the group and added the user. Works now :)
