### ISSUE TITLE
FHS compliant build is broken

### ISSUE THREAD

**Issue by GugolPlex** [DOMjudge/domjudge#513]
### Description of the problem

````configure --enable-fhs```` fails to create a valid configuration and the frontend fails.

  I'm aware of #280 but it seems the problem was not completely solved.

### Environment

- DOMjudge 6.0.3 (also tested with github version)
- Debian 9.8, 64 bits
- Apache

### Steps to reproduce

After install all prerequisites and untar the source code from https://www.domjudge.org/releases/domjudge-6.0.3.tar.gz :

    ./configure --enable-fhs
    [ ... ]
    Summary:
     * project.............: DOMjudge 6.0.3
     * prefix..............: /usr/local
    [ ... ]

     * documentation.......: ${datarootdir}/doc/${PACKAGE_TARNAME}

     * domserver...........: 
        - bin..............: ${exec_prefix}/bin
        - etc..............: ${prefix}/etc/domjudge
        - lib..............: ${exec_prefix}/lib/domjudge
        - libvendor........: ${exec_prefix}/lib/domjudge/vendor
        - libwww...........: ${exec_prefix}/lib/domjudge/www
        - libsubmit........: ${exec_prefix}/lib/domjudge/submit
        - log..............: ${prefix}/var/log/domjudge
        - run..............: ${prefix}/var/run/domjudge
        - sql..............: ${datarootdir}/domjudge/sql
        - submit...........: ${prefix}/var/lib/domjudge/submissions
        - tmp..............: /tmp
        - www..............: ${datarootdir}/domjudge/www
        - webapp...........: 
    [ ... ]

  The webapp variable is left uninitialized and ````make domserver; make install-domserver```` ends creating files in ````/web````  (root directory). Apache is unable to serve DOMjudge.

  This behaviour also occurs when using the source code from GitHub (doing ````make dist```` first, as said in the admin manual and suggested in #280).

  I've been looking for the problem and ````configure[.ac]```` seems to forget configuring ````webapp```` when FHS compliant is enabled:

    [ configure.ac, near line 140 ]
    if test "x$FHS_ENABLED" = xyes ; then
    	AC_SUBST(domserver_root,        '')
    	AC_SUBST(domserver_bindir,      $bindir)
    	AC_SUBST(domserver_etcdir,      $sysconfdir/${PACKAGE_TARNAME})
    	AC_SUBST(domserver_sqldir,      $datadir/${PACKAGE_TARNAME}/sql)
    	AC_SUBST(domserver_libdir,      $libdir/${PACKAGE_TARNAME})
    	AC_SUBST(domserver_libvendordir,$libdir/${PACKAGE_TARNAME}/vendor)
    	AC_SUBST(domserver_libwwwdir,   $libdir/${PACKAGE_TARNAME}/www)
    	    [  No reference to domserver_webappdir here ]
    	AC_SUBST(domserver_libsubmitdir,$libdir/${PACKAGE_TARNAME}/submit)

  I'm unsure the correct value for this var. I've tested two options:

    AC_SUBST(domserver_webappdir,   $libdir/${PACKAGE_TARNAME}/webapp)

  and

    AC_SUBST(domserver_webappdir,   $datadir/${PACKAGE_TARNAME}/webapp)

  Both options provide a value for the variable and ````configure --enable-fhs```` gets it. But nevertheless Apache fails to serve the pages because a problem with ````require````:

    [Thu Feb 28 17:55:47.867539 2019] [:error] [pid 3135] [client xx.xx.xx.xx:xxxx] PHP Fatal error:  require(): Failed opening required '/usr/local/share/domjudge/webapp/app/../../lib/vendor/autoload.php' (include_path='.:/usr/share/php') in /usr/local/share/domjudge/webapp/app/autoload.php on line 7

  The problem is due to the directories structure. I think it would be solved if the ````${PACKAGE_TARNAME}```` were removed from the variables, but this would break the FHS, I guess. Maybe ````webapp/app/autoload.php```` should use ````domserver-static.php```` and its ````LIBVENDORDIR```` but I'm also unsure.

**Comment by nickygerritsen** [comment]
We are aware of this problem but it is not easily fixed for 6.0. The next version has some changes that will hopefully make this better.

I will try to fix the fhs flag on master

**Comment by GugolPlex** [comment]
Ok, thank you!

Maybe this could be indicated in the doc for 6.0.x, then.

**Comment by nickygerritsen** [comment]
I’ll look into that too. I think indeed if we let autoload use the static file we should be almost there :)

**Comment by nickygerritsen** [comment]
After some fighting with makefiles and UNIX tools it seems to work now in my PR, see #514.
Once this is merged I will add a comment to the manual for 6.0 that it doesn't work there.

**Comment by nickygerritsen** [comment]
This has now been fixed on master.
