### ISSUE TITLE
Category name "Self-Registered" tied to function

### ISSUE THREAD

**Issue by alessiojr** [DOMjudge/domjudge#515]
I did the installation of DomJudge and everything was working normally. But at a certain point the user registry has stopped working. (\ register)

The problem is: It should be impossible to change the category name "_Self-Registred_" in a team category.

in line 92 of src / DOMJudgeBundle / Controller / SecurityController.php

  $ self_registered_category = $ in-> getRepository ('DOMJudgeBundle: TeamCategory') -> findOneByName ('**Self-Registered'**);

The problem is beacouse I had renamed the "**Self-Registred" Category to "Normal User"**

on the line

             $ em-> persist ($ user);
             $ em-> persist ($ team);
             $ em-> flush ();
  it would be wise to try try

**Comment by eldering** [comment]
I'm not sure I'd call this a "bug", but it's not ideal that the name of the categoy is coupled to the function of self registration. For example this doesn't allow translation of the category name.
I would propose that we make the name of the category for self-registration a configuration variable. It could simply replace the current `allow_registration`, where unset means not available.
