### ISSUE TITLE
The Submmit Botton Doesnt work

### ISSUE THREAD

**Issue by alessiojr** [DOMjudge/domjudge#519]
Hello
    I'm using a version of the dev version along with my students. And tring to find Bugs :)

Type error: Too few arguments to function DOMJudgeBundle\Controller\Team\SubmissionController::__construct(), 3 passed in /dados/sites/domserver/webapp/var/cache/prod/ContainerCn0j0so/getSubmissionController3Service.php on line 13 and exactly 4 expected

**Comment by alessiojr** [comment]
call the url team/submit

**Comment by nickygerritsen** [comment]
Did you call the cache:clear command? It should work but maybe we have some missing services

**Comment by alessiojr** [comment]
Sorry, the problem is on my server. :)
