### ISSUE TITLE
Rename DB field `team.teampage_first_visited`

### ISSUE THREAD

**Issue by eldering** [DOMjudge/domjudge#520]
Since #359 was fixed, the name `team.teampage_first_visited` does not reflect the meaning anymore, since any team login activity will trigger it to update. This field should be renamed.

**Comment by nickygerritsen** [comment]
> since any team login activity will trigger it to update

But only if it was not set yet. Maybe we should rename it to `first_activity`? And maybe maybe even move it to the user?

**Comment by eldering** [comment]
Agreed on both. We should still show in the team overview which teams have logged in (via their users).

**Comment by nickygerritsen** [comment]
Is this something we want for 6.1?
