### ISSUE TITLE
Kotlin executable not working.

### ISSUE THREAD

**Issue by ashihCT** [DOMjudge/domjudge#522]
I cannot get Kotlin to compile and run submissions successfully.

I have installed Kotlin on the Judge Host and also added Kotlin to the CHROOT.
I did modify the Kotlin executable to have the full path of where I installed it in the chroot:
`exec /usr/lib/kotlin-native-linux-1.1.2/bin/kotlin ...`

When testing the Hello World problem, I am getting:

```
Compiling failed with exitcode 1, compiler output:
Info: using main class provided by ENTRY_POINT='Test_helloKt'.
error: invalid argument: -d
info: use -help for more information
```
I am guessing this error is failing on a `kotlinc -d` command on line 37 in the executable, but I am able to use `kotlinc -d` when I run it from the terminal.

### Your environment
> Include details about your installation here. 
> - DOMjudge version 6.0.3
> - AWS Ubuntu 18.04
> - Apache 2

**Comment by nickygerritsen** [comment]
Did you try the suggestions @eldering gave on the mailing list:

> Do you have multiple versions of Kotlin installed and does one maybe support the option but another not?
> You could try removing the "-d ." from the compile script and see if it works then.
> As a last resort debug option, you could add lines:

```
kotlinc -version
kotlinc -help
```

> to the script to see what version of kotlin is called and which options it does support.

**Comment by ashihCT** [comment]
Hmm... I must not have received the response.

Weird...
It looks like when it runs it uses:
```
info: kotlinc-native 1.3.21 (JRE 1.8.0_191-8u191-b12-2ubuntu0.18.04.1-b12)
Kotlin/Native: 1.1.2
Usage: kotlinc-native <options> <source files>
```
which does not have the `-d` option.
But when I run from the terminal I get the correct:
```
info: kotlinc-jvm 1.3.21 (JRE 1.8.0_191-8u191-b12-2ubuntu0.18.04.1-b12)
Usage: kotlinc-jvm <options> <source files>
```
Which does have `-d` option. 

Why is it picking `kotlinc-native` instead of the standard `kotlinc`?

**Comment by nickygerritsen** [comment]
Could you run

```
which kotlinc
```

both from the executable as well as your CLI and see where they point to? I think this will be different.

**Comment by ashihCT** [comment]
You are right, it looks like they were using two different ones:
Executable: `/bin/kotlinc`
CLI: `/home/ubuntu/.sdkman/candidates/kotlin/current/bin/kotlinc` 

I changed the executable to use the path `/home/ubuntu/.sdkman/candidates/kotlin/current/bin/kotlinc` and it looks like it is passing compilation now.

Now I am getting a `RUN-ERROR`:
`Info: using main class provided by ENTRY_POINT='Test_helloKt'.`

**Comment by nickygerritsen** [comment]
That `Info` line is *not* the reason for the run error. That is only printed as an information message to show what the main class is that gets detected.

There should be another error somewhere why it actually crashed, when you look at the output of the first run. My guess it is because you `exec` it with kotlin-native (at least that is what you typed in the original issue description), but I'm not sure. Kotlin is a bit troublesome when it comes to running.

**Comment by ashihCT** [comment]
Thanks for getting me on the right path. It seems like the compiler I got from Kotlin's github is different and uses `kotlin-native` instead of `kotlin-jvm`. I copied over the compiler that I installed using SDKMan on the host server into the chroot and it's passing.

You rock, Nicky.
