### ISSUE TITLE
runguard compile faild because of permission denied

### ISSUE THREAD

**Issue by pqnguyen** [DOMjudge/domjudge#523]
I use domjudge for judge a submission but i get some problems. Please help me!! thank in advance!

![image](https://user-images.githubusercontent.com/23742014/54475211-53e2bd80-4821-11e9-80db-db8798ef274c.png)

**Comment by meisterT** [comment]
How did you install DOMjudge? These paths shouldn't be owned by the user `root`. Also which version do you run?

**Comment by pqnguyen** [comment]
sorry i don't know exactly how it was installed because my friend install it. I know it shoudn't be owned by the user root, but are there any solution to fix it ?? i neet it work first.

**Comment by meisterT** [comment]
It seems everything is now world readable and world writable and owned by root. The easiest is to dump the database (if it contains any useful data) and then redo the installation from scratch following the instructions here: https://www.domjudge.org/docs/admin-manual-3.html
and if successful then restore the DB dump.

**Comment by pqnguyen** [comment]
I just what install judgehost to judge my submissions. so i can call file script/1_compile to compilte source code and judge. After that i can get result file. Are there any instruction that guide install judgehost. Thanks so much!

**Comment by meisterT** [comment]
Yes, the link that I posted contains also instructions how to install the judgehosts.

**Comment by meisterT** [comment]
Closing this. Feel free to reopen if you find something unclear or if the instructions do not work.

**Comment by pqnguyen** [comment]
Thank you so much!
