### ISSUE TITLE
How to add more compiler to judgehost

### ISSUE THREAD

**Issue by pqnguyen** [DOMjudge/domjudge#530]
I saw that in judgehost there is a directory compiler that contain many compiler such as py2, cpp. In every compiler directory contain executable build, run. What is the purpose of these file ? and how to add more compiler to it. Thank in advance !!

**Comment by thijskh** [comment]
This is configured in the web interface. From the main page click "Languages". Edit a language and see that it has a compile script associated. You can add more scripts via the "Executables" option in the main menu. Also see our documentation at https://www.domjudge.org/docs/admin-manual-3.html#ss3.12
