### ISSUE TITLE
Submit while countdown paused is at epoch

### ISSUE THREAD

**Issue by thijskh** [DOMjudge/domjudge#533]
When the contest countdown is paused, there is temporarily "no" starttime. When a submission happens (necessarily by a jury member), this submission will have the submittime of ±0 therefore an extremely high number of minutes on the scoreboard.

**Comment by nickygerritsen** [comment]
I propose adding an argument to `Contest::getContestTime` to use the 'real' start time even when the contest is paused and using that in `ScoreboardService::calculateScoreRow`.

I think we can do this *always* because as said only jury can submit solutions during contest pause.

Any objections?
