### ISSUE TITLE
Add 'super lazy' mode when running in shadow mode to only judge submissions upon request

### ISSUE THREAD

**Issue by nickygerritsen** [DOMjudge/domjudge#540]
As requested by @SteinNorheim it would be great if we had a mode where we would not judge submissions automatically, but only when someone presses some button per submission.

We could do this by making the lazy judging mode a 'troolean' and modify the query to get the next judging to not return submissions we don't want.

This is related to #539 because this seems only useful when running in shadow mode.

**Comment by meisterT** [comment]
With the new judgehost API this basically means to create judgetasks on demand, similar to when a problem is not allowed to judge.

**Comment by vmcj** [comment]
So I have something in #1540 for this, but I assume that we also want to inverse this flag for the category the analysts belong to? Otherwise they have to press the button all the time to get their own submissions.

**Comment by nickygerritsen** [comment]
Maybe only do it for external judgements? The analyst once aren't external.

**Comment by vmcj** [comment]
I propose to close this as I think this is now implemented (#1540)

**Comment by vmcj** [comment]
@SuprDewd do you think the feature is now useful for analysts during the WF?
