### ISSUE TITLE
Re-add support for LDAP logins

### ISSUE THREAD

**Issue by nickygerritsen** [DOMjudge/domjudge#546]
We have heard from at least two people that they actively use the LDAP login method we had in 5.x.
This is currently not available yet in 6.x, but we should re-add it.

https://symfony.com/doc/3.4/security/ldap.html shows some pointers to get started.

**Comment by thijskh** [comment]
This can now be done with libapache2-mod-auth-ldap. Do we consider that sufficient for this issue, or do we want to add something more specific for LDAP to DOMjudge itself (likely not that difficult - but is it needed)?

**Comment by nickygerritsen** [comment]
I'd say if it works with REMOTE_USER we don't have to. I Googled to see if nginx also has such a moduke and found some LDAP modules, so probably you can also get it to work with that.

**Comment by thijskh** [comment]
It's documented here how you can enable LDAP for DOMjudge with an external authentication module:
https://github.com/DOMjudge/domjudge/blob/master/doc/manual/config-advanced.rst#using-remote-user

Should in the future it be necessary to add more specific LDAP integration into DOMjudge itself, or as a local change for an installation, this provides the steps: https://symfony.com/doc/4.4/security/ldap.html

I believe this suffices for now and I'll close this issue.
