### ISSUE TITLE
Left-over fixes from wf2019 branch

### ISSUE THREAD

**Issue by meisterT** [DOMjudge/domjudge#548]
We merged most of the changes we made exclusively on the wf2019 branch. This should be the list of the remaining commits to look at:

- [x] pre-contest-start last modified quickfix: ad5145629534ecef39744876d79a8bac40b0bd9e
- [x] don't overwrite shortnames during zip import: 2112341f786b36ec5d9b3b90d15f272b75fadc2a
- [x] set externalid for problems imported via problem.yaml: 549d0cea23fded7a3ebf066bf4162132d2b18382
- [x] set externalid for example contests: 96112a45efc1cb15302850d67005daf5ae6131e6
- [x] add comment in source code for 2a361c7fc0430a5bbb971676c91459d75b84e440

**Comment by meisterT** [comment]
Two more that perhaps need some discussion / thoughts. Updating compile scripts:
7267ee24b12fa40afb7b9bcd783dbcb54963f62a
1fb75669988e7f0a9e3dda0f803789aef71604b6

**Comment by nickygerritsen** [comment]
I think ad51456 is not needed anymore on master. We have it [here](https://github.com/DOMjudge/domjudge/blob/master/webapp/src/DOMJudgeBundle/Resources/views/partials/scoreboard.html.twig#L132) and the old code is gone.

**Comment by nickygerritsen** [comment]
For 549d0ce the new code is [here](https://github.com/DOMjudge/domjudge/blob/master/webapp/src/DOMJudgeBundle/Service/ImportExportService.php#L217).
For 96112a4 I think we should set the external ID's to `demo` and `demoprac`.

**Comment by nickygerritsen** [comment]
> Two more that perhaps need some discussion / thoughts. Updating compile scripts:
> [7267ee2](https://github.com/DOMjudge/domjudge/commit/7267ee24b12fa40afb7b9bcd783dbcb54963f62a)
> [1fb7566](https://github.com/DOMjudge/domjudge/commit/1fb75669988e7f0a9e3dda0f803789aef71604b6)

7267ee2: merge IMHO; it's 2019 so I think this makes sense....
1fb7566: there is also 65503779 which does a similar thing for extensions. I'm not sure if we want that by default. However, changing the compile scripts for every big contest is also... meh. I have no strong opinion on the `-g`, `-x`, `-Wall` and `-pipe` flags.

**Comment by eldering** [comment]
I prefer to keep the compile scripts agnostic of C/C++ language version. The compilers will automatically migrate to newer defaults. I think it's fine to cherry-pick those changes from last year.

**Comment by nickygerritsen** [comment]
> I prefer to keep the compile scripts agnostic of C/C++ language version. The compilers will automatically migrate to newer defaults. I think it's fine to cherry-pick those changes from last year.

Fair point. What about the extension checking and the flag? I'd say let's not do the extension-checking on master, but for the flags I don't know.

**Comment by eldering** [comment]
I don't agree with all those WF compiler flags. For example, we use `-x c` and `-x c++` to force compiling as C/C++ code. I think this makes sense and I don't like to drop that. Also, the `-pipe` option speeds up compilation if I remember correctly, and prevents potentially large intermediate files. And I don't really see the point of `-g` for debugging symbols, while `-Wall` is useful. So I'd prefer to keep them as is and cherry-pick again for next WFs.

**Comment by meisterT** [comment]
I don't feel strongly about the flags.
The extension checking should (and could) probably done in a generic way. I would prefer this behind a config variable over the filter in the script.

**Comment by thijskh** [comment]
Need to solve extensions issue generically tracked as #566.
Closing this now.
