### ISSUE TITLE
Restructure test sources

### ISSUE THREAD

**Issue by meisterT** [DOMjudge/domjudge#549]
27bc765094038b75f7aeb4bd8ffb92bff06f524e is the entry point hack we used for the finals both last and this year.
I want to rearrange test sources a little bit so that they comply with the problem tools format and with their TBD export format (with entry point).

**Comment by eldering** [comment]
Is there any suggested TBD export format?

**Comment by meisterT** [comment]
I guess we should work with the Kattis folks on a format that problemtools could export, perhaps this is something to discuss for one of the next standards meetings.

Note that for last NWERC I did a dirty hack where we created a `submissions.json` file: https://github.com/DOMjudge/domjudge/commit/bb6e9c497d8dea5a635f51dd24293648865d7ab9
This made sure we submit the jury submissions under their name (`submissions.json` was auto-generated with some heuristics based on the filename prefix falling back to consulting git to find out the initial author of that submission).

The file used the submission file names as key and then a dict as value where the following attributes (all optional) make sense to me:

- team_id
- team_name (only one of those two can be set)
- entry_point
- language_id

**Comment by vmcj** [comment]
@eldering @nickygerritsen can this be done with the CAF?
