### ISSUE TITLE
Judges Viewing Runs

### ISSUE THREAD

**Issue by eldering** [DOMjudge/domjudge#55]
The CCS must provide a human judge with the ability to perform each of the following operations: 
1. See a list of all submitted runs, where the list includes (for each run) the contest-relative time at which the run was submitted, the problem for which the run was submitted, the language specified in the run submission, and any judgments applied.
2. Sort the list of runs by submission time (newest runs first).
3. Filter the list of runs by:
   - Problem
   - Team
   - Language
   - Judgement applied. 
4. View and download the output produced by the program when run against the specified input data
5. View and download the source code contained in any specific submitted run
6. View the compiler output resulting from compiling any specific run utilizing the compiler arguments configured in the CCS
7. View the validator output resulting from invoking the external validator associated with the contest problem for any specific submitted run
8. View and download the judge's input data file associated with the contest problem for any specific submitted run
9. View and download the "judge's output" (the "correct answer" file) associated with the contest problem for any specific submitted run
10. View the judge data description, if available.
11. View a diff between team output for the submission and judge answer file for the problem
12. View previous submissions by the same team on the same problem

**Comment by thijskh** [comment]
I think this is complete.
