### ISSUE TITLE
Add cache-control headers to static files in nginx config

### ISSUE THREAD

**Issue by nickygerritsen** [DOMjudge/domjudge#551]
For the nginx config we do not set cache-control headers yet for static files, like the Javascript, CSS and image files. We might want to do this to reduce the number of HTTP requests.

**Comment by thijskh** [comment]
Doesn't do nginx this automatically (like Apache does)?
BTW the caching seemed to work just fine the last contest we ran with it.

**Comment by nickygerritsen** [comment]
> Doesn't do nginx this automatically (like Apache does)?
> BTW the caching seemed to work just fine the last contest we ran with it.

Not by default, you need to add the line `expires 24h` or similar for static files.
The caching at the World Finals was not entirely correct, I saw some users requesting the images way too often.

**Comment by thijskh** [comment]
A drawback is that fixing an 'incorrect' logo does not show up quickly in the interface.

**Comment by tuupke** [comment]
Why not use ETag's? Most modern browsers support this and changes should be picked up immediately since the hash of the file changes. http://nginx.org/en/docs/http/ngx_http_core_module.html#etag

**Comment by nickygerritsen** [comment]
I *think* we are already sending ETags (will check later), but without a `Cache-Control` header nothing will happen. However, we might set it to `must-revalidate`?

**Comment by thijskh** [comment]
I don't think we "ignore" static asset caching, we just rely on the defaults of these webservers. Which means they already do and support E-Tag and I-M-S. I'm not sure we need to be explicitly more aggressive than that, since 304 responses can be served very quickly and efficiently while retaining the freshness of these assets.

**Comment by nickygerritsen** [comment]
> I don't think we "ignore" static asset caching, we just rely on the defaults of these webservers. Which means they already do and support E-Tag and I-M-S. I'm not sure we need to be explicitly more aggressive than that, since 304 responses can be served very quickly and efficiently while retaining the freshness of these assets.

I was not talking about the 304's. Or well, I was. If I open https://nwerc-judge.gehack.nl/ in my browser, the first time I *do* see requests to all images, JS and CSS as I expect. After that, if i click the scoreboard again I see *no* request. The browser decided it can still keep this file, probably with some heuristic, because we send *no* Cache-Control headers (but as said we do send etags and i-m-s'es).

However, never did I see requests that resulted in a 304, neither in the browser nor on the server. Which I think the browser *only* does if we sent a cache-control header.

However, apparently etags do something that make the browsers be smart and that seems to be fine enough, so I will close this issue.

**Comment by thijskh** [comment]
I've verified at the WF that conditional requests were sent by team workstations and 304's were served in response.

**Comment by nickygerritsen** [comment]
> I've verified at the WF that conditional requests were sent by team workstations and 304's were served in response.

OK that sounds good 😄 Then I don't know why I can't get my browsers to do that but maybe I just need to wait longer. Anyway, closed is then the right state for this issue 🙈 .
