### ISSUE TITLE
Eventdaemon leaks memory

### ISSUE THREAD

**Issue by meisterT** [DOMjudge/domjudge#553]
While the event daemon is not doing much after initial insertion of static data, its memory usage did grow to > 10GB after running for half a day (on the wf2019).
Our current assumption is that it holds on to some internal state in doctrine.

**Comment by nickygerritsen** [comment]
It might be interesting to see what happens if we upgrade Doctrine, when we have PHP > 7.0

**Comment by nickygerritsen** [comment]
Also: https://stackoverflow.com/questions/26616861/memory-leak-when-executing-doctrine-query-in-loop

Maybe we did run it in debugmode...?
