### ISSUE TITLE
Ballon "first in contest/problem/team" broken in newest version

### ISSUE THREAD

**Issue by bumfo** [DOMjudge/domjudge#557]
### Description of the problem / feature request
> first in contest/problem/team shown in ballon status is wrong

### Your environment
> Include details about your installation here. 
> - 6.0.3
> - Ubuntu 16.04
> - Apache

### Steps to reproduce
> - Submit two accepted submissions for one problem with two team
> - View ballon status
> - The newest submission is shown as first for problem/team/contest etc.

### Expected behaviour
> The earliest submission is shown as first for problem/team/contest etc.

### Actual behaviour
> The newest submission is shown as first for problem/team/contest etc.

### Any other information that you want to share?
It seems that first for xxx calculation assumes balloons are in desc order
however they are ordered by done asc, balloonid (done ? desc : asc)
making first for xxx incorrect

**Comment by bumfo** [comment]
by the way, order by balloonid to determine first in xxx is not accurate.
e.g. two team submitted (correct submission) at the same time, if judging of the first submission is finished after the second one, ballonid of the second one < ballonid of the first one, but submission time is reverse.

**Comment by nickygerritsen** [comment]
On `master` we now store first to solve in the scoreboard caching table and we do the calculation there correctly (the case you mention is indeed one that is fixed there).
I think for the next release we should use that information to determine FTS balloons.

@thijskh do you agree?

**Comment by nickygerritsen** [comment]
Also I'm not sure if we can fix this easily on on 6.0.3 in the proper way, but a 'quick' solution would be to hand them out ordered on submitit? Then at least if you wait 'long enough' you get the correct FTS balloon.

**Comment by thijskh** [comment]
Yes, it makes sense to reuse that information so we only calculate this in one place. Should still find a solution for 'first in contest' and 'first for team', regardless.

**Comment by thijskh** [comment]
The code has completely changed in master. So I don't see it as opportune to fix this in 6.0.x.

**Comment by bumfo** [comment]
I have a fix for this, it just makes sure balloons are ordered by submission time desc, and then first to solve etc. is correct. 

If it's needed to be shown in undone first, done last, sort it at client side should be ok.

**Comment by thijskh** [comment]
I have fixed this in master in a combined approach. Change sorting to submittime solves it for first-in-contest / first-for-team, because we don't order by 'done' already in master But for first-for-problem, need to query the scorecache as there can be multiple of these (one per sortorder). So the fix is not easily backportable to 6.0.x.
