### ISSUE TITLE
DESTDIR included in symlink in webapps

### ISSUE THREAD

**Issue by ss1h2a3tw** [DOMjudge/domjudge#560]
### Description of the problem / feature request
It seems like the same FHS problem in https://github.com/DOMjudge/domjudge/issues/558.
The symlink in webapps is broken due to including the DESTDIR variable.

> [shane@dom webapp]$ pwd
> /var/lib/domjudge/webapp
> // List the broken links
> [shane@dom webapp]$ sudo find . -xtype l
> ./web/webfonts
> ./web/css/bootstrap.min.css
> ./web/css/select2.min.css
> ./web/css/dataTables.bootstrap4.min.css
> ./web/css/bootstrap.min.css.map
> ./web/css/nv.d3.min.css
> ./web/css/fontawesome-all.min.css
> ./web/css/nv.d3.min.css.map
> ./web/css/select2-bootstrap.min.css
> ./web/js/d3.min.js
> ./web/js/nv.d3.min.js
> ./web/js/bootstrap.bundle.min.js
> ./web/js/bootstrap.bundle.min.js.map
> ./web/js/jquery.dataTables.min.js
> ./web/js/jquery.min.js
> ./web/js/dataTables.bootstrap4.min.js
> ./web/js/select2.min.js
> ./web/doc
> 

### Your environment
With commit https://github.com/DOMjudge/domjudge/commit/596995ee91497a0eab3bc0baa544cc3828cf6c78
Arch linux

### Steps to reproduce
Enable FHS and package

**Comment by nickygerritsen** [comment]
At least now I know how to fix it 😄 
I have just pushed what I believe is the fix.
