### ISSUE TITLE
Add option to specify team and association during self-registration

### ISSUE THREAD

**Issue by nickygerritsen** [DOMjudge/domjudge#561]
When self-registration is enabled, it would be nice if users could specify the name of the team they want and the affiliation they want to belong to.

For the team name we can just add an input field, which checks if the team doesn't exist yet. If it does, give an error.

For affiliation, we can show a toggle to either select an existing one or create a new one. In the latter case users can provide a name and optional country (if enabled). Again, when creating a new one we need to check if it already exists.

**Comment by eldering** [comment]
I think it would be good to make the option to create a new affiliation dependent on a configuration setting.

**Comment by ykazakov** [comment]
Sorry for resurrecting an old issue, do I understand it properly that for self-registration it is not possible for several users to join one team? Why is this not allowed?

Also, why the full name of the user cannot be entered using this form?

**Comment by mvr320** [comment]
Hi @ykazakov,

I think resurrecting this issue is indeed not the correct method. Could you make two issues for this? One for the several users and one for the full name?

It will make discussion easier.

**Comment by ykazakov** [comment]
@mvr320 sure, no problem. I thought at least the first issue should be related to this ticket.
