### ISSUE TITLE
How to install domjudge on macos

### ISSUE THREAD

**Issue by pqnguyen** [DOMjudge/domjudge#562]
I have seen domjudge document, that is only about installation on ubuntu or debian. I want to install on my macbook, but i don't know how to install. Are there any guide installation on macos? thank in advanced!

**Comment by nickygerritsen** [comment]
Hi @pqnguyen . We natively only support Linux-based operating systems.
However, using our [Docker images](http://hub.docker.com/r/domjudge/domserver/) you can install on macOS (and Windows) as well. That page should contain enough information for you to get started.

**Comment by pqnguyen** [comment]
Thank for your reply @nickygerritsen , because i am trying to write some code base on judgehost, so i need to run it natively on macOS so it is easy for me to write code. But the setup is so complicate. So i need a guide that tell me which package need to be install to run natively on macOS. Anyway thank you so much for your reply!

**Comment by nickygerritsen** [comment]
In that case look at our domjudge-contributor docker image. In our normal domjudge repo there is a docker composer file you can run which will set up everything to get coding on macOS.

**Comment by eldering** [comment]
Closing this as the question seems answered.
