### ISSUE TITLE
demoweb is broken

### ISSUE THREAD

**Issue by meisterT** [DOMjudge/domjudge#564]
- login with admin/admin does not work, jury/jury works
- team page and scoreboard page while being logged in as jury gives a 500 with message `Type error: preg_match_all() expects parameter 2 to be string, null given` (public scoreboard works)

**Comment by nickygerritsen** [comment]
See f7cb69df31cddedfb18cf68fe57d14533b55a326 for the `preg_match_all` fix.

Logging in as admin/admin does seem to work here...

**Comment by meisterT** [comment]
admin/admin now works for me too.
