### ISSUE TITLE
Generic way to limit compile scripts to specific extensions

### ISSUE THREAD

**Issue by thijskh** [DOMjudge/domjudge#566]
Introduce a generic way to bind compile scripts to specific file extensions.

This was done ad hoc in 1fb7566 and 6550377.

**Comment by nickygerritsen** [comment]
If we modify [this line](https://github.com/DOMjudge/domjudge/blob/master/judge/judgedaemon.main.php#L739) to add a check if the extension of the file is in the list of extensions for the language (which we can send in the API in `$row`) we should be fine, right?

We *do* want to copy other source files, for example for C++ we also have `.h` files which are not in the extension list but should be copied.

**Comment by eldering** [comment]
I'm not convinced we should restrict the list of files we send to the compile script. I think that this filtering may/should be language dependent, thus done inside the scripts. Also, if the compile script wanted to do anything specific with files that don't match the language extensions, then this makes it more complicated.

**Comment by nickygerritsen** [comment]
So then we should pass the list of extensions to the compile script and use that in the compile script?

We can do that even exactly like we do in 1fb7566, by setting an environment variable with the extensions, just like we do with the entry point?

Then the scripts can decide what to do with the list and we modify our default scripts to check the list?

If we really want, we can put this (the setting of the environment var) behind a config flag so it can be enabled/disabled?

**Comment by eldering** [comment]
Passing this in an environment variable sounds reasonable to me. I don't think we need to put this behind a configuration setting: the compile script can easily ignore it.
