### ISSUE TITLE
Submissions disappeared in judge queue during applying rejudge

### ISSUE THREAD

**Issue by ss1h2a3tw** [DOMjudge/domjudge#572]
### Description of the problem / feature request
During applying a rejudge, some submissions will be added, but not be judged. The status of the submission will be judging, but no judgehost is judging it, and cannot be rejudged.

### Your environment
Archlinux
https://github.com/DOMjudge/domjudge/commit/84b4f56b5e014e1d3c3f164134fc8e8509b8d1e9

### Any other information that you want to share?
I will send the log after the contest ends.

**Comment by meisterT** [comment]
Do you have perhaps judgehost restrictions in place (in particular the not self restriction)?

**Comment by ss1h2a3tw** [comment]
No, the restriction is empty

**Comment by ss1h2a3tw** [comment]
I checked the database. The submission is in the submission table but not in the judging table. But the judgehost in the submission table is assigned

**Comment by meisterT** [comment]
and this judgehost didn't crash?

**Comment by ss1h2a3tw** [comment]
Yeah, it did not crash during the rejudge.
But this judgehost has been restarted earlier.

**Comment by ss1h2a3tw** [comment]
https://pastebin.com/eeKG0Mfk
Here is the audit log. At the bottom is the rejudge apply start event. And some new submission are sent. s916, s917, s919, s920, s924, s925 are not pushed inside the judge queue.

**Comment by ss1h2a3tw** [comment]
Do you need the database dump?

**Comment by nickygerritsen** [comment]
A dump would really help. Can you also send the webserver log and webapp/var/log/prod.log?

**Comment by thijskh** [comment]
Would be great if you’d be able to reproduce it, is that the case?

**Comment by nickygerritsen** [comment]
I tried the 'easy' test:
* Create a rejudging
* Let it finish
* Add a `sleep(5)` in the apply function so I have time (it was a small rejudging)
* Apply the rejudging
* Submit a new solution

This didn't give any issue, so your case is at least more elaborate.

**Comment by ss1h2a3tw** [comment]
Here is the prod.log
https://drive.google.com/file/d/1q1kdciZokskVybrO-Pb4Eu5njvbdUT4q/view?usp=sharing

**Comment by ss1h2a3tw** [comment]
Here are the database dump, these are dump during a contest (now). So maybe some of them will not be consistent at the latest data.
The dumped tables are `event.sql  internal_error.sql  judgehost.sql  judging.sql  rejudging.sql  submission.sql`
https://drive.google.com/file/d/1PCaOju4ejxUSQS_bTpXT5Fy9QA6wu4GA/view?usp=sharing

**Comment by meisterT** [comment]
Thanks for the report and the data. This should be fixed with https://github.com/DOMjudge/domjudge/commit/13c2cd96e0c7569408f0e88209a3d9ce887d970b
