### ISSUE TITLE
Add support for ruby

### ISSUE THREAD

**Issue by jahirfiquitiva** [DOMjudge/domjudge#577]
### Description of the problem / feature request

Hello

I have installed Ruby and enabled it in the languages site, but for some reason scripts are not executed, although they seem to be compiled properly.

What can I do to fix this issue? Thanks in advance

### Your environment
> - DOMjudge version: 6.0.1
> - Operating system / Linux distribution and version: Debian 9
> - Webserver: Apache

**Comment by meisterT** [comment]
What's the exact error that you got? Did you install Ruby in the chroot?

**Comment by jahirfiquitiva** [comment]
I installed with my normal user ... I'm not sure about how to install it in the chroot

**Comment by meisterT** [comment]
The easiest is probably to recreate the chroot and pass the additional required packages via the `-i` option, see https://github.com/DOMjudge/domjudge/blob/master/misc-tools/dj_make_chroot.in

If you want to modify it, become root and do something like
```
chroot /chroot/domjudge /bin/bash
apt install ruby
```
Make sure to use the correct path to your chroot and the right packages necessary for ruby.

**Comment by jahirfiquitiva** [comment]
Thank you so much for the help! It worked 👌
