### ISSUE TITLE
Public scoreboard - private contest

### ISSUE THREAD

**Issue by jahirfiquitiva** [DOMjudge/domjudge#578]
### Description of the problem / feature request

Hello, I want to know if it's possible to show a scoreboard publicly while keeping the contest available to certain teams only.

Thanks

### Your environment
> - DOMjudge version: 7.0.0
> - Operating system / Linux distribution and version: Debian 9
> - Webserver: Apache

**Comment by thijskh** [comment]
Only teams with accounts can access DOMjudge (if you keep "allow registration" disabled). So if you only create accounts for teams that may access it, you will get a public scoreboard and only access to the team interface for said teams. Or do I not understand your use case well enough?

**Comment by jahirfiquitiva** [comment]
I have "allow registration" disabled

when I enter `/domjudge/public` I can see the scoreboards of any public contest *without* signing in.

But if the contest is not public, the scoreboard won't appear there.

I want to keep the contest private (so only selected teams participate) but also show its scoreboard publicly

**Comment by nickygerritsen** [comment]
Currently, this is not possible.
However we have heard more requests for this so we will look into this.

**Comment by jahirfiquitiva** [comment]
Great! Thank you so much @nickygerritsen
