### ISSUE TITLE
Option to allow viewing sample test case output

### ISSUE THREAD

**Issue by jahirfiquitiva** [DOMjudge/domjudge#579]
### Description of the problem / feature request

Hello

Is there a way I can enable showing the expected and actual output of the sample test cases to users, so that they can see the output differences?

Thanks in advance

### Your environment
> Include details about your installation here. 
> - DOMjudge version: 7.0.0
> - Operating system / Linux distribution and version: Debian 9
> - Webserver: Apache

**Comment by nickygerritsen** [comment]
The `show_sample_output` configuration option should do exactly this. Or is that not what you want/need?

**Comment by thijskh** [comment]
I think you are looking for the setting  show_sample_output  in the admin interface under Configuration -> Display options.

**Comment by jahirfiquitiva** [comment]
Yes, that's the right option. Thanks for the info 😀
