### ISSUE TITLE
Balloons status page not showing correct information

### ISSUE THREAD

**Issue by ss1h2a3tw** [DOMjudge/domjudge#581]
### Description of the problem / feature request
In the page `domjudge/jury/balloons`, it should show the balloon status. But this page changes every time I reload it. There are even submissions not in the current contest.  

### Your environment
Arch Linux
https://github.com/DOMjudge/domjudge/commit/84b4f56b5e014e1d3c3f164134fc8e8509b8d1e9

### Steps to reproduce
The current environment have held two contests, so maybe the case here is quite complicated. I have my database dumps and logs here. 
prod.log: https://drive.google.com/file/d/1ZV0BsCl66JCPQSJwNVOwymzhtHZ8F438/view?usp=sharing
sql: https://drive.google.com/file/d/1sd2DYfV8CbCrxOz46AW4zsgfk3aMLLNs/view?usp=sharing

**Comment by thijskh** [comment]
The balloons page currently is not scoped to the selected contest.

I believe indeed that this is not nice per se (but a legacy from the time we were single contest).

The approach is now different per page. Some will only show data for the selected contest. Others (e.g. clarifications) will show all, but with an indication of the contest it pertains to. Some are hybrid, like problems. Definitely something we need to be more consistent in.

Probably a good idea if we decide how we want to go forward in general and then clean up all pages to match.

**Comment by ss1h2a3tw** [comment]
But the page info I got here does not match the scenario if it should list all of the activated contests. They even list deactivated contests but not all the submission from that contest. And sometimes it shows nothing.

**Comment by thijskh** [comment]
Thanks. In that case we need to investigate.

**Comment by thijskh** [comment]
Small data point: the (arguably simple) cosmic ray contest had a correct list of balloons.

**Comment by thijskh** [comment]
The database dump is not complete so I cannot import it to reproduce the problem. Looking at the dump, there's a number of balloons listed for contest 6 and a small number for contest 7. Is that not what you see?

**Comment by ss1h2a3tw** [comment]
Yes, but there are not all of the submission of either contest. Here are some screenshots of the scoreboard and the balloon pages. https://imgur.com/a/46KgHi0

**Comment by thijskh** [comment]
Were you by any chance also running the `misc-tools/balloons` daemon?

**Comment by ss1h2a3tw** [comment]
No, it is not even installed in the domserver host. Should it be installed?

**Comment by ss1h2a3tw** [comment]
Ah, sorry. It **is** installed.

**Comment by thijskh** [comment]
Installed but not used?

**Comment by ss1h2a3tw** [comment]
No, it is not used. Is it necessary to run this daemon?

**Comment by thijskh** [comment]
No

**Comment by thijskh** [comment]
I'm afraid that I don't know how to reproduce this.

**Comment by ss1h2a3tw** [comment]
I'm afraid that I cant provide the full database dump, because it contains some sensitive data (and maybe some copyright issues). I will report again if this occurs again in later version.

**Comment by DerBaer0** [comment]
I might have found the problem.
https://github.com/DOMjudge/domjudge/blob/master/webapp/src/DOMJudgeBundle/Controller/Jury/BalloonController.php#L93
It appears there is a missing third parameter Join::WITH as shown here: `public function leftJoin($join, $alias, $conditionType = null, $condition = null, $indexBy = null);` (https://www.doctrine-project.org/projects/doctrine-orm/en/2.6/reference/query-builder.html)
With out this, the second part of the condition is dropped and the results appear to be quite unpredictable.
(I will create a pull request soon with an improved BalloonController which includes this fix)
