### ISSUE TITLE
500 error when submit

### ISSUE THREAD

**Issue by 2014CAIS01** [DOMjudge/domjudge#587]
### Description of the problem / feature request
> I got 500 error when I set the `sourcefiles_limit` to 1, and make some submissions.

### Your environment
> - DOMjudge 7.0.0
> - CentOS 6.5
> - Apache

### Steps to reproduce
> - Set `sourcefiles_limit` to 1
> - Start the contest and make some submissions.
```
Type error: Argument 5 passed to DOMJudgeBundle\Service\SubmissionService::submitSolution() must be of the type array, object given, called in /path/to/domjudge/domserver/webapp/src/DOMJudgeBundle/Controller/Team/SubmissionController.php on line 96
```

https://github.com/DOMjudge/domjudge/blob/master/webapp/src/DOMJudgeBundle/Controller/Team/SubmissionController.php#L94-L96

But if I change it to 2 or bigger, it can work normally.

**Comment by nickygerritsen** [comment]
Thanks for reporting. I have just fixed this and this will be in 7.0.1, which we plan to release later today or tomorrow.
