### ISSUE TITLE
Make judgedaemon not depend on all of vendor

### ISSUE THREAD

**Issue by thijskh** [DOMjudge/domjudge#591]
Judgedaemon currently require()s the autoload.php from libvendor. This means that the entire vendor dir needs to be present on all judgehosts (it's currently 160 MB of php files) and these are also all loaded by the daemon.

It seems that the judgedaemon only uses one function of this huge dependency: spyc_load() in read_metadata(). Interestingly enough the web interface does not use spyc at all.

I'd propose to make the judgedaemon much more lean by not sharing the libvendor from the web interface. Suggested ways to do this:
- Put spyc locally under the judgedir and remove from vendor dir.
- Use a different way of yaml processing (e.g. php-yaml module).
- Stop using yaml in judgedaemon.
- Give judgedaemon its own vendor/ dir.

**Comment by eldering** [comment]
I'd prefer option 1 or 2. Not sure if php-yaml is sufficient, no clue why we didn't use it before...

**Comment by thijskh** [comment]
It’s available only from stretch and up.

**Comment by eldering** [comment]
Ok. And it's also available in Ubuntu 18.04 LTS, so I'd say let's go with option 2.
