### ISSUE TITLE
Cannot start judge daemon

### ISSUE THREAD

**Issue by jizhuozhi** [DOMjudge/domjudge#592]
NOTE: If this is a _discussion starter_, you need any _installation help_ or have a _question_ on how to accomplish something,
rather send an email to our
[DOMjudge-devel mailinglist](https://www.domjudge.org/mailman/listinfo/domjudge-devel)
instead of filing an issue here.

### Description of the problem
> Cannot start judge daemon

### Your environment
> Include details about your installation here.
```shell
sudo apt-get -y install domjudge-*
```
> - DOMjudge version (e.g. 7.0.0 or a github commit hash)
7.0.1
> - Operating system / Linux distribution and version (e.g. Ubuntu 18.04)
Ubuntu 18.04.2
> - Webserver (e.g. Apache or nginx)
Apache2

### Steps to reproduce
```shell
$ sudo judgedaemon

[May 10 15:27:37.758] judgedaemon[13096]: Judge started on DOMjudge [DOMjudge/7.0.1]
[May 10 15:27:37.760] judgedaemon[13096]: executing chroot script: 'chroot-startstop.sh check'
chroot dir '/var/lib/domjudge/chroot' does not exist, run dj_create_chroot
[May 10 15:27:37.761] judgedaemon[13096]: error: chroot sanity check exited with exitcode 2

$ dj_create_chroot

dj_create_chroot：Cannot found command

$ dj_ [tab]

dj_make_chroot              dj_make_chroot_docker       dj_make_ubuntu_java_chroot  dj_run_chroot               dj_upgrade_chroot

```

### Expected behaviour
Create chroot environment  with `dj_create_chroot`

### Actual behaviour
Create chroot environment with `dj_make_chroot`

**Comment by thijskh** [comment]
Thanks for reporting. The improved werror message already been fixed :-) and will be part of 7.0.2.
