### ISSUE TITLE
genrestapicredentials should also be installed in make install-judgehost

### ISSUE THREAD

**Issue by ss1h2a3tw** [DOMjudge/domjudge#593]
### Description of the problem
In 7.0.1 release, the Makefile https://github.com/DOMjudge/domjudge/blob/master/etc/Makefile 
only installs genrestapicredentials when install-domserver, but install-judgehost should also install this utility since it will use restapi.secret too.
### Your environment
Archlinux
Domjudge 7.0.1
https://aur.archlinux.org/packages/domjudge-judgehost/

**Comment by thijskh** [comment]
Do you think so? The reasoning is that you generate this file once on the server and distribute it over the judgehosts.

**Comment by ss1h2a3tw** [comment]
Since users can still generate the password at judgehost and copy it into domserver, I think it will be better to have the utility also in the judgehost side. Just in case.

**Comment by thijskh** [comment]
Fair enough!
