### ISSUE TITLE
gensymfonyparams needs to be run after executing dj_setup_database

### ISSUE THREAD

**Issue by ss1h2a3tw** [DOMjudge/domjudge#597]
### Description of the problem
If user regenerates the dbpasswords.secret, the `webapp/app/config/parameters.yml` won't be  updated into the password in `dbpasswords.secret`. Because this script is not installed by default. Adding the content at the end to `dj_setup_databse` or adding this script into the Makefile target (letting users to run it by themselves) should solve this problem.

### Your environment
DOMjudge 7.0.1
https://aur.archlinux.org/packages/domjudge-domserver/

**Comment by meisterT** [comment]
is this still a problem after @nickygerritsen's recent changes?

**Comment by ss1h2a3tw** [comment]
Sorry, I'm still serving my military service. I will check it out after I finished it. (around November).

**Comment by eldering** [comment]
Note that since 02a8562c75e66f2fe9c30e9b2698 the DB credentials live in a single file: `etc/dbpasswords.secret`.

**Comment by thijskh** [comment]
Let’s close this since it seems reasonable to assume it’s fixed by the commit Jaap references.
