### ISSUE TITLE
domserver won't print by lpr by default

### ISSUE THREAD

**Issue by ss1h2a3tw** [DOMjudge/domjudge#603]
### Description of the problem
In the file `webapp/src/DOMJudgeBundle/Utils/Printing.php`, it will only generates the postscript file.
But in the document it said that it will print by lpr by default.

**Comment by thijskh** [comment]
Thanks for reporting! When porting it to the new framework, some debugging code was accidentally left enabled.

We could consider to make the debugging dependent on the value of DEBUG. But for now I've just solved it like it was in the past.
