### ISSUE TITLE
Modifying contest times with an invalid date format temporarily affects the coundown timer

### ISSUE THREAD

**Issue by DerBaer0** [DOMjudge/domjudge#608]
### Description of the problem
> When modifying the contest start or end date and using an incorrect format (in our case no leading zeros for the hours / minutes), the countdown timer in the top right shows the indended (new) time. However the setting is not saved and the input field shows a small error message. After a page refresh, the unmodified value is used again.

### Your environment
> last commit: 2ae1b7528498d9b1204f1459a3cd2bd0a7945f98

### Expected behaviour
> An error message on the top to inform about the invalid format used.
> The countdown should be consistent with the actual contest settings

I guess (without looking any deeper into this) that `Entity/Contest.php::validate` applies the change because it can parse this minor mistake, but some checks later strictly enforce the format and avoid the change to be persisted.

**Comment by nickygerritsen** [comment]
Might be that we reuse the form variable for the top-right as well.... Should be an easy fix :).

**Comment by thijskh** [comment]
This is indeed most likely related to the generically named `contest` Twig variable name that is used there. We've been replacing that with `current_contest` in some places already to be less conflictprone.
