### ISSUE TITLE
How to use submission api to post file? (in fetch function)

### ISSUE THREAD

**Issue by lishuyan0715** [DOMjudge/domjudge#609]
### Description of the problem
> Hello, I can submit a solution file to Domjudge by the following cURL command. However, I tried to make a fetch function to submit the solution file to Domjudge automatically. 

 curl --user "team"  -n -F "shortname=add_one" -F "langid=py3" -F "contest=test" -F "code[]=@iso_8859-1.txt" [url]/domjudge/api/submissions

I used the following code but it did not work because it cannot pass the authorization verification. (get 400: bad request)

let base64 = require("base-64");
let pwd = base64.encode("team:team");
 var data = {
            'shortname': 'add_one',
            'langid': 'py3',
            'contest': 'test',
            'code': ['https://www.w3.org/TR/PNG/iso_8859-1.txt']
        }

fetch(
  "[url]/domjudge/api/submissions",
  {
    method: "POST",
    body: data,
    headers: {
      Authorization: "Basic " + pwd,
      "Content-Type": "multipart/form-data"
    }
  }
)

Does anyone have any idea for how to use fetch to submit files in Domjudge? Thanks very much!

### Your environment
> Include details about your installation here.
> - DOMjudge version: 5.3.0
> - Operating system / Linux distribution and version :Ubuntu 16.04.6 LTS
> - Webserver: Apache

**Comment by thijskh** [comment]
As discussed on chat, `code` must not be an URL but the actual file contents.
