### ISSUE TITLE
Error on Edit Contest (Add Problem)

### ISSUE THREAD

**Issue by alessiojr** [DOMjudge/domjudge#616]
When editing a Contest, there is an error in the OneToMany relationship when adding a new ConsteProblem.

Entity of type App\Entity\ContestProblem is missing an assigned ID for field 'contest'. The identifier generation strategy for this entity requires the ID field to be populated before EntityManager#persist() is called. If you want automatically generated identifiers instead you need to adjust the metadata mapping accordingly.

On Jury/ConstestController line 442 

            $this->saveEntity($this->em, $this->eventLogService, $this->dj, $contest,
                              $contest->getCid(), false);

**Comment by nickygerritsen** [comment]
This has been fixed in ca6aadc050542f19a764511ecdc060aa5bc90156
