### ISSUE TITLE
Judgehost systemd service fails to start on Debian 10

### ISSUE THREAD

**Issue by gozzarda** [DOMjudge/domjudge#617]
NOTE: If this is a _discussion starter_, you need any _installation help_ or have a _question_ on how to accomplish something,
rather send an email to our
[DOMjudge-devel mailinglist](https://www.domjudge.org/mailman/listinfo/domjudge-devel)
instead of filing an issue here.

### Description of the problem
> systemd/init.d service for judgehost fails to start due to incorrect CGROUPDIR

### Your environment
> Include details about your installation here.
> - DOMjudge 7.0.3 (from apt)
> - Debian 10

### Steps to reproduce
> - Install `domjudge-judgehost` from apt as per https://www.domjudge.org/download and https://www.domjudge.org/docs/admin-manual-3.html#ss3.7
>    - Edit `/etc/default/grub` to enable cgroups, `update-grub`
>    - `dj_make_chroot`
>    - `reboot`
>  - `systemctl start domjudge-judgehost`

### Expected behaviour
> Judgehost starts

### Actual behaviour
> Judgehost errors with "Error: Swapaccounting support missing from cgroups. Unable to continue."

### Any other information that you want to share?
> The systemd service is generated automatically from `/etc/init.d/domjudge-judgehost`
> This file appaears to be packaged from https://github.com/DOMjudge/domjudge-packaging/blob/master/debian/domjudge-judgehost.init
> `CGROUPDIR=/cgroup` is incorrect, at least on Debian 10, and should be `/sys/fs/cgroup`
> Editing the script to change `CGROUPDIR` fixes the issue
> Note: The script appears to be generated from https://github.com/DOMjudge/domjudge/blob/master/etc/domjudge-judgehost.init.in
> Current config shows that it should be generating `/sys/fs/cgroup`: https://github.com/DOMjudge/domjudge/blob/9d056fb96cff29527413eb5dca9f2844037af0eb/configure.ac#L207
> Therefore I think we can assume this is a build issue.

**Comment by eldering** [comment]
Indeed this is bug, but with the Debian packaging, so I opened an issue there: https://github.com/DOMjudge/domjudge-packaging/issues/41 and will close this one.
