### ISSUE TITLE
Document problem import format

### ISSUE THREAD

**Issue by nickygerritsen** [DOMjudge/domjudge#622]
We support importing problems from ZIP's.

Although it is very much based on the problemtools format, we have some differences:

- [x] The filename of the ZIP is used as contestproblem shortname.
- [x] We support a `domjudge-problem.ini` file with additional settings.
- [ ] We support `@EXPECTED_RESULTS@` in the sourcecode to add additional expected results (but the original result from the directory name should be in there).
- [x] We support importing problemtext PDFs.
- [x] We support `.timelimit` which is an "unofficial feature" of problemtools.

It would be nice if we would document this somewhere.

**Comment by nickygerritsen** [comment]
Ah we do have some documentation: https://www.domjudge.org/docs/judge-manual-6.html

**Comment by eldering** [comment]
I _think_ that that documentation is not quite uptodate anymore with respect to `domjudge-problem.ini` being required, even if importing a new problem.
Also, I'm pushing for the problemtext PDFs and timelimit to be included in (an exported/compiled variant of) the problem package specification.
