### ISSUE TITLE
Judging goes into infinite loop on large testcases

### ISSUE THREAD

**Issue by RagnarGrootKoerkamp** [DOMjudge/domjudge#625]
For BAPC prelims Nijmegen has the runners run on AWS. By default these have some configuration to only allow packages up to 1MB to be sent.

Before we were aware of this, DJ was rejudging submissions on one problem in an infinite loop. Each time the judging would crash on the same testcase, the first one over 1MB.
Somehow DJ doesn't catch this error it starts rejudging the same submission from start repeatedly and goes into an infinite loop.

Ideally there'd be some way to detect that the testcase the problem (and not the runner) and disable the problem automatically.

### Environment
> - DOMjudge version 7.0.3

**Comment by nickygerritsen** [comment]
More details: this was because of a client max body size in a proxy, which is quite a common setting to forget.
We should at least do something like create an internal error for that problem or similar

**Comment by meisterT** [comment]
When I try to repro by decreasing `post_max_size` on my machine I see a different behavior:
```
[Sep 22 13:55:28.588] judgedaemon[20194]: error: Error while executing curl POST to url http://localhost/domjudge/api/judgehosts/add-judging-run/bar-0/32: http status code: 400, response: {"code":400,"message":"Body data exceeded php.ini's 'post_max_size' directive (currently set to 1k)"}
```

How exactly can I repro your problem?

**Comment by nickygerritsen** [comment]
I’m not sure what Apache has for max body size. But try it to set it pretty low

**Comment by pingiun** [comment]
Our issue was with NGINX, it was fixed when I set `client_max_body_size 2G;`. I got this error with nginx: 
```
2019/09/17 23:35:12 [error] 2508#2508: *27933 client intended to send too large body: 1333575 bytes, client: 10.1.1.86, server: _, request: "POST /api/v4/judgehosts/add-judging-run/ip-10-1-1-86-0/72 HTTP/1.1", host: "10.1.0.102"
```
