### ISSUE TITLE
More debug info on `could not run ./build` internal error

### ISSUE THREAD

**Issue by RagnarGrootKoerkamp** [DOMjudge/domjudge#626]
We had some 'internal errors' because of an output validator that didn't compile:
```
[Sep 18 10:12:27.078] judgedaemon[34]: Compiling
[Sep 18 10:12:27.129] judgedaemon[34]: fetching executable failed for compare script 'x_cmp':Could not run ./build in /opt/domjudge/judgehost/judgings/ip-10-1-1-86-0/endpoint-default/executable/x_cmp
```
It would be nice if this message could also contain the actual compilation output, as it wasn't clear to me that this indicates a compilation error.

**Comment by meisterT** [comment]
soon it will look like this:
![Screenshot from 2019-09-22 13-38-51](https://user-images.githubusercontent.com/418721/65386684-4a419180-dd3f-11e9-8994-4308ad791be3.png)
