### ISSUE TITLE
'internal error' can't be deleted after associated problem is deleted

### ISSUE THREAD

**Issue by RagnarGrootKoerkamp** [DOMjudge/domjudge#627]
After having accumulated some 'internal errors' (see #626) I repeatedly deleted the problem these were attached to and imported a new `.zip` containing all the data.

At this point clicking on the original `internal error` (for the deleted problem) gives a pages with the message:
```
Call to a member function getShortname() on null
```

It's now impossible to delete those errors via the UI. Two possible solutions:
- Propagate the delete on a problem to linked internal errors
- Be able to render the internal error page even if the associated problem was deleted

**Comment by meisterT** [comment]
I tried to repro, but for me it cascades to internal errors and it's deleted. Which DOMjudge version do you run?

**Comment by nickygerritsen** [comment]
Ah might be that I changed this there in 7.1?

**Comment by RagnarGrootKoerkamp** [comment]
This was on 7.0.3

**Comment by nickygerritsen** [comment]
a6a582d435 fixed most of this, but I did a final small change to fix everything.
