### ISSUE TITLE
Feature request: support team-specific printer-queues for printing from web interface

### ISSUE THREAD

**Issue by JobDoesburg** [DOMjudge/domjudge#629]
When using the DOMjudge Print interface to let teams print their code, this is done using `enscript` to the default printer queue of the (cups) system. In a setup where teams are located in different rooms, it might be useful to send the print jobs to the printer that is physically located the nearest to that team. This can be realized quite easily by specifying the `--printer` option of `enscript`. Teams or users should get an extra field 'printername' (only if printing is enabled) and when that user/team tries to print, that value should be passed on to `enscript` (similar to how the team location is set as header option of enscript).

For documentation: The printer name should match a printing queue setup on the system (either locally, or at an external cups server by specifying `ServerName <hostname-of-external-cups-server>` in /etc/cups/client.conf ).

**Comment by eldering** [comment]
I'm not sure we should implement this: in the past we've seen that printing depends very much on the local system configuration. We can't adapt to all possible circumstances, and if you need more flexibility, then it might be better to modify the code or directly print via the system.

**Comment by thijskh** [comment]
Indeed, would it not be better to implement this in a script that DOMjudge calls when printing? Then you have turing complete configuration of all printing desires.

**Comment by nickygerritsen** [comment]
I like the idea of calling a script. We could do something similar to `BALLOON_CMD` or, IMHO even better, make it a configuration option using the configuration table, where you can set some predefined arguments like `[team]`, `[language]` etc?

**Comment by JobDoesburg** [comment]
I agree that it is doubtful wether this should belong in DOMjudge. My reasoning was that by defining print queues, you would make the print feature very versatile and outsource all other things you want to set to CUPS. But calling a script also sounds good.

**Comment by eldering** [comment]
I think we used to have printing as a script but for some reason migrated it to the current situation. This printing feature has always been there as a backup/last resort option in the case where using the normal system route for printing wasn't available.

**Comment by thijskh** [comment]
Printing via OS remains preferred, also because it integrates with your editor etc

**Comment by nickygerritsen** [comment]
Yes but I think that if we do the script + config option, it is not that much effort to implement and would help people who do not want to change the code (or use or Docker images).

We can even change the `enable_printing` config option to a string, where empty means disabled.
