### ISSUE TITLE
university logos on the scoreboard

### ISSUE THREAD

**Issue by asdcxsd** [DOMjudge/domjudge#634]
I read 
Fixed with commit [6c9d9a9](https://github.com/DOMjudge/domjudge/commit/6c9d9a91cb1d6ff7edbc76d2fe5c8062d46951ba). but I don't find  "lib/www/scoreboard.php"

**Comment by nickygerritsen** [comment]
That is pretty old code. Place the images in `webapp/web/images/affiliations/` and call them `<id>.png` with `<id>` being the affiliation ID

**Comment by asdcxsd** [comment]
I rename file image  .png to  U-*.png so it showed in info of affiliations.
But it don't show
- Scoreboard  <http://27.71.225.85/public>
- <http://27.71.225.85/public/problems>


Vào Th 4, 9 thg 10, 2019 vào lúc 23:10 Nicky Gerritsen <
notifications@github.com> đã viết:

**Comment by nickygerritsen** [comment]
Did you enable "show_affiliation_logos" on the Configuration settings admin page?

**Comment by meisterT** [comment]
For future readers: since d9988e099b3c6e5dfd60d77129fb654c1295af92 the correct path is `webapp/public/images/affiliations`.
