### ISSUE TITLE
Balloon Status page returns 500 Internal Server Error after upgrade from 5.1.3 to 7.0.3

### ISSUE THREAD

**Issue by jason-klein** [DOMjudge/domjudge#635]
### Description of the problem
> The Balloon Status page returns a 500 error after upgrading from DOMjudge 5.1.3 to 7.0.3:
> 
> The error is being caused by code in `Controller/Jury/BalloonController.php` that is attempting to detect the "first solve" for a problem:
> `elseif (in_array($balloonId, $AWARD_BALLOONS['problem'][$balloonsData['probid']], true))`
>
> This code assumes `$AWARD_BALLOONS['problem'][$balloonsData['probid']]` will always contain an array. I confirmed `$balloonsData['probid']` always contains an integer, but there are many cases in our environment where `$AWARD_BALLOONS['problem'][$balloonsData['probid']]` is empty.
> 
> I was able to avoid the 500 error by updating the code as follows. I will submit a pull request.
> `} elseif (is_array($AWARD_BALLOONS['problem'][$balloonsData['probid']])
                   && in_array($balloonId, $AWARD_BALLOONS['problem'][$balloonsData['probid']], true)) {`
>
> It is unclear exactly what causes this inconsistent state. Perhaps enabling balloons on a contest after submissions were already received?
> Refreshing scoreboard cache clears up this issue, but you must activate all prior contests, refresh scoreboard cache, then deactivate all the prior contests.

### Your environment
> - DOMjudge version: 7.0.3
> - Operating system / Linux distribution and version: Debian 9.11
> - Webserver: Apache

### Steps to reproduce
> - Use DOMjudge 5.1.3 in production
> - Upgrade from DOMjudge 5.1.3 to DOMjudge 7.0.3

### Expected behaviour
> Page should display Balloon Status

### Actual behaviour
> Page displays the following 500 error:
> 
> 500 Internal Server Error
> Sorry, an error has occured: Internal Server Error.
> Please contact a staff member for assistance.
> Type error: in_array() expects parameter 2 to be array, null given

### Any other information that you want to share?
> Here is a screenshot of the error
![domjudge-balloons-500](https://user-images.githubusercontent.com/5200725/66717571-2ef6fe80-eda0-11e9-82c7-a5b329b5dc4d.png)

**Comment by thijskh** [comment]
Yes, this is likely from using older contest/cache data. So we should definitely be able to accept such situations.

**Comment by thijskh** [comment]
What we also seem to be missing is filtering the list for only active contests. We have that information available right now. But likely the more structural solution is to fix #599
