### ISSUE TITLE
Rejudging should select all submissions not only the last one

### ISSUE THREAD

**Issue by baierjan** [DOMjudge/domjudge#641]
#### Actual behaviour
1. Team submit a wrong submission for a problem
2. Team submit a correct submission for the same problem
3. There is a problem with a test case, the test case is changed
4. Rejudging is being made (with all verdicts)
5. Only the correct submission is rejudged (and is still correct)

#### Expected behaviour
The wrong submission will be rejudged as well, as it will be correct and the team will not have the penalization for first attempt.

### Your environment
- DOMjudge 7.1.0
- Debian 10 / Apache 2.4

**Comment by meisterT** [comment]
From which page did you trigger the rejudging? From the problem page or the rejudging one?

**Comment by meisterT** [comment]
I tried from both of those pages and cannot repro this. It always rejudged all submissions that were in scope (e.g. all from a problem). It might be easy to miss since the default filter on the rejudging page shows only the diff.

Are you able to repro this behavior?

**Comment by meisterT** [comment]
There's one more thing which could have happened here: if you do select multiple submissions to rejudge and a subset of those is part of another *active* rejudge, they would be silently skipped.
I'll try to add a flash notification in that case.

**Comment by baierjan** [comment]
Thank your for looking into this, I did it through the rejudging page. I will try to reproduce the issue as soon as I will not need the current contest data anymore.

**Comment by meisterT** [comment]
Jan, did you have the time to try a repro the issue?

**Comment by baierjan** [comment]
I tried to reproduce the issue with a simple setup and if the rejudging is created through the main menu, everything is working as expected. Apparently, the setup to recreate is more complicated and it could be a race-condition of some sort. Will re-open if the issue reappears.
