### ISSUE TITLE
First solve a problem after public scoreboard frozen.

### ISSUE THREAD

**Issue by 2014CAIS01** [DOMjudge/domjudge#644]
If a team solve a problem after public scoreboard frozen, the summary will show 0 min like this.
(In ICPC Aisa Nanjing 2019, domjudge 7.0.4)
![image](https://user-images.githubusercontent.com/22931465/67637343-b2722d00-f914-11e9-8e6e-241349d16e3f.png)

**Comment by eldering** [comment]
Is that the public or jury summary?

Also, assuming the public summary, what would you expect? We should not print any time ther as that would reveal information. The best alternative would be something like `?`

**Comment by 2014CAIS01** [comment]
This is public summary,  so we expect n/a, but it shows 0min after a team first solve this problem!

**Comment by nickygerritsen** [comment]
I’d say indeed ? Or n/a would be better. Even more so I suspect that we now *only* print 0 if it is actually solved in the freeze, leaking info

**Comment by xzm2000** [comment]
public summary.

I saw the scoreboard at that time. Personally, I think it should be `n/a` because if there is not any person solve this problem, it will show `n/a`.

![image](https://user-images.githubusercontent.com/42742291/67638288-b3f42300-f91d-11e9-876c-290ef025fc96.png)

like this image (it's from this contest before G was solved), we can easily see the difference

**Comment by nickygerritsen** [comment]
Indeed we showed `0` when it was first solved in the freeze. Now it shows N/A again :)

**Comment by eldering** [comment]
Note that it will now also show `n/a` when someone solved the problem already, but another earlier *correct* submission is still pending; this is correct IMO. OTOH, if an earlier incorrect submission is still pending verification, it shows a first to solve time; here it should also show `n/a`

**Comment by nickygerritsen** [comment]
@thijskh could you look at that case?
