### ISSUE TITLE
Changing verified required config may lose some event-feed.

### ISSUE THREAD

**Issue by 2014CAIS01** [DOMjudge/domjudge#645]
In an official contest, at the first we want to use `verification_required` config to ensure every problem is ok and every submission is ok. But after one or two hour, some easy problems are solved by many team, and we want to judge automaticaly, so we close `verification_required`, and refresh the rank cache. But, the submissions juding finished but unverified at that moment haven't update the event, (CDS shows the related submissions pending). This issue may affect some tools like ICPC resolver or CDS using event-feed.(Domjudge 7.0.4)

In addation, I also suggest that `verification_required` can be set for a specific problem.

**Comment by eldering** [comment]
Indeed, that's an edge case we have overlooked.

**Comment by eldering** [comment]
For the feature request: it's better to report that as a separate issue. I think that's low priority though.
