### ISSUE TITLE
Single user / individual contest mode

### ISSUE THREAD

**Issue by yudhaprimadiansyah** [DOMjudge/domjudge#647]
Can i create single user competition which has no team for each user? , Sorry to ask this , i cant find any guides about this and i new to deploy this cool platform

**Comment by nickygerritsen** [comment]
We require a team for each user since that is how our whole structure is set up. Of course you van just automatically create a user for each team

**Comment by yudhaprimadiansyah** [comment]
Hmm , i thought that there was a way to create per-user competition system, but it is ok, thankss for answerr 🙏🙏👍👍👍
