### ISSUE TITLE
Implement team display name

### ISSUE THREAD

**Issue by nickygerritsen** [DOMjudge/domjudge#651]
During a (semi) recent CLICS call we decided to have an additional field on a team, called "display name". If that field is filled, that value should be used to instead of the team name on the scoreboard, etc.

We should think about how we want to implement this. IMHO we have two options:

* Just not implement it and hope / assume the CDS will add it to events before passing it on to downstream clients. DOMjudge can display both team name and affiliation name on the scoreboard so perhaps we don't really need the team display name ourselves? But then we do require the CDS to do stuff
* Add a DB field display_name to team and fill it with the display name if desired. Add two functions to the `Team` entity, `getDisplayName` which returns this field and another function (... no clue what to call it) that returns `getDisplayName() ?? getName()` (we need the former because otherwise when you edit the team you have no way of knowing whether it was null or not. And then also use that new function instead of `team->getName()` everywhere.

Do note that we don't know yet how the `teams2.tsv` file will be modified for this field, but we can probably assume there will be an extra field.

Thoughts welcome.

**Comment by eldering** [comment]
I don't think we need that other function that returns `getDisplayName() ?? getName()`. We've said that `display_name` should be optional and nullable, so we can simply only output it if it's not null. Any client can do the `getDisplayName() ?? getName()` logic.

**Comment by nickygerritsen** [comment]
> Edit: wait, we do need it for our own web pages...

Yes otherwise we need to do the `??` thing everytime... Which is not ideal.

**Comment by thijskh** [comment]
Why would we need to store it? If a team has a display_name we import that name otherwise the normal name. Or are there cases where we still need the full name? (Perhaps the actual functional requirement is missing from this issue.)

**Comment by eldering** [comment]
This has still not completely crystallized, but the rough idea at the WFs would be to assign to a team as display name the university (possibly with some suffix if a university has multiple teams). If we keep the original team names too, then that data can simply be passed on via CDS to ICPC-live and they'd be happy and we all have consistent data.

**Comment by nickygerritsen** [comment]
Yes indeed. Clients needing the original team name is the biggest reason to not overwrite it

**Comment by eldering** [comment]
Ok, so given that the specification is agreed on now, we probably need an extra column to store this.
I think that for all practical purposes, we should show `$display_name ?? $name` in the UI, except for very specific pages, such as the team page in the jury interface.
And, indeed, we should have a separate function that returns `$display_name ?? $name` (ugh!), something like "effective name"? (I know the CDS uses "actual name", but not a huge fan of that.)

**Comment by nickygerritsen** [comment]
I like effective more than actual.
And this will be a big thing I guess, since even Jetbrains refactoring will surely miss some $team->getName() changes :(
