### ISSUE TITLE
Cancelling a rejudgement can give 500

### ISSUE THREAD

**Issue by austrin** [DOMjudge/domjudge#656]
![20191115_200105](https://user-images.githubusercontent.com/8777673/68995060-e85a5f80-0889-11ea-816d-a437366f4159.jpg)

**Comment by eldering** [comment]
Maybe related: after a couple of rejudgings of submission 2331, I saw this:
```
Cancel rejudging r38
s2331, s2331, s2331, s2331, s2331, s2331,

Rejudging r38 canceled in 1.44 seconds.
```
It seems likely that we attempt to process each submission for the number of judgings it has.
