### ISSUE TITLE
Add index to events table to speed up lookup / insert

### ISSUE THREAD

**Issue by nickygerritsen** [DOMjudge/domjudge#662]
We check if an event with the same `cid, endpointtype, endpointid` already exists before inserting a new one, to check if we need to do a `create` or `update`. However we do not have an index on these fields, which makes that query very slow for bigger event tables.

We should add such an index.

**Comment by eldering** [comment]
Sounds good to me. There's already an index `cid`, so we can extend it.

**Comment by nickygerritsen** [comment]
> Sounds good to me. There's already an index `cid`, so we can extend it.

@eldering do you still want to name it `cid`? I can do this tonight :)
