### ISSUE TITLE
First solve a problem after public scoreboard frozen will show on team page

### ISSUE THREAD

**Issue by xzm2000** [DOMjudge/domjudge#666]
domjudge version: 7.1.1

The issue [#644](https://github.com/DOMjudge/domjudge/issues/644) said that if a team solve a problem after public scoreboard frozen, the summary will show 0 min and I found that the team page will tell him he is the FB like this (We frozen the public scoreboard after 30 mins/10:20).

![JTLUS%9LT3M{ G7XQWC MS](https://user-images.githubusercontent.com/42742291/69300813-4783ef80-0c4f-11ea-949a-8482f04a47f5.png)

**Comment by nickygerritsen** [comment]
Indeed this seems like another FTS-related bug. We will look into this.
