### ISSUE TITLE
Validators

### ISSUE THREAD

**Issue by eldering** [DOMjudge/domjudge#67]
The CCS must support problem-specific Output validators as described in the problem format standard. As described there, the output validators must adhere to the output validator standard.

**Comment by meisterT** [comment]
Implemented in 325b1b12246d70687384fd1a00210e8bff53aec6, 1e1bde548fbb2333423e07e10a844aaafbd2a715, 7d6cbbcbbe341945515b1134a91293e49f7196f1 and 914d3da1c11421359e0fdc38740f29a5f5e1f5d0.
