### ISSUE TITLE
Current install process is broken/fragile.

### ISSUE THREAD

**Issue by eldering** [DOMjudge/domjudge#673]
We need to improve the install process. Maintainer-mode install works quite ok, but a normal install has various problems:

- Permissions are not properly set on cache/log directories  #650
- DB passwords are stored in multiple places (`etc/dbpasswords.secret`, `webapp/.env.local*` and possibly in Symfony cache), which makes updating it break an installation. See also #670 
- We should not rely on composer commands like `dump-env` at user install time.

**Comment by nickygerritsen** [comment]
@eldering I think only the first point of this issue still remains right?

**Comment by eldering** [comment]
Indeed, I think so.

**Comment by eldering** [comment]
Closing this as the only remaining point is already tracked in #630
