### ISSUE TITLE
Balloonfilter not working

### ISSUE THREAD

**Issue by DerBaer0** [DOMjudge/domjudge#692]
The Balloon-filter is not working because it applies a filter using the affiliation id (e.g. 4), but the data value for the balloons are set to the shortcode of the affiliation (e.g. FAU).

**Comment by eldering** [comment]
For which version is this?

**Comment by DerBaer0** [comment]
ah sorry. This is for commit [f40f4fd47e99d2390a1bf4d19892e9b56ffe1ce4](https://github.com/DOMjudge/domjudge/commit/f40f4fd47e99d2390a1bf4d19892e9b56ffe1ce4)
