### ISSUE TITLE
'gen_all_secrets' not found

### ISSUE THREAD

**Issue by yanhaozhe** [DOMjudge/domjudge#696]
When I am setting up the data base, the following information appears.

bin/dj_setup_database: 264: bin/dj_setup_database: /home/yhz/domjudge/domserver/etc/gen_all_secrets: not found

**Comment by nickygerritsen** [comment]
I had the same problem and reported it on Slack before. I think you can skip that step from the documentation for now and we will look into it.

**Comment by eldering** [comment]
See the commit for a fix: you can copy all `etc/gen*` scripts from the source tree into the `etc` directory of the domserver installation.
