### ISSUE TITLE
500 Internal Error after finishing all installion of domserver

### ISSUE THREAD

**Issue by yanhaozhe** [DOMjudge/domjudge#697]
After finishing all process, I found I cannot enter the login page, and it shows 500 internal error.
I suspect it caused by the permissions. When I set the owner and group to 'www-data' and it works well. I don't know if it is secure to do those settings.

The image shows the permission of domserver/webapp folder. The left one use v7.1.1 and works well while the right one met 500 internal error.

![image](https://user-images.githubusercontent.com/54829520/74536561-4bd05800-4f73-11ea-9cd8-c88080f92240.png)

**Comment by nickygerritsen** [comment]
Yep this is a known issue, see #650 .

For now this should fix it:

```
chown -R www-data:www-data webapp/var/{cache,log}
```

**Comment by meisterT** [comment]
Closing in favor of #650
