### ISSUE TITLE
404 error for click 'DOMjudge Manual' in DOMJudge Jury Interface

### ISSUE THREAD

**Issue by yanhaozhe** [DOMjudge/domjudge#698]
http://xx.xx.xx.xx/domjudge/doc/manual/build/html/index.html?v=7.2.0

It will report a 404 error after clicking the highlighted hyperlink.

![image](https://user-images.githubusercontent.com/54829520/74539036-4b868b80-4f78-11ea-8313-9d7c7f6957c6.png)

**Comment by nickygerritsen** [comment]
Did you run `make docs && sudo make install-docs`?

We might want to hide the link if the docs are not there perhaps.

**Comment by yanhaozhe** [comment]
> Did you run `make docs && sudo make install-docs`?
> 
> We might want to hide the link if the docs are not there perhaps.

Yes. And I can open the 'team manual' link succefully.

**Comment by nickygerritsen** [comment]
> > Did you run `make docs && sudo make install-docs`?
> > We might want to hide the link if the docs are not there perhaps.
> 
> Yes. And I can open the 'team manual' link succefully.

Hmmmm, can you check what is in <domjudgedir>/doc/manual?
Did the makefile give any warnings or errors?

**Comment by yanhaozhe** [comment]
OK. I'll have a try.

I found another problem when installing the judge host, could you help me?

I separate the domserver and domjudge.
The internal IP is:
server: 172.18.202.41
judgehost: 172.18.202.42

Should I configure the judgehost with "./configure --prefix=$HOME/domjudge --with-baseurl=172.18.202.41/" ? 

And after I configured it, I found the following error. However, I have already copied the restapi.sceret to 'judgehost/etc/restapi.secret' 

_
/usr/bin/install -c -m 0644 -o yhz -m 0700 -d /home/yhz/domjudge/judgehost/log
/usr/bin/install -c -m 0644 -o yhz -m 0700 -d /home/yhz/domjudge/judgehost/run
/usr/bin/install -c -m 0644 -o yhz -m 0711 -d /home/yhz/domjudge/judgehost/judgings
/usr/bin/install -c -m 0644 -o yhz -m 0700 -d /home/yhz/domjudge/judgehost/tmp
/usr/bin/install -c -m 0644 -o yhz -m 0600 -t /home/yhz/domjudge/judgehost/etc \
        etc/restapi.secret
/usr/bin/install: cannot stat 'etc/restapi.secret': No such file or directory
_

**Comment by nickygerritsen** [comment]
The base URL looks OK. You can copy the restapi.secret to the directory where you run configure, that should work?

**Comment by yanhaozhe** [comment]
No, it still does not work. 

The error log shows 
_
/usr/bin/install -c -m 0644 -o yhz -m 0600 -t /home/yhz/domjudge/judgehost/etc \
        etc/restapi.secret
_

The 'etc' appears twice, is it a mistyping?

**Comment by yanhaozhe** [comment]
I solved it. I put it in the /etc folder and it works correcly.

**Comment by eldering** [comment]
> No, it still does not work.
> 
> The error log shows
> _
> /usr/bin/install -c -m 0644 -o yhz -m 0600 -t /home/yhz/domjudge/judgehost/etc
> etc/restapi.secret
> _

What is the precise error it showed?

> The 'etc' appears twice, is it a mistyping?

No, that's not a typo: this is executed from the base of the source tree and it copies the file `etc/restapi.secret` from the source tree into the judgehost installation tree.

Could you tell precisely what you did to solve it? Copy the file from the source tree to which `etc` directory?

**Comment by yanhaozhe** [comment]
> > No, it still does not work.
> > The error log shows
> > _
> > /usr/bin/install -c -m 0644 -o yhz -m 0600 -t /home/yhz/domjudge/judgehost/etc
> > etc/restapi.secret
> > _
> 
> What is the precise error it showed?
> 
> > The 'etc' appears twice, is it a mistyping?
> 
> No, that's not a typo: this is executed from the base of the source tree and it copies the file `etc/restapi.secret` from the source tree into the judgehost installation tree.
> 
> Could you tell precisely what you did to solve it? Copy the file from the source tree to which `etc` directory?

Yes. Thanks.
I directly put in the /etc folder under where I executed ./confirgure

By the way, I still cannot view the manual under doc folder because all the owners are root.
![image](https://user-images.githubusercontent.com/54829520/74582967-4586be00-4ffd-11ea-8558-dade2d5e5839.png)


Another question, how does "--with-baseurl" argument work? Do I need to put the IP address of domserver if I want to set up another judgehost?

**Comment by eldering** [comment]
> > Could you tell precisely what you did to solve it? Copy the file from the source tree to which `etc` directory?
> 
> Yes. Thanks.
> I directly put in the /etc folder under where I executed ./confirgure
> 
> By the way, I still cannot view the manual under doc folder because all the owners are root.
> ![image](https://user-images.githubusercontent.com/54829520/74582967-4586be00-4ffd-11ea-8558-dade2d5e5839.png)

That in itself doesn't seem to be the problem because the files are world-readable. Can you show the symlink (with target) from the installation directory, and check that all the directories in the complete path leading to the docs are world-readable and accessible?

> Another question, how does "--with-baseurl" argument work? Do I need to put the IP address of domserver if I want to set up another judgehost?

You should specify a URL, so something of the form `https://example.com/domjudge` and you can use an IP address in there, but if you have a hostname, then that's preferable. This is not needed for setting up another judgehost (for that, just edit restapi.secret on that judgehost to point to the domserver), but for configuring the submit client and generated documentation correctly.

**Comment by thijskh** [comment]
Please don’t mix different questions in one issue. I’m now lost on where we are with the original issue. Is it still present?
