### ISSUE TITLE
Issues with restore_sources2db

### ISSUE THREAD

**Issue by thijskh** [DOMjudge/domjudge#701]
There are some issues with restore_sources2db which makes it currently not work:
* submitdir does not store entry point information, making it not possible to reliably reconstruct the db from the source files;
* it uses second precision for the timestamps, this should be microsecond (not natively supported in PHP, need to call `stat`);
* it tries to query a hardcoded "domjudge-test" database (could maybe be addressed by just removing legacy code).

But given these problems that have existed for a while now, it begs the question of whether we should fix all of them or rather drop the facility. The first one seems hardest to fix.

**Comment by eldering** [comment]
I think we can indeed drop this (and also `save_sources2file`) and replace it with import/export functionality to the contest archive format (which is near finalized).
