### ISSUE TITLE
Importing submissions should skip known events

### ISSUE THREAD

**Issue by meisterT** [DOMjudge/domjudge#704]
While importing data via an event feed we should have a way to skip already known events.
Assume a scenario where the feed reading stops because of a network problem.
Otherwise it takes a long time until we are back to the point where feed reading crashed.

**Comment by nickygerritsen** [comment]
We have a flag to start at a certain event right?

**Comment by meisterT** [comment]
That's correct, we have `--since-event=SINCE-EVENT`.

What do you think about making this default to the last imported event?

**Comment by nickygerritsen** [comment]
Something like that might indeed be nice, but we do need to store it somewhere. Maybe when we have added that config file that specifies the url put it there as well, I.e. update the config file while reading

**Comment by meisterT** [comment]
Don't we have external event IDs somewhere in our DB?

**Comment by nickygerritsen** [comment]
I don’t think we do. Or I have totally forgotten we do

**Comment by eldering** [comment]
What about storing the processed event feed somewhere in raw original form? Per line that is processed we can just append it to a local log file on disk. When the import script restarts it can deduce at which event ID it has to restart importing.
This way it can also be used to diagnose issues after the fact and e.g. check if the event feed changed retro-actively.
