### ISSUE TITLE
Add an option to import from a CDS with a self-signed certificate

### ISSUE THREAD

**Issue by meisterT** [DOMjudge/domjudge#705]
While this should not be default, we probably want to add the equivalent of curl's `-k` option.

Probably we only have to change the http client options like this when the option is passed.
```
-        $client = HttpClient::create();
+       $client = HttpClient::create([
+               'verify_peer' => False,
+               'verify_host' => False,
+       ]);
```

**Comment by thijskh** [comment]
Or just add its EE cert to the local trust store?

**Comment by thijskh** [comment]
Or document how to add its EE cert to the local trust store?

**Comment by meisterT** [comment]
If you know how to do it, then this would also work.

**Comment by thijskh** [comment]
Do we actually _have_ any documentation on CDS import?

**Comment by nickygerritsen** [comment]
This is actually not really a 'CDS import' but more of a 'reading feed from some primary source'. The only documentation we have is the `--help` of the command (which contains at least some stuff). We could add a documentation page somewhere, but note that I might change the arguments of the command based on what we discuss later today.
