### ISSUE TITLE
Scoring Data Generation

### ISSUE THREAD

**Issue by eldering** [DOMjudge/domjudge#71]
The CCS must be capable of automatically generating up-to-date scoring data according to the following: 

 1. For purposes of scoring, the contest time of a submission is the number of minutes elapsed from the beginning of the contest when the submission was made, skipping removed time intervals if specified (see Removing Time Intervals). This is rounded down to the nearest minute, so 59.99 seconds is 0 minutes.
 1. The contest time that a team solved a problem is the contest time of the team's first accepted submission to that problem.
 1. A team's penalty time on a problem is the contest time that the team solved the problem, plus penaltytime (from contest.yaml) minutes for each previous rejected run by that team on that problem, or 0 if the team has not solved the problem.
 1. A team's total penalty time is the sum of the penalty times for all problems plus any judge added penalty time.
 1. A team's last accepted submission is the contest time of the problem that the team solved last.
 1. The position of a team is determined by sorting the teams by number of problems solved (descending), total penalty time (ascending), last accepted submission (ascending).
 1. The rank of a team is the determined as follows:
   1. For teams in positions up to and including 12+B, the rank equals the position (B is provided when finalizing the contest, the default value is 0).
   1. Teams that solved fewer problems than the median team are not ranked at all.
   1. For the remaining teams, the rank is determined by sorting the teams by number of problems solved (descending). 
 1. The award of a team is:
   1. gold if rank is 1 through 4.
   1. silver if rank is 5 through 8.
   1. bronze if rank is 9 through 12+B.
   1. ranked if rank is not 1 through 12+B but the team is ranked.
   1. honorable otherwise. 

When a number of teams are tied for the same position/rank, they all occupy the same position/rank and a suitable number of subsequent positions/ranks are left empty. For instance, if four teams are tied for 17th position, they are all in 17th position and positions 18, 19 and 20 are unoccupied. 

A submission is pending judgement if it has no judgement or if the judgement is Judging System Error. Pending judgements have no effect on scoring.

Runs marked as Deleted have no effect on scoring.

**Comment by meisterT** [comment]
Implemented in 2d80de4d40ffeeea809528efeba245ecd7a8459d
