### ISSUE TITLE
Add a download submission button for teams as an option 

### ISSUE THREAD

**Issue by ilyasELBANI** [DOMjudge/domjudge#714]
Understanding the security reasons why this is not already added. It would be great if there was an option to allow submission downloads

**Comment by thijskh** [comment]
I do not disagree with this. A pull request would be welcome. It should be a switchable option to allow it or not.

**Comment by meisterT** [comment]
I know that this is not really what was asked for here, but I thought we could store the submissions that were made with the submit client in a directory under `~/.cache` including some metadata. That would help answering most questions like "I didn't change anything between my two last submissions and only the second was accepted" without the downside of opening up an attack vector.

**Comment by nickygerritsen** [comment]
But that doesn’t fix it for browser submissions. I’d say let’s just add it as an option

**Comment by eldering** [comment]
Note that there is already `~/.submit` for the submit client.
