### ISSUE TITLE
Wrong sed script in judge/compile.sh

### ISSUE THREAD

**Issue by david-perez** [DOMjudge/domjudge#724]
[This](https://github.com/DOMjudge/domjudge/blob/master/judge/compile.sh#L173) sed script fails because it's not using parentheses to capture into `\1`. 

```
sed: -e expression #1, char 39: invalid reference \1 on `s' command's RHS
```

The contents of `compile.tmp` were

```
internal-error: total memory 71679 KiB <= 65536 + 65536 = 131072 KiB reserved for JVM and stack leaves none for heap.
```

I had set memory limit for a problem to 71679 KiB, which apparently I can't because the JVM, according to `sql/files/defaultdata/java_javac_detect/run`, needs at least 131072 KiB (?)

I'd happily submit a patch fixing the sed script, but I don't know what its intention is. I guess you wanted to tack on ` compile script:` after `internal-error:`? i.e. something like this maybe?

```
grep -i '^internal-error: ' compile.tmp | sed 's/^\(internal-error:\)/\1 compile script:/i'
```

**Comment by thijskh** [comment]
It seems so indeed. Wonder why it would not use the intended static string instead of backreferences then. @eldering?

**Comment by eldering** [comment]
Indeed, that was the intention. I think I used the back-reference to prevent a bit of string duplication, but I'm happy to admit that could be considered over-engineering.
