### ISSUE TITLE
Per-contest scoreboard disable

### ISSUE THREAD

**Issue by felixjingga** [DOMjudge/domjudge#727]
As the title, how about a feature that can disable the scoreboard from teams (only admin can see the scoreboard) per contest?

The workaround is to set the freeze time to start time. But it will serve you with the "big scoreboard" instead of a notice like "Scoreboard viewing is disabled for this contest"

**Comment by eldering** [comment]
I'm a little hesitant to add arbitrary new features without a good reason: especially if such features are rarely used, that will easily lead to bugs when we overlook interaction of them with other code changes or features.
So can you explain the reason and when and how often this would be used?

**Comment by felixjingga** [comment]
1. can be used in an internal contest that results can't be known in advanced for users.
2. for IOI simulation contest. (In IOI, the students can't see the scoreboard)
3. Some contest might prefer to use custom built scoreboard via the API

**Comment by thijskh** [comment]
So if I understand it, it would work the same as a permanently frozen scoreboard. That is, no rank info on team score row, and also no data in the API for teams. I can see some use cases but I wonder how invasive such a change would be. Perhaps a proposed PR would give some insight into the impact.

**Comment by mvr320** [comment]
As discussed in chat, when one alters the:
<DOMjudge installdir>/domserver/webapp/src/DOMJudgeBundle/Resources/views/public/scoreboard.html.twig, one can outcomment the parts which display the scoreboard.

this would not fix per contest, but probably having 1 contest where you want the public and at the same time having the other one is probably happening so little

**Comment by eldering** [comment]
Closing this as there are alternative workarounds (full freeze or disable scoreboard page code) and we think the trade-off against feature creep is not worth it.
