### ISSUE TITLE
Replace creating non-rejudging rejudge with auto-applying rejudging

### ISSUE THREAD

**Issue by nickygerritsen** [DOMjudge/domjudge#732]
Currently there is an option to rejudge a submission (or a set of them) without creating a full blown rejudging.

This complicates the backend code. If we change this to actually always create a full blown rejudging but automatically apply it, this might simplify things. We can either apply each submission after it finished or apply everything at the end, we should decide on one of these.

**Comment by mathew947** [comment]
mathew947

**Comment by ffreeman61** [comment]
Great
