### ISSUE TITLE
Compile script java_java_detect broken on rename+rejudge

### ISSUE THREAD

**Issue by eldering** [DOMjudge/domjudge#735]
When you submit a Java source that requires a file rename to match a publicly declared class (for example https://github.com/DOMjudge/domjudge/blob/master/tests/test-classname.java), then the rename is done and then the *renamed* entry point is stored with the submission. When the submission is rejudged, this renamed entry point is passed to the compile script. This will not perform a rename anymore, but simply error out.

The simple fix of trying to rename again in the compile script is not the correct one, since if we pass this to any downstream/shadow system, then this will still fail. Effectively, we changed the submission and should store the renamed file. Ugh.

**Comment by meisterT** [comment]
So basically, if you submit invalid java code we try to fix it for your and then later get in trouble for it, right? Can we just don't try to be smart?

**Comment by eldering** [comment]
Yes, I think that makes sense. I think this is still from before we stored the file names of submissions. If you submit public Java classes, you should name them correctly.
