### ISSUE TITLE
Event Feed

### ISSUE THREAD

**Issue by eldering** [DOMjudge/domjudge#74]
It is a requirement that the CCS provide an external event feed. This means that the CCS must have a mechanism for external processes to connect to the CCS and obtain dynamic real-time updates regarding the current state of the contest. The CCS event feed mechanism must comply with the Event Feed specification.

**Comment by eldering** [comment]
The event feed has now been integrated into the master branch as well, see 26e6b5a57bf91305d13619337282ce9738119d0f

**Comment by meisterT** [comment]
We should create a proper event feed streaming solution as a separate program.

**Comment by eldering** [comment]
Closing this issue as we're moving towards a new [Contest API](https://clics.ecs.baylor.edu/index.php/Contest_API) that includes a NDJSON `event-feed` endpoint.
