### ISSUE TITLE
Final Results Data File

### ISSUE THREAD

**Issue by eldering** [DOMjudge/domjudge#76]
The final results lists the ranked teams sorted by rank (with alphabetical order on team name as tie breaker), followed by the unranked teams (sorted alphabetically by team name). It includes for each ranked team their rank and:

 1. The number of problems solved, if the team is ranked (i.e., if they solved more than the median number of problems).
 1. The total penalty time and time of last accepted submission, if the team is in rank 1 through 12+B (where B is as defined in Scoring Data Generation). 

The CCS must be capable of generating an external file containing the final results of the World Finals contest. The format of this file must be as defined in the results.tsv.

**Comment by meisterT** [comment]
implemented in 2d80de4d40ffeeea809528efeba245ecd7a8459d
