### ISSUE TITLE
Standard Compliance Document

### ISSUE THREAD

**Issue by eldering** [DOMjudge/domjudge#79]
The CCS must include a Standard Compliance document in PDF format, that for each requirement (referencing by requirement number) in this standard document confirms that the CCS conforms and explains how the functionality is implemented.

**Comment by thijskh** [comment]
This just seems busywork now. There's no party currently interested in being on the receiving end of such a document. I propose we close the issue as there's no useful action at this point. We can reopen it/create the document when there's a need for it.
