### ISSUE TITLE
Team manual: DOMjudge logo layout issue

### ISSUE THREAD

**Issue by tom93** [DOMjudge/domjudge#799]
The DOMjudge logo breaks the layout in the HTML version of the team manual (doc/manual/build/html/team.html), with a random blank area:

![team-manual-html-logo](https://user-images.githubusercontent.com/5887562/82068170-c43ae680-9725-11ea-91e1-c4602e296130.png)

<sup>Web browser: Firefox</sup>

The PDF version isn't great either because there no text wrapping, but it's not as bad:

![team-manual-pdf-logo](https://user-images.githubusercontent.com/5887562/82068189-cac95e00-9725-11ea-98f9-7822d0a6ce58.png)

For reference, here is the old LaTeX manual:

![old-team-manual-pdf-logo](https://user-images.githubusercontent.com/5887562/82068274-d87ee380-9725-11ea-9480-64dcd4b18c36.png)

### Cause (HTML)

The width of the image is set to `10%` in team.rst, but the [width attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Img#attr-width) of HTML `<img>` elements must be in pixels, without a unit.

I don't know why the PDF doesn't have text wrapping or how to fix it.

### Idea for fix

Setting the width to `60pt` (and height to `132pt` to preserve aspect ratio) fixes the blank area in the HTML version, and produces reasonable sizes in both versions for me. The `pt` unit is an ugly hack – without it, the logo in the PDF version is too small. I hope web browsers will ignore it reliably; I only tested in Firefox.

For reference, the old LaTeX version set the height to [4cm](https://github.com/DOMjudge/domjudge/blob/eaabe710a4f7a2b00d28e082066f1d0eb0758d91/doc/team/team-manual-preamble.tex#L55).

**Comment by thijskh** [comment]
Thanks for the detailed report. Indeed it's a pity that the text does not yet properly wrap in the pdf.

However, I do not experience your issue in the HTML docs. This is with FF 76.
![afbeelding](https://user-images.githubusercontent.com/3808792/82129942-141dba00-97c7-11ea-8e66-1b5dc3ba5eb2.png)

**Comment by tom93** [comment]
That's odd. I consistently get same issue, locally with FF 68.8.0esr and FF 76 on Linux, and also on a cloud-based platform:

[Comparium](https://comparium.app), Windows 7, Firefox 75:

![team-manual-logo-comparium-win-7-firefox-75](https://user-images.githubusercontent.com/5887562/82131476-afe01200-9829-11ea-89e1-30207007865b.png)

Comparium, Windows 7, Chrome 81:

![team-manual-logo-comparium-win-7-chrome-81](https://user-images.githubusercontent.com/5887562/82131478-b1a9d580-9829-11ea-85a9-e089beb024b0.png)

I uploaded the documentation to https://tom93.github.io/domjudge-docs-test/html/team.html, built using
```
git clone https://github.com/DOMjudge/domjudge.git
cd domjudge
git checkout e194930c7
image=domjudge/domjudge-contributor@sha256:7b83efab3ea302e42b632b40204a0c86f65bb552c86ff3880c698b39a54bdb31 # (Ubuntu 20.04)
docker run -v $PWD:/domjudge -it $image
```

**Comment by thijskh** [comment]
Your link does indeed show the same effect with me so I that would help to reproduce it.

**Comment by thijskh** [comment]
It seems your version has an extra `<div>` around the logo that causes this. Apparently a "bug" that was fixed in more recent sphinx versions. Will see if your workaround does not cause and adverse effects in these newer versions.
