### ISSUE TITLE
Team manual: "Summary" sidebar layout issue in HTML output

### ISSUE THREAD

**Issue by tom93** [DOMjudge/domjudge#800]
The "Summary" section of the team manual uses an RST sidebar element, which looks nice in the PDF version:

![team-manual-pdf-summary-sidebar](https://user-images.githubusercontent.com/5887562/82070942-85a72b00-9729-11ea-976d-cc31c3a81e7a.png)

However, it looks bad in the HTML version:

![team-manual-html-summary-sidebar](https://user-images.githubusercontent.com/5887562/82071282-ffd7af80-9729-11ea-91f1-65c4183b6077.png)

<sup>Web browser: Firefox</sup>

The narrow sidebar doesn't suite the amount of text (I cut some out for the screenshot).
Also, the heading of the following section ("Overview of the interface") is separated from its content because there is a wide image that gets pushed down below the sidebar.

(It's not because of the window size; a wider window only makes the right margin wider.)

### Ideas for fix

The `admonition` element looks very similar to `sidebar` in the PDF version, and I like the HTML version except it adds an exclamation mark to the title (even though it's supposed to be a generic note):

![team-manual-html-summary-admonition](https://user-images.githubusercontent.com/5887562/82071752-a4f28800-972a-11ea-95f1-e63a6c6056fb.png)

The `topic` element seems most accurate semantically, but it doesn't stand out visually.

Of course, another option is to just use a normal section.

**Comment by thijskh** [comment]
Thanks, In general, the layout of the team image can indeed be polished. I don't see many downsides to using `admonition`, it does seem to be a net improvement to the docs. So I've applied that as a fix for this issue.
