### ISSUE TITLE
Team manual has undefined substitutions when using `make dist`

### ISSUE THREAD

**Issue by tom93** [DOMjudge/domjudge#801]
### Description of the problem

When `make dist` is used to bootstrap from sources (i.e. generate the configuration scripts and documentation for distribution), the generated team manual contains unsubstituted variable names instead of values (e.g. `|SOURCESIZE|` instead of 256; screenshots below).

This affects both the PDF version (_doc/manual/build/team/domjudge-team-manual.pdf_) and the HTML version (_doc/manual/build/html/team.html_).

### Cause

This happens because _team.rst_ includes the file _substitutions_, which doesn't exist at the bootstrap stage – it can only be generated from _substitutions.in_ after the configuration step, because it depends on _paths.mk_.

### Steps to reproduce

```
git clone https://github.com/DOMjudge/domjudge.git
cd domjudge
git checkout d57272ea0
image=domjudge/domjudge-contributor@sha256:7b83efab3ea302e42b632b40204a0c86f65bb552c86ff3880c698b39a54bdb31 # (Ubuntu 20.04)
docker run -v $PWD:/domjudge -it $image make -C /domjudge dist
```
The issue doesn't occur when using the default entrypoint, _/script/start.sh_, because it uses `make maintainer-conf` (which generates the configuration without building the docs) rather than `make dist`.

### Expected behaviour

It would be nice if the team manual contained default values. They are pretty straightforward:

 - `|DOMjudge|` (replaced with `@PACKAGE_NAME@`): can use "DOMjudge" as the default

 - `|baseurlteam|` (replaced with `@BASEURL@team`): can use https://example.com/domjudge/team to match the default BASEURL (also used in the [old LaTeX version](https://github.com/DOMjudge/domjudge/blob/eaabe710a4f7a2b00d28e082066f1d0eb0758d91/doc/team/gentexconfig.in#L39))

 - `|submit_enabled|`: unused, can be removed

 - `|SOURCESIZE|`, `|COMPILETIME|`, `|PROCLIMIT|`: these are replaced with hard-coded values, so don't depend on paths.mk

### Actual behaviour

The generated team manual contains unsubstituted variable names instead of values; in the PDF version they are red, in the HTML version they are blue links that don't go anywhere.
The build output contains several red warning messages about undefined substitutions.

### Screenshots

PDF (red variable names instead of values):

![team-manual-pdf-1](https://user-images.githubusercontent.com/5887562/82073804-dcaeff00-972d-11ea-8524-928bbb8f15f8.png)

![team-manual-pdf-2](https://user-images.githubusercontent.com/5887562/82073808-de78c280-972d-11ea-94bb-fec3fe25a639.png)

HTML (blue variable names instead of values):

![team-manual-html](https://user-images.githubusercontent.com/5887562/82073812-e0db1c80-972d-11ea-9ea2-64a39eeeb181.png)

### Ideas for fix

I am not sure what the cleanest way is to implement a fix.

A simple hack would be to insert a command in _doc/manual/Makefile_ before `$(MAKE) html team` that checks if _substitutions_ exists, and if not generates it with default values (it will be correctly updated later, except in one unlikely build sequence).

Another idea is to define the substitutions from _conf.py_ in a similar way to _version.py_ and _version.dist.py_, using [rst_prolog](https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-rst_prolog)/[rst_epilog](https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-rst_epilog).

I'd be happy to put together a PR.

### Build output

<details>

```diff
 make: Entering directory '/domjudge'
 make -C doc distdocs
 make[1]: Entering directory '/domjudge/doc'
 Recursing target `distdocs' into: manual examples
 make[2]: Entering directory '/domjudge/doc/manual'
 make html team
 make[3]: Entering directory '/domjudge/doc/manual'
 ./gen_conf_ref.py
 ./gen_conf_ref.py:84: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
   db_config = yaml.load(db_config_file)
 sphinx-build -M html . build
 Running Sphinx v1.8.5
 loading translations [en]... done
 making output directory...
-WARNING: The config value `pdf_use_toc' has type `str', defaults to `bool'.
 building [mo]: targets for 0 po files that are out of date
 building [html]: targets for 18 source files that are out of date
 updating environment: 18 added, 0 changed, 0 removed
 reading sources... [100%] upgrading
 /domjudge/doc/manual/team.rst:4: WARNING: Problems with "include" directive path:
 InputError: [Errno 2] No such file or directory: 'substitutions'.
-/domjudge/doc/manual/team.rst:8: WARNING: Undefined substitution referenced: "DOMjudge".
-/domjudge/doc/manual/team.rst:26: WARNING: Undefined substitution referenced: "baseurlteam".
-/domjudge/doc/manual/team.rst:46: WARNING: Undefined substitution referenced: "baseurlteam".
-/domjudge/doc/manual/team.rst:54: WARNING: Undefined substitution referenced: "baseurlteam".
-/domjudge/doc/manual/team.rst:131: WARNING: Undefined substitution referenced: "baseurlteam".
-/domjudge/doc/manual/team.rst:150: WARNING: Undefined substitution referenced: "baseurlteam".
-/domjudge/doc/manual/team.rst:185: WARNING: Undefined substitution referenced: "COMPILETIME".
-/domjudge/doc/manual/team.rst:302: WARNING: Undefined substitution referenced: "COMPILETIME".
-/domjudge/doc/manual/team.rst:309: WARNING: Undefined substitution referenced: "SOURCESIZE".
-/domjudge/doc/manual/team.rst:321: WARNING: Undefined substitution referenced: "PROCLIMIT".
 looking for now-outdated files... none found
 pickling environment... done
 checking consistency... done
 preparing documents... done
 writing output... [100%] upgrading
 generating indices... genindex
 writing additional pages... search
 copying images... [100%] team-scoreboard.png
 copying static files... done
 copying extra files... done
 dumping search index in English (code: en) ... done
 dumping object inventory... done
 build succeeded, 12 warnings.
 
 The HTML pages are in build/html.
 sphinx-build -b pdf . build/team
 Running Sphinx v1.8.5
 loading translations [en]... done
 making output directory...
-WARNING: The config value `pdf_use_toc' has type `str', defaults to `bool'.
 building [mo]: targets for 0 po files that are out of date
 building [pdf]: targets for 18 source files that are out of date
 updating environment: 18 added, 0 changed, 0 removed
 reading sources... [100%] upgrading
 /domjudge/doc/manual/team.rst:4: WARNING: Problems with "include" directive path:
 InputError: [Errno 2] No such file or directory: 'substitutions'.
-/domjudge/doc/manual/team.rst:8: WARNING: Undefined substitution referenced: "DOMjudge".
-/domjudge/doc/manual/team.rst:26: WARNING: Undefined substitution referenced: "baseurlteam".
-/domjudge/doc/manual/team.rst:46: WARNING: Undefined substitution referenced: "baseurlteam".
-/domjudge/doc/manual/team.rst:54: WARNING: Undefined substitution referenced: "baseurlteam".
-/domjudge/doc/manual/team.rst:131: WARNING: Undefined substitution referenced: "baseurlteam".
-/domjudge/doc/manual/team.rst:150: WARNING: Undefined substitution referenced: "baseurlteam".
-/domjudge/doc/manual/team.rst:185: WARNING: Undefined substitution referenced: "COMPILETIME".
-/domjudge/doc/manual/team.rst:302: WARNING: Undefined substitution referenced: "COMPILETIME".
-/domjudge/doc/manual/team.rst:309: WARNING: Undefined substitution referenced: "SOURCESIZE".
-/domjudge/doc/manual/team.rst:321: WARNING: Undefined substitution referenced: "PROCLIMIT".
 looking for now-outdated files... none found
 pickling environment... done
 checking consistency... done
 processing domjudge-team-manual...
 team
 resolving references...
 done
 writing domjudge-team-manual...
 [WARNING] styles.py:555 Using undefined style 'std', aliased to style 'normal'.
 done
 build succeeded, 12 warnings.
 make[3]: Leaving directory '/domjudge/doc/manual'
 make[2]: Leaving directory '/domjudge/doc/manual'
 ...
```

</details>

**Comment by thijskh** [comment]
Fwiw, the old team manual made use of some default values, overridden after you ran configure:

https://github.com/DOMjudge/domjudge/blob/7.2/doc/team/gentexconfig.in

**Comment by eldering** [comment]
Note: we had the same issue with the old PDF team manual. There we had a script `gentexconfig` generated from `gentexconfig.in` with the actual parameters. Then in `genteammanuals`, it would execute `gentexconfig` if it existed, or fall back to `gentexconfig.in` with default values.
Here, I think we should use the same setup as `version.dist.py` and `version.py.in`, or simply merge the extra config into `version.*` (renamed appropriately).
