### ISSUE TITLE
Can't access inactive contests through API even with role `API_READER`

### ISSUE THREAD

**Issue by tim3z** [DOMjudge/domjudge#814]
### Description of the problem
Trying to access the scoreboard of an inactive contest even with a user with the `API_READER` role results in an `HTTP 404`. While the documentation does not make entirely clear, what the desired behavior would be, line 140 in the API `ScoreboardController.php` clearly indicates that a user with the `API_READER` role should be allowed to access such a contest. The reason why it does not work is the call to `getContestId($request)` in line 139. This call ends up going through `getContestQueryBuilder()` in the `AbstractRestController.php` which excludes deactivated contests regardless of any roles which leads to the `404`.

### Your environment
Version 7.2.0

### Steps to reproduce
- Create contest with deactivation time in the past.
- Create user with `API_READER` role.
- `GET https://domjudge.iti.kit.edu/main/api/v4/contests/<cid>/scoreboard`

### Expected behaviour
The API returns the scoreboard data.

### Actual behaviour
A `404` is thrown.

**Comment by nickygerritsen** [comment]
Hmmm I wonder if we would break assumptions if we change this.
I agree with you that line 140 clearly indicates we want inactive contests, but this would mean you would suddenly get contents in the past that are inactive as well.

Note sure if this is a problem... cc @eldering @meisterT

**Comment by tim3z** [comment]
Hm, ok. Getting data about contests in the past is exactly the use case I have. We maintain one Domjudge installation with multiple contests for a practical university course throughout a semester and need to fetch the data about all contests...

**Comment by nickygerritsen** [comment]
I do see the use of it. I currently can't decide if it has drawbacks when we change the behavior, that's why maybe Tobi or Jaap has an opinion.

**Comment by eldering** [comment]
Indeed looks like an oversight to me. We should make sure this consistently applies to all the endpoints inside a deactivated contest though, not just the scoreboard.

**Comment by nickygerritsen** [comment]
I believe all API actions use this shared method, but we might have missed one that has custom code.

I guess grepping on `deactivatetime` should give a definitive answer.

**Comment by tim3z** [comment]
Grepping for `deactivatetime` in `/Controller/API` returns only that method in `AbstractRestController.php`

**Comment by nickygerritsen** [comment]
Then it seems ok 😄 .

**Comment by thijskh** [comment]
Yes, well this did change expectations somewhat. In the past /contests would always return active contests for everyone, which is a sensible default because usually you're not interested in deactivated contests. Now for api_reader and admin it returns all contests. To avoid consumers having to interpret the state of each contests themselves again, I've added a `onlyActive` parameter which you can supply if you're only interested in active contests.
