### ISSUE TITLE
AVX2 processor extensions can be enabled via pragma

### ISSUE THREAD

**Issue by lkempf** [DOMjudge/domjudge#824]
### Description of the problem
This issue only applies to submissions written in C or C++.
Since AVX2 processor extension are hardware specific, they need to be enabled for compilation in gcc. Normally, this is done using the -mavx2 switch during compilation or some other similar switch. DOMjudge does not include this command line switch. However, the same effect can be achieved using `#pragma GCC target "avx2"` within the source code. This might potentially give an unfair advantage to users aware of this feature.

### Steps to reproduce
- Upload a file including `immintrin.h`.
- Upload the same file again, but with the line `#pragma GCC target "avx2"` inserted on top.

### Expected behaviour
Either both submissions are accepted or both are rejected.

### Actual behaviour
The first submission does not compile, the second submission works without error (assuming the compiling machine supports AVX2).

### Potential fixes
- Use the `-march=native` switch when compiling. This will enable all instruction sets supported by the compiling machine.
- Scan submissions for the string `#pragma GCC target`.
- Just ignore this behavior because it is not that big a deal.

**Comment by thijskh** [comment]
Hi Lukas, thanks for the detailed report.

We are aware of the ability to influence compiler behaviour via pragma statements (AXV2 is one example of things that can be enabled this way). It is e.g. also possible to enable certain optimizations. We've chosen not to block this. It is not evident that it should not be allowable if the teams want to use this functionality.

If there's a problem that submissions are passing that should not have becaue of these pragmas, that raises more of a question about the quality of testcases than of the behaviour of the team using it. In any case there are many other ways to 'optimize' code. It's even possible to use inline assembly. So it's not clear why pragmas specifically should be suspect per se.

A contest that is concerned about it could of course use your first suggestion. But our default configuration chooses the third bullet.
