### ISSUE TITLE
systemd units installed in wrong directory

### ISSUE THREAD

**Issue by thijskh** [DOMjudge/domjudge#834]
The systemd units under `judge/` are installed in `/usr/lib/systemd/system` while this should be (on Debian at least) `/lib/systemd/system`. They will not be read from the former.

The systemd manual has some a recipe on how to determine the right installation path with automake:
https://www.freedesktop.org/software/systemd/man/daemon.html#Installing%20systemd%20Service%20Files

Maybe we can follow that. Or just call pkg-config at install time?

**Comment by ykazakov** [comment]
@thijskh Which `--prefix` did you set for `./configure` during the installation?

**Comment by thijskh** [comment]
```
		--enable-fhs \
		--prefix=/usr \
```

**Comment by ykazakov** [comment]
I just tried to set `--prefix=/usr/local` (which should be by default but apparently isn't, see #856), and after that systemd seem to pick up the installed modules:

```
$ sudo systemctl enable create-cgroups --now
Created symlink /etc/systemd/system/multi-user.target.wants/create-cgroups.service → /usr/local/lib/systemd/system/create-cgroups.service.
```
