### ISSUE TITLE
Register: Error when affiliation name is longer than 32 chars

### ISSUE THREAD

**Issue by tom93** [DOMjudge/domjudge#841]
### Description of the problem

During registration, if a new affiliation is added with a name longer than 32 characters, the server returns a 500 Internal Server Error page.

> An exception occurred while executing 'INSERT INTO team_affiliation (externalid, shortname, name, country, comments) VALUES (?, ?, ?, ?, ?)' with params [null, "A very long team affiliation name", "A very long team affiliation name", null, null]:
>
> SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'shortname' at row 1

### Environment

DOMjudge 7.1.3, 7.2.1, master @ aac01de9.

### Expected behaviour

Either registration should succeed, or there should be a friendly error message.
(I think this is reasonable to expect because the limit is so small.)

### Cause

The input from the user is used as both the name and the shortname of the new affiliation. The length limit of the name is 255, while the length limit of the shortname is only 32.

### Ideas for fix

 - Add validation to forbid names longer than 32 characters (simple, but needlessly restricts the length of the full name).
 - Truncate the input to 32 characters for the shortname (may result in duplicate shortnames; not sure if this is a problem, e.g. for exporting/importing).
 - Generate a unique shortname (e.g. first 20 characters of user input followed by an incrementing integer).

I'd be happy to implement one of these, just not sure what the preferred approach would be.

### Stack trace

<details>

```
Doctrine\DBAL\Exception\DriverException:
An exception occurred while executing 'INSERT INTO team_affiliation (externalid, shortname, name, country, comments) VALUES (?, ?, ?, ?, ?)' with params [null, "A very long team affiliation name", "A very long team affiliation name", null, null]:

SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'shortname' at row 1

  at /domjudge/lib/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:106
  at Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException()
     (/domjudge/lib/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php:169)
  at Doctrine\DBAL\DBALException::wrapException()
     (/domjudge/lib/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php:149)
  at Doctrine\DBAL\DBALException::driverExceptionDuringQuery()
     (/domjudge/lib/vendor/doctrine/dbal/lib/Doctrine/DBAL/Statement.php:162)
  at Doctrine\DBAL\Statement->execute()
     (/domjudge/lib/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php:287)
  at Doctrine\ORM\Persisters\Entity\BasicEntityPersister->executeInserts()
     (/domjudge/lib/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php:1087)
  at Doctrine\ORM\UnitOfWork->executeInserts()
     (/domjudge/lib/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php:400)
  at Doctrine\ORM\UnitOfWork->commit()
     (/domjudge/lib/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php:368)
  at Doctrine\ORM\EntityManager->flush()
     (src/Controller/SecurityController.php:177)
  at App\Controller\SecurityController->registerAction()
     (/domjudge/lib/vendor/symfony/http-kernel/HttpKernel.php:158)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw()
     (/domjudge/lib/vendor/symfony/http-kernel/HttpKernel.php:80)
  at Symfony\Component\HttpKernel\HttpKernel->handle()
     (/domjudge/lib/vendor/symfony/http-kernel/Kernel.php:201)
  at Symfony\Component\HttpKernel\Kernel->handle()
     (public/index.php:25)
```

</details>

**Comment by thijskh** [comment]
For the record, it only fails when MySQL is in some kind of strict mode. In my (default Debian) installation, it does not fail but the value is silently truncated, which we all know and love from MySQL.

In the admin interface we do not currently enforce any shortname uniqueness.

I doubt there's much to gain from making the self-registered shortnames forcefully unique. Because in self registration we currently accept long names "Utrecht University" and "Universiteit Utrecht" and "Utrecht University " as all new affiliations. Only exact stringwise matches are not accepted. So there's no real expectation of uniqueness for self-declared affiliations, I think. So also not for shortnames?

**Comment by thijskh** [comment]
A fourth option is to ask the user to also provide a meaningful shortname during registration.

**Comment by eldering** [comment]
To me asking the user for a shortname and otherwise generate a unique one from the affiliation name sounds like a good candidate solution. Although just picking either of those is also fine.
