### ISSUE TITLE
Missing etc/restapi.secret when installing a judgehost

### ISSUE THREAD

**Issue by ykazakov** [DOMjudge/domjudge#852]
### Description of the problem
The [instructions](https://www.domjudge.org/docs/manual/7.3/install-judgehost.html) for building and installing a judgehost do not work.

### Your environment
- DOMjudge 7.3.0
- Ubuntu 20.04 server running inside an LXD container (not sure if that matters)
- Linux judgehost1 5.4.0-33-generic #37-Ubuntu SMP Thu May 21 12:53:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- LXC version 4.3

### Steps to reproduce
```
$ # create a fresh lxd container based on ubuntu 20.04 
$ # (should also work if run directly on ubuntu 20.04, but I did not test it)
$ lxc launch ubuntu:focal judgehost1
$ # enter the container under the user ubuntu
$ lxc exec judgehost1 -- su ubuntu -l
$ # download and unpack domjudge
$ wget https://www.domjudge.org/releases/domjudge-7.3.0.tar.gz
$ tar xzf domjudge-7.3.0.tar.gz
$ cd domjudge-7.3.0/
$ # install required packages
$ sudo apt update
$ sudo apt upgrade -y
$ sudo apt install -y make debootstrap libcgroup-dev php-cli php-curl php-json php-xml php-zip gcc g++ default-jre-headless default-jdk-headless ghc fp-compiler libcurl4-nss-dev libjsoncpp-dev
$ # building and installing judgehost according to the manual
$ ./configure --prefix=$HOME/domjudge
$ make judgehost
$ sudo make install-judgehost # <= ERROR HERE
```

### Expected behaviour
I expect no error messages

### Actual behaviour

```
/usr/bin/install: cannot stat 'etc/restapi.secret': No such file or directory
```

Full log:

```
$ sudo make install-judgehost
sudo: setrlimit(RLIMIT_CORE): Operation not permitted
make -C etc config
make[1]: Entering directory '/home/ubuntu/domjudge-7.3.0/etc'
make[1]: Nothing to be done for 'config'.
make[1]: Leaving directory '/home/ubuntu/domjudge-7.3.0/etc'
Recursing target `judgehost' into: etc judge misc-tools
make[1]: Entering directory '/home/ubuntu/domjudge-7.3.0/etc'
make[1]: Nothing to be done for 'judgehost'.
make[1]: Leaving directory '/home/ubuntu/domjudge-7.3.0/etc'
make[1]: Entering directory '/home/ubuntu/domjudge-7.3.0/judge'
make[1]: Nothing to be done for 'judgehost'.
make[1]: Leaving directory '/home/ubuntu/domjudge-7.3.0/judge'
make[1]: Entering directory '/home/ubuntu/domjudge-7.3.0/misc-tools'
make[1]: Nothing to be done for 'judgehost'.
make[1]: Leaving directory '/home/ubuntu/domjudge-7.3.0/misc-tools'
make[1]: Entering directory '/home/ubuntu/domjudge-7.3.0'
make[1]: Nothing to be done for 'judgehost-l'.
make[1]: Leaving directory '/home/ubuntu/domjudge-7.3.0'
/usr/bin/install -c -d /home/ubuntu/domjudge/judgehost/bin /home/ubuntu/domjudge/judgehost/etc /home/ubuntu/domjudge/judgehost/lib /home/ubuntu/domjudge/judgehost/lib/judge /home/ubuntu/domjudge/judgehost/log /home/ubuntu/domjudge/judgehost/run /home/ubuntu/domjudge/judgehost/judgings
Recursing target `install-judgehost' into: etc lib judge misc-tools
make[1]: Entering directory '/home/ubuntu/domjudge-7.3.0/etc'
/usr/bin/install -c -m 0644 -t /home/ubuntu/domjudge/judgehost/etc \
	judgehost-static.php sudoers-domjudge genrestapicredentials
/usr/bin/install -c -m 0644 -t /home/ubuntu/domjudge/judgehost/etc \
	judgehost-config.php common-config.php
make[1]: Leaving directory '/home/ubuntu/domjudge-7.3.0/etc'
make[1]: Entering directory '/home/ubuntu/domjudge-7.3.0/lib'
/usr/bin/install -c -m 0644 -t /home/ubuntu/domjudge/judgehost/lib    *.php *.sh
/usr/bin/install -c -t /home/ubuntu/domjudge/judgehost/lib    alert
make[1]: Leaving directory '/home/ubuntu/domjudge-7.3.0/lib'
make[1]: Entering directory '/home/ubuntu/domjudge-7.3.0/judge'
/usr/bin/install -c -t /home/ubuntu/domjudge/judgehost/lib/judge \
	compile*.sh testcase_run.sh chroot-startstop.sh \
	check_diff.sh evict
/usr/bin/install -c -m 0644 -t /home/ubuntu/domjudge/judgehost/lib/judge \
	judgedaemon.main.php
/usr/bin/install -c -t /home/ubuntu/domjudge/judgehost/bin \
        judgedaemon runguard runpipe create_cgroups
/usr/bin/install -c -d     /home/ubuntu/domjudge/lib/systemd/system/
/usr/bin/install -c -m 0644 -t /home/ubuntu/domjudge/lib/systemd/system/ \
        create-cgroups.service domjudge-judgehost.service
make[1]: Leaving directory '/home/ubuntu/domjudge-7.3.0/judge'
make[1]: Entering directory '/home/ubuntu/domjudge-7.3.0/misc-tools'
/usr/bin/install -c -t /home/ubuntu/domjudge/judgehost/bin dj_make_chroot dj_run_chroot dj_make_chroot_docker dj_judgehost_cleanup \
	dj_make_ubuntu_java_chroot
make[1]: Leaving directory '/home/ubuntu/domjudge-7.3.0/misc-tools'
make[1]: Entering directory '/home/ubuntu/domjudge-7.3.0'
make check-root
make[2]: Entering directory '/home/ubuntu/domjudge-7.3.0'
make[2]: Leaving directory '/home/ubuntu/domjudge-7.3.0'
/usr/bin/install -c -m 0644 -o ubuntu -m 0700 -d /home/ubuntu/domjudge/judgehost/log
/usr/bin/install -c -m 0644 -o ubuntu -m 0700 -d /home/ubuntu/domjudge/judgehost/run
/usr/bin/install -c -m 0644 -o ubuntu -m 0711 -d /home/ubuntu/domjudge/judgehost/judgings
/usr/bin/install -c -m 0644 -o ubuntu -m 0700 -d /home/ubuntu/domjudge/judgehost/tmp
/usr/bin/install -c -m 0644 -o ubuntu -m 0600 -t /home/ubuntu/domjudge/judgehost/etc \
	etc/restapi.secret
/usr/bin/install: cannot stat 'etc/restapi.secret': No such file or directory
make[1]: [Makefile:149: install-judgehost-l] Error 1 (ignored)
make[1]: Leaving directory '/home/ubuntu/domjudge-7.3.0'
```

### Any other information that you want to share?
Works if I run `make build` instead of `make judgehost`:

```
$ ./configure --prefix=$HOME/domjudge
$ make build
$ sudo make install-judgehost
```

**Comment by nickygerritsen** [comment]
The documentation does state you need to copy this file: https://www.domjudge.org/docs/manual/7.3/install-judgehost.html#rest-api-credentials
However I think we should not crash the installation because the file is missing, especially since that documentation only appears later on.

**Comment by ykazakov** [comment]
I see. I did not get to that point yet. ;-)

**Comment by thijskh** [comment]
I think this is an artefact of #862: the installation of a judgehost assumes that a domserver has been configured on this machine.

**Comment by BSEF8M014** [comment]
~/Desktop/domjudge-8.0.0$ ./configure
checking whether configure should try to set CFLAGS... yes
checking whether configure should try to set CXXFLAGS... yes
checking whether configure should try to set LDFLAGS... yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether C compiler accepts -Wall... yes
checking whether C compiler accepts -fstack-protector... yes
checking whether C compiler accepts -fPIE... yes
checking whether C compiler accepts -D_FORTIFY_SOURCE=2... yes
checking whether the linker accepts -fPIE... yes
checking whether the linker accepts -pie... yes
checking whether the linker accepts -Wl,-z,relro... yes
checking whether the linker accepts -Wl,-z,now... yes
checking domjudge-user... waleed.khalid@ebryx.com (default: current user)
checking webserver-group... www-data (detected)
checking runuser... domjudge-run (default)
checking rungroup... domjudge-run (default)
checking for cgroup_init in -lcgroup... no
configure: error: Linux cgroup library not found.

**Comment by BSEF8M014** [comment]
> ~/Desktop/domjudge-8.0.0$ ./configure checking whether configure should try to set CFLAGS... yes checking whether configure should try to set CXXFLAGS... yes checking whether configure should try to set LDFLAGS... yes checking for gcc... gcc checking whether the C compiler works... yes checking for C compiler default output file name... a.out checking for suffix of executables... checking whether we are cross compiling... no checking for suffix of object files... o checking whether we are using the GNU C compiler... yes checking whether gcc accepts -g... yes checking for gcc option to accept ISO C89... none needed checking whether C compiler accepts -Wall... yes checking whether C compiler accepts -fstack-protector... yes checking whether C compiler accepts -fPIE... yes checking whether C compiler accepts -D_FORTIFY_SOURCE=2... yes checking whether the linker accepts -fPIE... yes checking whether the linker accepts -pie... yes checking whether the linker accepts -Wl,-z,relro... yes checking whether the linker accepts -Wl,-z,now... yes checking domjudge-user... [waleed.khalid@ebryx.com](mailto:waleed.khalid@ebryx.com) (default: current user) checking webserver-group... www-data (detected) checking runuser... domjudge-run (default) checking rungroup... domjudge-run (default) checking for cgroup_init in -lcgroup... no configure: error: Linux cgroup library not found.

Any solution to this error

**Comment by eldering** [comment]
> > ~/Desktop/domjudge-8.0.0$ ./configure checking whether configure should try to set CFLAGS... yes checking whether configure should try to set CXXFLAGS... yes checking whether configure should try to set LDFLAGS... yes checking for gcc... gcc checking whether the C compiler works... yes checking for C compiler default output file name... a.out checking for suffix of executables... checking whether we are cross compiling... no checking for suffix of object files... o checking whether we are using the GNU C compiler... yes checking whether gcc accepts -g... yes checking for gcc option to accept ISO C89... none needed checking whether C compiler accepts -Wall... yes checking whether C compiler accepts -fstack-protector... yes checking whether C compiler accepts -fPIE... yes checking whether C compiler accepts -D_FORTIFY_SOURCE=2... yes checking whether the linker accepts -fPIE... yes checking whether the linker accepts -pie... yes checking whether the linker accepts -Wl,-z,relro... yes checking whether the linker accepts -Wl,-z,now... yes checking domjudge-user... [waleed.khalid@ebryx.com](mailto:waleed.khalid@ebryx.com) (default: current user) checking webserver-group... www-data (detected) checking runuser... domjudge-run (default) checking rungroup... domjudge-run (default) checking for cgroup_init in -lcgroup... no configure: error: Linux cgroup library not found.
> 
> Any solution to this error

@BSEF8M014 don't hijack old, unrelated issues. And also please first ask questions either on slack or the mailinglist. Issues are for reporting bugs (and I'm pretty sure this is not a bug).
