### ISSUE TITLE
Document how to set credentials for the submit/submit script

### ISSUE THREAD

**Issue by ykazakov** [DOMjudge/domjudge#853]
### Description of the problem

I am following the [Quick installation checklist](https://www.domjudge.org/docs/manual/7.3/quick-install.html).
Unfortunately, I get problems when running the final tests:

```
cd tests
make check
```

I am getting lots of errors like this:
```
[Jul 27 18:11:30.650] ../submit/submit[2417]: error: Authentication failed. Please check your DOMjudge credentials.
```

The documentation of `submit` does not seem mention how to specify any credentials.

### Your environment
- DOMjudge 7.3.0
- Ubuntu 20.04 server running inside an LXD container (not sure if that matters)
- LXC version 4.3
- $ uname -a
Linux domjudge1 5.4.0-33-generic #37-Ubuntu SMP Thu May 21 12:53:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

### Steps to reproduce
```
$ # create a fresh lxd container based on ubuntu 20.04 
$ # (should also work if run directly on ubuntu 20.04, but I did not test it)
$ lxc launch ubuntu:focal domjudge1
$ # enter the container under the user ubuntu
$ lxc exec domjudge1 -- su ubuntu -l
$ # download and unpack domjudge
$ wget https://www.domjudge.org/releases/domjudge-7.3.0.tar.gz
$ tar xzf domjudge-7.3.0.tar.gz
$ cd domjudge-7.3.0/
$ # install required packages
$ sudo apt update
$ sudo apt upgrade -y
$ apt install -y zip unzip mariadb-server apache2 php php-fpm php-cli php-gd php-curl php-mysql php-json php-xml php-intl php-mbstring php-zip composer ntp build-essential libcgroup-dev libcurl4-nss-dev libjsoncpp-dev acl 
$ # building and installing judgehost according to the manual
$ ./configure --prefix=$HOME/domjudge  --with-baseurl='http://localhost/domjudge/'
$ sudo make install-domserver
$ cd ../domserver/
$ sudo bin/dj_setup_database install
$ sudo ln -s ~/domjudge/domserver/etc/apache.conf /etc/apache2/conf-available/domjudge.conf
$ sudo ln -s ~/domjudge/domserver/etc/domjudge-fpm.conf /etc/php/7.4/fpm/pool.d/domjudge.conf
$ sudo a2enmod proxy_fcgi setenvif rewrite
$ sudo a2enconf php7.4-fpm domjudge
$ sudo service php7.4-fpm reload
$ sudo service apache2 reload
$ cd ../domjudge-7.3.0/tests/
$ make check # <= Lots of error
```

### Expected behaviour
I expect tests to pass. Otherwise, what's the point of tests? ;-)

### Actual behaviour
Here is the first few lines output of tests (can submit the full output if necessary):

```
$ make check
Submitting normal test sources...
Submitting 'test-binary-content.c' WARNING: `test-binary-content.c' has not been modified for 44535 minutes!
[Jul 27 18:32:19.276] ../submit/submit[2608]: error: Authentication failed. Please check your DOMjudge credentials.

Submitting 'test-binary-output.c' WARNING: `test-binary-output.c' has not been modified for 44535 minutes!
[Jul 27 18:32:19.319] ../submit/submit[2610]: error: Authentication failed. Please check your DOMjudge credentials.

Submitting 'test-classname.java' WARNING: `test-classname.java' has not been modified for 44535 minutes!
[Jul 27 18:32:19.362] ../submit/submit[2612]: error: Authentication failed. Please check your DOMjudge credentials.

Submitting 'test-compile-error.c' WARNING: `test-compile-error.c' has not been modified for 44535 minutes!
[Jul 27 18:32:19.407] ../submit/submit[2614]: error: Authentication failed. Please check your DOMjudge credentials.

Submitting 'test-compile-error.lua' WARNING: `test-compile-error.lua' has not been modified for 44535 minutes!
[Jul 27 18:32:19.443] ../submit/submit[2616]: error: no language specified or detected
Type '../submit/submit --help' to get help.

Submitting 'test-compile-error.pas' WARNING: `test-compile-error.pas' has not been modified for 44535 minutes!
[Jul 27 18:32:19.479] ../submit/submit[2618]: error: no language specified or detected
Type '../submit/submit --help' to get help.

Submitting 'test-compile-error.pl' WARNING: `test-compile-error.pl' has not been modified for 44535 minutes!
[Jul 27 18:32:19.519] ../submit/submit[2620]: error: no language specified or detected
Type '../submit/submit --help' to get help.

Submitting 'test-compile-error.py' WARNING: `test-compile-error.py' has not been modified for 44535 minutes!
[Jul 27 18:32:19.555] ../submit/submit[2622]: error: no language specified or detected
Type '../submit/submit --help' to get help.
```

### Any other information that you want to share?

Also: should the configure option `--with-baseurl=<url>` be necessarily specified? The [installation instruction for DOMserver](https://www.domjudge.org/docs/manual/7.3/install-domserver.html) do not mention that but it is mentioned in [quick-install](https://www.domjudge.org/docs/manual/7.3/quick-install.html). Without this option, `submit/submit` seems to connect to the default url `https://example.com/domjudge/`, which clearly fails. Should the default url be something that has a chance to work, e.g., `http://localhost/domjudge/`? (If necessary, I could open another ticked for that).

**Comment by thijskh** [comment]
The credentials are in `~/.netrc`, and this is documented in the manual: https://www.domjudge.org/docs/manual/7.3/install-workstation.html#command-line-submit-client . That also mentions to use `--with-baseurl`.

I do indeed think that it would be good to also document this in the --help output.

**Comment by ykazakov** [comment]
@thijskh thanks for the quick feedback! Looks like I have missed this part. Providing the documentation with the client would be really helpful!

**Comment by ykazakov** [comment]
Just to give a feedback: creating the file `~/.netrc` with the content for the dummy user (created by the installation) indeed solves the problem:
```
machine localhost login dummy password xxxxxxxxxx
```
It would be nice if it were also mentioned in the quick installation checklist. I was under impression that installation for team workstations is not related to the installation of the domjudge/judgehosts, so I did not check this section of the documentation.

**Comment by thijskh** [comment]
There is indeed more than one interdependency between domserver/judgehost/submit client even though they in principle can target different machines. We need to devise a way to deal with rhat.
