### ISSUE TITLE
Creating a chroot environment for judgehosts fails on Ubuntu 20.04

### ISSUE THREAD

**Issue by ykazakov** [DOMjudge/domjudge#854]
### Description of the problem

I have difficulties [creating a chroot environment](https://www.domjudge.org/docs/manual/7.3/install-judgehost.html#creating-a-chroot-environment) in an lxd container under ubuntu 20.04 server (both host and the container). When running `debootstrap` there appear to besome dependency problems for packages. I am not sure if it is because I am running inside a container. If I manually specify to create a chroot for ubuntu 18.04 everything works fine. As far as I understand, the script builds by default a chroot for the latest (stable) ubuntu.

### Your environment
- DOMjudge 7.3.0
- Ubuntu 20.04 server running inside an LXD container (not sure if that matters)
- LXC version 4.3
- $ uname -a
Linux judgehost2 5.4.0-42-generic #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

### Steps to reproduce
```
$ # create a fresh lxd container based on ubuntu 20.04 
$ lxc launch ubuntu:focal judgehost2
$ # make sure that mknod works since the container is unprivileged 
$ lxc config set judgehost2 security.syscalls.intercept.mknod true
$ lxc restart judgehost2
$ # enter the container under the user ubuntu
$ lxc exec judgehost2 -- su ubuntu -l
$ # download and unpack domjudge
$ wget https://www.domjudge.org/releases/domjudge-7.3.0.tar.gz
$ tar xzf domjudge-7.3.0.tar.gz
$ cd domjudge-7.3.0/
$ # install required packages
$ sudo apt update
$ sudo apt upgrade -y
$ sudo apt install -y make debootstrap libcgroup-dev php-cli php-curl php-json php-xml php-zip gcc g++ default-jre-headless default-jdk-headless ghc fp-compiler libcurl4-nss-dev libjsoncpp-dev
$ vi etc/restapi.secret # paste the credentials from etc/restapi.secret of DOMserver
$ # building and installing judgehost according to the manual
$ ./configure --prefix=$HOME/domjudge
$  make judgehost
$ sudo make install-judgehost
$ sudo useradd -d /nonexistent -U -M -s /bin/false domjudge-run
$  sudo cp etc/sudoers-domjudge /etc/sudoers.d/
$ # setup chroot
$ cd ../domjudge/judgehost/
$ sudo bin/dj_make_chroot # <= Fails
```
### Expected behaviour
Should run fine

### Actual behaviour

The debootstrap script seem to fails:

```
I: Configuring python3-requests-unixsocket...
I: Configuring libc-bin...
I: Configuring systemd...
I: Configuring ca-certificates...
W: Failure while configuring base packages.  This will be re-attempted up to five times.
W: See /chroot/domjudge/debootstrap/debootstrap.log for details (possibly the package dconf-service is at fault)
W: Failure while configuring base packages.  This will be re-attempted up to five times.
W: See /chroot/domjudge/debootstrap/debootstrap.log for details (possibly the package dconf-service is at fault)
W: Failure while configuring base packages.  This will be re-attempted up to five times.
W: See /chroot/domjudge/debootstrap/debootstrap.log for details (possibly the package dconf-service is at fault)
W: Failure while configuring base packages.  This will be re-attempted up to five times.
W: See /chroot/domjudge/debootstrap/debootstrap.log for details (possibly the package dconf-service is at fault)
W: Failure while configuring base packages.  This will be re-attempted up to five times.
W: See /chroot/domjudge/debootstrap/debootstrap.log for details (possibly the package dconf-service is at fault)
```

There are many dependency problems in the `debootstrap.log`. The log is attached.
[debootstrap.log](https://github.com/DOMjudge/domjudge/files/4984068/debootstrap.log)

### Any other information that you want to share?

Creating a chroot for ubuntu 18.04 (within the same container) seem to work fine:

```
sudo bin/dj_make_chroot -D Ubuntu -R bionic 
```

**Comment by eldering** [comment]
I don't know exactly how LXC works, but I expect that it doesn't provide sufficient permissions. Can you build a chroot inside a plain Ubuntu 20.04 installation?

**Comment by ykazakov** [comment]
I can try to find another machine, but as I wrote, a chroot environment for 18.04 could be installed within the same container without problems.

**Comment by ykazakov** [comment]
I was not able to find a bare metal ubuntu, but I ran the setup again under an ubuntu 20.04 VM (not a container!) with similar results. So, permission problems with `mknod` do not appear to be the main cause.

```
$ uname -a
Linux judgehost-vm1 5.4.0-42-generic #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

For some reason, `libc6` do not appear to be installed by debootstrap.

[debootstrap.log](https://github.com/DOMjudge/domjudge/files/4990379/debootstrap.log)

**Comment by ykazakov** [comment]
Just to confirm, ubuntu 18.04 chroot could be built inside the VM also without problems.
```
sudo bin/dj_make_chroot -D Ubuntu -R bionic 
```
