### ISSUE TITLE
Blocked queued and Problem is currently not allowed to be judged!

### ISSUE THREAD

**Issue by USERCALL** [DOMjudge/domjudge#858]
[sorry by english] i hope these will be usuful

### Description of the problem
> Today, we have a training with this sotware, 
but at the end of the session, a judgehost stop and we did not why 

The code has a logical error but the server dont show a timelimit error 

### Steps to reproduce
> submit this code to cpp 
```#include<iostream>
using namespace std;
int main(){
	int x,m,n,cont,p;
	cin>>x;
	
for(p=1;p=x;p++){
	cout<<endl;
	cin>>m>>n;
	for(m;m<=n;m++){
		for(int i=1;i<=m;i++){
            if(m%i==0){
                cont++;
            }
        }
        if(cont==2){
            cout<<m;
            cout<<endl;
        }
        cont=0;
	}
}
return 0;
}

```

### Expected behaviour
> Time limit 
### Actual behaviour
> Stop the queued

### Any other information that you want to share?
> After ignore this submit, all summit can't judge and also rejudge 
The error message said `"Problem is currently not allowed to be judged!"`,
 we need to modify values on "
``SELECT allow_judge FROM contestproblem
```
from 0 to 1,  To solve this issuse  and the  we could rejudge. 

But again if we judge the cpp code above, it block the server again

**Comment by meisterT** [comment]
Did you see an internal error being filed? What does it say? What is the last log output of the judgedaemon?

**Comment by USERCALL** [comment]
I don´t have access to the server again, I request that but I don´t believe it´s possible,

**Comment by thijskh** [comment]
I have tested the given submission and it returns timelimit with me (as expected).

I understand that you do not have access to the DOMjudge webinterface of this installation anymore? Then it will be hard to debug it without that information.
