### ISSUE TITLE
Installation process not properly separated

### ISSUE THREAD

**Issue by thijskh** [DOMjudge/domjudge#862]
If you follow the installation steps in the manual it does not currently work. This is because they are spilt over domserver and judgehost and it's not currently possible to install on a machine only a judgehost when installing only the dependencies of that judgehost.

The current (automake) system requires that you install the superset of dependencies for domserver, judgehost and submit client for it to pass. And you are required to pass configuration (baseurl) that is only relevant for one component (submit).

This is not a documentation issue but an issue with the installation system. It should be possible to install a judgehost on a system with no need for any dependencies of the domserver or for configuration options of the domserver.

**Comment by thijskh** [comment]
One approach could be to give each component its own (automake or other) installation process in its own subdir in the tarball (odmjudge.tar.gz would contain `submit/`, `judge/` and `server/` and each has a configure. This keeps it very clean and there's virtually no shared code or options. (An even more radical variant of this is to split the judgehost and submit client off to separate repositories and released tarballs. Drawback is that it requires more fiddling if you _are_ installing everything on one machine.)

Another approach may be to keep the current integrated configuration but make it more dynamic by requiring that you --enable the parts that you are building on this machine.

**Comment by mvr320** [comment]
> And you are required to pass configuration (baseurl) that is only relevant for one component (submit).
The docs also use it.

I think the --enable route is friendly enough and makes that people only have to stay in a single directory for everything to work. I think me as a user would prefer that and if I would be inexperienced with Linux this is the approach which can create the least _hard_ to debug situations.

Ofcourse my argument becomes invalid if people would use the debs/docker when configure is something they have problems with.

**Comment by eldering** [comment]
Alternative/combination of already suggested options: I think that autoconf allows for sub-projects, so we could have independent subdirectories with their own configure/make code and then in the root directory a configure/make script that allows building all together.
I think that already matches pretty much how `webapp`, `submit`, `judge`, `doc` are split up, but the configuration might be the most tricky one to deal with.

**Comment by vmcj** [comment]
Closed with: ef548499cdd1c727a974300cb2a03834fcc59d8f
