### ISSUE TITLE
Self-registration form should allow entering the full name

### ISSUE THREAD

**Issue by ykazakov** [DOMjudge/domjudge#868]
### Description of the problem

Currently only the username and email fields can be entered in the self-registration form, but not the name field (for the full name).

In contrast, creating users through the admin interface make it possible to enter both fields.

I suggest to add the field for the "name" to the self-registration form, make it optional, and if not filled-in, use the username value, which should mimic the current behaviour.

### Your environment
- Domjudge 7.3.0

### Steps to reproduce
- Ensure there is a team category with self registration enabled
- Press login
- Click "Register now".

**Comment by thijskh** [comment]
Fully agreed. A PR would be welcome!
