### ISSUE TITLE
Add a possibility to join an existing team for self-registration

### ISSUE THREAD

**Issue by ykazakov** [DOMjudge/domjudge#869]
### Description of the problem

In #561 a feature was added for a user to specify a team during the self-registration of users.
However, this form does not let the user to join an existing team. It would be nice to allow self-registered users to join teams.

### Your environment
- DOMjudge 7.3.0

### Steps to reproduce
- Ensure there is a team category with self registration enabled
- Press Login
- Click "Register now".
- Enter new login details with some team
- Press "Register"
- Press "Logout"
- Press "Login"
- Click "Register now".
- Enter new login details with the same team as in the previous step

### Expected behaviour
- A user joins the specified team

### Actual behaviour
- A error message pops up: "ERROR This team name is already in use."

### Any other information that you want to share?
I can see situations which may lead to some security problems, i.e., unwanted users joining teams during contests.
To avoid this situation (and mimic the old behaviour) one could, perhaps, add a flag to team categories to enable joining existing teams during self-registration. In addition, maybe allow the team members to "lock" the team so to prevent other members joining this team.

**Comment by ykazakov** [comment]
I have just created a PR #871 for this issue .
In the patch, it is possible to join teams, which categories allow self registration. So, once self-registration is disabled in these categories, it is no longer possible to join these teams. Or, to prevent joining a particular team, it is sufficient to just change its category to other category which does not allow self-registration. I think it is a sensible solution.

**Comment by meisterT** [comment]
What's the exact user journey for all people involved (original team member, new team member and contest organizer)?

I am worried that any random user could join any team. Without confirmation this sounds suboptimal (and a potential security issue). With confirmation the question is how we would implement confirmation: do the original team members accept the new team member or is that the job of the contest organizers?
We also don't have any email functionality built-in (whether that's a positive or negative is debatable), so currently there's no way to inform old team members that someone wants to join their team.
One could think of a token that the original team member could share with the new team member which they have to enter on registration if they want to join an existing team.

**Comment by ykazakov** [comment]
I could imagine the following workflow:
- Admin creates a team category, which allows self-registration
- Users sign up, join or create teams
- Before the contest starts, admin checks if the teams are OK and disables self-registration

The only problem: currently the team members cannot see who else is in their team. Or am I missing something? This way, if some unintended user joins a team, they cannot report this to the organiser.

Of course, confirming registration by existing team members is even a better option. One can make users to be "team admins" (by default house that create the teams), who should be able to approve other team users or set other users to be team admins. Can the same mechanism as used for clarification be used for sending messages to team members?

Creating team tokens for team registration could be a solution that is much simpler to implement.

Another approach could be to separate registration of users from registration of teams. E.g., a user can register without choosing a team, and then other team users are able to add registered team-less users to their teams, similarly as I did for #872 in PR #871. That may, however, lead to another privacy issue: should registered users be able to see other registered users?

In any case, I think there should be some further UI improvements to manage users and teams. E.g., currently, as far as I see, it is not possible for team users to change any data provided during the registration (password, email addresses, affiliations, teams).

**Comment by JobDoesburg** [comment]
Why not go for the easy way and make it a configuration setting `allow_self_registration_join_existing_team`

**Comment by ykazakov** [comment]
@JobDoesburg I think adding a new configuration option is not enough. Currently users cannot see which other users are in their teams, so detecting undesired team users is difficult. Even admins cannot currently (directly) see the team users. See #872.

**Comment by eldering** [comment]
We've discussed and think it is too complex to implement in our main codebase.
