### ISSUE TITLE
Make it possible to see team members from the web interface

### ISSUE THREAD

**Issue by ykazakov** [DOMjudge/domjudge#872]
### Description of the problem

Currently it is not possible to see from the Jury interface, which users belong to a particular team.
There appears to be the field Members in the form, but is always empty, unless some text is entered there manually.

> Replace this line with a short description.

### Your environment
- DOMjudge 7.3.0

### Steps to reproduce
- install Domserver and initialise the database according to the [manual](https://www.domjudge.org/docs/manual/7.3/index.html)
- login as admin with the initial password
- under the Users link (Before contest) observe that the dummy user is a member of "Example tamname" (press the edit symbol to open the form)

![Screenshot 2020-10-02 at 15 27 32](https://user-images.githubusercontent.com/2140361/94928629-46089200-04c4-11eb-9130-6d0d485074b8.png)

- under the Teams link (Before contest) observe that the "Example tamname" does not have any member:

![Screenshot 2020-10-02 at 15 29 43](https://user-images.githubusercontent.com/2140361/94928641-486aec00-04c4-11eb-86c9-4d945062b58b.png)

### Expected behaviour
I think that team members should be shown in this form, and it should be possible to add / remove users to / from teams.

### Actual behaviour
Team members are not visible.

### Any other information that you want to share?

In database, there appears to be two columns of the team table: "users" which stores the list of users having this team, and "members", which as far as I see is not used anywhere in the code.

I think it should not be difficult to display / add / remove users from the team form, similar to Contests field in the bottom of the form:

![Screenshot 2020-10-02 at 15 34 55](https://user-images.githubusercontent.com/2140361/94929034-d3e47d00-04c4-11eb-8c24-3c08561d31da.png)

Maybe the only question is when adding users to teams, should all users be shown or only users that do not belong a team. I think the latter is a better option.

**Comment by nickygerritsen** [comment]
In a lot of setups there is only one user per team but multiple people accessing that one user.

That is the reason we have this free form members field.

However I'd say it would be useful to have the users belonging to a team **besides** the free form members.

Selecting users when editing a team can also be a feature.

**Comment by ykazakov** [comment]
@nickygerritsen is it really a good practice to use one account per team? Maybe that should be discouraged especially if an option for self-registration with an existing team can be provided? See #871 

To avoid confusion with members/users, should the free form field be renamed to something neutral, like "Description"?

**Comment by nickygerritsen** [comment]
During ICPC contests where people are on site the rules are simple:
3 people in a team, one pc. I think it doesn't make sense to have 3 users then.

For self registration multiple users make sense yes, but I think a lot of contests have different rules.

**Comment by ykazakov** [comment]
OK, I see, with one pc it makes sense. Then I can just append the field "users" to this form. Should I rename "Members" to "Description" to distinguish it from "users"? Then the database column should probably be renamed as well.

**Comment by nickygerritsen** [comment]
Let's see what others think about members vs description. I think it's also used in the api and imports, so renaming it seems like a thing that needs to be thought through

**Comment by nickygerritsen** [comment]
I wonder if this is not enough actually:
![image](https://user-images.githubusercontent.com/550145/128558018-e883826e-2948-4848-a9da-4a2546245513.png)
This shows all users belonging to a team, which we already show since a few years.
I know it's not the (freeform) members field, but we show the users.

Two questions do remain:

* Do we want to rename "team members"  to "description" or similar?
* Do we want to append a form element for selecting users when adding/editing a team?

**Comment by mvr320** [comment]
>     * Do we want to rename "team members"  to "description" or similar?
> 
no
>     * Do we want to append a form element for selecting users when adding/editing a team?
I see an usecase for it.

**Comment by vmcj** [comment]
I think DOMjudge also displays the freeform field when it has values.

**Comment by vmcj** [comment]
We think this is reasonable in the current state and adding more really complicates the logic.
