### ISSUE TITLE
Implement visual regression test

### ISSUE THREAD

**Issue by mvr320** [DOMjudge/domjudge#874]
NOTE: If this is a _discussion starter_, you need any _installation help_ or have a _question_ on how to accomplish something,
rather post at [our discussion channel](https://www.domjudge.org/chat) or send an email to our
[DOMjudge-devel mailinglist](https://www.domjudge.org/mailman/listinfo/domjudge-devel)
instead of filing an issue here.

### Description of the problem
> Currently when sending a PR there are no visual regression tests, 

### Your environment
> Maintainer image

### Steps to reproduce
> Submit a PR

### Expected behaviour
> A test outcome with changes to the UI if there are differences between my PR and main branch

### Actual behaviour
> No test

### Any other information that you want to share?
> I think this is doable with https://github.com/symfony/panther as it can give a screenshot which can be compared with ImageMagick
> Another solution might be https://github.com/facebookarchive/huxley
> https://symfony.com/blog/introducing-symfony-panther-a-browser-testing-and-web-scrapping-library-for-php shows it can work with BrowserStack but that might be overkill
> I'm not sure if its wanted if so i'm happy to build something but as the direction to go can be based on preference I think starting the discussion first might be a good idea.

**Comment by thijskh** [comment]
More tests and more kinds of tests are much needed in DOMjudge.

I've also been using Cypress for visual regression. Not an expert on the differences between all of them or have a specific preference.

**Comment by mvr320** [comment]
Currently the test is implemented via: https://github.com/DOMjudge/domjudge/pull/884

There seems to be a timing issue still as sometimes the flag is shown and sometimes the ALT text:
https://gitlab.com/DOMjudge/domjudge/-/jobs/867890887/artifacts/file/failingchanges/public.html-ff.png

A rerun seems to fix this.

**Comment by mvr320** [comment]
Although the current test is sometimes a bit flaky I think its good enough for now.
