### ISSUE TITLE
Add JSON support to users/accounts API endpoint

### ISSUE THREAD

**Issue by jeremy-london** [DOMjudge/domjudge#878]
Currently the /api/v4/users/accounts route only supports `.tsv` file injection.

I propose aligning with the other users API POST routes and support `.json` as a input 🚀

**Comment by nickygerritsen** [comment]
I wonder if we actually want/need this if we do #877 (for which I just opened a PR)?

**Comment by nickygerritsen** [comment]
Closed in favor of #877
