### ISSUE TITLE
Judgehost page gives error on JS datatables

### ISSUE THREAD

**Issue by nickygerritsen** [DOMjudge/domjudge#885]
When staying on the judgehost page datatables seem to be called more than once, which breaks. See attached screenshot.
![CannotDatatable](https://user-images.githubusercontent.com/550145/97608364-89e2ae80-1a12-11eb-8896-9b627cb65d4d.png)

**Comment by meisterT** [comment]
How can I reproduce this? I don't see it when just idling on the judgehosts page. Neither on my local installation nor on demoweb.

**Comment by nickygerritsen** [comment]
I'm not sure. This was reported on the mailinglist.

**Comment by thijskh** [comment]
More information about the error is on https://datatables.net/manual/tech-notes/3
