### ISSUE TITLE
Unable to run `dj_setup_database` with MySQL 8 due to depreated/removed SQL syntax.

### ISSUE THREAD

**Issue by hoony9x** [DOMjudge/domjudge#886]
NOTE: If this is a _discussion starter_, you need any _installation help_ or have a _question_ on how to accomplish something,
rather post at [our discussion channel](https://www.domjudge.org/chat) or send an email to our
[DOMjudge-devel mailinglist](https://www.domjudge.org/mailman/listinfo/domjudge-devel)
instead of filing an issue here.

### Description of the problem
Unable to run `bin/dj_setup_database` due to incompatible SQL query.  
In [`domjudge/sql/dj_setup_database.in`, line 201](https://github.com/DOMjudge/domjudge/blob/master/sql/dj_setup_database.in), we can find SQL query that creates new user and grant permissions.
```sql
GRANT SELECT, INSERT, UPDATE, DELETE ON \`$DBNAME\`.* TO '$domjudge_DBUSER'@'localhost' IDENTIFIED BY '$domjudge_PASSWD';
```
However, this line generates error when I trying to use DOMjudge with MySQL 8.  
In [this documentation](https://dev.mysql.com/doc/refman/5.7/en/grant.html), we can find this comment.
> However, use of GRANT to create accounts or define nonprivilege characteristics is deprecated in MySQL 5.7.
> Instead, perform these tasks using CREATE USER or ALTER USER.

I think that SQL code must be replaced with correct syntax, like this.
```sql
CREATE USER '$domjudge_DBUSER'@'localhost' IDENTIFIED BY '$domjudge_PASSWD';
GRANT SELECT, INSERT, UPDATE, DELETE ON \`$DBNAME\`.* TO '$domjudge_DBUSER'@'localhost';
FLUSH PRIVILEGES;
```

### Your environment
- DOMjudge version: 7.3.0
- Operating system / Linux distribution and version: Debian GNU/Linux 9 (stretch)
- Webserver: nginx

### Steps to reproduce
- Run `dj_setup_database` with MySQL 8.

### Expected behaviour
> DOMjudge tables should be created.

### Actual behaviour
> Error occurred when we use MySQL 8. 

### Any other information that you want to share?
- https://dev.mysql.com/doc/refman/5.7/en/grant.html
> However, use of GRANT to create accounts or define nonprivilege characteristics is deprecated in MySQL 5.7.
> Instead, perform these tasks using CREATE USER or ALTER USER.
- https://stackoverflow.com/questions/50177216/how-to-grant-all-privileges-to-root-user-in-mysql-8-0/50197630
> Starting with MySQL 8 you no longer can (implicitly) create a user using the GRANT command.
> Use CREATE USER instead, followed by the GRANT statement:

**Comment by thijskh** [comment]
Would be great if you could suggest (in a pull request) working alternative queries?

**Comment by hoony9x** [comment]
@thijskh I added PR #889 that will fix incompatibility issue.

**Comment by hoony9x** [comment]
#889 PR approved and merged.
