### ISSUE TITLE
Custom CSS/JS

### ISSUE THREAD

**Issue by mvr320** [DOMjudge/domjudge#908]
Currently we get some questions from people who wish to customize the UI. I propose to have a folder:
webapp/public/custom/{js,css,...}

which will include all files in the folders if these exist. A possible default value there should than tell people to use !important for CSS.

Such a folder can than also be easily be included from the docker image.

It could even be extended for webfonts and favicon which should be out of scope in my opinion (for now).

**Comment by thijskh** [comment]
Yes but is it fast? Maybe it is if we do the exists detection at template compile time?

**Comment by nickygerritsen** [comment]
Let me implement it the 'stupid' way and see how slow a is_dir/scandir is?

**Comment by nickygerritsen** [comment]
It seems to have no noticable impact on my machine. Both without and with loading custom CSS/JS the debug bar tells me it renders in betwee 60-70 ms. Probably if you have 5 million files in the dir it will be worse, so let's add to the docs that you should not do that?
