### ISSUE TITLE
Document contest properties in hover texts

### ISSUE THREAD

**Issue by RagnarGrootKoerkamp** [DOMjudge/domjudge#911]
When creating/editing a contest, it's always a bit unclear to me what the _exact_ purpose of all of the following fields is, and how they are different:

- Activate time
- Start time
- Start time enabled
- Contest open to all teams
  Does `no` mean the contest is completely hidden from non-admin/jury users (apart from those explicitly listed)
- Enabled
 
In particular the difference between `enabled` and `active` isn't clear to me. It seems a contest need to be both `enabled` and `active` to judge jury submissions?

I'd suggest to add hover texts to these (or all) of the form fields with a brief explanation of what each field does.

**Comment by eldering** [comment]
Just to clarify: the `activate time` is from when the contest becomes visible to public/teams. `Enabled` is a single switch to easily remove a contest from view without having to change anything else. So a contest is indeed only visible when it is enabled and the activate time has past (and deactivate time not yet).
