### ISSUE TITLE
Allow user to switch to dark theme

### ISSUE THREAD

**Issue by mpsijm** [DOMjudge/domjudge#922]
In light of the recent additions in PR #909 (issue #908), we might just as well add a default dark theme :smile: 

As discussed in the BAPC slack, this issue is to track interest :slightly_smiling_face: 

Ideally, we'd use something similar to what YouTube uses to switch between themes:
![image](https://user-images.githubusercontent.com/9739541/99143660-90526680-265f-11eb-8b45-b36267d695c9.png)

**Comment by thijskh** [comment]
I second the idea of a dark theme, but should we let users select it? Why not just follow device configuration?

**Comment by nickygerritsen** [comment]
> I second the idea of a dark theme, but should we let users select it? Why not just follow device configuration?

It might be that some people have a preference to have a dark theme globally but not on DJ or the other way around? I'm not sure but at least I have some websites where I use the light theme even though my device is set to dark.

**Comment by mpsijm** [comment]
Also, Chrome does not properly detect dark theme yet. The screenshot I sent was from FireFox (which does properly handle dark theme detection), while in Chrome this does not work (yet) :stuck_out_tongue:

**Comment by JobDoesburg** [comment]
If there's going to be both a dark theme and light theme, there should be a way to have a dark-banner en light-banner (and affiliation logos) too

**Comment by vmcj** [comment]
Because this would make the UI much harder to test if everything is still visible etc. and we have little time to work on this I think its more work to implement+maintain than the worth. I'll close this now but when someone wants to work on this we can reconsider.
