### ISSUE TITLE
Consider hiding sample download for interactive problems

### ISSUE THREAD

**Issue by nickygerritsen** [DOMjudge/domjudge#926]
As mentioned in #920 and also discussed during the CCS Specs standards call, for interactive problems the sample data is mostly useful for the validator and not for teams. The sample data mostly contains information for the validator to run.

I believe it makes more sense to hide the download of the samples for interactive problems for this reason.
#920 makes it that we can have attachments if one wants multiple data to pass to some testing tool.

Any thoughts?

**Comment by thijskh** [comment]
Is it just me or are you overloading the concept of 'sample data' if you're adding sample data that's not sample data?

**Comment by nickygerritsen** [comment]
Yes. But the problem is that they *are* sample testcases. We *do* want to have the option to show sample runs to teams. It should show information there.

**Comment by eldering** [comment]
I think the problem is that the concept of sample data really splits into two different concepts for interactive problems:

1. A sample interaction between submission and jury program.
2. Data required for a provided interaction tool to run your code against locally.

**Comment by nickygerritsen** [comment]
I agree. But it seemed we were getting nowhere during the standards call on deciding anything on this.
We can decide to just leave it as is now for the time being until the standard gets updated (if ever), but it will give confusion to teams for interactive problems.

**Comment by meisterT** [comment]
@jsannemo said that there will be a problem spec change.

**Comment by nickygerritsen** [comment]
@eldering will take a look at that
