### ISSUE TITLE
Add Sitemanager role

### ISSUE THREAD

**Issue by mvr320** [DOMjudge/domjudge#941]
Currently the only roles allowed to send clarifications are the Jury (and Admin as super role of jury)

This creates the problem that during the freeze certain info is available outside the jury room (which is unwanted) especially as the sitemanager might have little to do with the judging of the contest. It would be nice if there is a rol which can send clarifications (food is available, toilet overflowing has been fixed, pens will be send to you) but also only the "public" scoreboard.

Giving Jury to this role might be unwanted (and it might be nice if there is an interface to add capabilities to roles) so one can add this specific right to accounts or make a custom role with this right. For my usecase this would be more than is needed but I dont know if there are more of these usecases?

**Comment by nickygerritsen** [comment]
I think currently the assumption is the 'site manager' can view jury stuff (or even admin stuff). I think there is normally a trust between jury and these people.

Also, this might be interesting: you probably also don't want to show this user *other* clarifications, since they might contain sensitive data?

I'm not sure if I like the idea, but maybe others do.

**Comment by mvr320** [comment]
Sitemanager might be wrong as a name.. I dont mean the ContestDirector here but would mean the one also handling the volunteers, where I do trust that person but (s)he might also share the machine with other volunteers (Who I do trust, but might be less knowledgeable on that info is secret at 1 point). 

The clarifications I find less of an issue,  but indeed if you want to be strict you have to add that part to it which would mean you need categories for tech/admin, jury, and site/balloons/runners

**Comment by thijskh** [comment]
I do see a use for it but would make it a bit more generic. We have a role “balloons” that controls access to (only) the balloon interface. We could similarly also have a role “clarifications/clarification handler” that controls access to clarifications (r/w).

Jury has this role implied, and you can indeed give it separately to contest support staff.

It’s not super fine grained (only access to specific queues etc) but I think that is overkill as some level of trust is already required.

**Comment by nickygerritsen** [comment]
A clarifications role seems usable and easy to implement.
