### ISSUE TITLE
Judgehosts should (optionally) clean up old judging data

### ISSUE THREAD

**Issue by ubergeek42** [DOMjudge/domjudge#943]
For long running contests(or even short ones where you don't have a ton of disk space) it'd be nice for judgehosts to have an option to clean up old judging data, instead of just throwing an internal error and stopping judging.

**Comment by thijskh** [comment]
What should be criteria to clean something up? Configurable amount of time old? Keep only last _n_? Keep only data associated with contests that are active? All these?

**Comment by thijskh** [comment]
Configuration option like this (can select 0 or more):

**Judgehost autoclean**
- [ ] remove judgedata older than [    ] days
- [ ] remove judgedata from inactive contests (in the past?)

**Comment by ubergeek42** [comment]
The only one of those that would have helped my use case(small disk, busy contest) is the second one. x days old/inactive contests won't help if you get into a bad situation in a single contest.

Another option might be "limit judgedata to [ ] megabytes", or "remove judgedata to keep [ ] megabytes free"(but recent [ ] judgings is good enough to cover that use case).

**Comment by thijskh** [comment]
Since we already check for available diskspace and have a config option for that... how about we use that existing code and add a flag that instead of emitting the warning, it will be cleaning up old judgings until its above the threshold again?

And if so, does it make sense if this is a judgedaemon commandline option on startup?

**Comment by nickygerritsen** [comment]
Wouldn’t that mean it would clean up about 1 old judging every time? As soon as it gets below the threshold it cleans, it removes a judging, or goes above the threshold. Then it runs a judging. And repeat.
I wonder if we can better add some “wait period” or “clean extra MB’s”?

**Comment by thijskh** [comment]
Why is it bad to clean one at a time?

**Comment by nickygerritsen** [comment]
I wonder if the overhead of cleaning every time would be higher. But I’m not sure

**Comment by thijskh** [comment]
I would assume that the time it takes is quite linear with the amount of files removed. If you use any reasonable FS (not ext*) it will be fast anyway?

**Comment by nickygerritsen** [comment]
But you always have the overhead of checking which files are there and which are the oldest? This time is the same for removing 1 or 10000 judgings

**Comment by thijskh** [comment]
I would not remove the oldest file, just the oldest judging.

**Comment by eldering** [comment]
I think if anything it should just clean oldest judgings until free space is above threshold again. That requires the least amount of extra configuration and preserves data the longest.
