### ISSUE TITLE
Add shell escaping to judgedaemon

### ISSUE THREAD

**Issue by ubergeek42** [DOMjudge/domjudge#960]
We pass some strings directly to `system()` in judgedaemon, and we should shell_escape them. See https://github.com/DOMjudge/domjudge/pull/888#discussion_r554036763

Not super high priority since we mostly filter these on the domjudge server side, but we should be more paranoid.

**Comment by mvr320** [comment]
@ubergeek42 so you want everything shell escaped which is coming from the domserver (so also https://github.com/DOMjudge/domjudge/blob/7cd4caee06eaecf9ea7780990d1c82e3bbd36f04/judge/judgedaemon.main.php#L262 which is only currently safe when you trust an admin) or only things where a user might have interaction (so submission files etc.)?

**Comment by thijskh** [comment]
We want to be as safe as possible. Why is it a problem to escape `$execdir` in this example?

**Comment by mvr320** [comment]
Because every extra call takes extra time, so is the security:

Judgedaemon trusts only stuff which is locally defined but distrusts input coming in from the domserver,
Or does it only trust things which are entered from a trustworthy user (admin user uploading a problem zip which contains testcases etc.),

I assume you prefer option 1,

**Comment by ubergeek42** [comment]
I would imagine the overhead of shell escaping is dwarfed by the call to system itself. So I would like to see any user input filtered(whether it's from an admin or a user). It also helps protect against bugs if some input ends up with special characters that have meaning to the shell.

**Comment by thijskh** [comment]
It does not trust anything entered by any user regardless of that user's level.

**Comment by mvr320** [comment]
So I did: https://github.com/DOMjudge/domjudge/pull/1004 which I think handles all cases where there is a variable and its not escaped. Calls with a constant are kept to keep it readable and 1 glob is left but explicit annotated. Can this issue be closed or should more be done?
