### ISSUE TITLE
Change a testcase as a Jury member

### ISSUE THREAD

**Issue by mvr320** [DOMjudge/domjudge#962]
### Your environment
> - Master

### Steps to reproduce
> Login as Jury and go to a problem its testcases
> In the UI the button is not there
> Login as Admin and go to a problem its testcases
> In the UI the button is there

### Expected behaviour
> According to @nickygerritsen a jury role has the rights to edit a testcase for a problem

### Actual behaviour
> The jury role cannot change the testcase

### Any other information that you want to share?
- https://domjudge-org.slack.com/files/UJ9HA6HEU/F01J5T8A0A2/image.png
- https://domjudge-org.slack.com/files/UJ9HA6HEU/F01JR9T5RGR/image.png

This is the discussion starter, what is the expected functionality.

**Comment by meisterT** [comment]
I would argue it's intentional and in line with the rest of the behavior, e.g. you can't create a contest/problem without admin permissions.

**Comment by nickygerritsen** [comment]
> I would argue it's intentional and in line with the rest of the behavior, e.g. you can't create a contest/problem without admin permissions.

In that case we need to update the controller to also check for it, since currently you could do a manual POST probably.
