### ISSUE TITLE
Adding Affiliation on master

### ISSUE THREAD

**Issue by mvr320** [DOMjudge/domjudge#974]
### Description of the problem
When visiting https://www.domjudge.org/demoweb/jury/affiliations/add there is an error.

### Your environment
Demoweb/master (also in my master)

### Expected behaviour
I expect this to work

**Comment by mvr320** [comment]
I assume the null type for external_id can be null? But i'm not sure if this is according to specs?

**Comment by nickygerritsen** [comment]
External ID’s are always optional
