### ISSUE TITLE
Failed testcase cannot be reenabled

### ISSUE THREAD

**Issue by thijskh** [DOMjudge/domjudge#984]
When a testcase has caused an internal error, and you try to resolve this error and reenable the testcase in the web interface, you get:

```
An exception occurred while executing 'INSERT INTO judging_run (judgetaskid, runresult, runtime, endtime, judgingid, testcaseid) VALUES (?, ?, ?, ?, ?, ?)' with params [46, null, null, null, 85, 1017]:

SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '85-1017' for key 'testcaseid'
```

**Comment by meisterT** [comment]
I can repro this (by changing the judgedaemon code to provoke such an internal error). I think we should remap this to disabling a problem server-side, but have to think a little bit more how to do that cleanly since judgetasks have no direct mapping to problem.
