### ISSUE TITLE
JudgehostController calls setDisabled(null) which is not allowed

### ISSUE THREAD

**Issue by thijskh** [DOMjudge/domjudge#987]
There are two instances in JudgehostController where it explicitly calls `setDisabled(null)` for an InternalError:
https://github.com/DOMjudge/domjudge/blob/14104d4639630f72534b3bcd0458225c715d36c1/webapp/src/Controller/API/JudgehostController.php#L399
https://github.com/DOMjudge/domjudge/blob/14104d4639630f72534b3bcd0458225c715d36c1/webapp/src/Controller/API/JudgehostController.php#L444

The entity however does not allow this usage. The way it now triggers might be related to 6a862f42471adc781b2946be506fe5f4fa6f0b3a where a type hint was added, but it seems that at least the schema has never allowed this to be nullable so maybe before it accidentally worked. Since I'm not sure what the exact intent of the `null` parameter is, I don't know what fix to propose.

```
[Feb 05 18:42:24.392] judgedaemon[2259355]:   Working directory: /home/thijs/DJ/domjudge/output/judgings/djdev/endpoint-default/20/37
[Feb 05 18:42:24.396] judgedaemon[2259355]:   √ Executing chroot script: 'chroot-startstop.sh start'
[Feb 05 18:42:26.394] judgedaemon[2259355]:   💻 Compilation: ('test-hello.cc') 'correct'
[Feb 05 18:42:26.723] judgedaemon[2259355]: error: Error while executing curl PUT to url http://localhost/domjudge/api/judgehosts/update-judging/djdev/133: http status code: 500, request size = 33, response: array (
  'code' => 500,
  'message' => 'Argument 1 passed to App\\Entity\\InternalError::setDisabled() must be of the type array, null given, called in /home/thijs/DJ/domjudge/webapp/src/Controller/API/JudgehostController.php on line 399',
  'class' => 'TypeError',
  'trace' => 
  array (
    0 => 
    array (
      'namespace' => '',
      'short_class' => '',
      'class' => '',
      'type' => '',
      'function' => '',
      'file' => '/home/thijs/DJ/domjudge/webapp/src/Entity/InternalError.php',
      'line' => 129,
      'args' => 
      array (
      ),
    ),
```

**Comment by meisterT** [comment]
So, this definitely is a condition that we want to highlight to the jury since something is quite broken since two judgedaemons might be configured differently.

I assume we do want to disable the judgedaemon that gave the compile error (which isn't necessarily the same as the one that uncovered the problem)?

**Comment by thijskh** [comment]
Disabling one of the two judgehosts might indeed make most sense, although it's still indeed guesswork as to the cause of the issue so we can't be sure what we need to disable. But disabling something is a clear signal to the jury that it needs investigation.
