### ISSUE TITLE
Api/JudgehostController::internalErrorAction has unset variables

### ISSUE THREAD

**Issue by nickygerritsen** [DOMjudge/domjudge#988]
`$cid` and `$judgingId` are used in the `internalErrorAction` but never set since our new judgehost API.
I think @meisterT said the new judgehost doesn't know about these values, so if that is the case, we should remove the code from the action.

See:
https://github.com/DOMjudge/domjudge/blob/14104d4639630f72534b3bcd0458225c715d36c1/webapp/src/Controller/API/JudgehostController.php#L775 and https://github.com/DOMjudge/domjudge/blob/14104d4639630f72534b3bcd0458225c715d36c1/webapp/src/Controller/API/JudgehostController.php#L788

This would also mean the internal error model only has a  contest and judging when being set from updateJudgingAction in the `} elseif ($judging->getResult() === Judging::RESULT_COMPILER_ERROR) {` cases (see also #987).

If we still want that we should figure out a way to set the data again.

**Comment by meisterT** [comment]
Did you see https://github.com/DOMjudge/domjudge/blob/14104d4639630f72534b3bcd0458225c715d36c1/webapp/src/Controller/API/JudgehostController.php#L718-721?

**Comment by nickygerritsen** [comment]
I did not. See #988 for my proposed fix in that case.
