### ISSUE TITLE
Deprecated composer dependencies

### ISSUE THREAD

**Issue by nickygerritsen** [DOMjudge/domjudge#990]
Our current `master` has the following deprecated composer packages:

```
Package doctrine/doctrine-cache-bundle is abandoned, you should avoid using it. No replacement was suggested.
Package doctrine/reflection is abandoned, you should avoid using it. Use roave/better-reflection instead.
Package phpunit/php-token-stream is abandoned, you should avoid using it. No replacement was suggested.
Package twig/extensions is abandoned, you should avoid using it. No replacement was suggested.
Package zendframework/zend-code is abandoned, you should avoid using it. Use laminas/laminas-code instead.
```

Do we want to get rid of them? Below a list of where they come from.

# doctrine/doctrine-cache-bundle

- [x] This is a root dependency which is deprecated and not used anymore for Symfony 5. I think we can just remove it (and maybe add `doctrine/cache` if we still use it

# doctrine/reflection

- [x] Used by `doctrine/common`. We could update that if we update doctrine/doctrine-bundle.

# phpunit/php-token-stream

- [ ] Used by `phpunit/php-code-coverage` 7.x and 8.x. 9.x requires PHP 7.3 but since it is only for the tests we could do that.

# twig/extensions

- [x] See https://github.com/twigphp/Twig-extensions. Not sure which extensions we actually use but we can probably figure that out.

# zendframework/zend-code

- [x] Used by `ocramius/proxy-manager` which in turn is used by `jms/serializer`, `doctrine/doctrine-bundle` and `doctrine/doctrine-bundle`. `jms/serializer` we can just upgrade. For the latter two we could upgrade again.

**Comment by thijskh** [comment]
`twig/extensions` is gone now

**Comment by thijskh** [comment]
I disagree with `phpunit/php-token-stream`. If we support PHP 7.2 we must also be able to run the unit tests against it. If we do not currently do so you could even see that as a bug/missing feature. But in any case I don't think we should actively break that. Let's just accept that one.

**Comment by nickygerritsen** [comment]
> I disagree with `phpunit/php-token-stream`. If we support PHP 7.2 we must also be able to run the unit tests against it. If we do not currently do so you could even see that as a bug/missing feature. But in any case I don't think we should actively break that. Let's just accept that one.

Agreed. We can update when we move to a newer php
