### ISSUE TITLE
 Non-existent class or interface: "ZipArchive".

### ISSUE THREAD

**Issue by Celso1912** [DOMjudge/domjudge#996]
Im running the dj_setup_database [-u <mysql admin user>] [-p <password>|-r] install and find the following message error:
 
 [Symfony\Component\DependencyInjection\Exception\InvalidArgumentException] - Cannot determine controller argument for "App\Controller\Jury\ProblemController::addTestcasesToZip()": the $zip argument is type-hinted with the[ non-existent class or interface: "ZipArchive".](url)

Is there any known solution for this issue?

**Comment by nickygerritsen** [comment]
Did you install `php-zip`? The [documentation](https://www.domjudge.org/docs/manual/7.3/install-domserver.html#software-requirements) states this as a requirement and it should provide the `ZIPArchive` class.

**Comment by Celso1912** [comment]
> Did you install `php-zip`? The [documentation](https://www.domjudge.org/docs/manual/7.3/install-domserver.html#software-requirements) states this as a requirement and it should provide the `ZIPArchive` class.

Yes, I instlled, but I could identify the issue. I'm current using PHP803.
celsorb@LAPTOP-KJRU8OD0:~/domjudge/domserver$ apt list php-z*
Listing... Done
php-zend-code/focal 3.4.1-1 all
php-zend-eventmanager/focal 3.2.1-1 all
php-zend-stdlib/focal 3.2.1-1 all
php-zeroc-ice/focal 3.7.3-1build2 amd64
php-zeta-base/focal 1.9.1-2 all
php-zeta-console-tools/focal 1.7-5 all
php-zeta-unit-test/focal 1.1.2-2 all
**php-zip/focal,now 2:7.4+75 all [installed]**
php-zmq/focal 1.1.3-11build1 amd64

**Comment by nickygerritsen** [comment]
We haven’t tested with 8.0 yet. Not sure which php repo you use as well?

**Comment by Celso1912** [comment]
> We haven’t tested with 8.0 yet. Not sure which php repo you use as well?

I've moved to PHP 7.4.3 and now it's working.

tkx!

**Comment by thijskh** [comment]
The php-zip module you list is for 7.4:

> php-zip/focal,now 2:7.4+75 all [installed]

so if you are using PHP 8.0 you should install the zip module that comes with those packages
